---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter Plug-in for Microsoft SQL Server のバックアップから SQL Server データベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。 
---
= データベースをリストアするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft SQL Server のバックアップから SQL Server データベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。

* データベースをリストアするには、ターゲットの SQL Server インスタンスがオンラインで稼働している必要があります。
+
この環境では、ユーザデータベースのリストア処理とシステムデータベースのリストア処理の両方が実行されます。

* リモートアドミニストレーションサーバまたはリモート検証サーバでスケジュール設定しているジョブも含め、リストアする SQL Server データに対して実行されるスケジュール設定されている SnapCenter 処理を無効にする必要があります。
* システムデータベースが機能していない場合は、まず SQL Server ユーティリティを使用してシステムデータベースを再構築する必要があります。
* プラグインをインストールするときは、可用性グループ（ AG ）バックアップをリストアする権限を他のロールに付与します。
+
次のいずれかの条件に該当する場合、 AG のリストアが失敗します。

+
** RBAC ユーザがプラグインをインストールし、管理者が AG バックアップをリストアしようとした場合
** 管理者がプラグインをインストールし、 RBAC ユーザが AG バックアップをリストアしようとした場合


* カスタム・ログ・ディレクトリのバックアップを代替ホストにリストアする場合は、 SnapCenter サーバとプラグイン・ホストに同じバージョンの SnapCenter がインストールされている必要があります。
* Microsoft の修正プログラム KB2887595 をインストールしておく必要があります。マイクロソフトサポートサイトには、 KB2887595 に関する詳細情報が記載されています。
+
https://support.microsoft.com/kb/2887595["Microsoft のサポート記事 2887595 ：「 Windows RT 8.1 、 Windows 8.1 、 and Windows Server 2012 R2 update rollup ： November 2013"]

* リソースグループまたはデータベースをバックアップしておく必要があります。
* Snapshot コピーをミラーまたはバックアップにレプリケートするユーザには、 SnapCenter 管理者がユーザに対してソースとデスティネーションの両方のボリューム用に Storage Virtual Machine （ SVM ）を割り当てる必要があります。
+
管理者によるユーザへのリソースの割り当て方法については、 SnapCenter のインストール情報を参照してください。

* データベースをリストアする前に、バックアップジョブとクローニングジョブをすべて停止する必要があります。
* データベースサイズがテラバイト（ TB ）単位の場合、リストア処理がタイムアウトすることがあります。
+
次のコマンドを実行して、 SnapCenter サーバの RESTTimeout パラメータの値を 20000000ms に増やす必要があります。 Set-SmConfigSettings -Agent -configSettings @ ｛ "RESTTimeout" = "20000000" ｝ 。データベースのサイズに応じて、タイムアウト値を変更でき、設定可能な最大値は 214748648 です。



データベースをオンラインにしたままリストアする場合は、リストアページでオンラインリストアオプションを有効にする必要があります。
