---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords: Requirements 
summary: SnapCenter Plug-in for Microsoft SQL Server のバックアップから SQL Server データベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。 
---
= データベースをリストアする際の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft SQL Server のバックアップから SQL Server データベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。

* データベースをリストアするには、ターゲットSQL Serverインスタンスがオンラインで実行されている必要があります。
+
これは、ユーザデータベースのリストア処理とシステムデータベースのリストア処理の両方に該当します。

* リモートアドミニストレーションサーバまたはリモート検証サーバでスケジュール設定しているジョブも含め、リストアする SQL Server データに対して実行されるスケジュール設定されている SnapCenter 処理を無効にする必要があります。
* システムデータベースが機能していない場合は、まずSQL Serverユーティリティを使用してシステムデータベースを再構築する必要があります。
* プラグインをインストールする場合は、可用性グループ（AG）のバックアップをリストアする権限を他のロールに付与してください。
+
次のいずれかの条件が満たされると、AGのリストアが失敗します。

+
** RBACユーザがプラグインをインストールし、管理者がAGバックアップをリストアしようとした場合
** 管理者がプラグインをインストールし、RBACユーザがAGバックアップをリストアしようとした場合


* カスタムログディレクトリのバックアップを別のホストにリストアする場合は、SnapCenterサーバとプラグインホストに同じバージョンのSnapCenterがインストールされている必要があります。
* Microsoft修正プログラムKB2887595をインストールしておく必要があります。KB2887595の詳細については、Microsoftサポートサイトを参照してください。
+
https://support.microsoft.com/kb/2887595["Microsoft のサポート記事 2887595 ：「 Windows RT 8.1 、 Windows 8.1 、 and Windows Server 2012 R2 update rollup ： November 2013"]

* リソースグループまたはデータベースをバックアップしておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートする場合は、SnapCenter管理者がユーザにソースボリュームとデスティネーションボリュームの両方に対してStorage Virtual Machine（SVM）を割り当てておく必要があります。
+
管理者によるユーザへのリソースの割り当て方法については、 SnapCenter のインストール情報を参照してください。

* データベースをリストアする前に、すべてのバックアップジョブとクローンジョブを停止する必要があります。
* データベースサイズがテラバイト（TB）単位の場合、リストア処理がタイムアウトすることがあります。
+
次のコマンドを実行して、 SnapCenter サーバの RESTTimeout パラメータの値を 20000000ms に増やす必要があります。 Set-SmConfigSettings -Agent -configSettings @ ｛ "RESTTimeout" = "20000000" ｝ 。データベースのサイズに応じてタイムアウト値を変更でき、設定可能な最大値は86400000ミリ秒です。



データベースをオンラインにしたままリストアする場合は、リストアページでオンラインリストアオプションを有効にする必要があります。
