---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: Plug-in for SQL Serverは、Windowsホスト上でMicrosoft SQL Serverと統合され、ストレージシステム上でNetApp Snapshotテクノロジと統合されます。Plug-in for SQL Server を操作するには、 SnapCenter インターフェイスを使用します。 
---
= SnapCenter Plug-in for Microsoft SQL Serverの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plug-in for SQL Serverは、Windowsホスト上でMicrosoft SQL Serverと統合され、ストレージシステム上でNetApp Snapshotテクノロジと統合されます。Plug-in for SQL Server を操作するには、 SnapCenter インターフェイスを使用します。

Plug-in for SQL Server の主な機能は次のとおりです。

* * SnapCenter * による統一されたグラフィカル・ユーザー・インターフェイス
+
SnapCenter のインターフェイスは、すべてのプラグインと環境で標準化され、一貫しています。SnapCenter インターフェイスを使用すると、すべてのプラグインでバックアッププロセスとリストアプロセスを一貫した方法で実行できるほか、ダッシュボードビューで概要を把握したり、ロールベースアクセス制御（ RBAC ）を設定したり、ジョブを監視したりすることができます。SnapCenter では、バックアップ処理とクローニング処理に対応したスケジュールとポリシーの一元管理も可能です。

* * 中央管理の自動化 *
+
日常的なSQL Serverバックアップのスケジュールを設定したり、ポリシーベースのバックアップ保持を設定したり、ポイントインタイムリストア処理と最新の状態へのリストア処理を設定したりできます。SnapCenter から E メールアラートを送信するように設定して、 SQL Server 環境をプロアクティブに監視することもできます。

* *無停止のNetAppスナップショットテクノロジ*
+
Plug-in for SQL Serverでは、NetApp SnapCenter Plug-in for Microsoft WindowsでNetAppのSnapshotテクノロジを使用します。これにより、データベースを数秒でバックアップし、SQL Serverをオフラインにすることなく迅速にリストアできます。Snapshotはストレージスペースを最小限しか消費しません。



Plug-in for SQL Server には、上記の主要な機能以外にも次のようなメリットがあります。

* バックアップ、リストア、クローニング、および検証のワークフローがサポートされます。
* RBACでサポートされるセキュリティと一元化されたロール委譲
* NetApp FlexClone テクノロジを使用して、本番環境のデータベースのスペース効率に優れたポイントインタイムコピーを作成し、テストまたはデータの抽出を行います
+
クローンを保持するストレージシステムにFlexCloneライセンスが必要です。

* 自動化された無停止のバックアップ検証
* 複数のサーバで同時に複数のバックアップを実行可能
* PowerShellコマンドレットを使用して、バックアップ、検証、リストア、クローニングの処理のスクリプトを作成できます。
* SQL ServerでAlwaysOn可用性グループ（AG）がサポートされ、AGのセットアップ、バックアップ、リストアの処理を高速化
* SQL Server 2014の一部としてのインメモリデータベースとバッファプール拡張（BPE）
* LUNおよび仮想マシンディスク（VMDK）のバックアップのサポート
* 物理インフラと仮想インフラをサポート
* iSCSI、ファイバチャネル、FCoE、rawデバイスマッピング（RDM）、NFSおよびVMFS経由のVMDKがサポートされます。
+

NOTE: Storage Virtual Machine（SVM）にNASボリュームのデフォルトのエクスポートポリシーが必要です。

* SQL ServerスタンドアロンデータベースでのFileStreamおよびファイルグループのサポート。
* Windows Server 2022でのNon-Volatile Memory Express（NVMe）のサポート
+
** NVMe over TCP / IPで作成されたVMDKレイアウト上のバックアップ、リストア、クローニング、検証のワークフロー
** ESX 8.0 Update 2以降のNVMeファームウェアバージョン1.3をサポートします。Virtualハードウェアバージョン21が必要です。
** Windows Serverフェイルオーバークラスタリング（WSFC）は、NVMe over TCP/IP上のVMDKを介したアプリケーションではサポートされません。


* SnapMirror Active Sync（当初はSnapMirror Business Continuity [SM-BC]としてリリース）をサポート。これにより、サイト全体に障害が発生してもビジネスサービスの運用を継続でき、アプリケーションがセカンダリコピーを使用して透過的にフェイルオーバーできるようになります。SnapMirror Active Syncでフェイルオーバーをトリガーするために、手動操作や追加のスクリプト作成は必要ありません。

