---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: SnapCenter を使用して SQL Server システムおよびユーザデータベースをバックアップするときは、データベース、 SQL Server インスタンス、可用性グループ（ AG ）などのリソースタイプを選択する必要があります。Snapshotテクノロジを使用して、リソースが配置されているボリュームのオンラインの読み取り専用コピーが作成されます。 
---
= サポートされるバックアップのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して SQL Server システムおよびユーザデータベースをバックアップするときは、データベース、 SQL Server インスタンス、可用性グループ（ AG ）などのリソースタイプを選択する必要があります。Snapshotテクノロジを使用して、リソースが配置されているボリュームのオンラインの読み取り専用コピーが作成されます。

コピーのみのオプションを選択すると、SQL Serverでトランザクションログが切り捨てられないように指定できます。このオプションは、他のバックアップアプリケーションでSQL Serverを管理する場合に使用します。トランザクションログをそのまま保持することで、すべてのバックアップアプリケーションでシステムデータベースをリストアできます。コピーのみのバックアップは、スケジュールされたバックアップの順序とは関係なく、データベースのバックアップおよびリストア手順には影響しません。

|===
| バックアップタイプ | 説明 | バックアップタイプを指定したコピーのみのオプション 


 a| 
フルバックアップとログバックアップ
 a| 
システムデータベースがバックアップされ、トランザクションログが切り捨てられます。

SQL Serverは、データベースにコミット済みのエントリを削除することで、トランザクションログを切り捨てます。

このオプションを選択すると、フルバックアップの完了後にトランザクションログが作成され、トランザクション情報がキャプチャされます。通常は、このオプションを選択する必要があります。ただし、バックアップ時間が短い場合は、フルバックアップでトランザクションログバックアップを実行しないように選択できます。

masterおよびmsdbシステムデータベースのログバックアップは作成できません。ただし、モデルシステムデータベースのログバックアップは作成できます。
 a| 
システムデータベースファイルとトランザクションログがバックアップされ、ログは切り捨てられません。

コピーのみのバックアップは差分ベースまたは差分バックアップとしては使用できず、差分ベースには影響しません。コピーのみのフルバックアップのリストアは、他のフルバックアップのリストアと同じです。



 a| 
フルデータベースバックアップ
 a| 
システムデータベースファイルがバックアップされます。

master、model、およびmsdbシステムデータベースのフルデータベースバックアップを作成できます。
 a| 
システムデータベースファイルがバックアップされます。



 a| 
トランザクションログバックアップ
 a| 
切り捨てられたトランザクションログがバックアップされます。コピーされるのは、最新のトランザクションログのバックアップ後にコミットされたトランザクションだけです。

フルデータベースバックアップとともにトランザクションログを頻繁にバックアップするようにスケジュールを設定する場合は、リカバリポイントをきめ細かく選択できます。
 a| 
トランザクションログを切り捨てずにバックアップします。

このバックアップタイプは、定期的なログバックアップの順序には影響しません。コピーのみのログバックアップは、オンラインリストア処理を実行する場合に役立ちます。

|===