---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter を使用して SQL Server システムおよびユーザデータベースをバックアップするときは、データベース、 SQL Server インスタンス、可用性グループ（ AG ）などのリソースタイプを選択する必要があります。Snapshot コピーテクノロジを使用して、リソースが存在するボリュームのオンラインの読み取り専用コピーが作成されます。 
---
= サポートされるバックアップのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して SQL Server システムおよびユーザデータベースをバックアップするときは、データベース、 SQL Server インスタンス、可用性グループ（ AG ）などのリソースタイプを選択する必要があります。Snapshot コピーテクノロジを使用して、リソースが存在するボリュームのオンラインの読み取り専用コピーが作成されます。

コピーのみのオプションを選択して、 SQL Server がトランザクションログを切り捨てないように指定できます。SQL Server の管理に他のバックアップアプリケーションも使用している場合は、このオプションを使用します。トランザクションログが変更されずに保持されるため、任意のバックアップアプリケーションでシステムデータベースをリストアできます。コピーのみのバックアップは、スケジュールされたバックアップとは関係なく実行され、データベースのバックアップおよびリストア手順には影響しません。

|===
| バックアップタイプ | 説明 | コピーのみのオプションでバックアップタイプを指定 


 a| 
フルバックアップとログバックアップ
 a| 
システムデータベースがバックアップされ、トランザクションログが切り捨てられます。

SQL Server は、データベースにコミット済みのエントリを削除することによってトランザクションログを切り捨てます。

このオプションを選択すると、フルバックアップの完了後にトランザクションログが作成されてトランザクション情報がキャプチャされます。通常は、このオプションを選択します。ただし、バックアップ時間が短い場合は、フルバックアップでトランザクションログバックアップを実行しないように選択することもできます。

master システムデータベースと msdb システムデータベースについては、ログバックアップを作成できません。model システムデータベースのログバックアップは作成できます。
 a| 
システムデータベースファイルとトランザクションログがバックアップされ、ログは切り捨てられません。

コピーのみのバックアップは差分ベースまたは差分バックアップとしては使用できず、差分ベースには影響しません。コピーのみのフルバックアップのリストアは、他のフルバックアップのリストアと同じです。



 a| 
フルデータベースバックアップ
 a| 
システムデータベースファイルがバックアップされます。

master 、 model 、 msdb の各システムデータベースのフルデータベースバックアップを作成できます。
 a| 
システムデータベースファイルがバックアップされます。



 a| 
トランザクションログバックアップ
 a| 
切り捨てられたトランザクションログがバックアップされ、最新のトランザクションログのバックアップ後にコミットされたトランザクションのみがコピーされます。

フルデータベースバックアップに加えてトランザクションログを頻繁にバックアップするスケジュールを設定すると、リカバリポイントをさらに細かく選択できます。
 a| 
トランザクションログが切り捨てられずにバックアップされます。

このバックアップタイプは、定期的なログバックアップには影響しません。コピーのみのログバックアップは、オンラインのリストア処理を実行する場合に便利です。

|===