---
permalink: protect-scsql/concept_backup_schedules_for_plugin_for_sql.html 
sidebar: sidebar 
keywords:  
summary: バックアップ頻度 \ （スケジュールタイプ \ ）はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。 
---
= Plug-in for SQL Server のバックアップスケジュール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


バックアップ頻度（スケジュールタイプ）はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは 1 時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは 1 日に 1 回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（ SLA ）、目標復旧時点（ RPO ）などがあります。

SLA は、想定されるサービスのレベルを定義し、サービスの可用性やパフォーマンスなど、サービス関連の多くの問題に対処します。RPO は、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA と RPO は、データ保護戦略に関与します。

使用頻度の高いリソースであっても、フルバックアップは 1 日に 1~2 回で十分です。たとえば、定期的なトランザクションログバックアップを実行すれば、必要なバックアップが作成されます。データベースをバックアップする回数が多いほど、リストア時に SnapCenter が使用する必要のあるトランザクションログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

バックアップスケジュールには、次の 2 つの要素があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインでは _ schedule type__ と呼ばれます。ポリシーでは、バックアップ頻度として、毎時、毎日、毎週、または毎月を選択できます。頻度を選択しない場合は、オンデマンドのみのポリシーが作成されます。ポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行される日時）は、リソースグループの設定の一部です。たとえば、リソースグループのポリシーで週に 1 回のバックアップが設定されている場合は、毎週木曜日の午後 10 時にバックアップが実行されるようにスケジュールを設定できます。リソースグループのスケジュールにアクセスするには、 * リソース * > * リソースグループ * をクリックします。


