---
permalink: protect-scsql/concept_what_you_can_do_with_the_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: SnapCenter Plug-in for Microsoft SQL Serverをインストールした環境では、SnapCenterを使用してSQL Serverデータベースをバックアップ、リストア、およびクローニングすることができます。 
---
= SnapCenter Plug-in for Microsoft SQL Server の機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft SQL Serverをインストールした環境では、SnapCenterを使用してSQL Serverデータベースをバックアップ、リストア、およびクローニングすることができます。

SQL Serverデータベースとデータベースリソースのバックアップ処理、リストア処理、およびクローニング処理をサポートする次のタスクを実行できます。

* SQL Serverデータベースおよび関連するトランザクションログをバックアップする
+
masterおよびmsdbシステムデータベースのログバックアップは作成できません。ただし、モデルシステムデータベースのログバックアップは作成できます。

* データベースリソースのリストア
+
** マスターシステムデータベース、msdbシステムデータベース、およびモデルシステムデータベースをリストアできます。
** 複数のデータベース、インスタンス、および可用性グループをリストアすることはできません。
** システムデータベースを別のパスにリストアすることはできません。


* 本番環境のデータベースのポイントインタイムクローンを作成
+
tempdbシステムデータベースでは、バックアップ、リストア、クローニング、およびクローンライフサイクルの処理を実行できません。

* バックアップ処理をただちに検証するか、あとで検証する
+
SQL Serverシステムデータベースの検証はサポートされていません。SnapCenterは、検証処理を実行するためにデータベースのクローニングを行います。SnapCenterではSQL Serverシステムデータベースをクローニングできないため、これらのデータベースの検証はサポートされていません。

* バックアップ処理とクローニング処理のスケジュールを設定する
* バックアップ処理、リストア処理、クローニング処理を監視する



NOTE: Plug-in for SQL Server では、 SMB 共有の SQL Server データベースのバックアップとリカバリはサポートされません。
