---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter サーバおよび SnapCenter Plug-in for Microsoft SQL Server をインストールする手順について説明します。 
---
= SnapCenter Plug-in for SQL Server のインストールのクイックスタート
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Server と SnapCenter Plug-in for Microsoft SQL Server のインストール手順を簡潔にまとめたものです。



== 設置を準備

* ドメインおよびワークグループの要件 *

SnapCenter サーバは、ドメインまたはワークグループ内のシステムにインストールできます。

Active Directory ドメインを使用している場合は、ローカル管理者の権限を持つドメインユーザを使用する必要があります。ドメインユーザは、 Windows ホストのローカル管理者グループのメンバーである必要があります。

ワークグループを使用している場合は、ローカル管理者の権限を持つローカルアカウントを使用します。

* ライセンス要件 *

インストールするライセンスのタイプは環境によって異なります。

|===
| 使用許諾 | 必要に応じて 


 a| 
SnapCenter 標準のコントローラベース
 a| 
FAS または AFF ストレージコントローラの場合は必須です

SnapCenter Standard ライセンスはコントローラベースのライセンスで、 Premium Bundle に含まれています。SnapManager スイートのライセンスをお持ちの場合は、 SnapCenter Standard のライセンスもご利用いただけます。FAS または AFF ストレージを使用した SnapCenter の試用版をインストールする場合は、営業担当者にお問い合わせください。



 a| 
SnapCenter - 容量ベース
 a| 
ONTAP Select および Cloud Volumes ONTAP で必要です

Cloud Volumes ONTAP または ONTAP Select を使用している場合は、 SnapCenter で管理するデータに基づいて、容量ベースのライセンスを 1TB 単位で購入する必要があります。デフォルトでは、 SnapCenter には 90 日間の 100TB SnapCenter の標準容量ベースの試用版ライセンスが組み込まれています。その他の詳細については、営業担当者にお問い合わせください。



 a| 
SnapMirror または SnapVault
 a| 
ONTAP

SnapCenter でレプリケーションを有効にする場合は、 SnapMirror または SnapVault のライセンスが必要です。



 a| 
追加ライセンス（オプション）
 a| 
を参照してください link:../install/concept_snapcenter_licenses.html["SnapCenter ライセンス"^]。



 a| 
SnapCenter 標準ライセンス（オプション）
 a| 
セカンダリデスティネーション


NOTE: セカンダリデスティネーションに SnapCenter Standard ライセンスを追加することを推奨しますが、必須ではありません。セカンダリデスティネーションで SnapCenter 標準ライセンスが有効になっていない場合、フェイルオーバー処理の実行後に、 SnapCenter を使用してセカンダリデスティネーションのリソースをバックアップすることはできません。ただし、クローニング処理と検証処理を実行するには、セカンダリデスティネーションに FlexClone ライセンスが必要です。

|===
* その他の要件 *

ONTAP およびアプリケーションプラグインの最小要件については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"^]

|===
| ホスト | 最小要件 


 a| 
オペレーティングシステム（ 64 ビット）
 a| 
を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"^]



 a| 
CPU
 a| 
* サーバホスト： 4 コア
* プラグインホスト： 1 コア




 a| 
RAM
 a| 
* サーバホスト： 8GB
* プラグインホスト： 1GB




 a| 
ハードドライブの空き容量
 a| 
サーバホスト：

* SnapCenter サーバソフトウェアとログの場合は 4GB
* SnapCenter リポジトリ用に 6GB
* 各プラグインホスト：プラグインのインストールとログ用に 2GB 。専用のホストにプラグインがインストールされている場合にのみ必要です。




 a| 
サードパーティのライブラリ
 a| 
SnapCenter サーバホストおよびプラグインホストで必要：

* Microsoft .NET Framework 4.5.2 以降
* Windows Management Framework （ WMF ） 4.0 以降
* PowerShell 4.0 以降




 a| 
ブラウザ
 a| 
Chrome 、 Internet Explorer 、および Microsoft Edge

|===
|===
| ポートタイプ | デフォルトのポート 


 a| 
SnapCenter ポート
 a| 
8146 （ HTTPS ）、双方向、カスタマイズ可能。 URL は、 https://server:8146_ を参照してください



 a| 
SnapCenter SMCore の通信ポート
 a| 
8145 （ HTTPS ）、双方向、カスタマイズ可能



 a| 
リポジトリデータベース
 a| 
3306 （ HTTPS ）、双方向



 a| 
Windows プラグインホスト
 a| 
135 、 445 （ TCP ）

ポート 135 および 445 に加え、 Microsoft が指定したダイナミックポート範囲も開いている必要があります。リモートインストール操作では、このポート範囲を動的に検索する Windows Management Instrumentation （ WMI ）サービスを使用します。

サポートされているダイナミックポート範囲については、を参照してください https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows のサービス概要とネットワークポート要件"^]。



 a| 
SnapCenter Plug-in for Windows の略
 a| 
8145 （ HTTPS ）、双方向、カスタマイズ可能



 a| 
ONTAP クラスタまたは SVM の通信ポート
 a| 
443 （ HTTPS ）、双方向、 80 （ HTTP ）、双方向

このポートは、 SnapCenter サーバホスト、プラグインホスト、 SVM または ONTAP クラスタ間の通信に使用されます。

|===
* SnapCenter Plug-in for Microsoft SQL Server の要件 *

ローカル管理者の権限を持つユーザが、リモートホストに対してローカルログインの権限を持っている必要があります。クラスタノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限を持つユーザが必要です。

SQL Server に対して sysadmin 権限を持つユーザが必要です。このプラグインは Microsoft VDI Framework を使用しますが、これには sysadmin アクセスが必要です。

SnapManager for Microsoft SQL Server を使用していて、 SnapManager for Microsoft SQL Server から SnapCenter にデータをインポートする場合は、を参照してください link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["アーカイブバックアップをインポートする"^]



== SnapCenter サーバをインストールします

* SnapCenter Server* をダウンロードしてインストールします

* 手順 *

. から SnapCenter Server インストールパッケージをダウンロードします https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["ネットアップサポートサイト"^] 次に、この exe をダブルクリックします。
+
インストールの開始後、すべての事前確認が実行され、最小要件を満たしていない場合には、対応するエラーまたは警告メッセージが表示されます。警告メッセージは無視してインストールを続行できますが、エラーは修正しておく必要があります。

. SnapCenter サーバのインストールに必要な設定済みの値を確認し、必要に応じて変更します。
+
MySQL Server リポジトリデータベースのパスワードを指定する必要はありません。SnapCenter サーバのインストール時に、パスワードは自動生成されます。

+

NOTE: インストール用のカスタムパスでは、特殊文字“ % ”はサポートされていません。パスに「 % 」を含めると、インストールは失敗します。

. [ 今すぐインストール ] をクリックします。


* SnapCenter * にログインします

* 手順 *

. ホストデスクトップのショートカットまたはインストールによって提供された URL （ SnapCenter Server がインストールされているデフォルトポート 8146 の場合は、 \\ https://server:8146_ ）から SnapCenter を起動します。
. クレデンシャルを入力します。
+
組み込みのドメイン管理者ユーザ名の形式には、 _NetBIOS_<username>_ または _<username>@<domain>_ または _<DomainFQDN>\<username>_ を使用します。

+
組み込みのローカル管理者ユーザ名の形式には、 _<username>_ を使用します。

. [ * サインイン * ] をクリックします。


* SnapCenter 標準コントローラベースライセンス * を追加します

* 手順 *

. ONTAP コマンドラインを使用してコントローラにログインし、次のように入力します。
+
'system license add-license-code <license_key>'

. ライセンスを確認します。
+
「 license show 」を参照してください



* SnapCenter の容量ベースのライセンスを追加 *

* 手順 *

. SnapCenter GUI の左ペインで、 *Settings > Software* をクリックし、 License セクションで *+* をクリックします。
. ライセンスを取得するには、次の 2 つの方法のいずれかを選択します。
+
** ライセンスをインポートするには、ネットアップサポートサイトのログインクレデンシャルを入力します。
** ネットアップライセンスファイルの場所を参照し、 * Open * をクリックします。


. ウィザードの ［ * 通知 * ］ ページで、デフォルトの容量しきい値 90% を使用します。
. [ 完了 ] をクリックします。


* ストレージ・システム接続のセットアップ *

* 手順 *

. 左側のペインで、 * ストレージ・システム > 新規 * をクリックします。
. Add Storage System ページで、次の手順を実行します。
+
.. ストレージシステムの名前または IP アドレスを入力します。
.. ストレージシステムへのアクセスに使用するクレデンシャルを入力します。
.. イベント管理システム（ EMS ）と AutoSupport を有効にするには、チェックボックスを選択します。


. プラットフォーム、プロトコル、ポート、およびタイムアウトに割り当てられたデフォルト値を変更する場合は、 [ その他のオプション *] をクリックします。
. [Submit （送信） ] をクリックします。




== Plug-in for Microsoft SQL Server をインストールします

* Run As クレデンシャルを設定して、 Plug-in for Microsoft SQL Server * をインストールします

* 手順 *

. 左側のペインで、 * Settings > Credentials > New * をクリックします。
. クレデンシャルを入力します。
+
組み込みのドメイン管理者ユーザ名の形式には、 _NetBIOS_<username>_ または _<username>@<domain>_ または _<DomainFQDN>\<username>_ を使用します。

+
組み込みのローカル管理者ユーザ名の形式には、 _<username>_ を使用します。



* ホストを追加し、 Plug-in for Microsoft SQL Server* をインストールします

* 手順 *

. SnapCenter GUI の左ペインで、 *Hosts > Managed Hosts > Add* の順にクリックします。
. ウィザードの ［ ホスト ］ ページで、次の手順を実行します。
+
.. Host Type ： Windows ホストタイプを選択します。
.. ホスト名： SQL ホストを使用するか、専用の Windows ホストの FQDN を指定します。
.. credentials ：作成したホストの有効なクレデンシャル名を選択するか、新しいクレデンシャルを作成します。


. インストールするプラグインの選択セクションで、 * Microsoft SQL Server * を選択します。
. [ その他のオプション ] をクリックして、次の詳細を指定します。
+
.. Port ：デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。
.. インストールパス：デフォルトのパスは、 _C ： \Program Files\NetApp\SnapManager _ です。必要に応じて、パスをカスタマイズできます。
.. Add all hosts in the cluster ： SQL in WSFC を使用している場合は、このチェックボックスを選択します。
.. インストール前チェックをスキップ：プラグインを手動でインストール済みの場合、またはプラグインのインストール要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。


. [Submit （送信） ] をクリックします。

