---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter サーバおよび SnapCenter Plug-in for Microsoft SQL Server をインストールする手順について説明します。 
---
= SnapCenter Plug-in for SQL Serverのインストールのクイックスタート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ServerおよびSnapCenter Plug-in for Microsoft SQL Serverのインストール手順をまとめたものです。



== 設置を準備



=== ドメインとワークグループの要件

SnapCenterサーバは、ドメインまたはワークグループ内のシステムにインストールできます。

Active Directoryドメインを使用している場合は、ローカル管理者の権限を持つドメインユーザを使用する必要があります。ドメインユーザは、Windowsホストのローカルの管理者グループのメンバーである必要があります。

ワークグループを使用している場合は、ローカル管理者の権限を持つローカルアカウントを使用してください。



=== ライセンス要件

インストールするライセンスのタイプは環境によって異なります。

[cols="1,3"]
|===
| ライセンス | 必要な場合 


 a| 
SnapCenter Standard（コントローラベース）
 a| 
FAS、AFF、またはAll SAN Array（ASA）ストレージコントローラに必要です

SnapCenter Standardライセンスはコントローラベースのライセンスで、Premium Bundleに含まれています。SnapManager Suiteライセンスをお持ちの場合は、SnapCenter Standardライセンスの使用権も取得できます。FAS、AFF、またはASAストレージにSnapCenterの試用版をインストールする場合は、営業担当者に連絡してPremium Bundleの評価ライセンスを取得してください。



 a| 
SnapMirrorまたはSnapVault
 a| 
ONTAP

SnapCenterでレプリケーションが有効になっている場合は、SnapMirrorまたはSnapVaultのいずれかのライセンスが必要です。



 a| 
追加ライセンス（オプション）
 a| 
を参照して link:../install/concept_snapcenter_licenses.html["SnapCenterライセンス"^]



 a| 
SnapCenter Standardライセンス（オプション）
 a| 
セカンダリデスティネーション


NOTE: セカンダリデスティネーションにSnapCenter Standardライセンスを追加することを推奨しますが、必須ではありません。セカンダリデスティネーションでSnapCenter Standardライセンスが有効になっていない場合、フェイルオーバー処理の実行後にSnapCenterを使用してセカンダリデスティネーションでリソースをバックアップすることはできません。ただし、クローニング処理と検証処理を実行するには、セカンダリデスティネーションに FlexClone ライセンスが必要です。

|===


=== ホストおよびポートの要件

ONTAPおよびアプリケーションプラグインの最小要件については https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT[]、[Interoperability Matrix Tool^]を参照してください。

[cols="1,3"]
|===
| ホスト | 最小要件 


 a| 
オペレーティングシステム（64ビット）
 a| 
を参照し https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT["Interoperability Matrix Tool"^]



 a| 
CPU
 a| 
* サーバホスト：4コア
* プラグインホスト：1コア




 a| 
RAM
 a| 
* サーバホスト：8 GB
* プラグインホスト：4GB




 a| 
ハードドライブの空き容量
 a| 
サーバホスト：

* SnapCenterサーバソフトウェアおよびログ用に7 GB
* SnapCenterリポジトリ用に8GB
* 各プラグインホスト：2GB（プラグインのインストールとログ用）。プラグインが専用ホストにインストールされている場合にのみ必要です。



NOTE: SnapCenterリポジトリがインストールされているホストにSnapCenterサーバがある場合は、15GBを推奨します。



 a| 
サードパーティライブラリ
 a| 
SnapCenter Serverホストおよびプラグインホストに必要：

* Microsoft .NET Framework 4.7.2以降
* ASP。 Net Core Hosting Bundle（8.0.5以降）
* PowerShell 7.4.2以降




 a| 
ブラウザ
 a| 
Chrome、Internet Explorer、Microsoft Edge

|===
[cols="1,3"]
|===
| ポートタイプ | デフォルトポート 


 a| 
SnapCenterポート
 a| 
8146（HTTPS）、URL _\https://server:8146_のように双方向、カスタマイズ可能



 a| 
SnapCenter SMCore通信ポート
 a| 
8145（HTTPS）、双方向、カスタマイズ可能



 a| 
リポジトリデータベース
 a| 
3306（HTTPS）、双方向



 a| 
Windowsプラグインホスト
 a| 
135、445（TCP）

ポート135と445に加えて、Microsoftが指定したダイナミックポート範囲もオープンにする必要があります。リモートインストール操作では、このポート範囲を動的に検索するWindows Management Instrumentation（WMI）サービスを使用します。

サポートされるダイナミックポート範囲については、を参照してください https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows のサービス概要とネットワークポート要件"^]。



 a| 
Windows向けSnapCenterプラグイン
 a| 
8145（HTTPS）、双方向、カスタマイズ可能



 a| 
ONTAPクラスタまたはSVMの通信ポート
 a| 
443 （ HTTPS ）、双方向、 80 （ HTTP ）、双方向

このポートは、SnapCenterサーバホスト、プラグインホスト、およびSVMまたはONTAPクラスタ間の通信に使用されます。

|===


=== SnapCenter Plug-in for Microsoft SQL Serverの要件

ローカル管理者権限があり、リモートホストに対するローカルログイン権限があるユーザが必要です。クラスタノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限を持つユーザが必要です。

SQL Serverに対するsysadmin権限を持つユーザが必要です。このプラグインはMicrosoft VDI Frameworkを使用しますが、これにはsysadminアクセスが必要です。



== SnapCenterサーバのインストール



=== ステップ1: SnapCenter サーバーをダウンロードしてインストールします

. からSnapCenterサーバインストールパッケージをダウンロードし https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetAppサポートサイト"^] 、exeファイルをダブルクリックします。
+
インストールを開始すると、すべての事前確認が実行され、最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。警告メッセージは無視してインストールを続行できますが、エラーは修正する必要があります。

. SnapCenterサーバのインストールに必要な値があらかじめ入力されていることを確認し、必要に応じて変更します。
+
MySQL Serverリポジトリデータベースのパスワードを指定する必要はありません。SnapCenterサーバのインストール中に、パスワードが自動的に生成されます。

+

NOTE: インストールのカスタムパスでは特殊文字「%」はサポートされていません。パスに「%」を含めると、インストールは失敗します。

. [ 今すぐインストール ] をクリックします。




=== ステップ2：SnapCenter にログインします

. ホストデスクトップ上のショートカットまたはインストール時に表示されたURL（SnapCenterサーバがインストールされているデフォルトポート8146の場合は_\https://server:8146_）からSnapCenterを起動します。
. クレデンシャルを入力します。
+
組み込みのドメイン管理者ユーザ名の形式には、 _NetBIOS_<username>_ または _<username>@<domain>_ または _<DomainFQDN>\<username>_ を使用します。

+
組み込みのローカル管理者ユーザ名の形式には、 _<username>_ を使用します。

. [ * サインイン * ] をクリックします。




=== 手順3：SnapCenter Standardコントローラベースライセンスを追加する

. ONTAPコマンドラインを使用してコントローラにログインし、次のように入力します。
+
`system license add -license-code <license_key>`

. ライセンスを確認します。
+
`license show`





=== 手順4：ストレージシステム接続をセットアップする

. 左側のペインで、 * ストレージ・システム > 新規 * をクリックします。
. [Add Storage System]ページで、次の手順を実行します。
+
.. ストレージシステムの名前またはIPアドレスを入力します。
.. ストレージシステムへのアクセスに使用するクレデンシャルを入力します。
.. チェックボックスをオンにして、イベント管理システム（EMS）とAutoSupportを有効にします。


. プラットフォーム、プロトコル、ポート、およびタイムアウトに割り当てられたデフォルト値を変更する場合は、 [ その他のオプション *] をクリックします。
. [Submit （送信） ] をクリックします。




== Plug-in for Microsoft SQL Serverのインストール



=== 手順1：Run AsクレデンシャルをセットアップしてPlug-in for Microsoft SQL Serverをインストールする

. 左側のペインで、 * Settings > Credentials > New * をクリックします。
. クレデンシャルを入力します。
+
組み込みのドメイン管理者ユーザ名の形式には、 _NetBIOS_<username>_ または _<username>@<domain>_ または _<DomainFQDN>\<username>_ を使用します。

+
組み込みのローカル管理者ユーザ名の形式には、 _<username>_ を使用します。





=== 手順2：ホストを追加してPlug-in for Microsoft SQL Serverをインストールする

. SnapCenter GUI の左ペインで、 *Hosts > Managed Hosts > Add* の順にクリックします。
. ウィザードの[Hosts]ページで、次の手順を実行します。
+
.. Host Type：Windowsホストタイプを選択します。
.. ホスト名：SQLホストを使用するか、専用のWindowsホストのFQDNを指定します。
.. Credentials：作成したホストの有効なクレデンシャル名を選択するか、新しいクレデンシャルを作成します。


. インストールするプラグインの選択セクションで、 * Microsoft SQL Server * を選択します。
. [ その他のオプション ] をクリックして、次の詳細を指定します。
+
.. ポート：デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。
.. インストールパス：デフォルトのパスは、 _C ： \Program Files\NetApp\SnapManager _ です。必要に応じてパスをカスタマイズできます。
.. クラスタ内のすべてのホストを追加：WSFCでSQLを使用している場合は、このチェックボックスをオンにします。
.. インストール前チェックをスキップ：プラグインを手動でインストール済みの場合、またはプラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスをオンにします。


. [Submit （送信） ] をクリックします。

