---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter ServerおよびSnapCenter Plug-in for Microsoft SQL Serverのインストールの準備手順について説明します。 
---
= SnapCenter サーバとプラグインのインストールを準備します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ServerおよびSnapCenter Plug-in for Microsoft SQL Serverをインストールするための準備手順をまとめたものです。



== ドメインとワークグループの要件

SnapCenterサーバは、ドメインまたはワークグループ内のシステムにインストールできます。

Active Directoryドメインを使用している場合は、ローカル管理者の権限を持つドメインユーザを使用する必要があります。ドメインユーザは、Windowsホストのローカルの管理者グループのメンバーである必要があります。

ワークグループを使用している場合は、ローカル管理者の権限を持つローカルアカウントを使用してください。



== ライセンス要件

インストールするライセンスのタイプは環境によって異なります。

[cols="1,3"]
|===
| ライセンス | 必要な場合 


 a| 
SnapCenter Standard（コントローラベース）
 a| 
FASマタハAFFストレエシコントロオラニヒツヨウ

SnapCenter Standardライセンスはコントローラベースのライセンスで、Premium Bundleに含まれています。SnapManager Suiteライセンスをお持ちの場合は、SnapCenter Standardライセンスの使用権も取得できます。FASまたはAFFストレージにSnapCenterの試用版をインストールする場合は、営業担当者にお問い合わせください。



 a| 
SnapMirrorまたはSnapVault
 a| 
ONTAP

SnapCenterでレプリケーションが有効になっている場合は、SnapMirrorまたはSnapVaultのいずれかのライセンスが必要です。



 a| 
追加ライセンス（オプション）
 a| 
を参照して link:../install/concept_snapcenter_licenses.html["SnapCenterライセンス"^]



 a| 
SnapCenter Standardライセンス（オプション）
 a| 
セカンダリデスティネーション


NOTE: セカンダリデスティネーションにSnapCenter Standardライセンスを追加することを推奨しますが、必須ではありません。セカンダリデスティネーションでSnapCenter Standardライセンスが有効になっていない場合、フェイルオーバー処理の実行後にSnapCenterを使用してセカンダリデスティネーションでリソースをバックアップすることはできません。ただし、クローニング処理と検証処理を実行するには、セカンダリデスティネーションに FlexClone ライセンスが必要です。

|===


== ホストおよびポートの要件

ONTAPおよびアプリケーションプラグインの最小要件については https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT[]、[Interoperability Matrix Tool^]を参照してください。

[cols="1,3"]
|===
| ホスト | 最小要件 


 a| 
オペレーティングシステム（64ビット）
 a| 
を参照し https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT["Interoperability Matrix Tool"^]



 a| 
CPU
 a| 
* サーバホスト：4コア
* プラグインホスト：4コア




 a| 
RAM
 a| 
* サーバホスト：8 GB
* プラグインホスト：4GB




 a| 
ハードドライブの空き容量
 a| 
サーバホスト：

* SnapCenterサーバソフトウェアおよびログ用に7 GB
* SnapCenterリポジトリ用に8GB
* 各プラグインホスト：2GB（プラグインのインストールとログ用）。プラグインが専用ホストにインストールされている場合にのみ必要です。




 a| 
サードパーティライブラリ
 a| 
SnapCenter Serverホストおよびプラグインホストに必要：

* Microsoft .NET Framework 4.7.2以降
* ASP。 Net Core Hosting Bundle（8.0.5以降）
* PowerShell 7.4.2以降




 a| 
ブラウザ
 a| 
Chrome、Internet Explorer、Microsoft Edge

|===
[cols="1,3"]
|===
| ポートタイプ | デフォルトポート 


 a| 
SnapCenterポート
 a| 
8146（HTTPS）、URL _\https://server:8146_のように双方向、カスタマイズ可能



 a| 
SnapCenter SMCore通信ポート
 a| 
8145（HTTPS）、双方向、カスタマイズ可能



 a| 
リポジトリデータベース
 a| 
3306（HTTPS）、双方向



 a| 
Windowsプラグインホスト
 a| 
135、445（TCP）

ポート135と445に加えて、Microsoftが指定したダイナミックポート範囲もオープンにする必要があります。リモートインストール操作では、このポート範囲を動的に検索するWindows Management Instrumentation（WMI）サービスを使用します。

サポートされるダイナミックポート範囲については、を参照してください https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows のサービス概要とネットワークポート要件"^]。



 a| 
Windows向けSnapCenterプラグイン
 a| 
8145（HTTPS）、双方向、カスタマイズ可能



 a| 
ONTAPクラスタまたはSVMの通信ポート
 a| 
443 （ HTTPS ）、双方向、 80 （ HTTP ）、双方向

このポートは、SnapCenterサーバホスト、プラグインホスト、およびSVMまたはONTAPクラスタ間の通信に使用されます。

|===


== SnapCenter Plug-in for Microsoft SQL Serverの要件

ローカル管理者権限があり、リモートホストに対するローカルログイン権限があるユーザが必要です。クラスタノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限を持つユーザが必要です。

SQL Serverに対するsysadmin権限を持つユーザが必要です。このプラグインはMicrosoft VDI Frameworkを使用しますが、これにはsysadminアクセスが必要です。

SnapManager for Microsoft SQL Serverを使用していて、SnapManager for Microsoft SQL ServerからSnapCenterにデータをインポートする場合は、を参照してください。 link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["アーカイブバックアップをインポートする"^]
