---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter を使用すると、リソースグループまたはデータベースからクローンを作成できます。クローニングはオンデマンドで実行することも、リソースグループまたはデータベースの定期的なクローニング処理をスケジュール設定することもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。 
---
= クローンライフサイクルの実行
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用すると、リソースグループまたはデータベースからクローンを作成できます。クローニングはオンデマンドで実行することも、リソースグループまたはデータベースの定期的なクローニング処理をスケジュール設定することもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。

SnapCenter では、複数のサーバで同時に複数のクローニング処理を実行するようにスケジュールを設定できます。

* 必要なもの *

* スタンドアロンデータベースインスタンスにクローニングする際には、マウントポイントパスが存在し、専用ディスクであることを確認してください。
* フェイルオーバークラスタインスタンス（ FCI ）にクローニングする際は、マウントポイントが存在すること、共有ディスクであること、およびパスと FCI が同じ SQL リソースグループに属していることを確認してください。
* ソースデータベースまたはターゲットインスタンスがクラスタ共有ボリューム（ CSV ）上にある場合、クローニングされたデータベースは CSV 上に作成されます。



NOTE: 仮想環境（ VMDK / RDM ）の場合は、マウントポイントが専用ディスクであることを確認します。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [* リソース ] ページで、 [ * 表示 ] リストから [ * データベース * ] または [ * リソースグループ * ] を選択します。
. リソースグループまたはデータベースを選択し、 * クローンライフサイクル * をクリックします。
. [* オプション * （ * Options * ） ] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
クローンジョブ名
 a| 
クローンライフサイクルジョブの名前を指定します。この名前は、クローンライフサイクルジョブを監視および変更する際に役立ちます。



 a| 
クローンサーバ
 a| 
クローンをどのホストに配置するかを選択します。



 a| 
インスタンスをクローニングします
 a| 
データベースのクローニング先となるクローンインスタンスを選択します。指定したクローンサーバ上の SQL インスタンスを選択する必要があります。



 a| 
クローンのサフィックス
 a| 
クローンデータベースに付加される、クローンであることを示すサフィックスを入力します。クローンリソースグループの作成に使用する各 SQL インスタンスには、一意のデータベース名が必要です。たとえば、クローンリソースグループに SQL インスタンス「 inst1 」からのソースデータベース「 `d b1' 」が含まれ、「 `db1' 」が「 inst1' 」にクローンされている場合、クローンデータベース名は「 `d b1_clone_` 」になります。データベースが同じインスタンスにクローンされるため '`__ clone は ' ユーザー定義の必須サフィックスです「 `db1' 」が SQL インスタンス「 inst2` 」にクローンされている場合、データベースは別のインスタンスにクローンされるため、クローンデータベース名は「 `db1' 」のままでかまいません（サフィックスはオプションです）。



 a| 
Auto assign mount point または Auto assign volume mount point under path
 a| 
マウントポイントを自動的に割り当てるか、またはパスを指定してボリュームマウントポイントを自動的に割り当てるかを選択します。パスの下にボリュームマウントポイントを自動で割り当てることを選択すると、特定のディレクトリを指定できます。指定したディレクトリにマウントポイントが作成されます。このオプションを選択する前に、ディレクトリが空であることを確認する必要があります。ディレクトリにデータベースが格納されている場合、そのデータベースはマウント処理後に無効な状態になります。

|===
. [ * 場所 * ] ページで、クローンを作成するストレージの場所を選択します。
. [ * スクリプト * ] ページで、クローニング処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、 SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+
デフォルトのスクリプトタイムアウトは 60 秒です。

. [ スケジュール *] ページで、次のいずれかの操作を実行します。
+
** クローニングジョブをすぐに実行する場合は、「 * Run Now * 」を選択します。
** クローン処理の実行頻度、クローンスケジュールの開始日時、クローニング処理の実行日、スケジュールの期限、スケジュールの期限が切れたあとにクローンを削除する必要があるかどうかを指定する場合は、 * Configure schedule * を選択します。


. [*Notification] ページの [*Email preference*] ドロップダウンリストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者の E メールアドレス、および E メールの件名を指定する必要があります。実行したクローン処理のレポートを添付する場合は、 * ジョブレポートの添付 * を選択します。

+

NOTE: E メール通知を利用する場合は、 GUI または PowerShell コマンド Set-SmtpServer を使用して、 SMTP サーバの詳細を指定しておく必要があります。

+
EMS については、を参照してください https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection["EMS データ収集を管理します"]

. 概要を確認し、 [ 完了 ] をクリックします。


クローニング処理は、 * Monitor * > * Jobs * ページで監視する必要があります。
