---
permalink: protect-scsql/task_reseed_availability_group_databases.html 
sidebar: sidebar 
keywords: reseed 
summary: 再シードは、可用性グループ（ AG ）データベースをリストアするためのオプションです。セカンダリデータベースがAG内のプライマリデータベースと同期していない場合は、セカンダリデータベースを再シードできます。 
---
= 可用性グループデータベースの再シード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
再シードは、可用性グループ（AG）データベースをリストアするためのオプションです。セカンダリデータベースがAG内のプライマリデータベースと同期していない場合は、セカンダリデータベースを再シードできます。

.開始する前に
* リストアするセカンダリAGデータベースのバックアップを作成しておく必要があります。
* SnapCenterサーバとプラグインホストに同じバージョンのSnapCenterがインストールされている必要があります。


.タスクの内容
* プライマリデータベースでは再シード処理を実行できません。
* 可用性グループからレプリカデータベースが削除されると、再シード処理を実行できません。レプリカが削除されると、再シード処理は失敗します。
* SQL可用性グループデータベースで再シード処理を実行する際には、その可用性グループデータベースのレプリカデータベースでログバックアップをトリガーしないでください。再シード処理中にログバックアップをトリガーすると、再シード処理が失敗し、ミラーデータベース「database_name」にプリンシパルデータベースエラーメッセージのログバックアップチェーンを保持するための十分なトランザクションログデータがありません。


.手順
. 左側のナビゲーションペインで、 [* リソース *] をクリックし、リストから [* SnapCenter Plug-in for SQL Server] を選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * データベース * ] を選択します。
. リストからセカンダリAGデータベースを選択します。
. [Reseed-*] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。

