---
permalink: protect-scsql/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_sql.html 
sidebar: sidebar 
keywords: credentials 
summary: PowerShell コマンドレットを使用してデータ保護処理を実行するには、 Storage Virtual Machine （ SVM ）接続とクレデンシャルを作成する必要があります。 
---
= PowerShell コマンドレットを使用してストレージシステム接続とクレデンシャルを作成します
:icons: font
:imagesdir: ../media/


PowerShell コマンドレットを使用してデータ保護処理を実行するには、 Storage Virtual Machine （ SVM ）接続とクレデンシャルを作成する必要があります。

* 必要なもの *

* PowerShell コマンドレットを実行できるように PowerShell 環境を準備しておく必要があります。
* ストレージ接続を作成するには、 Infrastructure Admin ロールに必要な権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ホスト・プラグインのインストールは ' ストレージ・システム接続の追加中は実行しないでくださいホスト・キャッシュが更新されず ' データベース・ステータスが SnapCenter GUI に表示される場合がありますこれは ' バックアップには使用できませんまたは NetApp ストレージには使用できません

* ストレージシステム名は一意である必要があります。
+
SnapCenter では、異なるクラスタに同じ名前のストレージシステムを複数配置することはサポートされていません。SnapCenter でサポートされるストレージシステムには、それぞれ一意の名前および管理 LIF の IP アドレスを割り当てる必要があります。



* 手順 *

. Open-SmConnection コマンドレットを使用して、 PowerShell 接続セッションを開始します。
+
PowerShell セッションを開く例を次に示します。

+
[listing]
----
PS C:\> Open-SmConnection
----
. Add-SmStorageConnection コマンドレットを使用して、ストレージシステムへの新しい接続を作成します。
+
この例では、新しいストレージシステム接続を作成しています。

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Add-SmCredential コマンドレットを使用して新しいクレデンシャルを作成します。
+
この例は、 Windows クレデンシャルを使用して FinanceAdmin という名前の新しいクレデンシャルを作成します。

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
