---
permalink: protect-scsql/task_install_snapcenter_plug_in_package_for_windows_server_on_multiple_remote_hosts_using_cmdlets_scsql.html 
sidebar: sidebar 
keywords: credentials 
summary: PowerShellコマンドレットInstall-SmHostPackageを使用すると、SnapCenter Plug-in for Microsoft SQL Serverを複数のホストに同時にインストールできます。 
---
= コマンドレットを使用した複数のリモートホストへのSnapCenter Plug-in for Microsoft SQL Serverのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShellコマンドレットInstall-SmHostPackageを使用すると、SnapCenter Plug-in for Microsoft SQL Serverを複数のホストに同時にインストールできます。

.開始する前に
プラグインパッケージをインストールする各ホストに対するローカル管理者権限を持つドメインユーザとしてSnapCenterにログインしておく必要があります。

.手順
. PowerShellを起動します。
. SnapCenterサーバホストで、Open-SmConnectionコマンドレットを使用してセッションを確立し、クレデンシャルを入力します。
. Install-SmHostPackageコマンドレットと必要なパラメータを使用して、複数のリモートホストにSnapCenter Plug-in for Microsoft SQL Serverをインストールします。
+
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。

+
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、 -skipprecheck オプションを使用できます。

. リモートインストールのクレデンシャルを入力します。

