---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter を使用すると、リソースグループまたはデータベースからクローンを作成できます。クローニングはオンデマンドで実行することも、リソースグループまたはデータベースの定期的なクローニング処理をスケジュール設定することもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。 
---
= クローンライフサイクルの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用すると、リソースグループまたはデータベースからクローンを作成できます。クローニングはオンデマンドで実行することも、リソースグループまたはデータベースに対して定期的なクローニング処理をスケジュール設定することもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。

SnapCenter では、複数のサーバで同時に複数のクローニング処理を実行するようにスケジュールを設定できます。

.開始する前に
* スタンドアロンデータベースインスタンスにクローニングする場合は、マウントポイントパスが存在し、専用ディスクであることを確認してください。
* フェイルオーバークラスタインスタンス（FCI）にクローニングする場合は、マウントポイントが存在し、共有ディスクであること、およびパスとFCIが同じSQLリソースグループに属していることを確認してください。
* ソースデータベースまたはターゲットインスタンスがクラスタ共有ボリューム（CSV）上にある場合、クローニングされたデータベースはCSV上に配置されます。



NOTE: 仮想環境（VMDK / RDM）の場合は、マウントポイントが専用ディスクであることを確認します。

.タスクの内容
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

* クローンライフサイクルウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要なフィールドを取り上げます。
* ONTAP 9.12.1以前のバージョンでは、Snapshotロック期間を指定すると、改ざん防止Snapshotから作成されたクローンにSnapLockの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。


.手順
. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * データベース * ] または [ * リソースグループ * ] を選択します。
. リソースグループまたはデータベースを選択し、 * クローンライフサイクル * をクリックします。
. [ オプション ] ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
クローンジョブ名
 a| 
クローンライフサイクルジョブの監視や変更に役立つ名前を指定します。



 a| 
クローンサーバ
 a| 
クローンをどのホストに配置するかを選択します。



 a| 
クローンインスタンス
 a| 
データベースのクローニング先となるクローンインスタンスを選択します。指定したクローンサーバ上のSQLインスタンスを指定する必要があります。



 a| 
クローンサフィックス
 a| 
クローンデータベースに付加される、クローンデータベースであることを示すサフィックスを入力します。クローンリソースグループの作成に使用する各SQLインスタンスには、一意のデータベース名が必要です。たとえば、クローンリソースグループに SQL インスタンス「 inst1 」からのソースデータベース「 `d b1' 」が含まれ、「 `db1' 」が「 inst1' 」にクローンされている場合、クローンデータベース名は「 `d b1_clone_` 」になります。データベースが同じインスタンスにクローンされるため '`__ clone は ' ユーザー定義の必須サフィックスです「 `db1' 」が SQL インスタンス「 inst2` 」にクローンされている場合、データベースは別のインスタンスにクローンされるため、クローンデータベース名は「 `db1' 」のままでかまいません（サフィックスはオプションです）。



 a| 
Auto assign mount pointまたはAuto assign volume mount point under path
 a| 
マウントポイントを自動的に割り当てるか、パスを使用してボリュームマウントポイントを自動的に割り当てるかを選択します。パスを使用してボリュームマウントポイントを自動割り当てするように選択すると、特定のディレクトリを指定できます。マウントポイントは、そのディレクトリ内に作成されます。このオプションを選択する前に、ディレクトリが空であることを確認する必要があります。ディレクトリにデータベースが格納されている場合、そのデータベースはマウント処理後に無効な状態になります。

|===
. [ 場所 ] ページで、クローンを作成するストレージの場所を選択します。
. スクリプトページで、クローニング処理の実行前または実行後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信などを行うスクリプトを実行できます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

+
デフォルトのスクリプトタイムアウトは60秒です。

. [ スケジュール ] ページで、次のいずれかの操作を実行します。
+
** クローニングジョブをすぐに実行する場合は、「 * Run Now * 」を選択します。
** クローン処理の実行頻度、クローンスケジュールの開始日時、クローニング処理の実行日、スケジュールの期限、スケジュールの期限が切れたあとにクローンを削除する必要があるかどうかを指定する場合は、 * Configure schedule * を選択します。


. [ 通知 ] ページの [ 電子メールの設定 *] ドロップダウンリストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者のEメールアドレス、およびEメールの件名を指定する必要があります。実行したクローン処理のレポートを添付する場合は、 * ジョブレポートの添付 * を選択します。

+

NOTE: Eメール通知を使用する場合は、GUIまたはPowerShellコマンドSet-SmSmSmtpServerを使用して、SMTPサーバの詳細を指定しておく必要があります。

+
EMSの場合は、 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["EMSデータ収集の管理"]

. 概要を確認し、 [ 完了 ] をクリックします。


クローニング処理は、 * Monitor * > * Jobs * ページで監視する必要があります。
