---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords:  
summary: クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。 
---
= SQL Server のクローニング戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。

. クローニング処理に関する制限事項を確認します。
. 必要なクローンのタイプを決定します。




== クローニング処理の制限事項

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* Oracle 11.2.0.4 ～ 12.1.0.1 のいずれかのバージョンを使用している場合、 _renamedg_command の実行時にクローン操作がハング状態になります。この問題を修正するには、 Oracle パッチ 19544733 を適用します。
* ホストに直接接続された LUN （ Windows ホストで Microsoft iSCSI イニシエータを使用した場合など）から、同じ Windows ホストまたは別の Windows ホスト上の VMDK または RDM LUN に、あるいはその逆に、データベースをクローニングすることはできません。
* ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* クローンが含まれている LUN を新しいボリュームに移動した場合、そのクローンは削除できません。




== クローニング処理のタイプ

SnapCenter を使用して、 SQL Server データベースのバックアップまたは本番環境のデータベースをクローニングすることができます。

* データベースバックアップからのクローニング
+
クローンデータベースは、新しいアプリケーションを開発する場合のベースラインとして使用でき、本番環境で発生したアプリケーションエラーの切り分けにも役立ちます。データベースのソフトエラーからのリカバリにも使用できます。

* クローンのライフサイクル
+
SnapCenter を使用して、本番環境のデータベースがビジー状態でないときに定期的なクローニングジョブをスケジュール設定できます。


