---
permalink: protect-scsql/task_failback_from_scsql_secondary_storage_to_primary_storage.html 
sidebar: sidebar 
keywords: failback, snapcenter 
summary: SnapCenter Plug-in for SQL Serverプライマリストレージがオンラインに戻ったら、プライマリストレージにフェイルバックする必要があります。 
---
= SnapCenter Plug-in for SQL Serverセカンダリストレージからプライマリストレージへのフェイルバック
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for SQL Serverプライマリストレージがオンラインに戻ったら、プライマリストレージにフェイルバックする必要があります。

.開始する前に
* Managed Hosts ページから SnapCenter Plug-in for SQL Server を * Maintenance * モードにします。
* セカンダリストレージをホストから切断し、プライマリストレージから接続します。
* プライマリストレージにフェイルバックするには、逆再同期処理を実行して、関係の方向がフェイルオーバー前と同じであることを確認します。
+
逆再同期処理の実行後もプライマリストレージとセカンダリストレージのロールを保持するには、逆再同期処理をもう一度実行します。

+
詳細については、 link:https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_reverse_resynchronizing_snapmirror_relationships.html["ミラー関係を逆再同期しています"]

* MSSQLサーバーサービスを再起動します。
* SQLリソースがオンラインに戻っていることを確認します。



NOTE: プラグインのフェイルオーバーまたはフェイルバック中、プラグインの全体的なステータスはすぐには更新されません。ホストおよびプラグインの全体的なステータスは、次回のホスト更新処理で更新されます。

.手順
. 設定ページで、 * 設定 * > * グローバル設定 * > * ディザスタ・リカバリ * と進みます。
. [Enable Disaster Recovery] を選択解除します。
. [ 適用（ Apply ） ] をクリックします。
. DR ジョブが有効になっているかどうかを確認するには、 * Monitor * > * Jobs * をクリックします。


.終了後
フェイルオーバー中に作成されたSnapCenter Plug-in for SQL Serverのバックアップは、UIまたは次のコマンドレットを使用して削除できます。 `Remove-SmDRFailoverBackups`
