---
permalink: protect-scsql/task_reseed_availability_group_databases.html 
sidebar: sidebar 
keywords:  
summary: 再シードは、可用性グループ（ AG ）データベースをリストアするためのオプションです。セカンダリデータベースが AG 内のプライマリデータベースと同期していない場合は、セカンダリデータベースを再シードできます。 
---
= 可用性グループデータベースを再シードしています
:icons: font
:imagesdir: ../media/


[role="lead"]
再シードは、可用性グループ（ AG ）データベースをリストアするためのオプションです。セカンダリデータベースが AG 内のプライマリデータベースと同期していない場合は、セカンダリデータベースを再シードできます。

* 必要なもの *

* リストアするセカンダリ AG データベースのバックアップを作成しておく必要があります。
* SnapCenter サーバとプラグインホストに同じ SnapCenter バージョンがインストールされている必要があります。


* このタスクについて *

* プライマリデータベースには再シード処理を実行できません。
* 可用性グループからレプリカデータベースが削除された場合は、再シード処理を実行できません。レプリカを削除すると、再シード処理が失敗します。
* SQL 可用性グループデータベースで再シード処理を実行する場合、その可用性グループデータベースのレプリカデータベースでログバックアップをトリガーしないでください。再シード処理中にログバックアップをトリガーすると、ミラーデータベースの再シード処理が失敗し、「 database_name 」にはプリンシパルデータベースのログバックアップチェーンを保持するための十分なトランザクションログデータがありませんというエラーメッセージが表示されます。


* 手順 *

. 左側のナビゲーションペインで、 [* リソース *] をクリックし、リストから [* SnapCenter Plug-in for SQL Server] を選択します。
. [ * リソース * ] ページで、 [ * 表示 ] リストから [ * データベース * ] を選択します。
. リストからセカンダリ AG データベースを選択します。
. [Reseed-*] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。

