---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter Plug-in for Microsoft Windows を使用してネットアップストレージシステムをプロビジョニングしたら、 SnapCenter グラフィカルユーザインターフェイス \ （ GUI\ ）または PowerShell コマンドレットを使用して、リソースをネットアップストレージシステムに移行するか、またはあるネットアップ LUN から別のネットアップ LUN に移行できます。 
---
= ネットアップストレージシステムにリソースを移行
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft Windows を使用してネットアップストレージシステムをプロビジョニングしたら、 SnapCenter グラフィカルユーザインターフェイス（ GUI ）または PowerShell コマンドレットを使用して、リソースをネットアップストレージシステムに移行するか、またはあるネットアップ LUN から別のネットアップ LUN に移行できます。

* 必要なもの *

* SnapCenter サーバにストレージシステムを追加しておく必要があります。
* SQL Server リソースを更新（検出）しておく必要があります。


ウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要な一部のフィールドを取り上げます。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [* リソース ] ページで、 [* ビュー *] ドロップダウン・リストから [* データベース *] または [* インスタンス *] を選択します。
. リストからデータベースまたはインスタンスを選択し、 * Migrate * をクリックします。
. [* リソース *] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
* データベース名 * （オプション）
 a| 
移行用のインスタンスを選択した場合は、そのインスタンスのデータベースを「 * Databases * 」ドロップダウンリストから選択する必要があります。



 a| 
* 目的地を選択 *
 a| 
データファイルとログファイルの保存先を選択します。

データファイルとログファイルは、選択したネットアップドライブの下の Data フォルダと Log フォルダにそれぞれ移動されます。フォルダ構造内にフォルダがない場合は、フォルダが作成され、リソースが移行されます。



 a| 
* データベースファイルの詳細を表示 * （オプション）
 a| 
このオプションは、 1 つのデータベースの複数のファイルを移行する場合に選択します。


NOTE: このオプションは、 * Instance * リソースを選択した場合には表示されません。



 a| 
* オプション *
 a| 
「 * 元の場所にある移行済みデータベースのコピーを削除する * 」を選択して、ソースからデータベースのコピーを削除します。

オプション： * データベースの接続を解除する前にテーブルに対して UPDATE STATISTICS を実行します。 *

|===
. [*verify*] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
* データベース整合性チェックオプション *
 a| 
移行前にデータベースの整合性をチェックするには、 * Run Before * を選択します。移行後にデータベースの整合性をチェックするには、 * Run After * を選択します。



 a| 
*DBCC CHECKDB オプション *
 a| 
** 整合性チェックの対象をデータベースの物理構造に限定し、データベースに影響を与える正しくないページ、チェックサム障害、および一般的なハードウェア障害を検出するには、「 * physical_only * 」オプションを選択します。
** すべての情報メッセージを停止するには、「 * NO_INFOMSGS * 」オプションを選択します。
** レポートされたエラーをオブジェクトごとにすべて表示するには、 * ALLERRORGS* オプションを選択します。
** 非クラスタ化インデックスをチェックしない場合は、 * noindex * オプションを選択します。
+
SQL Server データベースは、 Microsoft SQL Server の Database Consistency Checker （ DBCC ）を使用して、データベース内のオブジェクトの論理的な整合性と物理的な整合性をチェックします。

+

NOTE: このオプションを選択すると、実行時間を短縮できます。

** 内部データベースの Snapshot コピーを使用する代わりに、チェックを制限してロックを取得するには、 **TABLOCK ** オプションを選択します。


|===
. 概要を確認し、 [** 終了 ** ] をクリックします。

