---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenter を使用して SQL Server リソースをバックアップする前に、リソースまたはリソースグループのバックアップポリシーを作成することができます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。 
---
= SQL Serverデータベースのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して SQL Server リソースをバックアップする前に、リソースまたはリソースグループのバックアップポリシーを作成することができます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。

.開始する前に
* データ保護戦略を定義しておく必要があります。
* SnapCenter のインストール、ホストの追加、リソースの特定、ストレージシステム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* ログバックアップ用のホストログディレクトリを設定しておく必要があります。
* SQL Serverリソースをリフレッシュ（検出）しておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートする場合は、SnapCenter管理者がソースボリュームとデスティネーションボリュームの両方のStorage Virtual Machine（SVM）をユーザに割り当てておく必要があります。
+
管理者によるユーザへのリソースの割り当て方法については、 SnapCenter のインストール情報を参照してください。

* プリスクリプトとポストスクリプトでPowerShellスクリプトを実行する場合は、web.configファイルでusePowershellProcessforScriptsパラメータの値をtrueに設定する必要があります。
+
デフォルト値はfalseです。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"]。


.タスクの内容
* バックアップポリシーは、バックアップを管理および保持する方法、およびリソースまたはリソースグループをバックアップする頻度を規定する一連のルールです。レプリケーションとスクリプトの設定を指定することもできます。ポリシーでオプションを指定することで、別のリソースグループにポリシーを再利用して時間を節約できます。
+
scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。

+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
+
Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。

+
ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。







== 手順1：ポリシー名を作成します

. 左側のナビゲーションペインで、*[設定]*を選択します。
. [設定]ページで、*[ポリシー]*を選択します。
. [New]*を選択します。
. [名前*]ページで、ポリシーの名前と詳細を入力します。




== 手順2：ポリシーオプションを設定する

. [Policy type]ページで、次の手順を実行します。
+
.. ストレージタイプを選択します。
.. ポリシーの範囲を選択します。
+
[role="tabbed-block"]
====
.フルバックアップとログバックアップ
--
データベースファイルとトランザクションログをバックアップし、トランザクションログを切り捨てます。

... [ フルバックアップおよびログバックアップ * ] を選択します。
... Snapshotごとにバックアップするデータベースの最大数を入力します。
+

NOTE: 同時に複数のバックアップ処理を実行する場合は、この値を増やす必要があります。



--
.フルバックアップ
--
データベースファイルをバックアップします。

... [* Full backup* ] を選択します。
... Snapshotごとにバックアップするデータベースの最大数を入力します。デフォルト値は100
+

NOTE: 同時に複数のバックアップ処理を実行する場合は、この値を増やす必要があります。



--
.ログバックアップ
--
... トランザクションログをバックアップします。
... 「 * Log backup * 」を選択します。


--
.コピーのみのバックアップ
--
... 別のバックアップ・アプリケーションを使用してリソースをバックアップする場合は、 [* コピーのみのバックアップ * ] を選択します。


トランザクションログをそのまま保持すると、すべてのバックアップアプリケーションでデータベースをリストアできます。通常、他の状況ではコピーのみのオプションを使用しないでください。


NOTE: Microsoft SQL では、セカンダリ・ストレージのフル・バックアップおよびログ・バックアップ * オプションと * コピーのみのバックアップ * オプションはサポートされていません。

--
====






== 手順3：可用性グループを設定する

. 可用性グループの設定セクションで、次の操作を実行します。
+
.. 優先バックアップレプリカのみにバックアップ。
+
優先バックアップレプリカのみをバックアップする場合は、このオプションを選択します。優先バックアップレプリカは、SQL ServerのAGに対して設定されたバックアップ設定によって決まります。

.. バックアップするレプリカを選択します。
+
バックアップするプライマリまたはセカンダリのAGレプリカを選択します。

.. バックアップ優先度の選択（最小および最大バックアップ優先度）
+
バックアップのAGレプリカを決定する最小バックアップ優先順位と最大バックアップ優先順位を指定します。たとえば、最小優先度を10、最大優先度を50に設定できます。この場合、優先度が10より大きく50未満のすべてのAGレプリカがバックアップ対象とみなされます。

+
デフォルトでは、最小プライオリティは1、最大プライオリティは100です。



+

NOTE: クラスタ構成では、ポリシーで設定された保持設定に従って、バックアップがクラスタの各ノードで保持されます。AGの所有者ノードが変更された場合、保持設定に従ってバックアップが作成され、以前の所有者ノードのバックアップが保持されます。AGの保持設定はノードレベルでのみ適用されます。





== 手順4：Snapshotとレプリケーションの設定を構成する

. [Snapshot and Replication]ページで、次の手順を実行します。
+
.. スケジュールタイプを指定するには、「 * on demand * 」、「 * Hourly * 」、「 * Daily * 」、「 * Weekly * 」、または「 * Monthly * 」を選択します。
+
ポリシーに対して選択できるスケジュールタイプは1つだけです。

+

NOTE: リソースグループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定できます。これにより、ポリシーとバックアップ頻度が同じであるリソースグループを作成できますが、各ポリシーに異なるバックアップスケジュールを割り当てることができます。

+

NOTE: 午前2時にスケジュールを設定している場合、夏時間（DST）中はスケジュールはトリガーされません。







== 手順5：最新の状態へのリストア保持を設定する

. [Up-to-the-minute retention settings]セクションで、[Backup type]ページで選択したバックアップタイプに応じて、次の操作を1つ以上実行します。


[role="tabbed-block"]
====
.特定のコピー数
--
特定の数のSnapshotのみを保持します。

. ［ * 最新の < 日数 > 日数に適用可能なログバックアップを保持する ］ オプションを選択し、保持する日数を指定します。この上限に近づいた場合は、古いコピーを削除できます。


--
.特定の日数
--
バックアップコピーを特定の日数だけ保持します。

. ［ * 最新の < 日数 > フル・バックアップに適用可能なログ・バックアップを保持する ］ オプションを選択し、ログ・バックアップ・コピーを保持する日数を指定します。


--
====


== 手順6：Snapshotを設定する

. フルバックアップの保持設定では、次の操作を実行します。
+
.. 保持するSnapshotの総数を指定してください
+
... 保持するSnapshotの数を指定するには、*保持するコピー*を選択します。
... Snapshotの数が指定した数を超えると、最も古いコピーから順にSnapshotが削除されます。







IMPORTANT: デフォルトでは、保持数の値は2に設定されています。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗する可能性があります。


NOTE: 最大保持値は1018です。保持数を使用しているNetApp ONTAPバージョンでサポートされる値よりも大きい値に設定すると、バックアップは失敗します。

. Snapshotを保持する時間の長さ
+
.. Snapshotを保持してから削除するまでの日数を指定する場合は、*[コピーの保持期間]*を選択します。


. プライマリSnapshotコピーのロック期間を指定する場合は、*プライマリSnapshotコピーのロック期間*を選択し、日、月、または年を選択します。
+
SnapLock保持期間は100年未満にする必要があります。

. セカンダリSnapshotコピーのロック期間を指定する場合は、*[セカンダリSnapshotコピーのロック期間]*を選択し、日、月、または年を選択します。
+
この例では、ログSnapshotの保持期間を2に設定しています。

+
.例を示します
[]
====
Set-SmPolicy-PolicyName 'newpol'-PolicyType 'Backup'-PluginPolicyType 'SCSQL'-sqlbackuptype 'FullBackupAndLogBackup'-RetentionSettings@｛backupType='Hourly'；RetentionCount=2｝、@｛backupType='log_snapshot'；ScheduleType=2｝

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_retains_Snapshot_copies_of_the_database["SnapCenterがデータベースのSnapshotコピーを保持"]

. Snapshotラベルを選択してください
+
選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。

+

NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。





== 手順7：セカンダリレプリケーションオプションを設定する

. [Select secondary replication options]セクションで、次のセカンダリレプリケーションオプションの一方または両方を選択します。
+

NOTE: *セカンダリSnapshotコピーのロック期間*を有効にするには、セカンダリレプリケーションオプションを選択する必要があります。



[role="tabbed-block"]
====
.SnapMirrorの更新
--
ローカルSnapshotコピーの作成後にSnapMirrorを更新します。

. 別のボリュームにバックアップセットのミラーコピーを作成する場合（SnapMirror）は、このオプションを選択します。
+
このオプションは、SnapMirrorのアクティブな同期に対して有効にする必要があります。

+
セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

+
を参照して link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["[Topology]ページでのSQL Serverのバックアップとクローンの表示"]



--
.SnapVaultの更新
--
Snapshotコピーの作成後にSnapVault を更新

. ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。
+
セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

+
SnapLockがONTAPのセカンダリ（SnapLock Vault）にのみ設定されている場合、[Topology]ページの*[Refresh]*ボタンをクリックすると、ONTAPから取得したセカンダリのロック期間が更新されます。

+
SnapLock Vaultの詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["SnapVaultデスティネーションでSnapshotコピーをWORM状態にコミットする"]

+
を参照して link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["[Topology]ページでのSQL Serverのバックアップとクローンの表示"]



--
.エラー再試行回数
--
. レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。


--
====


== 手順8：スクリプト設定を構成します

. スクリプトページで、バックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信を行うスクリプトを実行できます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

+

NOTE: セカンダリストレージがSnapshotの最大数に達しないように、ONTAPでSnapMirror保持ポリシーを設定する必要があります。





== 手順9：検証設定を構成します

[Verification] ページで、次の手順を実行します。

. Run verification for following backup schedules セクションで、スケジュール頻度を選択します。
. Database consistency check options セクションで、次の操作を実行します。
+
.. 整合性構造をデータベースの物理構造に制限する（physical_only）
+
... 整合性チェックの対象をデータベースの物理構造に限定し、データベースに影響を与える正しくないページ、チェックサム障害、および一般的なハードウェア障害を検出するには、「 * 」を選択します。


.. すべての情報メッセージを抑制（INFOMSGSなし）
+
... すべての情報メッセージを停止するには、「 * 」を選択します（ NO_INFOMSGS ）。デフォルトで選択されています。


.. レポートされたすべてのエラーメッセージをオブジェクトごとに表示する（ALL_ERRORMSGS）
+
... レポートされたエラーをオブジェクトごとにすべて表示する場合は、このオプションを選択します。


.. クラスタ化されていないインデックスをチェックしない（NOINDEX）
+
... 非クラスタ化インデックスをチェックしない場合は、「 * 非クラスタ化インデックスをチェックしない」を選択します。SQL Serverデータベースは、Microsoft SQL Server Database Consistency Checker（DBCC）を使用して、データベース内のオブジェクトの論理的および物理的な整合性をチェックします。


.. 内部データベーススナップショット（TABLOCK）を使用する代わりに、チェックを制限してロックを取得する
+
... 内部データベースSnapshotを使用する代わりにチェックを制限してロックを取得する場合は、*[内部データベースSnapshotコピー（TABLOCK）を使用する代わりにチェックを制限してロックを取得する]*を選択します。




. [ ログ・バックアップ * ] セクションで、 [ 完了時にログ・バックアップを検証する * ] を選択し、完了時にログ・バックアップを検証します。
. 検証スクリプトの設定 * セクションで、検証処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。





== ステップ10：概要を確認します

. 概要を確認し、*[終了]*を選択します。

