---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますSnapCenter プラグインのインストールに必要なクレデンシャル、およびデータベースや Windows ファイルシステムでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。 
---
= SnapCenter Plug-ins Package for Windows のクレデンシャルを設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますSnapCenter プラグインのインストールに必要なクレデンシャル、およびデータベースや Windows ファイルシステムでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。

* 必要なもの *

* プラグインのインストール前に Windows クレデンシャルをセットアップする必要があります。
* リモートホストに対する管理者権限を含む、管理者権限でクレデンシャルを設定する必要があります。
* Windows ホストでの SQL 認証
+
プラグインのインストール後に SQL クレデンシャルを設定する必要があります。

+
SnapCenter Plug-in for Microsoft SQL Server を導入する場合は、プラグインのインストール後に SQL クレデンシャルを設定する必要があります。このクレデンシャルは、 SQL Server の sysadmin 権限を持つユーザに対して設定します。

+
SQL 認証方式は、 SQL Server インスタンスに照らして認証します。つまり、 SnapCenter で SQL Server インスタンスが検出されている必要があります。そのため、 SQL クレデンシャルを追加する前に、ホストの追加とプラグインパッケージのインストールを行って、リソースを更新しておく必要があります。SQL Server 認証は、スケジュール設定やリソース検出などの処理を実行する際に必要になります。



* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [* 設定 * （ * Settings * ） ] ページで、 [* 資格情報 * （ * Credential * ） ] を
. [ 新規作成（ New ） ] をクリックする。
. [*Credential* ] ページで、クレデンシャルの設定に必要な情報を指定します。
+
|===
| フィールド | 手順 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名 / パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者
+
SnapCenter プラグインをインストールするシステムのドメイン管理者を指定します。Username フィールドの有効な形式は次のとおりです。

+
*** NETBIOS/USERNAME
*** 「ドメイン FQDN\ ユーザ名」


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、 SnapCenter プラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザアカウントに昇格された権限がある場合、またはホストシステムでユーザアクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカルユーザアカウントを指定できます。Username フィールドの有効な形式は、「 username 」です

+
パスワードには二重引用符（ " ）を使用しないでください。





 a| 
認証モード
 a| 
使用する認証モードを選択します。SQL 認証モードを選択した場合は、 SQL Server インスタンスとその SQL インスタンスのホストも指定する必要があります。

|===
. [OK] をクリックします。


クレデンシャルの設定が完了したら、「 * User and Access * 」ページで、ユーザまたはユーザグループにクレデンシャルのメンテナンスを割り当てることができます。
