---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenterでは、クレデンシャルを使用してSnapCenter処理のユーザを認証します。SnapCenterプラグインのインストールに使用するクレデンシャルと、データベースまたはWindowsファイルシステムでデータ保護処理を実行するためのクレデンシャルをそれぞれ作成する必要があります。 
---
= SnapCenter Plug-ins Package for Windowsのクレデンシャルを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、クレデンシャルを使用してSnapCenter処理のユーザを認証します。SnapCenterプラグインのインストールに使用するクレデンシャルと、データベースまたはWindowsファイルシステムでデータ保護処理を実行するためのクレデンシャルをそれぞれ作成する必要があります。

.開始する前に
* プラグインをインストールする前にWindowsクレデンシャルを設定する必要があります。
* このクレデンシャルには、管理者権限（リモートホストに対する管理者権限を含む）を設定する必要があります。
* WindowsホストでのSQL認証
+
プラグインのインストール後にSQLクレデンシャルを設定する必要があります。

+
SnapCenter Plug-in for Microsoft SQL Server を導入する場合は、プラグインのインストール後に SQL クレデンシャルを設定する必要があります。SQL Serverのsysadmin権限を持つユーザのクレデンシャルを設定します。

+
SQL認証方式は、SQL Serverインスタンスに照らして認証します。つまり、 SnapCenter で SQL Server インスタンスが検出されている必要があります。そのため、SQLクレデンシャルを追加する前に、ホストの追加とプラグインパッケージのインストールを完了し、リソースを更新する必要があります。SQL Server認証は、リソースのスケジュール設定や検出などの処理を実行する際に必要になります。



.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [クレデンシャル]ページで、クレデンシャルの設定に必要な情報を指定します。
+
|===
| フィールド | 操作 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名 / パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者
+
SnapCenterプラグインをインストールするシステムのドメイン管理者を指定します。[Username]フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。[Username]フィールドの有効な形式は次のとおりです。 `UserName`

+
パスワードに二重引用符（"）またはバックティック（`）を使用しないでください。小なり（<）と感嘆符（！）は使用しないでください。 パスワードに記号を追加します。たとえば、lessthan <！10、lessthan10 <！、backtick 12とします。





 a| 
認証モード
 a| 
使用する認証モードを選択します。SQL認証モードを選択した場合は、SQL ServerインスタンスとSQLインスタンスが配置されているホストも指定する必要があります。

|===
. [OK]*をクリックします。


クレデンシャルの設定が完了したら、必要に応じて[User and Access]ページでユーザまたはユーザグループにクレデンシャルを割り当てることができます。
