---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: SnapCenter Plug-ins Package for Linux または SnapCenter Plug-ins Package for AIX を別の方法でインストールすることもできます。 
---
= Linux または AIX 用のプラグインパッケージをインストールする別の方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== コマンドレットを使用して複数のリモートホストにインストールします

Linux 用 SnapCenter Plug-ins Package または SnapCenter Plug-ins Package for AIX を複数のホストにインストールするには、 _ Install -SmHostPackage_PowerShell コマンドレットを使用する必要があります。

* 必要なもの *

プラグインパッケージをインストールする各ホストで、ローカル管理者の権限を持つドメインユーザとして SnapCenter にログインする必要があります。

* 手順 *

. PowerShell を起動します。
. SnapCenter サーバホストで、 _Open-SmConnection_cmdlet を使用してセッションを確立し、クレデンシャルを入力します。
. _ Install -SmHostPackage_cmdlet と、必要なパラメータを使用して、 Linux または SnapCenter Plug-in Package for AIX をインストール SnapCenter します。
+
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、 -skipprecheck _ オプションを使用できます。

+

NOTE: ファイアウォールの拒否ルールで指定されているプラグインポートのファイアウォールステータスは、事前確認スクリプトで検証されません。

. リモートインストールのクレデンシャルを入力します。


コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。



== クラスタホストにをインストールします

クラスタホストの両方のノードに、 SnapCenter Plug-ins Package for Linux または SnapCenter Plug-ins Package for AIX をインストールする必要があります。

クラスタホストの各ノードには 2 つの IP があります。IP の 1 つが各ノードのパブリック IP で、 2 つ目の IP が両方のノードで共有されるクラスタ IP になります。

* 手順 *

. クラスタホストの両方のノードに、 SnapCenter Plug-ins Package for Linux または SnapCenter Plug-ins Package for AIX をインストールします。
. SNAPCENTER_server_host 、 SPL_PORT 、 SNAPCENTER_server_port 、および SPL_enabled_plugins パラメータの正しい値が、 /var/opt/snapcenter /spl/etc/_ にある spl.properties ファイルで指定されていることを確認します。
+
spl.properties で SPL_enabled_plugins が指定されていない場合は、 SPL_enabled_plugins を追加して値 sco 、 SCU を割り当てることができます。

. SnapCenter サーバホストで、 _Open-SmConnection_cmdlet を使用してセッションを確立し、クレデンシャルを入力します。
. 各ノードで、 _Set-PreferredHostIPsInStorageExportPolicy_sccli コマンドおよび必要なパラメータを使用して、ノードの優先 IP を設定します。
. SnapCenter サーバホストで、クラスタ IP のエントリと、対応する DNS 名を _C ： \Windows\System32\drivers\etc\hosts_に 追加します。
. ホスト名に対応するクラスタ IP を指定して、 _Add-SmHost_cmdlet を使用して SnapCenter サーバにノードを追加します。


ノード 1 で Oracle データベースを検出し（クラスタ IP がノード 1 でホストされていることが前提）、データベースのバックアップを作成します。フェイルオーバーが発生した場合は、ノード 1 に作成されたバックアップを使用して、ノード 2 のデータベースをリストアできます。ノード 1 に作成したバックアップを使用して、ノード 2 にクローンを作成することもできます。


NOTE: 他の SnapCenter 処理の実行中にフェイルオーバーが発生すると、古いボリューム、ディレクトリ、およびロックファイルが存在します。



== Linux 用の Plug-ins Package をサイレントモードまたはコンソールモードでインストールします

SnapCenter Plug-ins Package for Linux は、コンソールモードまたはコマンドラインインターフェイス（ CLI ）を使用してサイレントモードでインストールできます。

* 必要なもの *

* プラグインパッケージをインストールするための前提条件を確認しておく必要があります。
* DISPLAY 環境変数が設定されていないことを確認する必要があります。
+
DISPLAY 環境変数が設定されている場合は、 UNSET DISPLAY を実行してから、プラグインを手動でインストールする必要があります。



* このタスクについて *

コンソールモードでのインストール中に必要なインストール情報を指定する必要がありますが、サイレントモードでのインストールでは、インストール情報を指定する必要はありません。

* 手順 *

. SnapCenter Plug-ins Package for Linux を SnapCenter Server のインストール場所からダウンロードします。
+
デフォルトのインストールパスは、 _C ： \ProgramData\NetApp\SnapCenter \PackageRepository_です 。このパスには、 SnapCenter サーバがインストールされているホストからアクセスできます。

. コマンドプロンプトで、インストールファイルをダウンロードしたディレクトリに移動します。
. 使用するインストールモードに応じて、次のいずれかの手順を実行します。
+
|===
| インストールモード | 手順 


 a| 
コンソールモード
 a| 
.. を実行します
+
SnapCenter_linux_host_plugin.bin – I console

.. 画面の指示に従ってインストールを完了します。




 a| 
サイレントモード
 a| 
を実行します

`../SnapCenter _Linux_host_plugin.bin -i サイレント -dport=8145 - DSERVER_IP=SnapCenter _Server_FQDN -DSERVER_HTTPS_PORT=SnapCenter _ Server_Port-DUSER_INSTALL_DIR=/opt/custom_path

|===
. /var/opt/snapcenter /spl/etc/__ にある spl.properties ファイルを編集して、 spl_enabled_plugins/SCO 、 SCU を追加し、 SnapCenter Plug-in Loader サービスを再起動します。



IMPORTANT: プラグインパッケージのインストールでは、 SnapCenter サーバではなく、ホストにプラグインが登録されます。SnapCenter GUI または PowerShell コマンドレットを使用してホストを追加し、 SnapCenter サーバにプラグインを登録します。ホストの追加中に、クレデンシャルとして [None] を選択します。ホストを追加すると、インストールしたプラグインが自動的に検出されます。



== AIX 用プラグインパッケージをサイレントモードでインストールします

コマンドラインインターフェイス（ CLI ）を使用して、 SnapCenter Plug-ins Package for AIX をサイレントモードでインストールできます。

* 必要なもの *

* プラグインパッケージをインストールするための前提条件を確認しておく必要があります。
* DISPLAY 環境変数が設定されていないことを確認する必要があります。
+
DISPLAY 環境変数が設定されている場合は、 UNSET DISPLAY を実行してから、プラグインを手動でインストールする必要があります。



* 手順 *

. SnapCenter Server のインストール場所から、 SnapCenter Plug-ins Package for AIX をダウンロードします。
+
デフォルトのインストールパスは、 _C ： \ProgramData\NetApp\SnapCenter \PackageRepository_です 。このパスには、 SnapCenter サーバがインストールされているホストからアクセスできます。

. コマンドプロンプトで、インストールファイルをダウンロードしたディレクトリに移動します。
. を実行します
+
`./snapcenter aix_host_plugin.bsx -i silent-dport=8145 - DSERVER_IP=SnapCenter _Server_FQDN -DSERVER_HTTPS_PORT=SnapCenter _Server_Port-DUSER_INSTALL_DIR=/opt/custom_path-DISKALL_LOG_LOG_NAME=SnapCenter _AIX_FILE_INSTAN_INSTAN_INSTAN_MANUALL_INSTALLATUE_FEATURE_FILE=SnapCenter _ インストール手動 MDULE=SnapCenter _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ インストール _ オプション =SnapCenter _ インストール _ インストール _ インストール _ インストール _ ホスト名 = SnapCenter _ インストール _

. /var/opt/snapcenter /spl/etc/__ にある spl.properties ファイルを編集して、 spl_enabled_plugins/SCO 、 SCU を追加し、 SnapCenter Plug-in Loader サービスを再起動します。



IMPORTANT: プラグインパッケージのインストールでは、 SnapCenter サーバではなく、ホストにプラグインが登録されます。SnapCenter GUI または PowerShell コマンドレットを使用してホストを追加し、 SnapCenter サーバにプラグインを登録します。ホストの追加中に、クレデンシャルとして [None] を選択します。ホストを追加すると、インストールしたプラグインが自動的に検出されます。
