---
permalink: protect-sco/backup_types.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: Oracleデータベースでサポートされるバックアップのタイプ。 
---
= Oracle データベースでサポートされるバックアップのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップタイプでは、作成するバックアップのタイプを指定します。SnapCenter では、 Oracle データベースに対してオンラインバックアップタイプとオフラインバックアップタイプがサポートされます。



== オンラインバックアップ

データベースがオンライン状態のときに作成されるバックアップを、オンラインバックアップと呼びます。ホットバックアップとも呼ばれるオンラインバックアップでは、データベースをシャットダウンすることなくバックアップを作成できます。

オンラインバックアップでは、次のファイルのバックアップを作成できます。

* データ・ファイルと制御ファイルのみ
* アーカイブログファイルのみ（この場合はデータベースがバックアップモードになりません）
* データ・ファイル、制御ファイル、およびアーカイブ・ログ・ファイルを含むフル・データベース




== オフラインバックアップ

データベースがマウント済み状態またはシャットダウン状態のときに作成されるバックアップを、オフラインバックアップと呼びます。オフラインバックアップはコールドバックアップとも呼ばれます。オフラインバックアップに含めることができるのは、データファイルと制御ファイルだけです。オフラインマウントバックアップまたはオフラインシャットダウンバックアップのいずれかを作成できます。

* オフラインマウントバックアップを作成する場合は、データベースがマウント済み状態であることを確認する必要があります。
+
データベースがそれ以外の状態の場合は、バックアップ処理が失敗します。

* オフラインシャットダウンバックアップを作成する場合、データベースはどの状態でもかまいません。
+
データベースは、バックアップを作成するために必要な状態に変更されます。バックアップが作成されると、データベースは元の状態に戻ります。


