---
permalink: protect-sco/concept_what_you_can_do_with_the_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: backup, restore, clone, oracle database 
summary: Plug-in for Oracle Database では、次のバックアップ、検証、リストア、リカバリ、マウントを実行できます。 Oracle データベースとそのリソースをアンマウントおよびクローニングする。また、 Oracle Recovery Manager （ RMAN ）でデータベースバックアップのカタログ化またはカタログ化解除を行うこともできます。 
---
= Plug-in for Oracle Database の機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Oracle Database は、 Oracle データベースに対応したデータ保護管理を提供する、 NetApp SnapCenter ソフトウェアのホスト側コンポーネントです。

Plug-in for Oracle Database によって、 Oracle Recovery Manager （ RMAN ）、検証、マウント、アンマウント、リストア、 SnapCenter 環境での Oracle データベースのリカバリとクローニングPlug-in for Oracle Database は、すべてのデータ保護処理を実行するために SnapCenter Plug-in for UNIX をインストールします。

Plug-in for Oracle Database では、 SAP アプリケーションを実行している Oracle データベースのバックアップを管理することができます。ただし、 SAP BR * Tools との統合はサポートされません。

* データファイル、制御ファイル、およびアーカイブログファイルをバックアップします。
+
バックアップはコンテナデータベース（ CDB ）レベルでのみサポートされます。

* データベース、 CDB 、および Pluggable Database （ PDB ）のリストアとリカバリを行います。
+
PDB の不完全リカバリはサポートされていません。

* ある時点までの本番環境データベースのクローンを作成します。
+
クローニングは CDB レベルでのみサポートされます。

* バックアップをただちに検証します。
* リカバリ処理のためにデータバックアップとログバックアップのマウントとアンマウントを行います。
* バックアップ処理と検証処理をスケジュールします。
* すべての処理を監視します。
* バックアップ、リストア、クローニングの各処理のレポートを表示します。

