---
permalink: protect-sco/concept_what_you_can_do_with_the_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: backup, restore, clone, oracle database 
summary: Plug-in for Oracle Database では、次のバックアップ、検証、リストア、リカバリ、マウントを実行できます。 Oracle データベースとそのリソースをアンマウントおよびクローニングする。また、 Oracle Recovery Manager （ RMAN ）でデータベースバックアップのカタログ化またはカタログ化解除を行うこともできます。 
---
= Plug-in for Oracle Databaseの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Oracle Databaseは、Oracleデータベースに対応したデータ保護管理を可能にする、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。

Plug-in for Oracle Databaseは、Oracle Recovery Manager（RMAN）を使用したバックアップ、カタログ化とカタログ化解除、検証、マウント、アンマウント、リストアを自動化します。 SnapCenter環境でのOracleデータベースのリカバリとクローニングPlug-in for Oracle Databaseは、すべてのデータ保護処理を実行するためにSnapCenter Plug-in for UNIXをインストールします。

Plug-in for Oracle Databaseを使用して、SAPアプリケーションを実行しているOracleデータベースのバックアップを管理できます。ただし、SAP BR * Toolsとの統合はサポートされていません。

* データファイル、制御ファイル、およびアーカイブログファイルをバックアップします。
+
バックアップは、コンテナデータベース（CDB）レベルでのみサポートされます。

* データベース、CDB、プラガブルデータベース（PDB）のリストアとリカバリ
+
PDBの不完全リカバリはサポートされていません。

* ある時点までの本番環境データベースのクローンを作成します。
+
クローニングはCDBレベルでのみサポートされます。

* バックアップをすぐに検証します。
* リカバリ処理用にデータバックアップとログバックアップをマウントおよびアンマウントします。
* バックアップ処理と検証処理をスケジュールします。
* すべての処理を監視します。
* バックアップ、リストア、クローニングの各処理のレポートを表示します。

