---
permalink: protect-sco/concept_prepare_for_protecting_oracle_databases.html 
sidebar: sidebar 
keywords: oracle, preparation for protection, prerequisites 
summary: バックアップ、クローニング、リストアなどのデータ保護処理を実行する場合は、事前に戦略を定義し、環境をセットアップする必要があります。また、 SnapVault サーバで SnapMirror テクノロジと SnapCenter テクノロジを使用するように設定することもできます。 
---
= Oracleデータベースを保護する準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ、クローニング、リストアなどのデータ保護処理を実行する場合は、事前に戦略を定義し、環境をセットアップする必要があります。また、 SnapVault サーバで SnapMirror テクノロジと SnapCenter テクノロジを使用するように設定することもできます。

SnapVaultテクノロジとSnapMirrorテクノロジを利用するには、ストレージデバイスのソースボリュームとデスティネーションボリューム間のデータ保護関係を設定して初期化する必要があります。これらのタスクは、NetAppSystem Managerを使用するか、ストレージコンソールのコマンドラインを使用して実行できます。

Plug-in for Oracle Databaseを使用する前に、SnapCenter管理者がSnapCenterサーバをインストールして設定し、前提条件となるタスクを実行する必要があります。

* SnapCenterサーバをインストールして設定します。 link:../install/task_install_the_snapcenter_server_using_the_install_wizard.html["詳細"^]
* ストレージシステム接続を追加してSnapCenter環境を設定します。 link:../install/task_add_storage_systems.html["詳細"^]
+

NOTE: SnapCenter では、異なるクラスタにある同じ名前の SVM は複数サポートされません。SVMの登録またはクラスタの登録を使用してSnapCenterに登録されるSVMは、それぞれ一意である必要があります。

* インストールユーザのクレデンシャルを、認証モードをLinuxまたはAIXに設定して作成します。 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#set-up-credentials["詳細"^]
* ホストを追加し、プラグインをインストールし、リソースを検出します。
* VMware RDM LUNまたはVMDKにあるOracleデータベースをSnapCenterサーバを使用して保護する場合は、SnapCenter Plug-in for VMware vSphereを導入してSnapCenterに登録する必要があります。
* LinuxホストまたはAIXホストにJavaをインストールします。
+
詳細については、またはを参照してください link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#linux-host-requirements["Linux ホストの要件"^] link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#aix-host-requirements["AIXホストの要件"^] 。

* アプリケーションファイアウォールのタイムアウト値は3時間以上に設定する必要があります。
* NFS環境でOracleデータベースを使用している場合は、マウント、クローニング、検証、およびリストアの処理を実行できるように、プライマリストレージまたはセカンダリストレージ用に少なくとも1つのNFSデータLIFを設定しておく必要があります。
* データパス（LIF）が複数ある場合やdNFS構成を使用している場合は、データベースホストでSnapCenter CLIを使用して次の作業を実行できます。
+
** デフォルトでは、データベースホストのすべての IP アドレスが、クローンボリュームの Storage Virtual Machine （ SVM ）の NFS ストレージエクスポートポリシーに追加されます。特定のIPアドレスを使用する場合、またはIPアドレスのサブセットに制限する場合は、Set-PreferredHostIPsInStorageExportPolicy CLIを実行します。
** SVM に複数のデータパス（ LIF ）がある場合は、 NFS クローンボリュームをマウントするための適切なデータパス（ LIF ）が SnapCenter によって選択されます。ただし、特定のデータパス（LIF）を指定する場合は、Set-SvmPreferredDataPath CLIを実行する必要があります。詳細については、コマンドリファレンスガイドを参照してください。


* SAN環境でOracleデータベースを使用している場合は、SAN環境が次のガイドに記載されている推奨事項に従って設定されていることを確認してください。
+
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["Using Linux Hosts with ONTAP storage"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMP1119218["AIX Host Utilitiesの影響を受けるホスト設定"^]


* Oracle LinuxまたはRHELオペレーティングシステムのLVMにOracleデータベースがある場合は、最新バージョンの論理ボリューム管理（LVM）をインストールします。
* SnapManager for Oracleを使用していて、SnapCenter Plug-in for Oracle Databaseに移行する場合は、sccliコマンドsc-migrateを使用して、SnapCenterのポリシーとリソースグループにプロファイルを移行できます。
* バックアップレプリケーションが必要な場合は、ONTAPでSnapMirrorとSnapVaultを設定する


SnapCenter 4.1.1 ユーザの場合、 SnapCenter Plug-in for VMware vSphere 4.1.1 のドキュメントには、仮想化されたデータベースとファイルシステムの保護に関する情報が記載されています。NetAppデータブローカー1.0および1.0.1のドキュメントには、SnapCenter 4.2.xのユーザ向けに、LinuxベースのNetAppデータブローカー仮想アプライアンス（オープン仮想アプライアンス形式）が提供するSnapCenter Plug-in for VMware vSphereを使用した仮想データベースおよびファイルシステムの保護に関する情報が記載されています。SnapCenter 4.3.xのユーザ向けに、SnapCenter Plug-in for VMware vSphere 4.3のドキュメントには、LinuxベースのSnapCenter Plug-in for VMware vSphere仮想アプライアンス（オープン仮想アプライアンス形式）を使用した仮想データベースとファイルシステムの保護に関する情報が記載されています。

* 詳細はこちら *

* https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html["SnapCenter Plug-in for VMware vSphereのドキュメント"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Data_protection_operation_fails_in_a_non-multipath_environment_in_RHEL_7_and_later["RHEL 7以降の非マルチパス環境でデータ保護処理が失敗する"^]

