---
permalink: protect-sco/discover-oracle-database.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter によるOracleデータベースの検出方法 
---
= SnapCenter による Oracle データベースの検出方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースとは、SnapCenter で管理されるホスト上のOracleデータベースです。使用可能なデータベースを検出したあとに、それらのデータベースをリソースグループに追加してデータ保護処理を実行できます。

次のセクションでは、SnapCenter がさまざまなタイプおよびバージョンのOracleデータベースを検出するために使用するプロセスについて説明します。



== Oracle バージョン 11_________ ～ 12_c_R1

.RACデータベース
RACデータベースは、/etc/oratab`エントリに基づいてのみ検出されます。/etc/oratab ファイル内にデータベース・エントリが必要です。

.スタンドアロン
スタンドアロンデータベースは、/etc/oratabエントリに基づいてのみ検出されます。

.ASM
ASMインスタンスエントリが/etc/oratabファイルにある必要があります。

.RAC 1ノード
RAC One Nodeデータベースは、/etc/oratabエントリに基づいてのみ検出されます。データベースがnomount、mount、またはopenのいずれかの状態である必要があります。/etc/oratab ファイル内にデータベース・エントリが必要です。

データベースがすでに検出され、バックアップが関連付けられている場合、 RAC One Node データベースのステータスは「 Renamed 」または「 deleted 」とマークされます。

データベースを再配置する場合は、次の手順を実行する必要があります。

. フェイルオーバーが発生した RAC ノードの /etc/oratab ファイルに、再配置されたデータベース・エントリを手動で追加します。
. リソースを手動で更新する。
. リソースページからRAC One Nodeデータベースを選択し、[データベース設定]をクリックします。
. データベースを設定して、データベースを現在ホストしている RAC ノードに優先クラスタノードを設定します。
. SnapCenter 処理を実行します。
. あるノードから別のノードにデータベースを再配置し、以前のノードのoratabエントリが削除されていない場合は、同じデータベースが2回表示されないように、oratabエントリを手動で削除します。




== Oracleバージョン12cR2～18cの場合

.RACデータベース
RACデータベースはsrvctl configコマンドを使用して検出されます。/etc/oratab ファイル内にデータベース・エントリが必要です。

.スタンドアロン
スタンドアロンデータベースは、/etc/oratabファイルのエントリとsrvctl configコマンドの出力に基づいて検出されます。

.ASM
ASMインスタンスエントリが/etc/oratabファイルに含まれている必要はありません。

.RAC 1ノード
RAC One Nodeデータベースは、srvctl configコマンドのみを使用して検出されます。データベースがnomount、mount、またはopenのいずれかの状態である必要があります。データベースがすでに検出され、バックアップが関連付けられている場合、 RAC One Node データベースのステータスは「 Renamed 」または「 deleted 」とマークされます。

データベースが再配置された場合は、次の手順を実行する必要があります。リソースを手動で更新する。。リソースページからRAC One Nodeデータベースを選択し、[データベース設定]をクリックします。。データベースを設定して、データベースを現在ホストしている RAC ノードに優先クラスタノードを設定します。。SnapCenter 処理を実行します。


NOTE: /etc/oratab ファイル内に Oracle 12_c__R2 および 18_c_database のエントリがあり、同じデータベースが srvctl config コマンドで登録されている場合、 SnapCenter は重複するデータベースエントリを削除します。古いデータベースエントリがある場合は、データベースは検出されますが、データベースにアクセスできず、ステータスはオフラインになります。
