---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, restore 
summary: SnapCenter では、データベースのリストア時にプリスクリプトとポストスクリプトを実行する際に、事前定義された環境変数を使用できます。 
---
= 特定のプリスクリプトとポストスクリプトをリストアするための事前定義された環境変数
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter では、データベースのリストア時にプリスクリプトとポストスクリプトを実行する際に、事前定義された環境変数を使用できます。

* データベースをリストアするためにサポートされている定義済み環境変数 *

* * sc_job_ID * は、処理のジョブ ID を指定します。
+
例： 257

* *SC_ORACLE_SID * はデータベースのシステム識別子を指定します
+
複数のデータベースを使用する処理の場合は、パイプで区切られたデータベース名が含まれます。

+
例： NFSB31

* *sc_host * は、データベースのホスト名を指定します。
+
このパラメータは、アプリケーションボリュームに対して入力されます。

+
例： scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER* は、データベースのオペレーティング・システムの所有者を指定します。
+
例： oracle

* * SC_OS_GROUP * はデータベースのオペレーティング・システム・グループを指定します
+
例： oinstall

* * SC_backup_name * はバックアップ名です
+
このパラメータは、アプリケーションボリュームに対して入力されます。

+
例

+
** データベースが ARCHIVELOG モードで実行されていない場合： DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _1
** データベースが ARCHIVELOG モードで実行されている場合： DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _1 、 Rg2_scspr2417819002_07 -21-2021 、 112.16.48.9267_1 、 Rg2_scspr2417819002_07 -22-2021 、 116.48.9267_1


* * SC_BACKUP ID * はバックアップの ID です
+
このパラメータは、アプリケーションボリュームに対して入力されます。

+
例

+
** データベースが ARCHIVELOG モードで実行されていない場合： DATA @203 | LOG@205
** データベースが ARCHIVELOG モードで実行されている場合： DATA @203 | LOG @ 205,206,207


* * sc_resource_group_name * で、リソースグループの名前を指定します。
+
例： RG1

* *SC_ORACLE_HOME* は Oracle ホーム・ディレクトリのパスを指定します
+
例： /ora01/app/oracle/product/18.1.0/db_1

* * SC_RECOVERY_TYPE * はリカバリされるファイルとリカバリ範囲を指定します
+
例： RESTORESCOPE:usingBackupControlfile=false|RECOVERYSCOPE:allLogs=true,nologs=false,UntilTime=false,untilscn=false



区切り記号の詳細については、を参照してください link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["サポートされるデリミタ"^]。
