---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter によるOracleデータベースの検出方法 
---
= RACセツトアツフノユウセンノオト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle Real Application Clusters（RAC）セットアップでは、SnapCenter がバックアップ処理の実行に使用する優先ノードを指定できます。優先ノードを指定しない場合は、 SnapCenter によって自動的に優先ノードが割り当てられ、そのノードにバックアップが作成されます。

優先ノードには、RACデータベースインスタンスが存在するクラスタノードの1つまたはすべてを指定できます。バックアップ処理は、これらの優先ノードで優先順にトリガーされます。

.例
RACデータベースcdbracには3つのインスタンスがあります。cdbrac1はnode1に、cdbrac2はnode2に、cdbrac3はnode3にあります。

node1とnode2のインスタンスが優先ノードとして設定され、node2が第1優先ノード、node1が第2優先ノードとして設定されます。バックアップ処理を実行すると、最初の優先ノードであるnode2で最初に処理が試行されます。

node2がバックアップ対象の状態でない場合（ホストでプラグインエージェントが実行されていないなどの複数の原因が考えられます）、ホスト上のデータベースインスタンスが指定したバックアップタイプに必要な状態ではありません。 または、FlexASM構成のnode2上のデータベースインスタンスがローカルASMインスタンスによって処理されていない場合、node1で処理が試行されます。

node3は優先ノードのリストにないため、バックアップには使用されません。



== Flex ASMセットアップ

Flex ASMセットアップでは、カーディナリティがRACクラスタ内のノード数より少ない場合、リーフノードは優先ノードとしてリストされません。Flex ASMクラスタノードのロールに変更があった場合は、優先ノードが更新されるように手動でを検出する必要があります。



== 必要なデータベースの状態

バックアップを正常に完了するには、優先ノード上のRACデータベースインスタンスが必要な状態である必要があります。

* オンラインバックアップを作成するには、設定された優先ノードのRACデータベースインスタンスの1つがOPEN状態である必要があります。
* オフラインマウントバックアップを作成するには、設定された優先ノード内のRACデータベースインスタンスの1つがマウント状態であり、他のすべてのインスタンス（他の優先ノードを含む）がマウント状態以下である必要があります。
* RACデータベースインスタンスはどの状態でもかまいませんが、オフラインシャットダウンバックアップを作成するには優先ノードを指定する必要があります。

