---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter によるOracleデータベースの検出方法 
---
= RAC セットアップで優先ノードを指定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle Real Application Clusters（RAC）セットアップでは、SnapCenter がバックアップ処理の実行に使用する優先ノードを指定できます。優先ノードを指定しない場合は、 SnapCenter によって自動的に優先ノードが割り当てられ、そのノードにバックアップが作成されます。

優先ノードには、 RAC データベースインスタンスが存在するクラスタノードを 1 つまたはすべて指定できます。バックアップ処理は、これらの優先ノードで優先順にトリガーされます。

.例
RACデータベースcdbracには3つのインスタンスがあります。cdbrac1はnode1に、cdbrac2はnode2に、cdbrac3はnode3にあります。

node1 インスタンスと node2 インスタンスが優先ノードとして設定され、 node2 に最初の優先順位、 node1 に 2 番目の優先順位が指定されます。バックアップ処理を実行すると、まず第 1 優先ノードである node2 で処理が試行されます。

node2 がバックアップの状態になっていない場合は、プラグインエージェントがホストで実行されていないなどの複数の理由で、ホスト上のデータベースインスタンスが指定したバックアップタイプに必要な状態になっていない可能性があります。 または、 FlexASM 構成内の node2 上のデータベースインスタンスがローカル ASM インスタンスで提供されていない場合は、 node1 で処理が試行されます。

node3 は、優先ノードのリストに含まれていないため、バックアップには使用されません。



== Flex ASMセットアップ

Flex ASM 設定では、カード濃度が RAC クラスタ内のノード数より少ない場合、リーフノードは優先ノードとして表示されません。Flex ASM クラスタノードのロールに変更がある場合は、優先ノードが更新されるように、手動で検出する必要があります。



== 必要なデータベースの状態

バックアップを正常に完了するには、優先ノード上の RAC データベースインスタンスが必要な状態であることが必要です。

* オンラインバックアップを作成する場合は、設定された優先ノードの RAC データベースインスタンスの 1 つがオープン状態であることが必要です。
* オフラインマウントバックアップを作成する場合は、設定された優先ノードの RAC データベースインスタンスの 1 つがマウント状態であり、かつ他の優先ノードを含むその他すべてのインスタンスがマウント状態またはそれより低いレベルの状態であることが必要です。
* オフラインシャットダウンバックアップを作成する場合は、 RAC データベースインスタンスはどの状態でもかまいませんが、優先ノードを指定する必要があります。

