---
permalink: protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_ins_package_for_aix.html 
sidebar: sidebar 
keywords: SnapCenter, host requirements for AIX, sudo privileges, non-root user 
summary: SnapCenter Plug-ins Package for AIX をインストールする前に、ホストが要件を満たしていることを確認する必要があります。 
---
= Plug-in Package for AIX をインストールするためのホストの要件
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-ins Package for AIX をインストールする前に、ホストが要件を満たしていることを確認する必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
AIX 4.3 以降



 a| 
ホスト上の SnapCenter プラグインの最小 RAM
 a| 
4 GB



 a| 
ホスト上の SnapCenter プラグインのインストールおよびログの最小スペース
 a| 
1 GB


NOTE: 十分なディスクスペースを割り当て、 logs フォルダによるストレージ消費を監視する必要があります。必要なログスペースは、保護するエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理に対してログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
Java 1.8.x （ 64 ビット） IBM Java

Java を最新バージョンにアップグレードした場合は、 /var/opt/snapcenter /etc/sp/etc/spl.properties にある JAVA_HOME オプションが正しい Java バージョンに設定されていること、および正しいパスが指定されていることを確認する必要があります。

|===
サポートされているバージョンの最新情報については、を参照してください http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。



== AIX プラグインホストの root 以外のユーザに sudo 権限を設定します

SnapCenter 4.4 以降では、 root 以外のユーザが SnapCenter Plug-ins Package for AIX をインストールしてプラグインプロセスを開始できます。いくつかのパスにアクセスできるように root 以外のユーザに sudo 権限を設定する必要があります。

* 必要なもの *

* sudo 1.8.7 以降。
* root 以外のユーザが Oracle インストールグループに含まれていることを確認します。
* /etc/ssh/sshd_config_file を編集して、メッセージ認証コードアルゴリズム MACs HMAC-sha2-256 および MACs HMAC-sha2-512 を設定します。
+
構成ファイルを更新したら、 sshd サービスを再起動します。

+
例

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


* このタスクについて *

次のパスにアクセスできるように root 以外のユーザに sudo 権限を設定する必要があります。

* /home/_aix_user_//.sc_netapp /snapcenter aix_host_plugin.bsx
* /custom_location/NetApp/snapcenter /spl/installing/plugins/uninstall
* /custom_location/NetApp/snapcenter /spl/bin/spl になります


* 手順 *

. SnapCenter Plug-ins Package for AIX をインストールする AIX ホストにログインします。
. visudo Linux ユーティリティを使用して、 /etc/sudoers ファイルに次の行を追加します。
+
[listing, subs="+quotes"]
----
Cmnd_Alias SCCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall,
/opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: SCCMD, PRECHECKCMD
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+
_aix_user_は 、作成した root 以外のユーザの名前です。

+
チェックサム値は、 _ C ： \ProgramData\NetApp\SnapCenter \Package Repository_に ある * ORACLE_checksum.txt * ファイルから取得できます。

+
カスタムの場所を指定した場合、場所は _custom_path \NetApp\SnapCenter \Package Repository_に なります。

+

IMPORTANT: この例は、独自のデータを作成するための参照としてのみ使用してください。



|===


| * ベストプラクティス：セキュリティ上の理由から、インストールまたはアップグレードのたびに sudo エントリを削除することを推奨します。 
|===