---
permalink: protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, Oracle path 
summary: ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。 
---
= ホストを追加して Plug-in Package for Linux または AIX をインストールするための前提条件
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。

* iSCSI を使用している場合は、 iSCSI サービスが実行されている必要があります。
* root ユーザまたは root 以外のユーザ用にパスワードベースの SSH 接続を有効にしておく必要があります。
+
SnapCenter Plug-in for Oracle Database は、 root 以外のユーザがインストールできます。ただし、プラグインプロセスをインストールして開始できるように root 以外のユーザに sudo 権限を設定する必要があります。プラグインをインストールすると、プロセスが有効な root ユーザとして実行されます。

* AIX ホストに SnapCenter Plug-ins Package for AIX をインストールする場合は、ディレクトリレベルのシンボリックリンクを手動で解決しておく必要があります。
+
SnapCenter Plug-ins Package for AIX は、ファイルレベルのシンボリックリンクを自動的に解決しますが、 JAVA_HOME の絶対パスを取得するためのディレクトリレベルのシンボリックリンクは解決しません。

* インストールユーザ用に、認証モードを Linux または AIX に設定してクレデンシャルを作成します。
* Linux または AIX ホストに Java 1.8.x 、 64 ビットをインストールしておく必要があります。
+
Java のダウンロード方法については、次を参照してください。

+
** http://www.java.com/en/download/manual.jsp["すべてのオペレーティングシステム用の Java のダウンロード"^]
** https://www.ibm.com/support/pages/java-sdk-aix["IBM Java for AIX の場合"^]


* Linux または AIX ホストで Oracle データベースを実行している場合は、 SnapCenter Plug-in for Oracle Database と SnapCenter Plug-in for UNIX の両方をインストールする必要があります。
+

NOTE: Plug-in for Oracle Database では、 SAP を対象とした Oracle データベースの管理も可能です。ただし、 SAP BR * Tools との統合はサポートされません。

* Oracle データベース 11.2.0.3 以降を使用している場合は、 13366202 Oracle パッチをインストールする必要があります。

