---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: Oracle データベースをクローニングする前に、前提条件を満たしていることを確認する必要があります。 
---
= Oracle データベースをクローニングするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle データベースをクローニングする前に、前提条件を満たしていることを確認する必要があります。

* SnapCenter を使用してデータベースのバックアップを作成しておく必要があります。
+
クローニング処理が成功するためには、オンラインデータバックアップとログバックアップ、またはオフライン（マウントまたはシャットダウン）バックアップが正常に作成されている必要があります。

* 制御ファイルまたは REDO ログファイルのパスをカスタマイズする場合は、必要なファイルシステムまたは Automatic Storage Management （ ASM ）ディスクグループを事前にプロビジョニングしておく必要があります。
+
デフォルトでは、クローンデータベースの REDO ログおよび制御ファイルは、 ASM ディスクグループ、またはクローンデータベースのデータファイル用に SnapCenter でプロビジョニングされたファイルシステムに作成されます。

* NFS 経由で ASM を使用している場合は、 ASM_diskstring パラメータで定義された既存のパスに /var/opt/snapcenter /scu/clones/*/*_ を追加する必要があります。
* ASM_diskstring パラメータで、 ASMFD または configure _ORCL ： * _ を使用する場合は、 _ AFD ： * _ を設定します。
+
asm_diskstring パラメータの編集方法については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["asm_diskstring にディスクパスを追加する方法"^]。

* 代替ホストでクローンを作成する場合、代替ホストは次の要件を満たす必要があります。
+
** SnapCenter Plug-in for Oracle Database を代替ホストにインストールする必要があります。
** クローンホストは、プライマリストレージまたはセカンダリストレージから LUN を検出できる必要があります。
+
*** プライマリストレージまたはセカンダリ（バックアップまたはミラー）ストレージから代替ホストにクローニングする場合は、セカンダリストレージと代替ホストの間に iSCSI セッションが確立されているか、 FC 用に適切にゾーニングされていることを確認してください。
*** バックアップ・ストレージまたはミラー・ストレージから同じホストにクローニングする場合は、バックアップまたはミラー・ストレージとホストの間に iSCSI セッションが確立されているか、 FC 用に適切にゾーニングされているかを確認してください。
*** 仮想環境でクローニングを行う場合は、プライマリストレージまたはセカンダリストレージと、代替ホストをホストする ESX サーバの間で iSCSI セッションが確立されていること、または FC 用に適切にゾーニングされていることを確認してください。
+
詳細については、を参照してください https://docs.netapp.com/us-en/ontap-sanhost/["Host Utilitiesのマニュアル"]。



** ソースデータベースが ASM データベースの場合は、次の手順を実行します。
+
*** クローンを実行するホスト上で、 ASM インスタンスが稼働している必要があります。
*** クローニングされたデータベースのアーカイブログファイルを専用の ASM ディスクグループに配置する場合は、クローン処理の前に ASM ディスクグループをプロビジョニングする必要があります。
*** データディスクグループの名前は設定できますが、クローンを実行するホスト上の他の ASM ディスクグループでは名前が使用されないようにしてください。
+
ASM ディスクグループにあるデータファイルは、 SnapCenter のクローニングワークフローの一環としてプロビジョニングされます。



** NVMeの場合、NVMe utilをインストールする必要があります


* データ LUN の保護タイプと、ミラー、バックアップ、ミラー - ヴォールトなどのログ LUN は、ログバックアップを使用して代替ホストへのクローニング中にセカンダリロケータを検出するために同じである必要があります。
* 12_c_databaseのバックアップをクローニングするためのシードPDB関連情報を取得するには、ソースデータベースのパラメータファイルでexclude_seed_cdb_viewの値をFALSEに設定する必要があります。
+
シード PDB とは、 CDB が PDB を作成する際に使用する、システム付属のテンプレートです。シード PDB の名前は PDB$SEED です。PDB$SEED については、 Oracle Doc ID 1940806.1 を参照してください。

+

NOTE: この値は、12_c_databaseをバックアップする前に設定する必要があります。

* SnapCenter は 'autofs サブシステムによって管理されるファイル・システムのバックアップをサポートしますデータベースを複製する場合は ' データ・マウント・ポイントが autofs マウント・ポイントのルートにないことを確認してくださいこれは ' プラグイン・ホストのルート・ユーザには 'autofs マウント・ポイントのルートの下にディレクトリを作成する権限がないためです
+
制御ログファイルと REDO ログファイルがデータマウントポイントにある場合は、制御ファイルのパスを変更し、それに応じてログファイルのパスをやり直す必要があります。

+

NOTE: 新しいクローン・マウント・ポイントを 'autofs サブシステムに手動で登録できます新しいクローンマウントポイントは自動的には登録されません。

* TDE （自動ログイン）を使用していて、同じホストまたは代替ホスト上にデータベースのクローンを作成する場合は、 /etc/oracle/ウォ レット /$ORACLE_SID_ の下にあるウォレット（キーファイル）をソースデータベースからクローンデータベースにコピーする必要があります。
* Oracle Linux 7 以降または Red Hat Enterprise Linux （ RHEL ） 7 以降の Storage Area Network （ SAN ；ストレージエリアネットワーク）環境でのクローニングを正常に実行するには、の値として、 /etc/lvm/lvmlvm/lvmmetad=0 を設定し、 lvm2-lvmetad サービスを停止する必要があります。
* Oracle データベース 11.2.0.3 以降を使用していて、 NID スクリプトを使用して補助インスタンスのデータベース ID を変更している場合は、 13366202 Oracle パッチをインストールする必要があります。
* ボリュームをホストするアグリゲートが Storage Virtual Machine （ SVM ）に割り当てられたアグリゲートリストに含まれていることを確認する必要があります。
* NVMeの場合、接続から除外するターゲットポートがあるときは、/var/opt/snapcenter/scu/etc/nvme.confファイルにターゲットノード名とポート名を追加します。
+
ファイルが存在しない場合は、次の例に示すようにファイルを作成する必要があります。

+
....
blacklist {
nn-0x<target_node_name_1>:pn-0x<target_port_name_1>
nn-0x<target_node_name_2>:pn-0x<target_port_name_2>
}
....
* iSCSIプロトコルとFCプロトコルが混在するigroupを使用して、LUNがAIXホストにマッピングされていないことを確認してください。詳細については、を参照してください https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["LUNのデバイスを検出できませんというエラーが表示されて処理に失敗します"^]。

