---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: Oracleデータベースをクローニングする前に、前提条件が完了していることを確認する必要があります。 
---
= Oracleデータベースをクローニングするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracleデータベースをクローニングする前に、前提条件が完了していることを確認する必要があります。

* SnapCenterを使用してデータベースのバックアップを作成しておく必要があります。
+
クローニング処理を成功させるには、オンラインのデータバックアップとログバックアップ、またはオフライン（マウントまたはシャットダウン）バックアップが正常に作成されている必要があります。

* 制御ファイルまたはREDOログファイルのパスをカスタマイズする場合は、必要なファイルシステムまたはAutomatic Storage Management（ASM）ディスクグループを事前にプロビジョニングしておく必要があります。
+
デフォルトでは、クローンデータベースのREDOログファイルと制御ファイルは、ASMディスクグループまたはクローンデータベースのデータファイル用にSnapCenterによってプロビジョニングされたファイルシステムに作成されます。

* NFS 経由で ASM を使用している場合は、 ASM_diskstring パラメータで定義された既存のパスに /var/opt/snapcenter /scu/clones/*/*_ を追加する必要があります。
* ASM_diskstring パラメータで、 ASMFD または configure _ORCL ： * _ を使用する場合は、 _ AFD ： * _ を設定します。
+
asm_diskstringパラメータの編集方法については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["asm_diskstring にディスクパスを追加する方法"^]。

* 代替ホストでクローンを作成する場合は、代替ホストが次の要件を満たしている必要があります。
+
** SnapCenter Plug-in for Oracle Database を代替ホストにインストールする必要があります。
** クローンホストは、プライマリストレージまたはセカンダリストレージから LUN を検出できる必要があります。
+
*** プライマリストレージまたはセカンダリ（バックアップまたはミラー）ストレージから代替ホストにクローニングする場合は、セカンダリストレージと代替ホストの間に iSCSI セッションが確立されているか、 FC 用に適切にゾーニングされていることを確認してください。
*** バックアップ・ストレージまたはミラー・ストレージから同じホストにクローニングする場合は、バックアップまたはミラー・ストレージとホストの間に iSCSI セッションが確立されているか、 FC 用に適切にゾーニングされているかを確認してください。
*** 仮想環境でクローニングを行う場合は、プライマリストレージまたはセカンダリストレージと、代替ホストをホストする ESX サーバの間で iSCSI セッションが確立されていること、または FC 用に適切にゾーニングされていることを確認してください。
+
詳細については、を参照して https://docs.netapp.com/us-en/ontap-sanhost/["Host Utilitiesのマニュアル"]ください。



** ソースデータベースが ASM データベースの場合は、次の手順を実行します。
+
*** クローンを実行するホスト上で、 ASM インスタンスが稼働している必要があります。
*** クローニングされたデータベースのアーカイブログファイルを専用の ASM ディスクグループに配置する場合は、クローン処理の前に ASM ディスクグループをプロビジョニングする必要があります。
*** データディスクグループの名前は設定できますが、クローンを実行するホスト上の他の ASM ディスクグループでは名前が使用されないようにしてください。
+
ASMディスクグループ上のデータファイルは、SnapCenterクローンワークフローの一部としてプロビジョニングされます。



** NVMeの場合は、NVMe utilがインストールされている必要があります


* ログバックアップを使用して代替ホストにクローニングする際にセカンダリロケータを検出するには、データLUNとログLUNの保護タイプ（mirror、vault、mirror-vaultなど）を同じにする必要があります。
* 12_c_databaseのバックアップをクローニングするためのシードPDB関連情報を取得するには、ソースデータベースのパラメータファイルでexclude_seed_cdb_viewの値をFALSEに設定する必要があります。
+
シードPDBは、CDBがPDBを作成するために使用できるシステム提供のテンプレートです。シードPDBの名前はPDB$SEEDです。PDB$SEEDの詳細については、Oracle Doc ID 1940806.1を参照してください。

+

NOTE: この値は、12_c_databaseをバックアップする前に設定する必要があります。

* SnapCenterは'autofsサブシステムによって管理されるファイル・システムのバックアップをサポートしますデータベースをクローニングする場合は、データマウントポイントがautofsマウントポイントのルートの下にないようにしてください。プラグインホストのrootユーザには、autofsマウントポイントのルートの下にディレクトリを作成する権限がないためです。
+
制御ログファイルとREDOログファイルがデータマウントポイントにある場合は、制御ファイルのパスを変更し、それに応じてREDOログファイルのパスを変更する必要があります。

+

NOTE: クローンされた新しいマウント・ポイントは'autofsサブシステムに手動で登録できますクローニングされた新しいマウントポイントは自動的には登録されません。

* TDE （自動ログイン）を使用していて、同じホストまたは代替ホスト上にデータベースのクローンを作成する場合は、 /etc/oracle/ウォ レット /$ORACLE_SID_ の下にあるウォレット（キーファイル）をソースデータベースからクローンデータベースにコピーする必要があります。
* Oracle Linux 7 以降または Red Hat Enterprise Linux （ RHEL ） 7 以降の Storage Area Network （ SAN ；ストレージエリアネットワーク）環境でのクローニングを正常に実行するには、の値として、 /etc/lvm/lvmlvm/lvmmetad=0 を設定し、 lvm2-lvmetad サービスを停止する必要があります。
* Oracleデータベース11.2.0.3以降を使用していて、NIDスクリプトを使用して補助インスタンスのデータベースIDを変更している場合は、13366202 Oracleパッチをインストールする必要があります。
* ボリュームをホストするアグリゲートがStorage Virtual Machine（SVM）の割り当て済みアグリゲートリストに含まれている必要があります。
* NVMeで接続から除外するターゲットポートがある場合は、/var/opt/snapcenter/scu/etc/nvme.confファイルにターゲットのノード名とポート名を追加します。
+
ファイルが存在しない場合は、次の例に示すようにファイルを作成する必要があります。

+
....
blacklist {
nn-0x<target_node_name_1>:pn-0x<target_port_name_1>
nn-0x<target_node_name_2>:pn-0x<target_port_name_2>
}
....
* iSCSIプロトコルとFCプロトコルが混在するigroupを使用して、LUNがAIXホストにマッピングされていないことを確認してください。詳細については、を参照してください https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["LUNのデバイスを検出できませんというエラーが表示されて処理に失敗します"^]。

