---
permalink: protect-sco/supported_backup_configs.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: SnapCenter では、各種の Oracle データベース構成のバックアップがサポートされます。 
---
= バックアップでサポートされるOracleデータベース構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter では、各種の Oracle データベース構成のバックアップがサポートされます。

* Oracleスタンドアロン
* Oracle Real Application Clusters（RAC）
* Oracleスタンドアロンレガシー
* Oracleスタンドアロンコンテナデータベース（CDB）
* Oracle Data Guardスタンバイ
+
オフラインマウントバックアップは、Data Guardスタンバイデータベースのみ作成できます。オフラインシャットダウンバックアップ、アーカイブログのみのバックアップ、およびフルバックアップはサポートされていません。

* Oracle Active Data Guardスタンバイ
+
オンラインバックアップは、Active Data Guardスタンバイデータベースのみ作成できます。アーカイブログのみのバックアップとフルバックアップはサポートされません。

+
Data GuardスタンバイデータベースまたはActive Data Guardスタンバイデータベースのバックアップを作成する前に、Managed Recovery Process（MRP；管理リカバリプロセス）が停止し、バックアップが作成されるとMRPが開始されます。

* Automatic Storage Management（ASM；自動ストレージ管理）
+
** 仮想マシンディスク（ VMDK ）上の ASM スタンドアロンおよび ASM RAC
+
Oracleデータベースでサポートされているすべてのリストア方式の中で、VMDK上で実行できるのはASM RACデータベースの接続およびコピーリストアだけです。

** ASMスタンドアロンおよびASM RAC on Raw Device Mapping（RDM）+ ASMLibの有無にかかわらず、ASM上のOracleデータベースに対してバックアップ、リストア、およびクローニングの操作を実行できます。
** Oracle ASMフィルタドライバ（ASMFD）
+
PDB移行およびPDBクローニング処理はサポートされていません。

** Oracle Flex ASM




サポートされているOracleのバージョンの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]ください。
