---
permalink: protect-sco/task_define_a_clone_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, cloning type, clone name, limitations 
summary: データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。 
---
= Oracleデータベースのクローニング戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。



== クローニングでサポートされるバックアップのタイプ

SnapCenterでは、Oracleデータベースのさまざまなタイプのバックアップのクローニングがサポートされます。

* オンラインデータバックアップ
* オンラインフルバックアップ
* オフラインマウントバックアップ
* オフラインシャットダウンバックアップ
* Data GuardスタンバイデータベースおよびActive Data Guardスタンバイデータベースのバックアップ
* Real Application Clusters（RAC）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、およびオフラインシャットダウンバックアップ
* Automatic Storage Management（ASM）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ
+

IMPORTANT: マルチパス構成ファイルのuser_friendly_namesオプションがyesに設定されている場合、SAN構成はサポートされません。




NOTE: アーカイブログバックアップのクローニングはサポートされていません。



== Oracleデータベースでサポートされるクローニングのタイプ

Oracle データベース環境では、 SnapCenter がデータベースバックアップのクローニングをサポートします。バックアップは、プライマリストレージシステムとセカンダリストレージシステムからクローニングできます。

SnapCenter サーバは、 NetApp FlexClone テクノロジを使用してバックアップをクローニングします。

クローンを更新するには、「Refresh-SmClone」コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除して、同じ名前のクローンを作成します。


NOTE: クローンの更新処理は、UNIXコマンドでのみ実行できます。



== Oracleデータベースのクローンの命名規則

SnapCenter 3.0 以降では、ファイルシステムのクローンに、 ASM ディスクグループのクローンとは異なる命名規則が使用されます。

* SANファイルシステムまたはNFSファイルシステムの命名規則は、FileSystemNameofsourcedatabase_CLONESIDです。
* ASMディスクグループの命名規則は、SC_HASHCODEofDISKGROUP_CLONESIDです。
+
HASHCODEofDISKGROUPは、ASMディスクグループごとに一意の、自動的に生成される番号（2～10桁）です。





== Oracleデータベースのクローニングに関する制限事項

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* Oracle 11.2.0.4 ～ 12.1.0.1 のいずれかのバージョンを使用している場合、 _renamedg_command の実行時にクローン操作がハング状態になります。この問題を修正するには、Oracleパッチ19544733を適用します。
* ホストに直接接続されているLUN（たとえば、WindowsホストでMicrosoft iSCSIイニシエータを使用）から、同じWindowsホスト上のVMDKまたはRDM LUN、または別のWindowsホスト（またはその逆）にデータベースをクローニングすることはできません。
* ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* クローンを含むLUNを新しいボリュームに移動した場合、そのクローンは削除できません。

