---
permalink: protect-sco/task_define_a_clone_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, cloning type, clone name, limitations 
summary: データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。 
---
= Oracle データベースのクローニング戦略を定義する
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。



== クローニングでサポートされるバックアップのタイプ

SnapCenter では、 Oracle データベースの各種バックアップのクローニングがサポートされます。

* オンラインデータバックアップ
* オンラインフルバックアップ
* オフラインマウントバックアップ
* オフラインシャットダウンバックアップ
* Data Guard スタンバイデータベースおよび Active Data Guard スタンバイデータベースのバックアップ
* Real Application Clusters （ RAC ）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ
* Automatic Storage Management （ ASM ）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ
+

IMPORTANT: マルチパス構成ファイルで user_friendly _name オプションが yes に設定されていて、 udev ルールファイルを使用して Oracle ASM ディスクに対してエイリアスまたはシンボリックリンクが定義されている場合、 Oracle ASM 設定はサポートされません。




NOTE: アーカイブログのバックアップのクローニングはサポートされていません。



== Oracle データベースでサポートされるクローニングのタイプ

Oracle データベース環境では、 SnapCenter がデータベースバックアップのクローニングをサポートします。バックアップのクローニングは、プライマリストレージシステムおよびセカンダリストレージシステムから行うことができます。

SnapCenter サーバは、 NetApp FlexClone テクノロジを使用してバックアップをクローニングします。

クローンを更新するには、「 Refresh-SmClone 」コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除し、同じ名前でクローンを作成します。


NOTE: クローンの更新処理は、 UNIX コマンドでのみ実行できます。



== Oracle データベースのクローンの命名規則

SnapCenter 3.0 以降では、ファイルシステムのクローンに、 ASM ディスクグループのクローンとは異なる命名規則が使用されます。

* SAN または NFS ファイルシステムの命名規則は、 FileSystemNameofsourcedatabE_CLONESID です。
* ASM ディスクグループの命名規則は、 SC_HASHCODEofDISKGROUP_CLONESID です。
+
HASHCODEofDISKGROUP は、 ASM ディスクグループごとに一意の自動生成番号（ 2 ～ 10 桁）です。





== Oracle データベースのクローニングの制限

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* Oracle 11.2.0.4 ～ 12.1.0.1 のいずれかのバージョンを使用している場合、 _renamedg_command の実行時にクローン操作がハング状態になります。この問題を修正するには、 Oracle パッチ 19544733 を適用します。
* ホストに直接接続された LUN （ Windows ホストで Microsoft iSCSI イニシエータを使用した場合など）から、同じ Windows ホストまたは別の Windows ホスト上の VMDK または RDM LUN に、あるいはその逆に、データベースをクローニングすることはできません。
* ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* クローンが含まれている LUN を新しいボリュームに移動した場合、そのクローンは削除できません。

