---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: 'クローンを更新するには、 [Refresh-SmClone] コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除し、同じ名前でクローンを作成します。' 
---
= クローンをリフレッシュします
:icons: font
:imagesdir: ../media/


[role="lead"]
クローンを更新するには、 _Refresh-SmClone_ コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除し、同じ名前でクローンを作成します。


NOTE: PDB クローンは更新できません。

* 必要なもの *

* スケジュールされたバックアップが有効になっていない状態で、オンラインフルバックアップまたはオフラインデータバックアップポリシーを作成します。
* バックアップエラーのみに関する E メール通知をポリシーで設定します。
* オンデマンドバックアップの保持数を適切に定義して、不要なバックアップがないことを確認します。
* 更新クローン処理で特定されるリソースグループには、オンラインフルバックアップまたはオフラインデータバックアップポリシーのみが関連付けられていることを確認します。
* データベースが 1 つだけのリソースグループを作成する。
* clone refresh コマンドに対して cron ジョブが作成される場合は、 SnapCenter スケジュールおよび cron スケジュールがデータベースリソースグループに対して重複しないようにしてください。
+
clone refresh コマンド用に作成された cron ジョブの場合、 24 時間ごとに Open-SmConnection を実行してください。

* クローンの SID がホストで一意であることを確認します。
+
複数の更新クローン処理で同じクローン仕様ファイルを使用する場合、または同じクローン SID を持つクローン仕様ファイルを使用する場合は、ホスト上で SID を持つ既存のクローンが削除され、そのクローンが作成されます。

* セカンダリ・バックアップを使用してクローンを作成するには ' バックアップ・ポリシーがセカンダリ保護で有効になっていること ' およびクローン仕様ファイルが作成されていることを確認してください
+
** プライマリクローン仕様ファイルを指定し、ポリシーでセカンダリ更新オプションを選択した場合、バックアップが作成され、セカンダリに更新が転送されます。ただし、クローンはプライマリバックアップから作成されます。
** プライマリクローン仕様ファイルを指定し、ポリシーでセカンダリ更新オプションが選択されていない場合、プライマリ上にバックアップが作成され、プライマリからクローンが作成されます。




* 手順 *

. 指定されたユーザ用に SnapCenter サーバとの接続セッションを開始します： _Open-SmConnection_
. 指定したバックアップから Oracle データベースのクローン仕様を作成します： _New-SmOracleCloneSpecification_
+

NOTE: セカンダリデータ保護ポリシーが Unified mirror-vault の場合は、 -IncludeSecondaryDetails のみを指定します。SecondaryStorageType を指定する必要はありません。

+
このコマンドは、指定したソースデータベースとそのバックアップに対して、 Oracle データベースのクローン仕様ファイルを自動的に作成します。作成するクローンデータベースに対して自動的に生成される値がこの仕様ファイルに取り込まれるようにするために、クローンデータベースの SID も指定する必要があります。

+

NOTE: クローン仕様ファイルは、 /var/opt/snapcenter /sca/clone_specs__ に作成されます。

. Run_Refresh - SmClone_ 。
+
"PL-SCO-20032: CanExecute 操作がエラーで失敗した場合 : PL-SCO-300331: Redo ログファイル +SC_2959770772_clmdb/clredolog/redo01_01.log Exist" エラーメッセージが表示されたときに、操作が失敗した場合は、 -WaitToTriggerClone_" に高い値を指定してください。

+
UNIX コマンドの詳細については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2877144["SnapCenter ソフトウェアコマンドリファレンスガイド"^]。


