---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: 'クローンを更新するには、 [Refresh-SmClone] コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除して、同じ名前のクローンを作成します。' 
---
= クローンを更新します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローンを更新するには、 _Refresh-SmClone_ コマンドを実行します。このコマンドは、データベースのバックアップを作成し、既存のクローンを削除して、同じ名前のクローンを作成します。


NOTE: PDBクローンは更新できません。

* 必要なもの *

* スケジュールされたバックアップを有効にしないで、オンラインフルバックアップまたはオフラインデータバックアップポリシーを作成します。
* バックアップが失敗した場合にのみ、ポリシーでEメール通知を設定します。
* 不要なバックアップがないように、オンデマンドバックアップの保持数を適切に定義します。
* クローン更新処理用に指定したリソースグループには、オンラインフルバックアップまたはオフラインデータバックアップポリシーのみが関連付けられていることを確認してください。
* データベースが1つだけのリソースグループを作成します。
* clone refreshコマンド用にcronジョブを作成する場合は、SnapCenterスケジュールとcronスケジュールがデータベースリソースグループで重複していないことを確認してください。
+
clone refreshコマンド用に作成されたcronジョブの場合は、必ず24時間ごとにOpen-SmConnectionを実行してください。

* クローンSIDがホストで一意であることを確認します。
+
複数のクローン更新処理で同じクローン仕様ファイルを使用する場合、または同じクローンSIDのクローン仕様ファイルを使用する場合は、ホスト上のSIDを持つ既存のクローンが削除され、クローンが作成されます。

* セカンダリ・バックアップを使用してクローンを作成するには ' バックアップ・ポリシーがセカンダリ保護で有効になっていること ' およびクローン仕様ファイルが作成されていることを確認してください
+
** プライマリクローン仕様ファイルを指定し、ポリシーでセカンダリ更新オプションを選択した場合、バックアップが作成され、セカンダリに更新が転送されます。ただし、クローンはプライマリバックアップから作成されます。
** プライマリクローン仕様ファイルを指定し、ポリシーでセカンダリ更新オプションが選択されていない場合、プライマリ上にバックアップが作成され、プライマリからクローンが作成されます。




* 手順 *

. 指定されたユーザ用に SnapCenter サーバとの接続セッションを開始します： _Open-SmConnection_
. 指定したバックアップから Oracle データベースのクローン仕様を作成します： _New-SmOracleCloneSpecification_
+

NOTE: セカンダリデータ保護ポリシーがunified mirror-vaultの場合は、-IncludeSecondaryDetailsのみを指定します。SecondaryStorageTypeを指定する必要はありません。

+
このコマンドは、指定したソースデータベースとそのバックアップ用に、Oracleデータベースのクローン仕様ファイルを自動的に作成します。また、作成するクローンデータベースに対して自動的に生成される値を仕様ファイルに含めるために、クローンデータベースのSIDも指定する必要があります。

+

NOTE: クローン仕様ファイルは、 /var/opt/snapcenter /sca/clone_specs__ に作成されます。

. Run_Refresh - SmClone_ 。
+
"PL-SCO-20032: CanExecute 操作がエラーで失敗した場合 : PL-SCO-300331: Redo ログファイル +SC_2959770772_clmdb/clredolog/redo01_01.log Exist" エラーメッセージが表示されたときに、操作が失敗した場合は、 -WaitToTriggerClone_" に高い値を指定してください。

+
UNIXコマンドの詳細については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP3323470["SnapCenter ソフトウェアコマンドリファレンスガイド"^]。


