---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。 
---
= Oracle データベースのリストアとリカバリの戦略を定義する
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。



== リストア処理とリカバリ処理でサポートされるバックアップのタイプ

SnapCenter では、各種の Oracle データベースバックアップのリストアとリカバリがサポートされます。

* オンラインデータバックアップ
* オフラインシャットダウンデータバックアップ
* オフラインマウントデータバックアップ
* フルバックアップ
* Data Guard スタンバイデータベースのオフラインマウントバックアップ
* Active Data Guard スタンバイデータベースの、データのみのオンラインバックアップ
+

NOTE: Active Data Guard スタンバイデータベースのリカバリは実行できません。

* Real Application Clusters （ RAC ）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ
* Automatic Storage Management （ ASM ）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ




== Oracle データベースでサポートされるリストア方式のタイプ

SnapCenter では、 Oracle データベースに対して Connect and Copy リストアと In Place リストアがサポートされます。SnapCenter は、リストア処理中に、データを失うことなくリストアに使用するファイルシステムに適したリストア方式を決定します。


NOTE: SnapCenter はボリュームベースの SnapRestore をサポートしていません。



=== Connect and Copy リストア

データベースレイアウトがバックアップと異なる場合や、バックアップ作成後に新しいファイルがある場合は、 Connect and Copy リストアが実行されます。Connect and Copy リストア方式では、次のタスクが実行されます。

* 手順 *

. ボリュームは Snapshot コピーからクローニングされ、ファイルシステムスタックは、クローニングされた LUN またはボリュームを使用してホスト上に構築されます。
. クローニングされたファイルシステムから元のファイルシステムにファイルがコピーされます。
. クローニングされたファイルシステムがホストからアンマウントされ、クローニングされたボリュームが ONTAP から削除されます。



NOTE: Flex ASM 設定（カードの数が RAC クラスタ内のノード数より少ない場合）または VMDK または RDM 上の ASM RAC データベースでは、 Connect and Copy リストア方式のみがサポートされます。

In Place リストアを強制的に有効にした場合でも、次のシナリオでは SnapCenter によって Connect and Copy リストアが実行されます。

* 8.3 より前のバージョンの Data ONTAP でセカンダリストレージシステムからリストアする
* データベースインスタンスが設定されていない Oracle RAC セットアップのノードに存在する ASM ディスクグループをリストアする場合
* Oracle RAC セットアップで、いずれかのピアノードで ASM インスタンスまたはクラスタインスタンスが実行されていない場合、またはピアノードが停止している場合
* 制御ファイルのみをリストア
* ASM ディスクグループに存在する表領域の一部をリストアします
* ディスクグループは、データファイル、 SP ファイル、パスワードファイルの間で共有されます
* RAC 環境のリモートノードに SnapCenter Plug-in Loader （ SPL ）サービスがインストールされていないか実行されていない場合
* Oracle RAC に新しいノードが追加され、 SnapCenter サーバは新しく追加されたノードを認識しません




=== In Place リストアを実行します

データベースレイアウトがバックアップとほぼ同じであり、かつストレージとデータベーススタックで設定変更が行われていない場合は、 In Place リストアが実行されて、ファイルまたは LUN のリストアが ONTAP 上で実行されます。SnapCenter では、 In Place リストア方式の一環として Single File SnapRestore （ SFSR ）のみがサポートされます。


NOTE: Data ONTAP 8.3 以降では、セカンダリサイトからの In Place リストアがサポートされます。

データベースで In Place リストアを実行する場合は、 ASM ディスクグループにデータファイルだけがあることを確認してください。ASM ディスクグループまたはデータベースの物理構造に変更を加えた場合は、バックアップを作成する必要があります。In Place リストアを実行すると、ディスクグループにバックアップ時と同じ数のデータファイルが格納されます。

ディスクグループまたはマウントポイントが次の基準に一致する場合は、 In Place リストアが自動的に適用されます。

* バックアップ後に新しいデータファイルが追加されていない（外部ファイルチェック）
* バックアップ後に ASM ディスクまたは LUN の追加、削除、または再作成が行われていない（ ASM ディスクグループの構造変更チェック）
* LVM ディスクグループに対して LUN の追加、削除、または再作成が行われていない（ LVM ディスクグループの構造変更チェック）



NOTE: In Place リストアを強制的に有効にすることもできます。有効にするには、 GUI 、 SnapCenter CLI 、または PowerShell コマンドレットを使用して、外部ファイルチェックおよび LVM ディスクグループの構造変更チェックを無効にします。



==== ASM RAC で In Place リストアを実行します

SnapCenter では、リストアを実行するノードがプライマリノードと呼ばれ、 ASM ディスクグループがある RAC 上のその他すべてのノードがピアノードと呼ばれます。SnapCenter は、ストレージリストア処理を実行する前に、 ASM ディスクグループがマウント状態にあるすべてのノードで、ディスマウントする ASM ディスクグループの状態を変更します。ストレージのリストアが完了すると、 SnapCenter はリストア処理前と同じ状態で ASM ディスクグループの状態を変更します。

SAN 環境では、ストレージリストア処理の前に、 SnapCenter がすべてのピアノードからデバイスを削除し、 LUN のマッピング解除処理を実行します。ストレージリストア処理が完了すると、 SnapCenter は LUN マップ処理を実行し、すべてのピアノードでデバイスを構築します。SAN 環境の LUN 上に Oracle RAC ASM レイアウトが存在する場合は、 SnapCenter のリストア中に、 ASM ディスクグループが存在する RAC クラスタのすべてのノードで LUN のマッピング解除、 LUN のリストア、および LUN のマッピングが実行されます。リストア前に RAC ノードのすべてのイニシエータが LUN に使用されていなかった場合でも、 SnapCenter をリストアすると、すべての RAC ノードのすべてのイニシエータを含む新しい igroup が作成されます。

* ピアノードでリストア前の処理中にエラーが発生した場合は、リストア前の処理が成功したピアノードで SnapCenter が自動的に ASM ディスクグループの状態をリストア実行前の状態にロールバックします。プライマリノードおよび処理が失敗したピアノードでは、ロールバックはサポートされていません。新たなリストアを実行する前に、ピアノードの問題を手動で修正し、プライマリノード上の ASM ディスクグループをマウント状態に戻す必要があります。
* リストア処理中にエラーが発生した場合は、リストア処理が失敗し、ロールバックは実行されません。新たなリストアを実行する前に、ストレージリストア問題を手動で修正し、プライマリノード上の ASM ディスクグループをマウント状態に戻す必要があります。
* いずれかのピアノードでリストア後の処理中にエラーが発生した場合、 SnapCenter は他のピアノードでリストア処理を続行します。ピアノードでリストア後の問題を手動で修正する必要があります。




== Oracle データベースでサポートされるリストア処理のタイプ

SnapCenter では、 Oracle データベースに対してさまざまなタイプのリストア処理を実行できます。

データベースをリストアする前に、バックアップが検証されて、実際のデータベースファイルと比較して足りないファイルがないかどうかが確認されます。



=== フルリストア

* データファイルのみをリストアします
* 制御ファイルのみをリストアします
* データファイルと制御ファイルをリストアします
* Data Guard スタンバイデータベースと Active Data Guard スタンバイデータベースにあるデータファイル、制御ファイル、および REDO ログファイルをリストアします




=== 部分リストア

* 選択した表領域のみをリストアします
* 選択した Pluggable Database （ PDB ）のみをリストア
* 1 つの PDB の選択した表領域のみをリストアします




== Oracle データベースでサポートされるリカバリ処理のタイプ

SnapCenter では、 Oracle データベースに対してさまざまなタイプのリカバリ処理を実行できます。

* 最後のトランザクションまで（すべてのログ）のデータベース
* 特定の System Change Number （ SCN ）までのデータベース
* 特定の日時までのデータベース
+
リカバリの日時はデータベースホストのタイムゾーンに基づいて指定する必要があります。

+
SnapCenter には 'Oracle データベースのリカバリ・オプションはありません




NOTE: スタンバイとしてのデータベースロールで作成されたバックアップを使用してリストアを実行した場合、 Plug-in for Oracle Database ではリカバリがサポートされません。物理スタンバイデータベースは、常に手動でリカバリする必要があります。



== Oracle データベースのリストアとリカバリに関する制限事項

リストア処理とリカバリ処理を実行する前に、制限事項を確認しておく必要があります。

11.2.0.4 から 12.1.0.1 までの Oracle のいずれかのバージョンを使用している場合、 _renamedg_command の実行時にリストア処理がハング状態になります。この問題を修正するには、 Oracle パッチ 19544733 を適用します。

次のリストア処理とリカバリ処理はサポートされていません。

* ルートコンテナデータベース（ CDB ）の表領域のリストアとリカバリ
* 一時表領域および PDB に関連付けられた一時表領域のリストア
* 複数の PDB から同時に行う表領域のリストアとリカバリ
* ログバックアップのリストア
* 別の場所へのバックアップのリストア
* Data Guard スタンバイデータベースまたは Active Data Guard スタンバイデータベース以外の構成での redo ログファイルのリストア
* SPFILE およびパスワード・ファイルのリストア
* 同じホスト上の既存のデータベース名を使用して再作成され、 SnapCenter で管理されていて、有効なバックアップがあるデータベースに対してリストア処理を実行すると、 DBID が異なる場合でも、新しく作成されたデータベースファイルが上書きされます。
+
これを回避するには、次のいずれかの操作を実行します。

+
** データベースを再作成したら、 SnapCenter リソースを検出します
** 再作成したデータベースのバックアップを作成します






== 表領域のポイントインタイムリカバリに関する制限事項

* SYSTEM 、 SYSAUX 、 UNDO の PITR （ポイント・イン・タイム・リカバリ）はサポートされていません
* 表領域の PITR は、他のタイプのリストアと同時には実行できません
* テーブルスペースの名前を変更したあと、名前を変更する前に名前を特定の時点にリカバリする場合は、以前の表領域名を指定する必要があります
* 1 つの表領域内の表に対する制約が別の表領域に含まれている場合は、両方の表領域をリカバリする必要があります
* テーブルとそのインデックスが異なるテーブルスペースに格納されている場合は、 PITR を実行する前にインデックスを削除する必要があります
* PITR を使用して、現在のデフォルトテーブルスペースを回復することはできません
* PITR を使用して、次のオブジェクトを含む表領域を回復することはできません。
+
** 基になるオブジェクト（実体化ビュー (Materialized View) など）または含まれるオブジェクト（パーティション化されたテーブルなど）を含むオブジェクトは ' 基になるオブジェクトまたは含まれるオブジェクトがすべてリカバリ・セットに含まれている場合を除きます
+
また、分割されたテーブルのパーティションが異なるテーブルスペースに格納されている場合は、 PITR を実行する前にテーブルを削除するか、すべてのパーティションを同じテーブルスペースに移動してから PITR を実行する必要があります。

** セグメントを元に戻すかロールバックします
** Oracle 8 では、複数の受信者と互換性のある拡張キューを使用でき
** SYS ユーザが所有するオブジェクト
+
これらのタイプのオブジェクトの例としては、 PL/SQL 、 Java クラス、呼び出しプログラム、ビュー、同義語、 ユーザー、特権、寸法、ディレクトリ、およびシーケンス。







== Oracle データベースをリストアするためのソースとデスティネーション

プライマリストレージまたはセカンダリストレージにあるバックアップコピーから Oracle データベースをリストアすることができます。データベースは、同じデータベースインスタンスの同じ場所にのみリストアできます。ただし、 Real Application Cluster （ RAC ）セットアップでは、データベースを他のノードにリストアできます。



=== リストア処理のソース

プライマリストレージまたはセカンダリストレージ上のバックアップからデータベースをリストアすることができます。複数ミラー構成でセカンダリストレージ上のバックアップからリストアする場合は、セカンダリストレージミラーをソースとして選択できます。



=== リストア処理のデスティネーション

データベースは、同じデータベースインスタンスの同じ場所にのみリストアできます。

RAC セットアップでは、クラスタ内の任意のノードから RAC データベースをリストアできます。
