---
permalink: protect-sco/task_define_a_backup_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: バックアップ戦略を定義することで、データベースを正常にリストアまたはクローニングできるようになります。 
---
= Oracleデータベースのバックアップ戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ戦略を定義して、データベースを正常にリストアまたはクローニングできるようにします。

バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。

* SLAは、期待されるサービスレベルを定義し、サービスの可用性やパフォーマンスなどのサービス関連の問題に対処するものです。
* RTOは、サービスの中断後にビジネスプロセスをリストアする必要がある時間を定義します。
* RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間を定義します。




== バックアップでサポートされるOracleデータベース構成

SnapCenter では、各種の Oracle データベース構成のバックアップがサポートされます。

* Oracleスタンドアロン
* Oracle Real Application Clusters（RAC）
* Oracleスタンドアロンレガシー
* Oracleスタンドアロンコンテナデータベース（CDB）
* Oracle Data Guardスタンバイ
+
オフラインマウントバックアップは、Data Guardスタンバイデータベースのみ作成できます。オフラインシャットダウンバックアップ、アーカイブログのみのバックアップ、およびフルバックアップはサポートされていません。

* Oracle Active Data Guardスタンバイ
+
オンラインバックアップは、Active Data Guardスタンバイデータベースのみ作成できます。アーカイブログのみのバックアップとフルバックアップはサポートされません。

+

NOTE: Data GuardスタンバイデータベースまたはActive Data Guardスタンバイデータベースのバックアップを作成する前に、Managed Recovery Process（MRP；管理リカバリプロセス）が停止し、バックアップが作成されるとMRPが開始されます。

* Automatic Storage Management（ASM；自動ストレージ管理）
+
** 仮想マシンディスク（ VMDK ）上の ASM スタンドアロンおよび ASM RAC
+

NOTE: Oracleデータベースでサポートされているすべてのリストア方式の中で、VMDK上で実行できるのはASM RACデータベースの接続およびコピーリストアだけです。

** raw デバイスマッピング（ RDM ）上の ASM スタンドアロンおよび ASM RAC では、 ASM 上の Oracle データベースに対して、 ASMLib の有無に関係なく、バックアップ、リストア、クローニングの各処理を実行できます。
** Oracle ASMフィルタドライバ（ASMFD）
+

NOTE: PDB移行およびPDBクローニング処理はサポートされていません。

** Oracle Flex ASM




サポートされているOracleのバージョンの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]ください。



== Oracleデータベースでサポートされるバックアップのタイプ

Backup typeには、作成するバックアップのタイプを指定します。SnapCenter では、 Oracle データベースに対してオンラインバックアップタイプとオフラインバックアップタイプがサポートされます。



=== オンラインバックアップ

データベースがオンライン状態のときに作成されるバックアップを、オンラインバックアップと呼びます。ホットバックアップとも呼ばれるオンラインバックアップでは、データベースをシャットダウンすることなくバックアップを作成できます。

オンラインバックアップの一環として、次のファイルのバックアップを作成できます。

* データファイルと制御ファイルのみ
* アーカイブログファイルのみ（このシナリオではデータベースはバックアップモードになりません）
* データファイル、制御ファイル、アーカイブログファイルを含むフルデータベース




=== オフラインバックアップ

データベースがマウント済み状態またはシャットダウン状態のときに作成されるバックアップを、オフラインバックアップと呼びます。オフラインバックアップはコールドバックアップとも呼ばれます。オフラインバックアップに含めることができるのはデータファイルと制御ファイルだけです。オフラインマウントバックアップまたはオフラインシャットダウンバックアップを作成できます。

* オフラインマウントバックアップを作成する場合は、データベースがマウント済み状態であることを確認する必要があります。
+
データベースがその他の状態の場合、バックアップ処理は失敗します。

* オフラインシャットダウンバックアップを作成する場合、データベースはどの状態でもかまいません。
+
データベースは、バックアップを作成するために必要な状態に変更されます。バックアップが作成されると、データベースは元の状態に戻ります。





== SnapCenterによるOracleデータベースの検出方法

「リソース」とは、SnapCenterによって管理されるホスト上のOracleデータベースです。使用可能なデータベースを検出したあとに、これらのデータベースをリソースグループに追加してデータ保護処理を実行できます。さまざまなタイプとバージョンのOracleデータベースを検出するためにSnapCenterが実行するプロセスを理解しておく必要があります。

|===
| Oracle バージョン 11_________ ～ 12_c_R1 | Oracle バージョン 12_c_R2 から 18_c_c__ 


 a| 
*RAC データベース *: RAC データベースは /etc/oratab エントリに基づいてのみ検出されます。

/etc/oratabファイルにデータベースエントリが格納されている必要があります。
 a| 
*RAC データベース *: srvctl config コマンドを使用して RAC データベースが検出されます。



 a| 
* スタンドアロン * ：スタンドアロン・データベースは、 /etc/oratab エントリに基づいてのみ検出されます。

/etc/oratabファイルにデータベースエントリが格納されている必要があります。
 a| 
* Standalone * ： /etc/oratab ファイル内のエントリおよび srvctl config コマンドの出力に基づいて、スタンドアロンデータベースが検出されます。



 a| 
*ASM*: ASM インスタンス・エントリは、 /etc/oratab ファイル内に存在する必要があります。
 a| 
*ASM*: ASM インスタンス・エントリは、 /etc/oratab ファイル内に存在する必要はありません。



 a| 
* RAC One Node * ： RAC One Node データベースは、 /etc/oratab エントリに基づいてのみ検出されます。

データベースは、 _nomount_ 、 _mount_、 または _open_state のいずれかである必要があります。/etc/oratabファイルにデータベースエントリが格納されている必要があります。

データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置する場合は、次の手順を実行する必要があります。

. フェイルオーバーされたRACノードの/etc/oratabファイルに、再配置されたデータベースエントリを手動で追加します。
. リソースを手動で更新します。
. リソースページから RAC One Node データベースを選択し、 * Database Settings * （データベース設定）をクリックします。
. データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタノードを設定します。
. SnapCenter処理を実行します。



NOTE: あるノードから別のノードにデータベースを再配置したときに、以前のノードのoratabエントリが削除されていない場合は、同じデータベースが2回表示されないように、oratabエントリを手動で削除する必要があります。
 a| 
* RAC One Node * ： srvctl config コマンドのみを使用して、 RAC One Node データベースを検出します。

データベースは、 _nomount_ 、 _mount_、 または _open_state のいずれかである必要があります。データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置する場合は、次の手順を実行する必要があります。

. リソースを手動で更新します。
. リソースページから RAC One Node データベースを選択し、 ** Database Settings ** をクリックします。
. データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタノードを設定します。
. SnapCenter処理を実行します。


|===

NOTE: /etc/oratab ファイル内に Oracle 12_c__R2 および 18_c_database のエントリがあり、同じデータベースが srvctl config コマンドで登録されている場合、 SnapCenter は重複するデータベースエントリを削除します。古いデータベースエントリがある場合、データベースは検出されますが、データベースは到達不能になり、ステータスはオフラインになります。



== RACセツトアツフノユウセンノオト

Oracle Real Application Clusters（RAC）セットアップでは、バックアップ処理を実行する優先ノードを指定できます。優先ノードを指定しない場合は、 SnapCenter によって自動的に優先ノードが割り当てられ、そのノードにバックアップが作成されます。

優先ノードには、RACデータベースインスタンスが存在するクラスタノードの1つまたはすべてを指定できます。バックアップ処理は、これらの優先ノードで優先順位に従ってトリガされます。

例： RAC データベース cdbrac に 3 つのインスタンスがあります。 cdbrac1 on node1 、 cdbrac2 on node2 、および cdbrac3 on node3node1とnode2のインスタンスが優先ノードとして設定され、node2が第1優先ノード、node1が第2優先ノードとして設定されます。バックアップ処理を実行すると、最初の優先ノードであるnode2で最初に処理が試行されます。node2がバックアップ対象の状態でない場合（ホストでプラグインエージェントが実行されていないなどの複数の原因が考えられます）、ホスト上のデータベースインスタンスが指定したバックアップタイプに必要な状態ではありません。 または、FlexASM構成のnode2上のデータベースインスタンスがローカルASMインスタンスによって処理されていない場合、node1で処理が試行されます。node3は優先ノードのリストにないため、バックアップには使用されません。

Flex ASMセットアップでは、カーディナリティがRACクラスタ内のノード数より少ない場合、リーフノードは優先ノードとしてリストされません。Flex ASMクラスタノードのロールに変更があった場合は、優先ノードが更新されるように手動でを検出する必要があります。



=== 必要なデータベースの状態

バックアップを正常に完了するには、優先ノード上のRACデータベースインスタンスが必要な状態である必要があります。

* オンラインバックアップを作成するには、設定された優先ノードのRACデータベースインスタンスの1つがOPEN状態である必要があります。
* オフラインマウントバックアップを作成するには、設定された優先ノード内のRACデータベースインスタンスの1つがマウント状態であり、他のすべてのインスタンス（他の優先ノードを含む）がマウント状態以下である必要があります。
* RACデータベースインスタンスはどの状態でもかまいませんが、オフラインシャットダウンバックアップを作成するには優先ノードを指定する必要があります。




== Oracle Recovery Managerを使用してバックアップをカタログ化する方法

Oracle Recovery Manager（RMAN）を使用してOracleデータベースのバックアップをカタログ化し、Oracle RMANリポジトリにバックアップ情報を格納できます。

カタログ化されたバックアップは、あとでブロックレベルのリストア処理や表領域のポイントインタイムリカバリ処理に使用できます。カタログ化されたバックアップが不要となった場合は、カタログ情報を削除できます。

カタログ化するためには、データベースの状態が少なくともマウント済み状態であることが必要です。カタログ化を実行できるのは、データバックアップ、アーカイブログバックアップ、およびフルバックアップです。複数のデータベースを含むリソースグループのバックアップに対してカタログ化が有効になっている場合は、データベースごとにカタログ化が実行されます。Oracle RACデータベースの場合、データベースが少なくともマウント済み状態である優先ノードでカタログ化が実行されます。


NOTE: RACデータベースのバックアップをカタログ化する場合は、そのデータベースに対して他のジョブが実行されていないことを確認します。別のジョブが実行されている場合は、カタログ化処理がキューに登録されずに失敗します。

デフォルトでは、ターゲットデータベースの制御ファイルがカタログ化に使用されます。外部カタログデータベースを追加する場合は、SnapCenterグラフィカルユーザインターフェイス（GUI）のデータベース設定ウィザードを使用して、外部カタログのクレデンシャルと透過ネットワーク印刷材（TNS）名を指定して構成できます。CLIから外部カタログデータベースを設定するには、-OracleRmanCatalogCredentialNameオプションと-OracleRmanCatalogTnsNameオプションを指定してConfigure-SmOracleDatabaseコマンドを実行します。

SnapCenter GUIでOracleバックアップポリシーを作成するときにカタログ化オプションを有効にした場合は、バックアップ処理の一環としてOracle RMANを使用してバックアップがカタログ化されます。Catalog-SmBackupWithOracleRMANコマンドを実行して、バックアップの遅延カタログ化を実行することもできます。バックアップをカタログ化したら、Get-SmBackupDetailsコマンドを実行して、カタログ化されたバックアップの情報（カタログ化されたデータファイルのタグ、制御ファイルのカタログパス、カタログ化されたアーカイブログの場所など）を取得できます。

SnapCenter 3.0以降では、ASMディスクグループ名が16文字以上の場合、バックアップに使用される命名形式はSC_HASHCODEofDISKGROUP_DBSID_BACKUPIDです。ただし、ディスクグループ名が16文字未満の場合、バックアップに使用される命名形式はDISKGROUPNAME_DBSID_BACKUPIDです。これは、SnapCenter 2.0で使用されている形式と同じです。


NOTE: HASHCODEofDISKGROUPは、ASMディスクグループごとに一意の、自動的に生成される番号（2～10桁）です。

クロスチェックを実行すると、リポジトリレコードが物理ステータスと一致しないバックアップに関するRMANリポジトリ情報を更新できます。たとえば、ユーザがオペレーティングシステムコマンドを使用してディスクからアーカイブログを削除しても、実際にはディスクにログがない場合でも、制御ファイルにはディスクにログがあることが示されます。クロスチェック処理では、制御ファイルの情報を更新できます。クロスチェックをイネーブルにするには、Set-SmConfigSettingsコマンドを実行し、ENABLE_CROSSCHECKパラメータにtrueを割り当てます。デフォルト値は FALSE です。

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`

カタログ情報を削除するには、Uncatalog-SmBackupWithOracleRMANコマンドを実行します。SnapCenter GUI ではカタログ情報を削除できません。ただし、バックアップを削除するとき、またはカタログ化されたバックアップに関連付けられている保持期間とリソースグループを削除するときに、カタログ化されたバックアップの情報が削除されます。


NOTE: SnapCenter ホストを強制的に削除する場合は、そのホストに関連するカタログ化されたバックアップの情報が削除されません。ホストを強制的に削除する場合は、事前にそのホストに関連するすべてのカタログ化されたバックアップの情報を削除しておく必要があります。

処理時間がORACLE_PLUGIN_RMAN_CATALOG_TIMEOUTパラメータに指定されたタイムアウト値を超えたためにカタログ化とカタログ化解除が失敗した場合は、次のコマンドを実行してパラメータの値を変更する必要があります。

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

パラメータの値を変更したら、次のコマンドを実行してSnapCenter Plug-in Loader（SPL）サービスを再起動します。

`/opt/NetApp/snapcenter/spl/bin/spl restart`

コマンドで使用できるパラメータとその説明については、Get-Help Command_nameを実行して確認できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP3323470["SnapCenter ソフトウェアコマンドリファレンスガイド"^]。



== バックアップスケジュール

バックアップ頻度（スケジュールタイプ）はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは1時間ごとにバックアップし、使用頻度の低いリソースは1日に1回バックアップすることもできます。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAは、期待されるサービスレベルと、サービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOはデータ保護戦略に影響します。

使用頻度の高いリソースであっても、フルバックアップを1日に1~2回以上実行する必要はありません。たとえば、定期的なトランザクションログバックアップで十分な場合は、必要なバックアップを作成できます。データベースをバックアップする回数が多いほど、リストア時に SnapCenter が使用する必要のあるトランザクションログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

バックアップスケジュールには、次の2つの部分があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインでは _ schedule type__ と呼ばれます。ポリシーでは、バックアップ頻度として、毎時、毎日、毎週、または毎月を選択できます。頻度を選択しない場合は、オンデマンドのみのポリシーが作成されます。ポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行されるタイミング）は、リソースグループ設定の一部です。たとえば、リソースグループのポリシーで週単位のバックアップが設定されている場合は、毎週木曜日の午後10時にバックアップが実行されるようにスケジュールを設定できます。リソースグループのスケジュールにアクセスするには、 * リソース * > * リソースグループ * をクリックします。





== バックアップの命名規則

Snapshotのデフォルトの命名規則を使用することも、カスタマイズした命名規則を使用することもできます。デフォルトのバックアップ命名規則では、Snapshot名にタイムスタンプが追加されるため、コピーがいつ作成されたかを確認できます。

Snapshotでは、次のデフォルトの命名規則が使用されます。

`resourcegroupname_hostname_timestamp`

バックアップリソースグループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* _dts1_は リソースグループ名です。
* _mach1x88_ はホスト名です。
* _03-12-2015_23.17.26_ は日付とタイムスタンプです。


または、*[Use custom name format for Snapshot copy]*を選択して、リソースまたはリソースグループを保護しながらSnapshot名の形式を指定することもできます。たとえば、customText_resourcegroup_policy_hostnameやresourcegroup_hostnameなどです。デフォルトでは、タイムスタンプのサフィックスがSnapshot名に追加されます。



== バックアップ保持オプション

バックアップコピーを保持する日数を選択することも、保持するバックアップコピーの数（ONTAPの最大コピー数255）を指定することもできます。たとえば、組織で、10日分のバックアップコピーや130個のバックアップコピーを保持する必要があるとします。

ポリシーの作成時に、バックアップタイプとスケジュールタイプの保持オプションを指定できます。

SnapMirrorレプリケーションを設定すると、デスティネーションボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、保持されているバックアップの保持ラベルがスケジュールタイプと一致する場合には、バックアップを削除します。リソースまたはリソースグループのスケジュールタイプを変更した場合、古いスケジュールタイプラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップコピーを長期にわたって保持する場合は、SnapVaultバックアップを使用する必要があります。



== プライマリストレージボリュームまたはセカンダリストレージボリュームを使用したバックアップコピーの検証

バックアップコピーは、プライマリストレージボリューム、またはSnapMirrorまたはSnapVaultセカンダリストレージボリュームで検証できます。セカンダリストレージボリュームを使用した検証により、プライマリストレージボリュームの負荷が軽減されます。

プライマリストレージボリュームまたはセカンダリストレージボリュームにあるバックアップを検証すると、すべてのプライマリSnapshotとセカンダリSnapshotが検証済みとマークされます。

SnapMirrorおよびSnapVaultセカンダリストレージボリューム上のバックアップコピーを検証するには、SnapRestoreライセンスが必要です。
