---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。 
---
= Oracleデータベースのリストアとリカバリの戦略を定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。



== リストア処理とリカバリ処理でサポートされるバックアップのタイプ

SnapCenterでは、さまざまなタイプのOracleデータベースバックアップのリストアとリカバリがサポートされます。

* オンラインデータバックアップ
* オフラインシャットダウンデータバックアップ
* オフラインマウントデータバックアップ
+

NOTE: オフラインシャットダウンまたはオフラインマウントデータバックアップをリストアする場合、SnapCenterはデータベースをオフライン状態のままにします。データベースを手動でリカバリし、ログをリセットする必要があります。

* フルバックアップ
* Data Guardスタンバイデータベースのオフラインマウントバックアップ
* Active Data Guardスタンバイデータベースのデータ専用オンラインバックアップ
+

NOTE: Active Data Guardスタンバイデータベースのリカバリは実行できません。

* Real Application Clusters（RAC）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、およびオフラインシャットダウンバックアップ
* Automatic Storage Management（ASM）構成でのオンラインデータバックアップ、オンラインフルバックアップ、オフラインマウントバックアップ、オフラインシャットダウンバックアップ




== Oracleデータベースでサポートされるリストア方式のタイプ

SnapCenter では、 Oracle データベースに対して Connect and Copy リストアと In Place リストアがサポートされます。SnapCenter は、リストア処理中に、データを失うことなくリストアに使用するファイルシステムに適したリストア方式を決定します。


NOTE: SnapCenter はボリュームベースの SnapRestore をサポートしていません。



=== Connect and Copyリストア

データベースレイアウトがバックアップと異なる場合、またはバックアップ作成後に新しいファイルが存在する場合は、Connect and Copyリストアが実行されます。Connect and Copyリストア方式では、次のタスクが実行されます。

* 手順 *

. ボリュームはSnapshotからクローニングされ、クローニングされたLUNまたはボリュームを使用してホスト上にファイルシステムスタックが構築されます。
. クローニングされたファイルシステムから元のファイルシステムにファイルがコピーされます。
. クローニングされたファイルシステムがホストからアンマウントされ、クローニングされたボリュームがONTAPから削除されます。



NOTE: Flex ASMセットアップ（RACクラスタ内のノード数よりも基数が少ない）またはVMDKまたはRDM上のASM RACデータベースでは、Connect and Copyリストア方式のみがサポートされます。

In Place リストアを強制的に有効にした場合でも、次のシナリオでは SnapCenter によって Connect and Copy リストアが実行されます。

* セカンダリストレージシステムからのリストア（Data ONTAP 8.3より前のバージョンの場合）
* データベースインスタンスが設定されていないOracle RACセットアップのノードにあるASMディスクグループのリストア
* Oracle RACセットアップで、いずれかのピアノード（ASMインスタンスまたはクラスタインスタンスが実行されていない場合、またはピアノードが停止している場合）
* 制御ファイルのみのリストア
* ASMディスクグループに存在する表領域のサブセットをリストアする
* ディスク・グループは'データ・ファイル'SPファイル'パスワード・ファイル間で共有されます
* RAC 環境のリモートノードに SnapCenter Plug-in Loader （ SPL ）サービスがインストールされていないか実行されていない場合
* Oracle RACに新しいノードが追加されたが、SnapCenterサーバは新たに追加されたノードを認識しない




=== In Placeリストア

データベースレイアウトがバックアップとほぼ同じで、ストレージとデータベーススタックで設定を変更していない場合は、In Placeリストアが実行され、ファイルまたはLUNのリストアがONTAP上で実行されます。SnapCenter では、 In Place リストア方式の一環として Single File SnapRestore （ SFSR ）のみがサポートされます。


NOTE: Data ONTAP 8.3以降では、セカンダリサイトからのIn Placeリストアがサポートされます。

データベースでIn Placeリストアを実行する場合は、ASMディスクグループにデータファイルだけがあることを確認してください。ASMディスクグループまたはデータベースの物理構造に変更を加えたあとに、バックアップを作成する必要があります。In Placeリストアの実行後、ディスクグループにはバックアップ時と同じ数のデータファイルが格納されます。

ディスクグループまたはマウントポイントが次の条件に一致すると、In Placeリストアが自動的に適用されます。

* バックアップ後に新しいデータファイルが追加されない（外部ファイルチェック）
* バックアップ後にASMディスクまたはLUNの追加、削除、再作成が行われない（ASMディスクグループの構造変更チェック）
* LVMディスクグループに対するLUNの追加、削除、または再作成が行われない（LVMディスクグループの構造変更チェック）



NOTE: In Place リストアを強制的に有効にすることもできます。有効にするには、 GUI 、 SnapCenter CLI 、または PowerShell コマンドレットを使用して、外部ファイルチェックおよび LVM ディスクグループの構造変更チェックを無効にします。



==== ASM RACでのIn Placeリストアの実行

SnapCenter では、リストアを実行するノードがプライマリノードと呼ばれ、 ASM ディスクグループがある RAC 上のその他すべてのノードがピアノードと呼ばれます。SnapCenter は、ストレージリストア処理を実行する前に、 ASM ディスクグループがマウント状態にあるすべてのノードで、ディスマウントする ASM ディスクグループの状態を変更します。ストレージのリストアが完了すると、SnapCenterはASMディスクグループの状態をリストア処理前の状態に変更します。

SAN 環境では、ストレージリストア処理の前に、 SnapCenter がすべてのピアノードからデバイスを削除し、 LUN のマッピング解除処理を実行します。ストレージリストア処理が完了すると、 SnapCenter は LUN マップ処理を実行し、すべてのピアノードでデバイスを構築します。SAN 環境の LUN 上に Oracle RAC ASM レイアウトが存在する場合は、 SnapCenter のリストア中に、 ASM ディスクグループが存在する RAC クラスタのすべてのノードで LUN のマッピング解除、 LUN のリストア、および LUN のマッピングが実行されます。リストア前に RAC ノードのすべてのイニシエータが LUN に使用されていなかった場合でも、 SnapCenter をリストアすると、すべての RAC ノードのすべてのイニシエータを含む新しい igroup が作成されます。

* ピアノードでリストア前の処理中にエラーが発生した場合は、リストア前の処理が成功したピアノードで SnapCenter が自動的に ASM ディスクグループの状態をリストア実行前の状態にロールバックします。ロールバックは、処理が失敗したプライマリノードおよびピアノードではサポートされていません。別のリストアを実行する前に、ピアノードの問題を手動で修正し、プライマリノードのASMディスクグループをMOUNT状態に戻す必要があります。
* リストア処理中にエラーが発生した場合は、リストア処理が失敗し、ロールバックは実行されません。別のリストアを実行する前に、ストレージリストアの問題を手動で修正し、プライマリノードのASMディスクグループをMOUNT状態に戻す必要があります。
* いずれかのピアノードでリストア後の処理中にエラーが発生した場合、 SnapCenter は他のピアノードでリストア処理を続行します。ピアノードでリストア後の問題を手動で修正する必要があります。




== Oracleデータベースでサポートされるリストア処理のタイプ

SnapCenter では、 Oracle データベースに対してさまざまなタイプのリストア処理を実行できます。

データベースをリストアする前に、バックアップが検証され、実際のデータベースファイルと比較して欠落しているファイルがないかどうかが確認されます。



=== フルリストア

* データファイルのみをリストア
* 制御ファイルのみをリストア
* データファイルと制御ファイルをリストア
* Data GuardスタンバイデータベースとActive Data Guardスタンバイデータベースのデータファイル、制御ファイル、REDOログファイルをリストア




=== パーシャルリストア

* 選択した表領域のみをリストア
* 選択したプラガブルデータベース（PDB）のみをリストア
* PDBの選択した表領域のみをリストア




== Oracleデータベースでサポートされるリカバリ処理のタイプ

SnapCenter では、 Oracle データベースに対してさまざまなタイプのリカバリ処理を実行できます。

* 最後のトランザクションまで（すべてのログ）のデータベース
* 特定のシステム変更番号（SCN）までのデータベース
* 特定の日時までのデータベース
+
リカバリの日時は、データベースホストのタイムゾーンに基づいて指定する必要があります。

+
SnapCenter には 'Oracle データベースのリカバリ・オプションはありません




NOTE: データベースロールをスタンバイとして作成されたバックアップを使用してリストアした場合、Plug-in for Oracle Databaseではリカバリがサポートされません。物理スタンバイデータベースのリカバリは、常に手動で実行する必要があります。



== Oracleデータベースのリストアとリカバリに関する制限事項

リストア処理とリカバリ処理を実行する前に、制限事項を確認しておく必要があります。

11.2.0.4 から 12.1.0.1 までの Oracle のいずれかのバージョンを使用している場合、 _renamedg_command の実行時にリストア処理がハング状態になります。この問題を修正するには、Oracleパッチ19544733を適用します。

次のリストア処理とリカバリ処理はサポートされていません。

* ルートコンテナデータベース（CDB）の表領域のリストアとリカバリ
* PDBに関連付けられた一時表領域および一時表領域のリストア
* 複数のPDBから同時に表領域をリストアおよびリカバリ
* ログバックアップのリストア
* 別の場所へのバックアップのリストア
* Data GuardスタンバイデータベースまたはActive Data Guardスタンバイデータベース以外の構成でのREDOログファイルのリストア
* SPFILEおよびパスワードファイルの復元
* 同じホスト上に既存のデータベース名を使用して再作成され、SnapCenterで管理されていて、有効なバックアップがあるデータベースに対してリストア処理を実行すると、DBIDが異なる場合でも、新しく作成されたデータベースファイルが上書きされます。
+
これを回避するには、次のいずれかの操作を実行します。

+
** データベースを再作成したら、 SnapCenter リソースを検出します
** 再作成したデータベースのバックアップを作成します






== 表領域のポイントインタイムリカバリに関する制限事項

* SYSTEM、SYSAUX、およびUNDO表領域のポイントインタイムリカバリ（PITR）はサポートされない
* 表領域のPITRを他のタイプのリストアと一緒に実行することはできない
* テーブルスペースの名前を変更し、名前を変更する前の状態に戻す場合は、テーブルスペースの以前の名前を指定する必要があります。
* ある表領域のテーブルの制約が別の表領域に含まれている場合は、両方の表領域をリカバリする必要があります。
* テーブルとそのインデックスが異なるテーブルスペースに格納されている場合は、PITRを実行する前にインデックスを削除する必要があります。
* PITRを使用して現在のデフォルト表領域をリカバリすることはできません
* PITRを使用して、次のいずれかのオブジェクトを含む表領域をリカバリすることはできません。
+
** 基になるオブジェクト（実体化ビュー (Materialized View) など）または含まれるオブジェクト（パーティション化されたテーブルなど）を含むオブジェクトは ' 基になるオブジェクトまたは含まれるオブジェクトがすべてリカバリ・セットに含まれている場合を除きます
+
また、パーティション化されたテーブルのパーティションが異なるテーブルスペースに格納されている場合は、PITRを実行する前にテーブルを削除するか、PITRを実行する前にすべてのパーティションを同じテーブルスペースに移動する必要があります。

** セグメントを元に戻すかロールバックします
** Oracle 8 では、複数の受信者と互換性のある拡張キューを使用でき
** SYS ユーザが所有するオブジェクト
+
これらのタイプのオブジェクトの例としては、PL/SQL、Javaクラス、呼び出しプログラム、ビュー、同義語、 ユーザー'特権'ディメンション'ディレクトリ'シーケンス







== Oracleデータベースをリストアするソースとデスティネーション

プライマリストレージまたはセカンダリストレージのバックアップコピーからOracleデータベースをリストアできます。データベースは、同じデータベースインスタンスの同じ場所にのみリストアできます。ただし、Real Application Cluster（RAC）セットアップでは、データベースを他のノードにリストアできます。



=== リストア処理のソース

プライマリストレージまたはセカンダリストレージ上のバックアップからデータベースをリストアできます。複数ミラー構成のセカンダリストレージ上のバックアップからリストアする場合は、セカンダリストレージミラーをソースとして選択できます。



=== リストア処理のデスティネーション

データベースは、同じデータベースインスタンスの同じ場所にのみリストアできます。

RACセットアップでは、クラスタ内の任意のノードからRACデータベースをリストアできます。
