---
permalink: protect-sco/task_set_up_credentials_for_installing_the_plug_in_package_for_linux_or_aix.html 
sidebar: sidebar 
keywords: credentials, authenticate, domain administrator, local administrator, workgroup, sudo, non-root user, root user 
summary: SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますLinux または AIX ホストにプラグインパッケージをインストールするためのクレデンシャルを作成する必要があります。 
---
= Plug-in Package for Linux または AIX をインストールするためのクレデンシャルを設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますLinux または AIX ホストにプラグインパッケージをインストールするためのクレデンシャルを作成する必要があります。

* このタスクについて *

このクレデンシャルは、 root ユーザに対して作成されるほか、プラグインプロセスをインストールして開始する sudo 権限がある root 以外のユーザに対しても作成されます。

詳細については、を参照してください link:../protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html#configuring-sudo-privileges-for-non-root-users-for-linux-plug-in-host["Linux ホストに sudo 権限を設定する"^] または 。

|===


| * ベストプラクティス： * ホストを導入してプラグインをインストールしたあとでクレデンシャルを作成することは可能ですが、 SVM を追加したあとで、ホストを導入してプラグインをインストールする前にクレデンシャルを作成することを推奨します。 
|===
* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [Credential] ページで、クレデンシャル情報を入力します。
+
|===
| フィールド | 手順 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名 / パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者
+
SnapCenter プラグインをインストールするシステムのドメイン管理者を指定します。Username フィールドの有効な形式は次のとおりです。

+
*** NETBIOS_USERNAME_
*** _ ドメイン FQDN\ ユーザ名 _


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、 SnapCenter プラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザアカウントに昇格された権限がある場合、またはホストシステムでユーザアクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカルユーザアカウントを指定できます。Username フィールドの有効な形式は、 _username_ です





 a| 
認証モード
 a| 
使用する認証モードを選択します。

プラグインホストのオペレーティングシステムに応じて、 Linux または AIX のいずれかを選択します。



 a| 
sudo 権限を使用する
 a| 
root 以外のユーザのクレデンシャルを作成する場合は、「 * sudo 権限を使用する * 」チェックボックスをオンにします。

|===
. [OK] をクリックします。


クレデンシャルの設定が完了したら、「 * User and Access * 」ページで、ユーザまたはユーザグループにクレデンシャルのメンテナンスを割り当てることができます。
