---
permalink: protect-sce/reference_exchange_server_cluster_node_privileges_required.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter で Exchange サーバまたは DAG を追加し、ホストまたは DAG に SnapCenter Plug-in for Microsoft Exchange Server をインストールできるようにするには、最小限の権限と権限を持つユーザのクレデンシャルを SnapCenter に設定する必要があります。 
---
= Exchange Server の権限が必要です
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter で Exchange サーバまたは DAG を追加し、ホストまたは DAG に SnapCenter Plug-in for Microsoft Exchange Server をインストールできるようにするには、最小限の権限と権限を持つユーザのクレデンシャルを SnapCenter に設定する必要があります。

ローカル管理者の権限を持つドメインユーザと、リモート Exchange ホストに対するローカルログイン権限、および DAG 内のすべてのノードに対する管理権限を持つドメインユーザが必要です。ドメインユーザには、次の最小権限が必要です。

* Add-MailboxDatabaseCopy を追加します
* dismount - データベース
* Get-AdServerSettings
* Get-DatabaseAvailabilityGroup 」を参照してください
* Get-ExchangeServer
* MailboxDatabase を取得します
* Get-MailboxDatabaseCopyStatus
* Get-MailboxServer
* Get-MailboxStatistics を実行します
* Get-PublicFolderDatabase を参照してください
* MOVE - ActiveMailboxDatabase
* move-DatabasePath-ConfigurationOnly:$true
* mount - データベース
* New-MailboxDatabase
* 新規 - PublicFolderDatabase
* MailboxDatabase を削除します
* MailboxDatabaseCopy を削除します
* -PublicFolderDatabase を削除します
* 履歴書 -MailboxDatabaseCopy
* 「設定」 - 「サーバ設定
* MailboxDatabase-allowfilerestore を $true に設定します
* MailboxDatabaseCopy を設定します
* 「 - PublicFolderDatabase 」を設定します
* Suspend-MailboxDatabaseCopy を実行します
* Update-MailboxDatabaseCopy

