---
permalink: protect-sce/reference_storage_types_supported_by_snapcenter_plug_in_for_microsoft_windows_and_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter は、物理マシンと仮想マシンの両方でさまざまなストレージタイプをサポートしています。ホストに対応したパッケージをインストールする前に、ストレージタイプがサポートされているかどうかを確認する必要があります。 
---
= SnapCenter Plug-in for Microsoft Windows および Microsoft Exchange Server でサポートされるストレージタイプ
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、物理マシンと仮想マシンの両方でさまざまなストレージタイプをサポートしています。ホストに対応したパッケージをインストールする前に、ストレージタイプがサポートされているかどうかを確認する必要があります。

Windows Server では、 SnapCenter プロビジョニングとデータ保護がサポートされます。サポートされているバージョンの最新情報については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。

|===
| マシン | ストレージタイプ | を使用してプロビジョニング | サポートのメモ 


 a| 
物理サーバ
 a| 
FC 接続 LUN
 a| 
SnapCenter のグラフィカルユーザインターフェイス（ GUI ）または PowerShell コマンドレット
 a| 



 a| 
物理サーバ
 a| 
iSCSI で接続された LUN
 a| 
SnapCenter GUI または PowerShell コマンドレット
 a| 



 a| 
VMware VM
 a| 
FC または iSCSI HBA で接続された RDM LUN
 a| 
PowerShell コマンドレット
 a| 
物理的な互換性のみ


NOTE: VMDK はサポートされません。



 a| 
VMware VM
 a| 
iSCSI イニシエータによってゲストシステムに直接接続された iSCSI LUN
 a| 
SnapCenter GUI または PowerShell コマンドレット
 a| 

NOTE: VMDK はサポートされません。



 a| 
Hyper-V VM
 a| 
仮想ファイバチャネルスイッチで接続された仮想 FC （ vFC ） LUN
 a| 
SnapCenter GUI または PowerShell コマンドレット
 a| 
仮想ファイバチャネルスイッチで接続された仮想 FC （ vFC ） LUN のプロビジョニングには、 Hyper-V Manager を使用する必要があります。


NOTE: Hyper-V のパススルーディスク、およびネットアップストレージでプロビジョニングされた VHD （ x ）でのデータベースのバックアップはサポートされていません。



 a| 
Hyper-V VM
 a| 
iSCSI イニシエータによってゲストシステムに直接接続された iSCSI LUN
 a| 
SnapCenter GUI または PowerShell コマンドレット
 a| 

NOTE: Hyper-V のパススルーディスク、およびネットアップストレージでプロビジョニングされた VHD （ x ）でのデータベースのバックアップはサポートされていません。

|===