---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords:  
summary: ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。 
---
= ホストを追加して SnapCenter Plug-in for Microsoft Exchange Server をインストールするための前提条件
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。

* iSCSI を使用している場合は、 iSCSI サービスが実行されている必要があります。
* ローカル管理者権限を持つドメインユーザがあり、リモートホストに対してローカルログイン権限が付与されている必要があります。
* スタンドアロン構成およびデータベース可用性グループ構成で Microsoft Exchange Server 2013 、 2016 、または 2019 を使用している必要があります。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* SnapCenter でクラスタノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限を持つユーザが必要です。
* Exchange Server に対する管理者権限を持つユーザが必要です。
* SnapManager for Microsoft Exchange Server および SnapDrive for Windows がすでにインストールされている場合は、 SnapDrive を使用してデータを確実に保護するために、同じ Exchange サーバに Plug-in for Exchange をインストールする前に、 SnapCenter for Windows で使用する VSS ハードウェアプロバイダの登録を解除する必要があります。
* SnapManager for Microsoft Exchange Server と Plug-in for Exchange が同じサーバにインストールされている場合は、 SnapManager for Microsoft Exchange Server で作成されたすべてのスケジュールを Windows スケジューラから一時停止または削除する必要があります。
* ホストがサーバから完全修飾ドメイン名（ FQDN ）に解決できる必要があります。hosts ファイルが解決可能になるように変更され、短縮名と FQDN の両方が hosts ファイルに指定されている場合は、 SnapCenter hosts ファイルに次の形式でエントリを作成します： _<IP_address> <host_fqdn><host_name> _ 。
* 次のポートがファイアウォールでブロックされていないことを確認してください。ブロックされていないとホストの追加操作が失敗します。この問題を解決するには、ダイナミックポート範囲を設定する必要があります。詳細については、を参照してください https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-rpc-dynamic-port-allocation-with-firewalls["Microsoft のドキュメント"^]。
+
** Windows 2016 および Exchange 2016 のポート範囲 50000 ~ 51000
** Windows Server 2012 R2 および Exchange 2013 用のポート範囲 6000-6500
** Windows 2019 のポート範囲は 49152~65536 です




[NOTE]
====
ポート範囲を特定するには、次のコマンドを実行します。

* netsh int ipv4 show dynamicport tcp
* netsh int ipv4 show dynamicport udp
* netsh int ipv6 show dynamicport tcp を実行します
* netsh int ipv6 show dynamicport udp


====


== SnapCenter Plug-ins Package for Windows をインストールするホストの要件

SnapCenter Plug-ins Package for Windows をインストールする前に、ホストシステムのいくつかの基本的なスペース要件とサイジング要件を確認しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows の場合

サポートされているバージョンの最新情報については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
ホスト上の SnapCenter プラグインの最小 RAM
 a| 
1 GB



 a| 
ホスト上の SnapCenter プラグインのインストールおよびログの最小スペース
 a| 
5 GB


NOTE: 十分なディスクスペースを割り当て、 logs フォルダによるストレージ消費を監視する必要があります。必要なログスペースは、保護するエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理に対してログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
* Microsoft .NET Framework 4.5.2 以降
* Windows Management Framework （ WMF ） 4.0 以降
* PowerShell 4.0 以降


サポートされているバージョンの最新情報については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。

|===


== Exchange Server の権限が必要です

SnapCenter で Exchange サーバまたは DAG を追加し、ホストまたは DAG に SnapCenter Plug-in for Microsoft Exchange Server をインストールできるようにするには、最小限の権限と権限を持つユーザのクレデンシャルを SnapCenter に設定する必要があります。

ローカル管理者の権限を持つドメインユーザと、リモート Exchange ホストに対するローカルログイン権限、および DAG 内のすべてのノードに対する管理権限を持つドメインユーザが必要です。ドメインユーザには、次の最小権限が必要です。

* Add-MailboxDatabaseCopy を追加します
* dismount - データベース
* Get-AdServerSettings
* Get-DatabaseAvailabilityGroup 」を参照してください
* Get-ExchangeServer
* MailboxDatabase を取得します
* Get-MailboxDatabaseCopyStatus
* Get-MailboxServer
* Get-MailboxStatistics を実行します
* Get-PublicFolderDatabase を参照してください
* MOVE - ActiveMailboxDatabase
* move-DatabasePath-ConfigurationOnly:$true
* mount - データベース
* New-MailboxDatabase
* 新規 - PublicFolderDatabase
* MailboxDatabase を削除します
* MailboxDatabaseCopy を削除します
* -PublicFolderDatabase を削除します
* 履歴書 -MailboxDatabaseCopy
* 「設定」 - 「サーバ設定
* MailboxDatabase-allowfilerestore を $true に設定します
* MailboxDatabaseCopy を設定します
* 「 - PublicFolderDatabase 」を設定します
* Suspend-MailboxDatabaseCopy を実行します
* Update-MailboxDatabaseCopy




== Windows Server 2012 以降で gMSA を構成します

SnapCenter Plug-ins Package for Windows をインストールする前に、ホストシステムのいくつかの基本的なスペース要件とサイジング要件を確認しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows の場合

サポートされているバージョンの最新情報については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
ホスト上の SnapCenter プラグインの最小 RAM
 a| 
1 GB



 a| 
ホスト上の SnapCenter プラグインのインストールおよびログの最小スペース
 a| 
5 GB


NOTE: 十分なディスクスペースを割り当て、 logs フォルダによるストレージ消費を監視する必要があります。必要なログスペースは、保護するエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理に対してログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
* Microsoft .NET Framework 4.5.2 以降
* Windows Management Framework （ WMF ） 4.0 以降
* PowerShell 4.0 以降


サポートされているバージョンの最新情報については、を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。

|===