---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますプラグインパッケージのインストールに使用するクレデンシャルと、データベースでデータ保護処理を実行するためのクレデンシャルをそれぞれ作成する必要があります。 
---
= SnapCenter Plug-in for Windowsのクレデンシャルを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますプラグインパッケージのインストールに使用するクレデンシャルと、データベースでデータ保護処理を実行するためのクレデンシャルをそれぞれ作成する必要があります。

.タスクの内容
Windowsホストにプラグインをインストールするには、クレデンシャルを設定する必要があります。Windowsのクレデンシャルは、ホストを導入してプラグインをインストールしたあとに作成することもできますが、SVMを追加したあと、ホストの導入とプラグインのインストールを開始する前に作成することを推奨します。

このクレデンシャルには、管理者権限（リモートホストに対する管理者権限を含む）を設定します。

個 々 のリソースグループのクレデンシャルを設定し、ユーザ名に完全なadmin権限がない場合は、少なくともリソースグループとバックアップの権限を割り当てる必要があります。

.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
+
[クレデンシャル]ウィンドウが表示されます。

. [Credential]ページで、次の手順を実行します。
+
|===
| フィールド | 操作 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名
 a| 
認証に使用するユーザ名を入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者またはSnapCenterプラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。ユーザ名フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。[Username]フィールドの有効な形式は次のとおりです。 `UserName`





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。



 a| 
認証
 a| 
認証モードとして[Windows]を選択します。

|===
. [OK]*をクリックします。

