---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Exchange Serverのリストア戦略を定義しておくと、データベースを正常にリストアできます。 
---
= Exchangeデータベースのリストア戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange Serverのリストア戦略を定義しておくと、データベースを正常にリストアできます。



== Exchange Serverでのリストア処理のソース

プライマリストレージ上のバックアップコピーからExchange Serverデータベースをリストアできます。

データベースはプライマリストレージからのみリストアできます。



== Exchange Serverでサポートされるリストア処理のタイプ

SnapCenterを使用すると、Exchangeリソースに対してさまざまなタイプのリストア処理を実行できます。

* 最新の状態へのリストア
* 過去のポイントインタイムへのリストア




=== 最新の状態へのリストア

最新の状態へのリストア処理では、障害発生時点までデータベースがリカバリされます。SnapCenterでは、この処理が次の順序で実行されます。

. 選択したフルデータベースバックアップからデータベースをリストアします。
. バックアップされたすべてのトランザクション・ログ、および最新のバックアップ以降に作成された新しいログが適用されます。
+
トランザクションログは先に移動され、選択したデータベースに適用されます。

+
リストアの完了後、Exchangeは新しいログチェーンを作成します。

+
|===


| * ベストプラクティス： * リストアの完了後に、新しいフルバックアップとログバックアップを実行することを推奨します。 
|===
+
最新の状態へのリストア処理では、連続するトランザクションログセットが必要です。

+
最新の状態へのリストアの実行後は、リストアに使用したバックアップをポイントインタイムリストア処理でのみ使用できます。

+
すべてのバックアップに対して最新の状態へのリストア機能を実行する必要がない場合は、バックアップポリシーを使用してシステムのトランザクションログバックアップの保持を設定できます。





=== 過去のポイントインタイムへのリストア

ポイントインタイムリストア処理では、データベースは過去の特定の時刻にのみリストアされます。ポイントインタイムリストア処理は、次の状況で実行されます。

* データベースは、バックアップトランザクションログの所定の時間にリストアされます。
* データベースがリストアされ、一部のバックアップトランザクションログのみが適用されます。

