---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords:  
summary: Exchange Server のリストア戦略を定義しておくと、それに従ってデータベースをリストアすることができます。 
---
= Exchange データベースのリストア戦略を定義する
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange Server のリストア戦略を定義しておくと、それに従ってデータベースをリストアすることができます。



== Exchange Server でのリストア処理のソースとなります

プライマリストレージ上のバックアップコピーから Exchange Server データベースをリストアすることができます。

データベースはプライマリストレージからのみリストアできます。



== Exchange Server でサポートされるリストア処理のタイプ

SnapCenter を使用すると、 Exchange リソースに対してさまざまなタイプのリストア処理を実行できます。

* 最新の状態にリストアします
* 前の時点にリストアします




=== 最新の状態にリストアします

最新の状態へのリストア処理では、障害発生時点までのデータベースのリカバリが行われます。SnapCenter では、この処理が次の順序で行われます。

. 選択したフルデータベースバックアップからデータベースがリストアされます。
. バックアップされたすべてのトランザクション・ログ、および最新のバックアップ以降に作成された新しいログを適用します。
+
トランザクションログは事前に移動され、選択したデータベースに適用されます。

+
リストアの完了後に、 Exchange は新しいログチェーンを作成します。

+
|===


| * ベストプラクティス： * リストアの完了後に、新しいフルバックアップとログバックアップを実行することを推奨します。 
|===
+
最新の状態へのリストア処理を実行するには、連続したトランザクションログセットが必要です。

+
最新の状態へのリストアを実行すると、リストアに使用したバックアップを使用できるのはポイントインタイムリストア処理だけになります。

+
すべてのバックアップに最新の状態へのリストア機能を使用する必要がない場合は、バックアップポリシーを使用してシステムのトランザクションログバックアップ保持を設定できます。





=== 前の時点にリストアします

ポイントインタイムリストア処理では、データベースが過去の特定の時点にリストアされます。ポイントインタイムリストア処理は次の状況で発生します。

* バックアップトランザクションログの所定の時刻までデータベースをリストアする。
* データベースをリストアし、一部のバックアップトランザクションログだけを適用する。

