---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter を使用して Microsoft Exchange Server リソースをバックアップする前に、 Exchange リソースまたはリソースグループのバックアップポリシーを作成することができます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。 
---
= Exchange Server データベースのバックアップポリシーを作成する
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して Microsoft Exchange Server リソースをバックアップする前に、 Exchange リソースまたはリソースグループのバックアップポリシーを作成することができます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。

* 必要なもの *

* データ保護戦略を定義しておく必要があります。
+
詳細については、 Exchange データベースのデータ保護戦略の定義に関する情報を参照してください。

* SnapCenter のインストール、ホストの追加、リソースの特定、ストレージシステム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* Exchange Server リソースを更新（検出）しておく必要があります。
* Snapshot コピーをミラーまたはバックアップにレプリケートするユーザには、 SnapCenter 管理者がユーザに対してソースとデスティネーションの両方のボリューム用に Storage Virtual Machine （ SVM ）を割り当てる必要があります。
* プリスクリプトとポストスクリプトで PowerShell スクリプトを実行する場合は、「 web.config 」ファイルで「 usePowershellProcessforScripts 」パラメータの値を true に設定する必要があります。
+
デフォルト値は false です。



* このタスクについて *

バックアップポリシーとは、バックアップを管理および保持する方法やリソースやリソースグループをバックアップする頻度を定めた一連のルールです。また、スクリプト設定を指定することもできます。ポリシーでオプションを指定しておくことで、別のリソースグループにポリシーを再利用して時間を節約することができます。

フルバックアップの保持は指定されたポリシーに固有です。フルバックアップ保持が 4 に設定されたポリシー A を使用するデータベースまたはリソースはフルバックアップを 4 つ保持し、同じデータベースまたはリソースのポリシー B には影響しません。これにより、フルバックアップを 3 つ保持するように 3 つ保持できます。

ログバックアップの保持は、ポリシーを問わず有効であり、データベースやリソースのすべてのログバックアップを環境で保持できます。したがって、ポリシー B を使用してフルバックアップを実行すると、同じデータベースまたはリソース上のポリシー A で作成されるログバックアップにログ保持設定が適用されます。同様に、ポリシー A のログ保持設定は、同じデータベースのポリシー B で作成されるログバックアップに影響します。

|===


| * ベストプラクティス： * 維持するフルバックアップとログバックアップの総数に基づいて、セカンダリ保持ポリシーを設定することを推奨します。セカンダリの保持ポリシーを設定する場合、異なるボリュームにあるデータベースとログの Snapshot コピーは、各バックアップに 3 つ作成できます。また、データベースとログが同じボリュームにある場合、各バックアップに 2 つの Snapshot コピーを保持できます。 
|===
* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [ 名前 ] ページで、ポリシー名と概要を入力します。
. [Backup Type] ページで、次の手順を実行します。
+
.. バックアップタイプを選択します。
+
|===
| 状況 | 手順 


 a| 
データベースファイルと必要なトランザクションログをバックアップします
 a| 
[ フルバックアップおよびログバックアップ * ] を選択します。

データベースはログを切り捨ててバックアップされ、切り捨てられたログを含むすべてのログがバックアップされます。


NOTE: これは推奨されるバックアップタイプです。



 a| 
データベースファイルおよびコミットされていないトランザクションログをバックアップします
 a| 
[* Full backup* ] を選択します。

ログを切り捨ててデータベースをバックアップし、切り捨てられたログはバックアップされません。



 a| 
すべてのトランザクションログをバックアップします
 a| 
「 * Log backup * 」を選択します。

アクティブファイルシステムのすべてのトランザクションログがバックアップされており、ログが切り捨てられていません。

ライブログと同じディスクに _scebackupinfo_directory が作成されます。このディレクトリには、 Exchange データベースの増分変更へのポインタが格納されます。このディレクトリは、完全なログファイルには相当しません。



 a| 
トランザクションログファイルを切り捨てずに、すべてのデータベースファイルとトランザクションログをバックアップします
 a| 
Copy Backup （バックアップのコピー） * を選択します。

すべてのデータベースとすべてのログがバックアップされ、ログが切り捨てられることはありません。通常、このバックアップタイプは、レプリカの再シード、または問題のテストや診断に使用します。

|===
+

NOTE: ログバックアップに必要なスペースは、最新の状態への（ UTM ）保持にではなく、フルバックアップ保持に基づいて定義する必要があります。

.. Database Availability Group Settings セクションで、次の操作を選択します。
+
|===
| フィールド | 手順 


 a| 
アクティブなコピーをバックアップする
 a| 
選択したデータベースのアクティブコピーのみをバックアップする場合は、このオプションを選択します。

Database Availability Group （ DAG ；データベース可用性グループ）の場合、このオプションは DAG 内のすべてのデータベースのアクティブコピーのみをバックアップします。

パッシブコピーはバックアップされません。



 a| 
バックアップジョブの作成時に選択されるサーバ上のバックアップコピー
 a| 
このオプションは、アクティブとパッシブの両方で、選択したサーバ上のデータベースのコピーをバックアップする場合に選択します。

DAG では、選択したサーバ上のすべてのデータベースのアクティブコピーとパッシブコピーの両方がバックアップされます。

|===
+

NOTE: クラスタ構成では、ポリシーで設定された保持設定に従って、クラスタの各ノードにバックアップが保持されます。クラスタの所有者ノードが変更された場合、以前の所有者ノードのバックアップは保持されます。保持設定はノードレベルでのみ適用できます。

.. [ スケジュール頻度 ] セクションで、 1 つ以上の頻度タイプを選択します。 * オンデマンド * 、 * 毎時 * 、 * 毎日 * 、 * 毎週 * 、および * 毎月 * 。
+

NOTE: リソースグループを作成する際に、バックアップ処理のスケジュール（開始日、終了日）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソースグループを作成できますが、各ポリシーに異なるバックアップスケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間（ DST ）中はスケジュールはトリガーされません。



. [ 保持 ] ページで ' 保持設定を構成します
+
表示されるオプションは、以前に選択したバックアップのタイプと頻度のタイプによって異なります。

+

NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持期間を基盤となる ONTAP バージョンの値よりも大きい値に設定すると、バックアップが失敗します。

+

IMPORTANT: SnapVault レプリケーションを有効にする場合は、保持数を 2 以上に設定する必要があります。保持数を 1 に設定すると、新しい Snapshot コピーがターゲットにレプリケートされるまで最初の Snapshot コピーが SnapVault 関係の参照 Snapshot コピーになるため、保持処理が失敗することがあります。

+
.. [Log backups retention settings] セクションで、次のいずれかを選択します。
+
|===
| 状況 | 手順 


 a| 
特定の数のログバックアップだけを保持します
 a| 
ログを保持するフルバックアップの数を * 選択し、最新の状態へのリストアを実行するフルバックアップの数を指定します。

UTM （最新状態）保持の環境ログバックアップは、フルバックアップまたはログバックアップを使用して作成されます。たとえば、 UTM 保持設定が、最新の 5 つのフルバックアップのログバックアップを保持するように設定されている場合、最新の 5 つのフルバックアップのログバックアップが保持されます。

フルバックアップとログバックアップの一部として作成されたログフォルダは、 UTM の一部として自動的に削除されます。ログフォルダは手動で削除できません。たとえば、フルバックアップまたはフルバックアップの保持設定が 1 カ月に設定されていて、 UTM 保持が 10 日に設定されている場合、これらのバックアップの一部として作成されたログフォルダは UTM のように削除されます。そのため、ログフォルダは 10 日しか作成されず、それ以外のバックアップはすべてポイントインタイムリストアの対象としてマークされます。

最新の状態へのリストアを実行しない場合は、 UTM 保持値を 0 に設定できます。これにより、ポイントインタイムリストア処理が有効になります。

* ベストプラクティス： * フルバックアップ保持の設定セクションの「 Total Snapshot copies （フルバックアップ）」の設定と同じにすることを推奨します。これにより、フルバックアップのたびにログファイルが保持されます。



 a| 
バックアップコピーを特定の日数だけ保持します
 a| 
「 * Keep log backups for last * 」オプションを選択し、ログバックアップコピーを保持する日数を指定します。

フルバックアップを保持する日数までのログバックアップが作成されます。

|===
+
バックアップタイプとして * Log backup * を選択した場合は、フルバックアップの最新の状態へのリストア保持設定の一部としてログバックアップが保持されます。

.. [ フル・バックアップ保持設定 ] セクションで、オンデマンド・バックアップ用に次のいずれかを選択し、フル・バックアップ用に 1 つ選択します。
+
|===
| フィールド | 手順 


 a| 
特定の数の Snapshot コピーだけを保持します
 a| 
保持するフルバックアップの数を指定する場合は、「保持する Snapshot コピーの総数」オプションを選択し、保持する Snapshot コピー（フルバックアップ）の数を指定します。

フルバックアップの数が指定した数を超えると、指定した数を超えるフルバックアップが削除され、古いコピーから順番に削除されます。



 a| 
フルバックアップを特定の日数だけ保持します
 a| 
「 * Snapshot コピーを保持する期間」オプションを選択し、 Snapshot コピーを保持する日数（フルバックアップ）を指定します。

|===
+

NOTE: DAG 構成のホストにはログバックアップのみを使用し、フルバックアップは実行しないデータベースがある場合、ログバックアップは次の方法で保持されます。

+
*** デフォルトでは、 SnapCenter は DAG 内の他のすべてのホストでこのデータベースの最も古いフルバックアップを検出し、フルバックアップの前に作成されたこのホスト上のすべてのログバックアップを削除します。
*** ログバックアップのみを使用する DAG 内のホストのデフォルトの保持設定を上書きするには、 _C ： \Program Files\NetApp\SnapManager WebApp\web.config_file にキー * MaxLogBackupOnlyCountWithoutFullBackup * を追加します。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
この例では、 10 という値は、ホストに最大 10 個のログバックアップを保持することを意味します。





. レプリケーションページで、次のセカンダリレプリケーションオプションのいずれか、または両方を選択します。
+
|===
| フィールド | 手順 


 a| 
ローカル Snapshot コピーの作成後に SnapMirror を更新します
 a| 
別のボリュームにバックアップセットのミラーコピーを保持する場合（ SnapMirror ）は、このオプションを選択します。



 a| 
ローカル Snapshot コピーの作成後に SnapVault を更新します
 a| 
ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。



 a| 
セカンダリポリシーのラベル
 a| 
Snapshot ラベルを選択します。

選択した Snapshot コピーラベルに応じて、 ONTAP はラベルに一致するセカンダリ Snapshot コピー保持ポリシーを適用します。


NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



 a| 
エラー再試行回数
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリストレージでの Snapshot コピーの最大数に達しないように、 ONTAP でセカンダリストレージの SnapMirror 保持ポリシーを設定する必要があります。

. スクリプトページで、バックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
** プリスクリプトのバックアップ引数には、「 $Database 」および「 $ServerInstance 」が含まれます。
** PostScript バックアップ引数には、「 $Database 」、「 $ServerInstance 」、「 $BackupName 」、「 $LogDirectory 」、「 $LogSnapshot 」が含まれます。
+
SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。



. 概要を確認し、 [ 完了 ] をクリックします。

