---
permalink: protect-sce/task_configure_snapmanager_7_x_for_exchange_and_snapcenter_plug_in_for_exchange_to_coexist.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter Plug-in for Microsoft Exchange ServerをSnapManager for Microsoft Exchange Serverと共存させるには、SnapManager for Microsoft Exchange ServerがインストールされているExchange ServerにSnapCenter Plug-in for Microsoft Exchange Serverをインストールし、SnapManager for Exchangeのスケジュールを無効にして、SnapCenter Plug-in for Microsoft Exchange Serverを使用して新しいスケジュールとバックアップを設定する必要があります。 
---
= ExchangeとSnapCenterが共存するようにSnapManager 7.xを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft Exchange ServerをSnapManager for Microsoft Exchange Serverと共存させるには、SnapManager for Microsoft Exchange ServerがインストールされているExchange ServerにSnapCenter Plug-in for Microsoft Exchange Serverをインストールし、SnapManager for Exchangeのスケジュールを無効にして、SnapCenter Plug-in for Microsoft Exchange Serverを使用して新しいスケジュールとバックアップを設定する必要があります。

.開始する前に
* SnapManager for Microsoft Exchange ServerおよびSnapDrive for Windowsがすでにインストールされており、SnapManager for Microsoft Exchange Serverのバックアップがシステム上およびSnapInfoディレクトリに存在します。
* 不要になったSnapManager for Microsoft Exchange Serverで作成したバックアップを削除または再利用しておく必要があります。
* SnapManager for Microsoft Exchange Serverで作成したすべてのスケジュールをWindowsスケジューラで一時停止または削除しておく必要があります。
* SnapCenter Plug-in for Microsoft Exchange ServerとSnapManager for Microsoft Exchange Serverは同じExchange Serverに共存できますが、既存のSnapManager for Microsoft Exchange Server環境をSnapCenterにアップグレードすることはできません。
+
SnapCenterにはアップグレードオプションがありません。

* SnapCenterでは、SnapManager for Microsoft Exchange ServerバックアップからのExchangeデータベースのリストアはサポートされていません。
+
SnapCenter Plug-in for Microsoft Exchange Serverのインストール後にSnapManager for Microsoft Exchange Serverをアンインストールせずに、あとでSnapManager for Microsoft Exchange Serverのバックアップをリストアする場合は、追加の手順を実行する必要があります。



.手順
. すべての DAG ノードで PowerShell を使用して、 SnapDrive for Windows VSS ハードウェアプロバイダが登録されているかどうかを確認します。 _vssadmin list provider_
+
[listing]
----
C:\Program Files\NetApp\SnapDrive>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {ddd3d232-a96f-4ac5-8f7b-250fd91fd102}
   Version: 7. 1. 4. 6845
----
. SnapDrive ディレクトリから、 SnapDrive for Windows から VSS ハードウェアプロバイダの登録を解除します。 _navssprv.exe -r service – u_
. VSS ハードウェアプロバイダが削除されたことを確認します。 _vssadmin list providers_
. SnapCenter に Exchange ホストを追加し、 SnapCenter Plug-in for Microsoft Windows および SnapCenter Plug-in for Microsoft Exchange Server をインストールします。
. すべての DAG ノードの SnapCenter Plug-in for Microsoft Windows ディレクトリで、 VSS ハードウェアプロバイダが登録されていることを確認します： _vssadmin list providers_
+
[listing]
----
[PS] C:\Windows\system32>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {31fca584-72be-45b6-9419-53a3277301d1}
   Version: 7. 0. 0. 5561
----
. SnapManager for Microsoft Exchange Server のバックアップスケジュールを停止します。
. SnapCenter GUI を使用して、オンデマンドバックアップの作成、スケジュールされたバックアップの設定、保持の設定を行います。
. SnapManager for Microsoft Exchange Server をアンインストールします。
+
SnapManager for Microsoft Exchange Server を今すぐアンインストールしないで、 SnapManager for Microsoft Exchange Server のバックアップをリストアする場合は、次の手順を実行します。

+
.. すべての DAG ノードから SnapCenter Plug-in for Microsoft Exchange Server の登録を解除します。 _navssprv.exe -r service -u _
+
[listing]
----
C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows>navssprv.exe -r service -u
----
.. C ： \Program Files\NetApp\SnapManager \SnapDrive\_directory から、すべての DAG ノードに SnapDrive for Windows を登録します。 _navssprv.exe -r service -c hostname \\username -p password_



