---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: コピーが破損している場合などにレプリカコピーを再シードする必要がある場合は、SnapCenterの再シード機能を使用して最新のバックアップに再シードできます。 
---
= Exchangeのパッシブノードレプリカの再シード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コピーが破損している場合などにレプリカコピーを再シードする必要がある場合は、SnapCenterの再シード機能を使用して最新のバックアップに再シードできます。

.開始する前に
* SnapCenterサーバ4.1以降およびPlug-in for Exchange 4.1以降を使用している必要があります。
+
レプリカの再シードは、バージョン4.1より前のSnapCenterではサポートされていません。

* 再シードするデータベースのバックアップを作成しておく必要があります。


|===


| * ベストプラクティス：ノード間の遅延を回避するために、再シード処理を実行する前に新しいバックアップを作成するか、最新のバックアップを実行しているホストを選択することを推奨します。 
|===
.手順
. 左側のナビゲーションペインで、 [* リソース ] をクリックし、リストから [Microsoft Exchange Server プラグイン *] を選択します。
. [Resources]ページで、[View]リストから適切なオプションを選択します。
+
|===
| オプション | 説明 


 a| 
単一のデータベースを再シードするには
 a| 
[ 表示 ] リストから [*Database] を選択します。



 a| 
DAG内のデータベースを再シードするには
 a| 
ビューリストから * データベース可用性グループ * を選択します。

|===
. 再シードするリソースを選択します。
. Manage Copies （コピーの管理）ページで、 * Reseed-* をクリックします。
. 再シードウィザードで問題のあるデータベースコピーのリストから、再シードするデータベースコピーを選択し、 * Next * をクリックします。
. Host ウィンドウで、再シードするバックアップを含むホストを選択し、 * Next * をクリックします。
. [ 通知 ] ページの [ 電子メールの設定 *] ドロップダウンリストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者のEメールアドレス、およびEメールの件名を指定する必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。
. ページ下部の[Activity]パネルを展開すると、ジョブのステータスを表示できます。
+

NOTE: データベースのパッシブコピーがネットアップ以外のストレージにある場合、再シード処理はサポートされません。


