---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: レプリカコピーを再シードする必要がある場合、たとえばコピーが破損した場合は、 SnapCenter の再シード機能を使用して最新のバックアップに再シードできます。 
---
= Exchange のパッシブノードレプリカを再シードします
:icons: font
:imagesdir: ../media/


[role="lead"]
レプリカコピーを再シードする必要がある場合、たとえばコピーが破損した場合は、 SnapCenter の再シード機能を使用して最新のバックアップに再シードできます。

* SnapCenter サーバ 4.1 以降および Plug-in for Exchange 4.1 以降を使用している必要があります。
+
レプリカの再シードは、 4.1 より前のバージョンの SnapCenter ではサポートされていません。

* 再シードするデータベースのバックアップを作成しておく必要があります。


|===


| * ベストプラクティス：ノード間の遅延を回避するために、再シード処理を実行する前に新しいバックアップを作成するか、最新のバックアップを実行しているホストを選択することを推奨します。 
|===
* 手順 *

. 左側のナビゲーションペインで、 [* リソース ] をクリックし、リストから [Microsoft Exchange Server プラグイン *] を選択します。
. [* リソース * （ * Resources * ） ] ページで、 [ 表示（ View ） ] リストから適切なオプションを選択する。
+
|===
| オプション | 説明 


 a| 
単一のデータベースを再シードする場合
 a| 
[ 表示 ] リストから [*Database] を選択します。



 a| 
DAG 内のデータベースを再シードする場合
 a| 
ビューリストから * データベース可用性グループ * を選択します。

|===
. 再シードするリソースを選択します。
. Manage Copies * ページで、 * Reseed-* をクリックします。
. 再シードウィザードで問題のあるデータベースコピーのリストから、再シードするデータベースコピーを選択し、 * Next * をクリックします。
. Host ウィンドウで、再シードするバックアップを含むホストを選択し、 * Next * をクリックします。
. [* スクリプト * ] ページで、再シード処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、 SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

. [*Notification] ページの [*Email preference*] ドロップダウンリストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者の E メールアドレス、および E メールの件名を指定する必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。
. ジョブのステータスを表示するには、ページの下部にある ［ アクティビティ ］ パネルを展開します。
+

NOTE: パッシブデータベースコピーがネットアップ以外のストレージにある場合は、再シード処理はサポートされません。


