---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords:  
summary: バックアップジョブを作成する前にバックアップ戦略を定義しておくと、データベースの正常なリストアに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA ）、目標復旧時間（ RTO ）、および目標復旧時点（ RPO ）によって決まります。 
---
= Exchange Server リソースのバックアップ戦略を定義する
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップジョブを作成する前にバックアップ戦略を定義しておくと、データベースの正常なリストアに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA ）、目標復旧時間（ RTO ）、および目標復旧時点（ RPO ）によって決まります。

SLA は、想定されるサービスのレベルを定義し、サービスの可用性やパフォーマンスなど、サービス関連の多くの問題に対処します。RTO は、サービスの停止からビジネスプロセスの復旧までに必要となる時間です。RPO は、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA 、 RTO 、および RPO は、バックアップ戦略に関与します。



== Exchange データベースでサポートされるバックアップのタイプ

SnapCenter を使用して Exchange メールボックスをバックアップするには、データベースやデータベース可用性グループ（ DAG ）などのリソースタイプを選択する必要があります。Snapshot コピーテクノロジを使用して、リソースが存在するボリュームのオンラインの読み取り専用コピーが作成されます。

|===
| バックアップタイプ | 説明 


 a| 
フルバックアップとログバックアップ
 a| 
データベースおよび切り捨てられたログを含むすべてのトランザクションログがバックアップされます。

フルバックアップが完了すると、 Exchange Server はデータベースにコミット済みのトランザクションログを切り捨てます。

通常は、このオプションを選択します。ただし、バックアップ時間が短い場合は、フルバックアップでトランザクションログバックアップを実行しないように選択することもできます。



 a| 
フルバックアップ
 a| 
データベースとトランザクションログがバックアップされます。

切り捨てられたトランザクションログはバックアップされません。



 a| 
ログバックアップ
 a| 
すべてのトランザクションログがバックアップされます。

データベースにコミット済みの切り捨てられたログはバックアップされません。フルデータベースバックアップ間にトランザクションログを頻繁にバックアップするようにスケジュールを設定すると、リカバリポイントをさらに細かく選択できます。

|===


== データベースプラグインのバックアップスケジュール

バックアップ頻度（スケジュールタイプ）はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは 1 時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは 1 日に 1 回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（ SLA ）、目標復旧時点（ RPO ）などがあります。

SLA は、想定されるサービスのレベルを定義し、サービスの可用性やパフォーマンスなど、サービス関連の多くの問題に対処します。RPO は、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA と RPO は、データ保護戦略に関与します。

使用頻度の高いリソースであっても、フルバックアップは 1 日に 1~2 回で十分です。たとえば、定期的なトランザクションログバックアップを実行すれば、必要なバックアップが作成されます。データベースをバックアップする回数が多いほど、リストア時に SnapCenter が使用する必要のあるトランザクションログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

バックアップスケジュールには、次の 2 つの要素があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインでは _ schedule type__ と呼ばれます。ポリシーでは、バックアップ頻度として、毎時、毎日、毎週、または毎月を選択できます。頻度を選択しない場合は、オンデマンドのみのポリシーが作成されます。ポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行される日時）は、リソースグループの設定の一部です。たとえば、リソースグループのポリシーで週に 1 回のバックアップが設定されている場合は、毎週木曜日の午後 10 時にバックアップが実行されるようにスケジュールを設定できます。リソースグループのスケジュールにアクセスするには、 * リソース * > * リソースグループ * をクリックします。





== データベースに必要なバックアップジョブの数

必要なバックアップジョブの数を左右する要因としては、リソースのサイズ、使用中のボリュームの数、リソースの変更率、サービスレベルアグリーメント（ SLA ）などがあります。



== バックアップの命名規則

Snapshot コピーのデフォルトの命名規則を使用するか、カスタマイズした命名規則を使用できます。デフォルトのバックアップ命名規則では Snapshot コピー名にタイムスタンプが追加されるため、コピーが作成されたタイミングを特定できます。

Snapshot コピーでは、次のデフォルトの命名規則が使用されます。

「 resourcegroupname_hostname_timestamp 」

バックアップリソースグループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* _dts1_は リソースグループ名です。
* _mach1x88_ はホスト名です。
* _03-12-2015_23.17.26_ は日付とタイムスタンプです。


または、「 * Snapshot コピーにカスタム名形式を使用」を選択して、リソースまたはリソースグループを保護しながら Snapshot コピー名の形式を指定することもできます。たとえば、 customtext_resourcegroup_policy_hostname や resourcegroup_hostname などの形式です。デフォルトでは、 Snapshot コピー名にタイムスタンプのサフィックスが追加されます。



== バックアップ保持オプション

バックアップコピーを保持する日数を選択するか、保持するバックアップコピーの数を指定できます。指定できる最大数は ONTAP で 255 個です。たとえば、組織の必要に応じて、 10 日分のバックアップコピーや 130 個のバックアップコピーを保持できます。

ポリシーを作成する際に、バックアップタイプおよびスケジュールタイプの保持オプションを指定できます。

SnapMirror レプリケーションを設定すると、デスティネーションボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、保持されているバックアップの保持ラベルがスケジュールタイプと一致する場合には、バックアップを削除します。リソースまたはリソースグループに対してスケジュールタイプが変更された場合、古いスケジュールタイプラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップコピーを長期にわたって保持する場合は、 SnapVault バックアップを使用する必要があります。



== Exchange Server のソースストレージボリュームにトランザクションログバックアップを保持する期間

SnapCenter Plug-in for Microsoft Exchange Server で最新の状態へのリストア処理を実行するには、トランザクションログバックアップが必要です。この場合、 2 つのフルバックアップの間の任意の時点の状態にデータベースがリストアされます。

たとえば、 Plug-in for Exchange で午前 8 時にフルとトランザクションログバックアップを作成しもう 1 つのフルおよびトランザクションログバックアップを午後 5 時に作成した場合は、最新のトランザクションログバックアップを使用して、午前 8 時から午後 5 時までの任意の時点の状態にデータベースをリストアできます午後 5 時までオープントランザクションログがない場合、 Plug-in for Exchange ではポイントインタイムリストア処理のみを実行できます。この場合、 Plug-in for Exchange がフルバックアップを完了した時点の状態にデータベースがリストアされます。

通常、最新の状態へのリストア処理が必要になるのは 1~2 日のみです。デフォルトでは、 SnapCenter は 2 日以上保持します。
