---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますプラグインパッケージをインストールするためのクレデンシャル、およびデータベースでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。 
---
= SnapCenter Plug-in for Windows のクレデンシャルを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますプラグインパッケージをインストールするためのクレデンシャル、およびデータベースでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。

* このタスクについて *

Windows ホストにプラグインをインストールするためのクレデンシャルを設定する必要があります。ホストを導入してプラグインをインストールしたあとに Windows のクレデンシャルを作成することもできますが、 SVM を追加したあとで、ホストを導入してプラグインをインストールする前にクレデンシャルを作成することを推奨します。

リモートホストに対する管理者権限を含む、管理者権限でクレデンシャルを設定します。

個々のリソースグループのクレデンシャルを設定していて、ユーザ名にフル管理者権限がない場合は、少なくともリソースグループとバックアップ権限をユーザ名に割り当てる必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
+
[ 資格情報 ] ウィンドウが表示されます。

. [ クレデンシャル ] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名
 a| 
認証に使用するユーザ名を入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者、または SnapCenter プラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。Username フィールドの有効な形式は次のとおりです。

+
*** NETBIOS/USERNAME
*** 「ドメイン FQDN\ ユーザ名」


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、 SnapCenter プラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザアカウントに昇格された権限がある場合、またはホストシステムでユーザアクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカルユーザアカウントを指定できます。Username フィールドの有効な形式は、「 username 」です





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。



 a| 
認証
 a| 
認証モードとして Windows を選択します。

|===
. [OK] をクリックします。

