---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenterを使用してMicrosoft Exchange Serverリソースをバックアップする前に、Exchangeリソースまたはリソースグループのバックアップポリシーを作成できます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。 
---
= Exchange Serverデータベースのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してMicrosoft Exchange Serverリソースをバックアップする前に、Exchangeリソースまたはリソースグループのバックアップポリシーを作成できます。また、リソースグループの作成時や単一のリソースのバックアップ時にバックアップポリシーを作成することもできます。

.開始する前に
* データ保護戦略を定義しておく必要があります。
+
詳細については、Exchangeデータベースのデータ保護戦略の定義に関する情報を参照してください。

* SnapCenter のインストール、ホストの追加、リソースの特定、ストレージシステム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* Exchange Serverリソースをリフレッシュ（検出）しておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートする場合は、SnapCenter管理者がソースボリュームとデスティネーションボリュームの両方のStorage Virtual Machine（SVM）をユーザに割り当てておく必要があります。
* プリスクリプトとポストスクリプトでPowerShellスクリプトを実行する場合は、ファイルでパラメータの値をtrueに設定する必要があります `usePowershellProcessforScripts` `web.config` 。
+
デフォルト値はfalseです。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"]。


.タスクの内容
* バックアップポリシーは、バックアップを管理および保持する方法、およびリソースまたはリソースグループをバックアップする頻度を規定する一連のルールです。また、スクリプト設定を指定することもできます。ポリシーでオプションを指定することで、別のリソースグループにポリシーを再利用して時間を節約できます。
* フルバックアップの保持は、特定のポリシーに固有です。フルバックアップの保持数が4のポリシーAを使用するデータベースまたはリソースでは、4つのフルバックアップが保持され、同じデータベースまたはリソースのポリシーBには影響しません。保持数を3に設定すると、3つのフルバックアップが保持される場合があります。
* ログバックアップの保持はポリシーに関係なく有効で、データベースまたはリソースのすべてのログバックアップに適用されます。したがって、ポリシーBを使用してフルバックアップを実行する場合、ログ保持設定は、ポリシーAで同じデータベースまたはリソース上に作成されたログバックアップに影響します。同様に、ポリシーAのログ保持設定は、同じデータベース上にポリシーBで作成されたログバックアップに影響します。
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

+
|===


| * ベストプラクティス： * 維持するフルバックアップとログバックアップの総数に基づいて、セカンダリ保持ポリシーを設定することを推奨します。セカンダリの保持ポリシーを設定する場合は、異なるボリュームにあるデータベースとログの場合、各バックアップに3つのSnapshotを保持でき、データベースとログが同じボリュームにある場合は、各バックアップに2つのSnapshotを保持できることに注意してください。 
|===
* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
+
Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。

+
ONTAP 9.12.1以前のバージョンでは、SnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。





.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [Name]ページで、ポリシーの名前と詳細を入力します。
. [Backup Type and Replication]ページで、次の手順を実行します。
+
.. バックアップタイプを選択：
+
|===
| 状況 | 操作 


 a| 
データベースファイルと必要なトランザクションログをバックアップする
 a| 
[ フルバックアップおよびログバックアップ * ] を選択します。

データベースはログを切り捨ててバックアップされ、切り捨てられたログを含むすべてのログがバックアップされます。


NOTE: これは推奨されるバックアップタイプです。



 a| 
データベースファイルとコミットされていないトランザクションログをバックアップする
 a| 
[* Full backup* ] を選択します。

データベースはログを切り捨ててバックアップされ、切り捨てられたログはバックアップされません。



 a| 
すべてのトランザクションログをバックアップする
 a| 
「 * Log backup * 」を選択します。

アクティブファイルシステム上のすべてのトランザクションログがバックアップされ、ログの切り捨ては行われません。

ライブログと同じディスクに _scebackupinfo_directory が作成されます。このディレクトリには、Exchangeデータベースの増分変更へのポインタが格納されており、完全なログ・ファイルとは異なります。



 a| 
トランザクションログファイルを切り捨てずに、すべてのデータベースファイルとトランザクションログをバックアップする
 a| 
Copy Backup （バックアップのコピー） * を選択します。

すべてのデータベースとすべてのログがバックアップされ、ログの切り捨ては行われません。このバックアップタイプは、通常、レプリカの再シードや問題のテストや診断に使用します。

|===
+

NOTE: ログバックアップに必要なスペースは、up-to-the-minute（UTM；最新の状態へのリストア）ではなく、フルバックアップの保持に基づいて定義する必要があります。

+

NOTE: Exchangeボリューム（LUN）を扱う場合は、ログとデータベースに対して個別のバックアップポリシーを作成し、同じラベルを使用して、ログポリシーのkeep（retention）をデータベースポリシーの2倍の数に設定します。詳細については、を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["SnapCenter for Exchangeバックアップでは、バックアップデスティネーションログボリュームに保持されるSnapshotの半分だけが保持されます"^]

.. [Database Availability Group Settings]セクションで、処理を選択します。
+
|===
| フィールド | 操作 


 a| 
アクティブなコピーをバックアップ
 a| 
選択したデータベースのアクティブコピーのみをバックアップする場合は、このオプションを選択します。

Database Availability Group（DAG；データベース可用性グループ）の場合は、DAG内のすべてのデータベースのアクティブコピーのみがバックアップされます。

パッシブコピーはバックアップされません。



 a| 
バックアップジョブの作成時に選択するサーバ上のコピーをバックアップする
 a| 
選択したサーバ上のデータベースのコピー（アクティブとパッシブの両方）をバックアップする場合は、このオプションを選択します。

DAGの場合は、選択したサーバ上のすべてのデータベースのアクティブコピーとパッシブコピーの両方がバックアップされます。

|===
+

NOTE: クラスタ構成では、ポリシーで設定された保持設定に従って、バックアップがクラスタの各ノードで保持されます。クラスタの所有者ノードが変更された場合、以前の所有者ノードのバックアップが保持されます。保持期間はノードレベルでのみ適用されます。

.. [ スケジュール頻度 ] セクションで、 1 つ以上の頻度タイプを選択します。 * オンデマンド * 、 * 毎時 * 、 * 毎日 * 、 * 毎週 * 、および * 毎月 * 。
+

NOTE: リソースグループを作成する際に、バックアップ処理のスケジュール（開始日、終了日）を指定できます。これにより、ポリシーとバックアップ頻度が同じであるリソースグループを作成できますが、各ポリシーに異なるバックアップスケジュールを割り当てることができます。

+

NOTE: 午前2時にスケジュールを設定している場合、夏時間（DST）中はスケジュールはトリガーされません。

.. ポリシーラベルを選択します。
+
選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。

+

NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。

.. [Select secondary replication options]セクションで、次のセカンダリレプリケーションオプションの一方または両方を選択します。
+

NOTE: *セカンダリSnapshotコピーのロック期間*を有効にするには、セカンダリレプリケーションオプションを選択する必要があります。[Retention]ページで、*[Secondary snapshot copy locking period]*オプションを使用できます。

+
|===
| フィールド | 操作 


 a| 
ローカルSnapshot作成後にSnapMirrorを更新する
 a| 
バックアップセットのミラーコピーを別のボリューム（SnapMirror）に保持する場合は、このオプションを選択します。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。

このオプションは、SnapMirrorのアクティブな同期に対して有効にする必要があります。


IMPORTANT: プライマリのみのポリシーは、Exchange ONTAPボリュームに対してSnapMirrorのアクティブな同期が設定されている場合は使用できません。SnapCenterではこれが許可されていません。「ミラー」オプションを有効にする必要があります。

[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

を参照して link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["[Topology]ページでのExchangeバックアップの表示"]



 a| 
ローカルSnapshot作成後にSnapVaultを更新
 a| 
ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。



 a| 
エラー時の再試行回数
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。



. [Retention]ページで、保持を設定します。
+
表示されるオプションは、以前に選択したバックアップタイプと頻度タイプによって異なります。

+

NOTE: 最大保持値は1018です。保持数を使用しているONTAPバージョンでサポートされる値よりも大きい値に設定すると、バックアップは失敗します。

+

IMPORTANT: SnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗する可能性があります。

+
.. [Log backups retention settings]セクションで、次のいずれかを選択します。
+
|===
| 状況 | 操作 


 a| 
特定の数のログバックアップのみを保持
 a| 
ログを保持するフルバックアップの数を * 選択し、最新の状態へのリストアを実行するフルバックアップの数を指定します。

up-to-the-minute（UTM；最新の状態へのリストア）の保持は、フルバックアップまたはログバックアップで作成されたログバックアップに適用されます。たとえば、過去5回のフルバックアップのログバックアップを保持するようにUTM保持設定が設定されている場合、過去5回のフルバックアップのログバックアップが保持されます。

フルおよびログバックアップの一部として作成されたログフォルダは、UTMの一部として自動的に削除されます。ログフォルダを手動で削除することはできません。たとえば、フルバックアップまたはフルバックアップの保持設定が1カ月に設定され、ログバックアップの保持期間が10日に設定されている場合、これらのバックアップの一部として作成されたログフォルダはUTMに従って削除されます。そのため、ログフォルダは10日間しか保持されず、その他のバックアップはすべてポイントインタイムリストアの対象としてマークされます。

最新の状態へのリストアを実行しない場合は、UTM保持の値を0に設定できます。これにより、ポイントインタイムリストア処理が有効になります。

*ベストプラクティス：*[Full backup retention settings]セクションの[Total Snapshots（フルバックアップ）]の設定と同じにすることを推奨します。これにより、フルバックアップごとにログファイルが保持されます。



 a| 
バックアップコピーを特定の日数だけ保持
 a| 
「 * Keep log backups for last * 」オプションを選択し、ログバックアップコピーを保持する日数を指定します。

フルバックアップが保持される日数までのログバックアップが保持されます。



 a| 
Snapshotロック期間
 a| 
[Snapshotコピーロック期間]*を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。

|===
+
バックアップタイプとして * Log backup * を選択した場合は、フルバックアップの最新の状態へのリストア保持設定の一部としてログバックアップが保持されます。

.. [Full backup retention settings]セクションで、オンデマンドバックアップの場合は次のいずれかを選択し、フルバックアップの場合は1つを選択します。
+
|===
| フィールド | 操作 


 a| 
特定の数のSnapshotのみを保持
 a| 
保持するフルバックアップの数を指定する場合は、*保持するSnapshotコピーの総数*オプションを選択し、保持するSnapshot（フルバックアップ）の数を指定します。

フルバックアップの数が指定した数を超えると、指定した数を超えるフルバックアップが削除され、最も古いコピーから順に削除されます。



 a| 
フルバックアップを特定の日数だけ保持
 a| 
[Keep Snapshot copies for]*オプションを選択し、Snapshot（フルバックアップ）を保持する日数を指定します。



 a| 
プライマリSnapshotロック期間
 a| 
[Primary snapshot copy locking period]*を選択し、[Days]、[Months]、または[Years]を選択します。

SnapLock保持期間は100年未満にする必要があります。



 a| 
セカンダリSnapshotのロック期間
 a| 
[Secondary snapshot copy locking period]*を選択し、[Days]、[Months]、または[Years]を選択します。

|===
+
DAG構成のホストにログバックアップのみのデータベースがあり、フルバックアップがない場合は、次の方法でログバックアップが保持されます。

+
*** デフォルトでは、 SnapCenter は DAG 内の他のすべてのホストでこのデータベースの最も古いフルバックアップを検出し、フルバックアップの前に作成されたこのホスト上のすべてのログバックアップを削除します。
*** ログバックアップのみを使用する DAG 内のホストのデフォルトの保持設定を上書きするには、 _C ： \Program Files\NetApp\SnapManager WebApp\web.config_file にキー * MaxLogBackupOnlyCountWithoutFullBackup * を追加します。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
この例の値が10の場合、ホストで保持できるログバックアップは最大10個です。





. スクリプトページで、バックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
** プリスクリプトのバックアップ引数には、「 $Database 」および「 $ServerInstance 」が含まれます。
** PostScript バックアップ引数には、「 $Database 」、「 $ServerInstance 」、「 $BackupName 」、「 $LogDirectory 」、「 $LogSnapshot 」が含まれます。
+
スクリプトを実行して、SNMPトラップの更新、アラートの自動化、ログの送信などを行うことができます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。



. 概要を確認し、 [ 完了 ] をクリックします。

