---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: バックアップジョブを作成する前にバックアップ戦略を定義しておくと、データベースの正常なリストアに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA ）、目標復旧時間（ RTO ）、および目標復旧時点（ RPO ）によって決まります。 
---
= Exchange Serverリソースのバックアップ戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップジョブを作成する前にバックアップ戦略を定義しておくと、データベースの正常なリストアに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。

SLAは、期待されるサービスレベルと、サービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RTOは、サービスの停止後にビジネスプロセスをリストアする必要があるまでの時間です。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA、RTO、RPOがバックアップ戦略に影響します。



== Exchangeデータベースでサポートされるバックアップのタイプ

SnapCenterを使用してExchangeメールボックスをバックアップするには、リソースタイプ（データベースやDatabase Availability Group（DAG；データベース可用性グループ）など）を選択する必要があります。Snapshotテクノロジを使用して、リソースが配置されているボリュームのオンラインの読み取り専用コピーが作成されます。

|===
| バックアップタイプ | 説明 


 a| 
フルバックアップとログバックアップ
 a| 
データベースと、切り捨てられるログを含むすべてのトランザクションログがバックアップされます。

フルバックアップが完了すると、Exchange Serverはデータベースにコミット済みのトランザクションログを切り捨てます。

通常は、このオプションを選択する必要があります。ただし、バックアップ時間が短い場合は、フルバックアップでトランザクションログバックアップを実行しないように選択できます。



 a| 
フルバックアップ
 a| 
データベースおよびトランザクションログがバックアップされます。

切り捨てられたトランザクションログはバックアップされません。



 a| 
ログバックアップ
 a| 
すべてのトランザクションログがバックアップされます。

データベースにコミット済みの切り捨てられたログはバックアップされません。フルデータベースバックアップの間にトランザクションログを頻繁にバックアップするようにスケジュールを設定すると、リカバリポイントをきめ細かく選択できます。

|===


== データベースプラグインのバックアップスケジュール

バックアップ頻度（スケジュールタイプ）はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは1時間ごとにバックアップし、使用頻度の低いリソースは1日に1回バックアップすることもできます。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAは、期待されるサービスレベルと、サービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOはデータ保護戦略に影響します。

使用頻度の高いリソースであっても、フルバックアップを1日に1~2回以上実行する必要はありません。たとえば、定期的なトランザクションログバックアップで十分な場合は、必要なバックアップを作成できます。データベースをバックアップする回数が多いほど、リストア時に SnapCenter が使用する必要のあるトランザクションログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

バックアップスケジュールには、次の2つの部分があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインでは _ schedule type__ と呼ばれます。ポリシーでは、バックアップ頻度として、毎時、毎日、毎週、または毎月を選択できます。頻度を選択しない場合は、オンデマンドのみのポリシーが作成されます。ポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行されるタイミング）は、リソースグループ設定の一部です。たとえば、リソースグループのポリシーで週単位のバックアップが設定されている場合は、毎週木曜日の午後10時にバックアップが実行されるようにスケジュールを設定できます。リソースグループのスケジュールにアクセスするには、 * リソース * > * リソースグループ * をクリックします。





== データベースに必要なバックアップジョブの数

必要なバックアップジョブの数を左右する要因には、リソースのサイズ、使用されているボリュームの数、リソースの変更率、サービスレベルアグリーメント（SLA）などがあります。



== バックアップの命名規則

Snapshotのデフォルトの命名規則を使用することも、カスタマイズした命名規則を使用することもできます。デフォルトのバックアップ命名規則では、Snapshot名にタイムスタンプが追加されるため、コピーがいつ作成されたかを確認できます。

Snapshotでは、次のデフォルトの命名規則が使用されます。

`resourcegroupname_hostname_timestamp`

バックアップリソースグループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* _dts1_は リソースグループ名です。
* _mach1x88_ はホスト名です。
* _03-12-2015_23.17.26_ は日付とタイムスタンプです。


または、*[Use custom name format for Snapshot copy]*を選択して、リソースまたはリソースグループを保護しながらSnapshot名の形式を指定することもできます。たとえば、customText_resourcegroup_policy_hostnameやresourcegroup_hostnameなどです。デフォルトでは、タイムスタンプのサフィックスがSnapshot名に追加されます。



== バックアップ保持オプション

バックアップコピーを保持する日数を選択することも、保持するバックアップコピーの数（ONTAPの最大コピー数255）を指定することもできます。たとえば、組織で、10日分のバックアップコピーや130個のバックアップコピーを保持する必要があるとします。

ポリシーの作成時に、バックアップタイプとスケジュールタイプの保持オプションを指定できます。

SnapMirrorレプリケーションを設定すると、デスティネーションボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、保持されているバックアップの保持ラベルがスケジュールタイプと一致する場合には、バックアップを削除します。リソースまたはリソースグループのスケジュールタイプを変更した場合、古いスケジュールタイプラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップコピーを長期にわたって保持する場合は、SnapVaultバックアップを使用する必要があります。



== Exchange Serverのソースストレージボリュームにトランザクションログバックアップを保持する期間

SnapCenter Plug-in for Microsoft Exchange Serverでは、最新の状態へのリストア処理を実行するためにトランザクションログバックアップが必要です。この場合、2つのフルバックアップの間の任意の時点の状態にデータベースがリストアされます。

たとえば、Plug-in for Exchangeで午前8時にフルバックアップとトランザクションログバックアップが、午後5時に別のフルバックアップとトランザクションログバックアップが作成された場合、最新のトランザクションログバックアップを使用して、午前8時から午後5時の任意の時点にデータベースをリストアできます。トランザクションログが使用できない場合、Plug-in for Exchangeはポイントインタイムリストア処理のみを実行できます。この場合、Plug-in for Exchangeはフルバックアップがフルバックアップを完了した時点のフルバックアップが完了した時点にデータベースをリストアできます。

通常、最新の状態へのリストア処理が必要になるのは1~2日です。デフォルトでは、SnapCenterの保持期間は最低2日です。
