---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: PowerShellコマンドレットを使用してバックアップとリストアを実行する前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。 
---
= Exchange Server用のPowerShellコマンドレットを使用して、ストレージシステム接続とクレデンシャルを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShellコマンドレットを使用してバックアップとリストアを実行する前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージ接続を作成するには、Infrastructure Adminロールに必要な権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ホスト・プラグインのインストールは ' ストレージ・システム接続の追加中は実行しないでくださいホスト・キャッシュが更新されず ' データベース・ステータスが SnapCenter GUI に表示される場合がありますこれは ' バックアップには使用できませんまたは NetApp ストレージには使用できません

* ストレージシステム名は一意である必要があります。
+
SnapCenter では、異なるクラスタに同じ名前のストレージシステムを複数配置することはサポートされていません。SnapCenter でサポートされるストレージシステムには、それぞれ一意の名前およびデータ LIF の IP アドレスを割り当てる必要があります。



.手順
. コマンドレットを使用して、PowerShell接続セッションを開始します `Open-SmConnection` 。
+
この例では、PowerShellセッションを開きます。

+
[listing]
----
PS C:\> Open-SmConnection
----
. コマンドレットを使用して、ストレージシステムへの新しい接続を作成し `Add-SmStorageConnection` ます。
+
新しいストレージシステム接続を作成する例を次に示します。

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. コマンドレットを使用して、新しいRun Asアカウントを作成し `Add-Credential` ます。
+
この例では、Windowsクレデンシャルを使用してExchangeAdminという名前の新しいRun Asアカウントを作成します。

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
