---
permalink: protect-sce/task_restore_exchange_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: b2589f75fce91547cb20c051fa1935d2 
---
= 97e9982b58636ac0e13e42585b460313
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
b2589f75fce91547cb20c051fa1935d2

c90de0347e94ade70c96034e2ffca3ba

.bbe48fb854ea022537208eeeff822f91
f2c85d871e7c5ae1520349e8a3869fea

.f3a29486bed19a90f2da6d007818b427
. e8b2bea378ae2d61944327f562235bbe
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146/
----
. 53d7030c30fb81234ffed5a3972eb621
+
ca85b74e61d8e4c683f3c66af932ac63

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
341                           ResourceGroup_36304978_UTM... 12/8/2017 4:13:24 PM          Full Backup
342                           ResourceGroup_36304978_UTM... 12/8/2017 4:16:23 PM          Full Backup
355                           ResourceGroup_06140588_UTM... 12/8/2017 6:32:36 PM          Log Backup
356                           ResourceGroup_06140588_UTM... 12/8/2017 6:36:20 PM          Full Backup
----
. a65b207e84f627a2af00b6dd102bd0e3
+
49ab07d3ee1a1aacb53dd0994a535a3f

+
[listing]
----
C:\PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true
----
+
ae366ae6cd13ff2aebcc8778c88b7cdc

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true -LogRestoreType ByTransactionLogs -LogCount 2
----
+
0a9c9fd6c01df5a0b90869291e5ac73d

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode 'SCE' -AppObjectId 'DB2' -BackupId 81 -IsRecoverMount:$true -Confirm:$false
-archive @{Primary="paw_vs:vol1";Secondary="paw_vs:vol1_mirror"} -logrestoretype All
----
+
b06e92bcd2117390a5fc5c7c54f2f6db

+
e51e9b753df6cec73dab9f0a39974009



74db7181476f94f0e2927d8c8d98cb97
