---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html 
sidebar: sidebar 
keywords:  
summary: SnapCenterAdd Host ページを使用して、 Windows ホストを追加できます。指定したホストに Plug-in for Exchange が自動的にインストールされます。これはプラグインのインストールに推奨される方法です。ホストを追加してプラグインをインストールするには、個々のホストまたはクラスタを使用します。 
---
= ホストを追加し、 Plug-in for Exchange をインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter のホストの追加ページを使用して、 Windows ホストを追加できます。指定したホストに Plug-in for Exchange が自動的にインストールされます。これはプラグインのインストールに推奨される方法です。ホストを追加してプラグインをインストールするには、個々のホストまたはクラスタを使用します。

* 必要なもの *

* SnapCenter Admin など、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* メッセージキューサービスが実行されている必要があります。
* Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用している場合は、管理者権限を持つ gMSA を設定する必要があります。詳細については、を参照してくださいlink:task_configure_gMSA_on_windows_server_2012_or_later.html["Microsoft Exchange Server 2012 以降でグループマネージドサービスアカウントを設定します"^]。


* このタスクについて *

* SnapCenter サーバをプラグインホストとして別の SnapCenter サーバに追加することはできません。
* ホストの追加とプラグインパッケージのインストールは、個々のホストまたはクラスタに対して実行できます。
* Exchange ノードが DAG の一部である場合、 SnapCenter サーバに追加できるノードは 1 つだけです。
* クラスタ（ Exchange DAG ）にプラグインをインストールする場合は、ネットアップ LUN 上にデータベースがないノードがある場合でも、クラスタのすべてのノードにインストールされます。


SnapCenter 4.6 以降では、 SCE はマルチテナンシーをサポートしており、次の方法を使用してホストを追加できます。

|===
| ホスト追加処理 | 4.5 以前 | 4.6 以降 


| IP なしの DAG をクロスドメインまたは別のドメインに追加 | サポート対象外 | サポートされます 


| 同じドメインまたはクロスドメインにそれぞれ固有の名前を持つ複数の IP DAG を追加します | サポートされます | サポートされます 


| クロスドメインに、ホスト名と DB 名が同じ IP DAG または IP レス DAG を複数追加する | サポート対象外 | サポートされます 


| 同じ名前でクロスドメインに属する IP/IP を行わない DAG を複数追加します | サポート対象外 | サポートされます 


| 同じ名前とクロスドメインを持つ複数のスタンドアロンホストを追加します | サポート対象外 | サポートされます 
|===
Plug-in for Exchange は Windows 用 SnapCenter プラグインパッケージによって異なり、バージョンも同じである必要があります。Plug-in for Exchange のインストール時に、デフォルトで SnapCenter Plug-ins Package for Windows が選択され、 VSS Hardware Provider とともにインストールされます。

SnapManager for Microsoft Exchange Server と SnapDrive for Windows がすでにインストールされている場合は、 同じ Exchange サーバに Plug-in for Exchange をインストールする場合は、 Plug-in for Exchange および SnapCenter Plug-ins Package for Windows と互換性がないため、 SnapDrive for Windows で使用する VSS ハードウェアプロバイダの登録を解除する必要があります。詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_manually_register_the_Data_ONTAP_VSS_Hardware_Provider["Data ONTAP VSS ハードウェアプロバイダを手動で登録する方法"]。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] が選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の手順を実行します。
+
|===
| フィールド | 手順 


 a| 
ホストタイプ
 a| 
ホストタイプとして * windows * を選択します。

SnapCenter サーバによってホストが追加され、 Plug-in for Windows と Plug-in for Exchange がまだインストールされていない場合はホストにインストールされます。

Plug-in for Windows および Plug-in for Exchange のバージョンが同じである必要があります。以前に別のバージョンの Plug-in for Windows がインストールされていた場合、 SnapCenter のインストール時にこのバージョンが更新されます。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。

SnapCenter は、 DNS の適切な設定によって異なります。そのため、ベストプラクティスは Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を入力することです。

信頼されていないドメインホストの IP アドレスは、 FQDN に解決される場合にのみサポートされます。

SnapCenter を使用してホストを追加する際、ホストがサブドメインの一部である場合は、 FQDN を指定する必要があります。

次のいずれかの IP アドレスまたは FQDN を入力できます。

** スタンドアロンホスト
** Exchange DAG
+
Exchange DAG の場合、次の操作を実行できます。

+
*** DAG 名、 DAG の IP アドレス、ノード名、またはノードの IP アドレスを指定して DAG を追加します。
*** DAG クラスタのいずれかのノードの IP アドレスまたは FQDN を指定して、 IP なしの DAG クラスタを追加します。
*** 同じドメインまたは別のドメインに属する IP なしの DAG を追加します。同じ名前でドメインが異なる複数の IP/IP が少ない DAG を追加することもできます。





NOTE: スタンドアロンホストまたは Exchange DAG （クロスドメインまたは同じドメイン）の場合は、ホストまたは DAG の FQDN または IP アドレスを指定することを推奨します。



 a| 
クレデンシャル
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

クレデンシャルの詳細を表示するには、指定したクレデンシャル名にカーソルを合わせます。


NOTE: 資格情報認証モードは、ホストの追加ウィザードで指定したホストタイプによって決まります。

|===
. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
+
Plug-in for Exchange を選択すると、 SnapCenter Plug-in for Microsoft SQL Server の選択が自動的に解除されます。Microsoft では、 Exchange で必要とされるメモリの使用量やその他のリソースの使用量が原因で、 SQL Server と Exchange サーバを同じシステムにインストールしないことを推奨しています。

. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 手順 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は 8145 です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
デフォルトパスは「 C ： \Program Files\NetApp\SnapCenter 」です。

必要に応じて、パスをカスタマイズできます。



 a| 
DAG 内のすべてのホストを追加します
 a| 
DAG を追加する場合は、このチェックボックスを選択します。



 a| 
インストール前のチェックをスキップします
 a| 
プラグインを手動でインストール済みで、プラグインのインストール要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
プラグインサービスを実行するには、 Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用します
 a| 
グループ管理サービスアカウント（ GMSA ）を使用してプラグインサービスを実行する場合は、このチェックボックスをオンにします。

gMSA 名を _domainName\accountName$_ の形式で指定します。


NOTE: gMSA は、 SnapCenter Plug-in for Windows サービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [Submit （送信） ] をクリックします。
+
Skip ケーブルの事前確認チェックボックスを選択しなかった場合は、プラグインのインストール要件を満たすかどうかをホストが検証されます。最小要件を満たしていない場合は、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたは RAM に関連している場合は、「 C ： \Program Files\NetApp\SnapCenter ’ WebApp 」にある web.config ファイルを更新して、デフォルト値を変更できます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HA セットアップで web.config ファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. インストールの進行状況を監視します。

