---
settings:
  name: SnapCenter Software 5.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '5.0'
    url: "/snapcenter"
  - version-number: '4.9'
    url: "/snapcenter-49"
  - version-number: '4.8'
    url: "/snapcenter-48"
  - version-number: '4.7'
    url: "/snapcenter-47"
  - version-number: '4.6'
    url: "/snapcenter-46"
  - version-number: '4.5'
    url: "/snapcenter-45"
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SnapCenterソフトウェア5.0のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/release-notes.html"
  - section: concept
  - section: install
  - section: protect-scsql
  - section: protect-hana
  - section: protect-sco
  - section: protect-scw
  - section: protect-sce
  - section: protect-scc
  - section: protect-scu
  - section: protect-azure
  - section: admin
  - section: upgrade
  - section: tech-refresh
  - section: uninstall
  - section: sc-automation
  - title: 法的通知
    url: "/legal-notices.html"
