---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Plug-in for Windows をインストールする前に、一定のインストール要件について理解しておく必要があります。 
---
= SnapCenter Plug-in for Microsoft Windowsのインストール要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plug-in for Windows をインストールする前に、一定のインストール要件について理解しておく必要があります。

ユーザが Plug-in for Windows の使用を開始するためには、 SnapCenter 管理者が事前に SnapCenter サーバをインストールして設定し、前提条件となるタスクを実行する必要があります。

* Plug-in for Windows をインストールするには、 SnapCenter 管理者権限が必要です。
+
SnapCenter 管理者ロールには管理者権限が必要です。

* SnapCenter サーバをインストールして設定しておく必要があります。
* Windowsホストにプラグインをインストールするときに、組み込みでないクレデンシャルを指定した場合やユーザがローカルワークグループに属している場合は、ホストのUACを無効にする必要があります。
* バックアップレプリケーションが必要な場合は、SnapMirrorとSnapVaultをセットアップする必要があります。




== SnapCenter Plug-ins Package for Windowsをインストールするホストの要件

SnapCenter Plug-ins Package for Windowsをインストールする前に、基本的なホストシステムのスペース要件とサイジング要件を理解しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows

サポートされているバージョンの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]ください。



 a| 
ホスト上のSnapCenterプラグイン用の最小RAM
 a| 
1GB



 a| 
ホスト上のSnapCenterプラグインのインストールとログの最小スペース
 a| 
5GB


NOTE: 十分なディスクスペースを割り当て、logsフォルダによるストレージ消費量を監視する必要があります。必要なログスペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理のログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
* です。 ネットコア8.0.5
* PowerShell Core 7.4.2
* Java 11 Oracle JavaおよびOpenJDK


サポートされているバージョンの最新情報については、を参照して https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]ください。

用。 NET固有のトラブルシューティング情報。を参照してください。 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["インターネットに接続されていない従来型システムでは、SnapCenter のアップグレードまたはインストールが失敗します。"]

|===


== Plug-in for Windowsのクレデンシャルを設定する

SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますSnapCenter プラグインのインストールに必要なクレデンシャル、および Windows ファイルシステムでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。

* 必要なもの *

* プラグインをインストールする前にWindowsクレデンシャルを設定する必要があります。
* このクレデンシャルには、リモートホストに対する管理者権限（管理者権限を含む）を設定する必要があります。
* 個 々 のリソースグループのクレデンシャルを設定する場合で、ユーザに完全なadmin権限がない場合は、少なくともリソースグループとバックアップの権限を割り当てる必要があります。


* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [Credential]ページで、次の手順を実行します。
+
|===
| フィールド | 操作 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名 / パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者またはSnapCenterプラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。ユーザ名フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。[Username]フィールドの有効な形式は次のとおりです。 `UserName`

+
パスワードに二重引用符（"）またはバックティック（`）を使用しないでください。小なり（<）と感嘆符（！）は使用しないでください。 パスワードに記号を追加します。たとえば、lessthan <！10、lessthan10 <！、backtick 12とします。





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。

|===
. [OK]*をクリックします。
+
クレデンシャルの設定が完了したら、必要に応じて[User and Access]ページでユーザまたはユーザグループにクレデンシャルを割り当てることができます。





== Windows Server 2016以降でのgMSAの設定

Windows Server 2016以降では、管理対象ドメインアカウントからサービスアカウントのパスワードを自動管理するグループ管理サービスアカウント（gMSA）を作成できます。

.開始する前に
* Windows Server 2016以降のドメインコントローラが必要です。
* ドメインのメンバーであるWindows Server 2016以降のホストが必要です。


.手順
. KDSルートキーを作成して、gMSA内のオブジェクトごとに一意のパスワードを生成します。
. ドメインごとに、 Windows ドメインコントローラから次のコマンドを実行します。 Add-KDSRootKey -EffectiveImmedient
. gMSAを作成して設定します。
+
.. 次の形式でユーザグループアカウントを作成します。
+
 domainName\accountName$
.. コンピュータオブジェクトをグループに追加します。
.. 作成したユーザグループを使用してgMSAを作成します。
+
例えば、

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. コマンドを実行し `Get-ADServiceAccount` てサービスアカウントを確認します。


. ホストでgMSAを設定します。
+
.. gMSAアカウントを使用するホストで、Windows PowerShell用Active Directoryモジュールを有効にします。
+
これを行うには、PowerShellから次のコマンドを実行します。

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. ホストを再起動します。
.. PowerShellコマンドプロンプトで次のコマンドを実行して、ホストにgMSAをインストールします。 `Install-AdServiceAccount <gMSA>`
.. 次のコマンドを実行して、gMSAアカウントを確認します。 `Test-AdServiceAccount <gMSA>`


. ホスト上の設定済みgMSAに管理者権限を割り当てます。
. SnapCenterサーバで設定済みのgMSAアカウントを指定してWindowsホストを追加します。
+
選択したプラグインがSnapCenterサーバにインストールされ、指定したgMSAがプラグインのインストール時にサービスのログオンアカウントとして使用されます。


