---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。 
---
= Windows ファイルシステムのバックアップポリシーの作成
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。

* 必要なもの *

* バックアップ戦略を定義しておく必要があります。 link:task_define_a_backup_strategy_for_windows_file_systems.html["詳細はこちら。"^]
* データ保護の準備が完了している必要があります。
+
データ保護の準備として、 SnapCenter のインストール、ホストの追加、リソースの検出、 Storage Virtual Machine （ SVM ）接続の作成などのタスクを完了しておく必要があります。

* Snapshot コピーをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートするユーザには、 SnapCenter 管理者がユーザに対してソースとデスティネーションの両方のボリューム用に SVM を割り当てる必要があります。
* プリスクリプトとポストスクリプトで PowerShell スクリプトを実行する場合は、 web.config ファイルで usePowershellProcessforScripts パラメータの値を true に設定する必要があります。
+
デフォルト値は false です。



* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. 既存のポリシーを使用できるかどうかを確認するには、ポリシー名を選択し、 [* 詳細 * ] をクリックします。
+
既存のポリシーを確認したあと、次のいずれかを実行できます。

+
** 既存のポリシーを使用する。
** 既存のポリシーをコピーしてポリシー設定を変更する。
** 新しいポリシーを作成します。


. 新しいポリシーを作成するには、 * New * をクリックします。
. [ 名前 ] ページで、ポリシー名と概要を入力します。
. [ バックアップオプション ] ページで、次のタスクを実行します。
+
.. バックアップ設定を選択します。
+
|===
| オプション | 説明 


 a| 
File System Consistent Backup の略
 a| 
ファイルシステムが配置されたディスクドライブをバックアップ処理の開始前に SnapCenter で休止し、バックアップ処理の終了後に再開する場合は、このオプションを選択します。



 a| 
ファイルシステムのクラッシュ整合性バックアップ
 a| 
ファイルシステムが配置されたディスクドライブを SnapCenter で休止しない場合は、このオプションを選択します。

|===
.. スケジュール頻度（ポリシータイプ）を選択します。
+
ポリシーではバックアップの頻度のみを指定します。バックアップの具体的なスケジュールは、リソースグループで定義します。したがって、複数のリソースグループで同じポリシーとバックアップ頻度を使用している場合でも、別々のバックアップスケジュールを設定できます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間（ DST ）中はスケジュールはトリガーされません。



. [ 保持 ] ページで ' オン・デマンド・バックアップおよび選択した各スケジュール頻度の保持設定を指定します
+
|===
| オプション | 説明 


 a| 
保持する Snapshot コピーの総数
 a| 
SnapCenter ストアを自動的に削除する前に Snapshot コピー数を指定する場合は、このオプションを選択します。



 a| 
より古い Snapshot コピーを削除します
 a| 
SnapCenter がバックアップコピーを保持する日数を指定する場合は、このオプションを選択します。指定した日数を過ぎると削除されます。

|===
+

IMPORTANT: SnapVault レプリケーションを有効にする場合は、保持数を 2 以上に設定する必要があります。レプリケーション数を 1 に設定すると、保持処理が失敗する可能性があります。これは、新しい Snapshot コピーがターゲットにレプリケートされるまで、最初の Snapshot コピーが SnapVault 関係の参照 Snapshot コピーになるためです。

+

NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持期間を基盤となる ONTAP バージョンの値よりも大きい値に設定すると、バックアップが失敗します。

. Replication （レプリケーション）ページで、セカンダリストレージシステムへのレプリケーションを指定します。
+
|===
| フィールド | 手順 


 a| 
ローカル Snapshot コピーの作成後に SnapMirror を更新します
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（ SnapMirror ）は、このオプションを選択します。



 a| 
Snapshot コピーの作成後に SnapVault を更新します
 a| 
ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。



 a| 
セカンダリポリシーのラベル
 a| 
Snapshot ラベルを選択します。

選択した Snapshot コピーラベルに応じて、 ONTAP はラベルに一致するセカンダリ Snapshot コピー保持ポリシーを適用します。


NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



 a| 
エラー再試行回数
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリストレージでの Snapshot コピーの最大数に達しないように、 ONTAP でセカンダリストレージの SnapMirror 保持ポリシーを設定する必要があります。

. スクリプトページで、 SnapCenter サーバでバックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと、 SnapCenter がスクリプトの実行を待機してからタイムアウトするまでの時間を入力します。
+
たとえば、 SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

. 概要を確認し、 [ 完了 ] をクリックします。

