---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: SnapCenter を使用すると、ファイルシステムのバックアップをリストアできます。ファイルシステムのリストアは段階的に実施され、指定したバックアップのすべてのデータがファイルシステムの元の場所にコピーされます。 
---
= Windows ファイルシステムのバックアップをリストアする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用すると、ファイルシステムのバックアップをリストアできます。ファイルシステムのリストアは段階的に実施され、指定したバックアップのすべてのデータがファイルシステムの元の場所にコピーされます。

* 必要なもの *

* ファイルシステムをバックアップしておく必要があります。
* ファイルシステムに対してバックアップ処理などのスケジュールが設定された処理が現在実行中の場合は、リストア処理を開始する前にキャンセルしておく必要があります。
* ファイルシステムのバックアップは元の場所にのみリストアでき、別のパスを指定することはできません。
+
ファイルシステムのリストアでは、ファイルシステムの元の場所にあるデータはすべて上書きされるため、バックアップからファイルを 1 つずつリストアすることはできません。ファイルシステムのバックアップから単一のファイルをリストアするには、バックアップをクローニングし、クローン内のファイルにアクセスする必要があります。

* システムボリュームやブートボリュームはリストアできません。
* SnapCenter では、クラスタグループをオフラインにすることなく、 Windows クラスタのファイルシステムをリストアできます。


* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. リソースのリストをフィルタリングするには、 [ ファイルシステム（ File System ） ] および [ リソースグループ（ Resource Group ） ] オプションを選択します。
. リストからリソースグループを選択し、 * リストア * をクリックします。
. バックアップページで、プライマリストレージシステムとセカンダリストレージシステムのどちらからリストアするかを選択し、リストアするバックアップを選択します。
. リストアウィザードでオプションを選択します。
. リストア処理の実行前や実行後に SnapCenter で実行するプリスクリプトやポストスクリプトのパスと引数を入力できます。
+
たとえば、 SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

. [ 通知 ] ページで、次のいずれかのオプションを選択します。
+
|===
| フィールド | 手順 


 a| 
SnapCenter サーバイベントをストレージシステムの syslog に記録します
 a| 
SnapCenter サーバのイベントをストレージ・システムの syslog に記録する場合は、このオプションを選択します。



 a| 
失敗した処理についての AutoSupport 通知をストレージシステムに送信します
 a| 
失敗した処理に関する情報を AutoSupport を使用してネットアップに送信する場合は、このオプションを選択します。



 a| 
E メール設定
 a| 
バックアップのリストア後に受信者にメールを送信するには、「 * Always * 」、「 * On Failure * 」、または「 * on failure or warning * 」を選択します。SMTP サーバ、 E メールのデフォルトの件名、および送信先と送信元の E メールアドレスを入力します。

|===
. 概要を確認し、 [ 完了 ] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。



IMPORTANT: リストアしたファイルシステムにデータベースが含まれている場合は、データベースもリストアする必要があります。データベースをリストアしないと、データベースが無効な状態になる可能性があります。データベースのリストアの詳細については、そのデータベースの『データ保護ガイド』を参照してください。
