---
permalink: protect-scw/task_set_up_your_credentials_for_the_plug_in_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますSnapCenter プラグインのインストールに必要なクレデンシャル、および Windows ファイルシステムでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。 
---
= Plug-in for Windows のクレデンシャルを設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、クレデンシャルを使用して SnapCenter 処理を実行するユーザを認証しますSnapCenter プラグインのインストールに必要なクレデンシャル、および Windows ファイルシステムでデータ保護処理を実行するための追加のクレデンシャルを作成する必要があります。

* 必要なもの *

* プラグインのインストール前に Windows クレデンシャルをセットアップする必要があります。
* リモートホストで、管理者権限を含む管理者権限でクレデンシャルを設定する必要があります。
* 個々のリソースグループのクレデンシャルを設定していて、そのユーザにフル管理者権限がない場合は、少なくともリソースグループとバックアップ権限をユーザに割り当てる必要があります。


* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [ クレデンシャル ] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザ名 / パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者、または SnapCenter プラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。Username フィールドの有効な形式は次のとおりです。

+
*** NETBIOS/USERNAME
*** 「ドメイン FQDN\ ユーザ名」
*** 「 username@UPN 」のようになります


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、 SnapCenter プラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザアカウントに昇格された権限がある場合、またはホストシステムでユーザアクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカルユーザアカウントを指定できます。Username フィールドの有効な形式は、「 username 」です

+
パスワードには二重引用符（ " ）を使用しないでください。





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。

|===
. [OK] をクリックします。
+
クレデンシャルの設定が完了したら、 * User and Access * ページで、ユーザまたはユーザグループにクレデンシャルメンテナンスを割り当てることができます。


