---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。 
---
= Windows ファイルシステムのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。

.作業を開始する前に
* バックアップ戦略を定義しておく必要があります。 link:task_define_a_backup_strategy_for_windows_file_systems.html["詳細はこちら。"^]
* データ保護の準備が完了している必要があります。
+
データ保護の準備として、 SnapCenter のインストール、ホストの追加、リソースの検出、 Storage Virtual Machine （ SVM ）接続の作成などのタスクを完了しておく必要があります。

* Snapshotをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートする場合は、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にSVMを割り当てておく必要があります。
* プリスクリプトとポストスクリプトで PowerShell スクリプトを実行する場合は、 web.config ファイルで usePowershellProcessforScripts パラメータの値を true に設定する必要があります。
+
デフォルト値は false です。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"]。


.このタスクについて
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義されます。
+
必要に応じて、このパスを変更し、SMcoreサービスを再起動できます。セキュリティのためにデフォルトパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用してキーの値を表示することができます。set APIはサポートされません。

* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。





NOTE: プライマリSnapLock設定はSnapCenterバックアップポリシーで管理され、セカンダリSnapLock設定はONTAPで管理されます。

.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. 既存のポリシーを使用できるかどうかを確認するには、ポリシー名を選択し、 [* 詳細 * ] をクリックします。
+
既存のポリシーを確認したあと、次のいずれかを実行できます。

+
** 既存のポリシーを使用する。
** 既存のポリシーをコピーしてポリシー設定を変更する。
** 新しいポリシーを作成します。


. 新しいポリシーを作成するには、 * New * をクリックします。
. [ 名前 ] ページで、ポリシー名と概要 を入力します。
. [ バックアップオプション ] ページで、次のタスクを実行します。
+
.. バックアップ設定を選択します。
+
|===
| オプション | 説明 


 a| 
File System Consistent Backup の略
 a| 
ファイルシステムが配置されたディスクドライブをバックアップ処理の開始前に SnapCenter で休止し、バックアップ処理の終了後に再開する場合は、このオプションを選択します。



 a| 
ファイルシステムのクラッシュ整合性バックアップ
 a| 
ファイルシステムが配置されたディスクドライブを SnapCenter で休止しない場合は、このオプションを選択します。

|===
.. スケジュール頻度（ポリシータイプ）を選択します。
+
ポリシーではバックアップの頻度のみを指定します。バックアップの具体的なスケジュールは、リソースグループで定義します。したがって、複数のリソースグループで同じポリシーとバックアップ頻度を使用している場合でも、別々のバックアップスケジュールを設定できます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間（ DST ）中はスケジュールはトリガーされません。



. [ 保持 ] ページで ' オン・デマンド・バックアップおよび選択した各スケジュール頻度の保持設定を指定します
+
|===
| オプション | 説明 


 a| 
保持する Snapshot コピーの総数
 a| 
SnapCenterストアのSnapshot数を指定してからSnapshotを自動的に削除する場合は、このオプションを選択します。



 a| 
より古い Snapshot コピーを削除します
 a| 
SnapCenter がバックアップコピーを保持する日数を指定する場合は、このオプションを選択します。指定した日数を過ぎると削除されます。



 a| 
Snapshotコピーのロック期間
 a| 
[Snapshot locking period]を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。

|===
+

IMPORTANT: 保持数を2以上に設定してください。保持数の最小値は2です。

+

NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持期間を基盤となる ONTAP バージョンの値よりも大きい値に設定すると、バックアップが失敗します。

. Replication （レプリケーション）ページで、セカンダリストレージシステムへのレプリケーションを指定します。
+
|===
| フィールド | 手順 


 a| 
* ローカル Snapshot コピー作成後に SnapMirror を更新 *
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（ SnapMirror ）は、このオプションを選択します。

このオプションは、SnapSnapMirrorのアクティブな同期に対して有効にする必要があります。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

を参照してください link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["トポロジページで関連するバックアップとクローンを表示します"]。



 a| 
Snapshot コピーの作成後に SnapVault を更新します
 a| 
ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

SnapLockがONTAPのセカンダリ（SnapLock Vault）にのみ設定されている場合は、[Topology]ページの[Refresh]ボタンをクリックすると、ONTAPから取得したセカンダリのロック期間が更新されます。

SnapLock Vaultの詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["SnapshotコピーをバックアップデスティネーションのWORM状態にコミットします"]



 a| 
セカンダリポリシーのラベル
 a| 
Snapshot ラベルを選択します。

選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。


NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



 a| 
エラー再試行回数
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。

. スクリプトページで、 SnapCenter サーバでバックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと、 SnapCenter がスクリプトの実行を待機してからタイムアウトするまでの時間を入力します。
+
たとえば、 SNMP トラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathに対する相対パスでなければなりません。

. 概要を確認し、 [ 完了 ] をクリックします。

