---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: SnapCenter を使用して、 Windows ファイルシステムのバックアップをクローニングすることができます。誤って削除または変更された単一のファイルのコピーが必要な場合は、バックアップをクローニングし、クローン内のファイルを使用できます。 
---
= Windows ファイルシステムのバックアップからのクローニング
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して、 Windows ファイルシステムのバックアップをクローニングすることができます。誤って削除または変更された単一のファイルのコピーが必要な場合は、バックアップをクローニングし、クローン内のファイルを使用できます。

* 必要なもの *

* データ保護の準備として、ホストの追加、リソースの特定、 Storage Virtual Machine （ SVM ）接続の作成などのタスクを完了しておく必要があります。
* ファイルシステムのバックアップを作成しておく必要があります。
* ボリュームをホストするアグリゲートが Storage Virtual Machine （ SVM ）に割り当てられたアグリゲートリストに含まれていることを確認する必要があります。
* リソースグループはクローニングできません。クローニングできるのは、個々のファイルシステムのバックアップだけです。
* VMDK ディスクを使用した仮想マシン上にあるバックアップは、 SnapCenter で物理サーバにクローニングできません。
* 共有 LUN やクラスタ共有ボリューム（ CSV ） LUN などの Windows クラスタをクローニングした場合、クローンは指定したホストに専用の LUN として格納されます。
* クローニング処理では、ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* クローンは、アグリゲートのホームノード以外のノードには作成できません。
* Windows ファイルシステムのクローニング処理では、定期的なスケジュール（クローンライフサイクル）は設定できません。バックアップのクローニングはオンデマンドでのみ実行できます。
* クローンが含まれている LUN を新しいボリュームに移動すると、 SnapCenter でそのクローンをサポートできなくなります。たとえば、 SnapCenter を使用してそのクローンを削除することはできません。
* 環境間でクローンを作成することはできません。たとえば、物理ディスクから仮想ディスクへのクローニングやその逆のクローニングがあります。


* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. リソースページで、リストから * ファイルシステム * を選択します。
. ホストを選択します。
+
リソースが保護されている場合は、トポロジビューが自動的に表示されます。

. リソースのリストからクローニングするバックアップを選択し、クローンアイコンをクリックします。
. [ オプション ] ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
クローンサーバ
 a| 
クローンを作成するホストを選択します。



 a| 
「 Auto assign mount point 」または「 Auto assign volume mount point under path 」
 a| 
マウントポイントを自動的に割り当てるか、パスを指定してボリュームマウントポイントを自動的に割り当てるかを選択します。

Auto assign volume mount point under path ：マウントポイントを作成する特定のディレクトリのパスを指定できます。このオプションを選択する場合は、ディレクトリが空であることを事前に確認しておく必要があります。ディレクトリにバックアップが格納されている場合、そのバックアップはマウント処理後に無効な状態になります。



 a| 
アーカイブの場所
 a| 
セカンダリバックアップをクローニングする場合にアーカイブの場所を選択します。

|===
. スクリプトページで、実行するプリスクリプトまたはポストスクリプトを指定します。
. 概要を確認し、 [ 完了 ] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。

