---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: SnapCenter を使用して、 Windows ファイルシステムのバックアップをクローニングすることができます。誤って削除または変更された単一のファイルのコピーが必要な場合は、バックアップをクローニングし、クローン内のファイルを使用できます。 
---
= Windowsファイルシステムのバックアップからのクローニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して、 Windows ファイルシステムのバックアップをクローニングすることができます。誤って削除または変更された単一のファイルのコピーが必要な場合は、バックアップをクローニングし、クローン内のファイルを使用できます。

.開始する前に
* データ保護の準備として、ホストの追加、リソースの特定、Storage Virtual Machine（SVM）接続の作成などのタスクを完了しておく必要があります。
* ファイルシステムのバックアップを作成しておく必要があります。
* ボリュームをホストするアグリゲートがStorage Virtual Machine（SVM）の割り当て済みアグリゲートリストに含まれている必要があります。
* リソースグループはクローニングできません。クローニングできるのは、個々のファイルシステムのバックアップだけです。
* VMDK ディスクを使用した仮想マシン上にあるバックアップは、 SnapCenter で物理サーバにクローニングできません。
* 共有LUNやクラスタ共有ボリューム（CSV）LUNなどのWindowsクラスタをクローニングすると、クローンは指定したホストに専用のLUNとして格納されます。
* クローニング処理では、ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* アグリゲートのホームノード以外のノードにクローンを作成することはできません。
* Windowsファイルシステムでは、定期的なクローニング（クローンライフサイクル）処理のスケジュールを設定することはできません。バックアップのクローニングはオンデマンドでのみ実行できます。
* クローンが含まれている LUN を新しいボリュームに移動すると、 SnapCenter でそのクローンをサポートできなくなります。たとえば、 SnapCenter を使用してそのクローンを削除することはできません。
* 複数の環境間でのクローニングは実行できません。たとえば、物理ディスクから仮想ディスクへ、またはその逆のクローンを作成します。


.タスクの内容
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

* ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。


.手順
. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. リソースページで、リストから * ファイルシステム * を選択します。
. ホストを選択します。
+
リソースが保護されている場合は、トポロジビューが自動的に表示されます。

. リソースリストからクローニングするバックアップを選択し、クローニングアイコンをクリックします。
. [ オプション ] ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
クローンサーバ
 a| 
クローンを作成するホストを選択します。



 a| 
「 Auto assign mount point 」または「 Auto assign volume mount point under path 」
 a| 
マウントポイントを自動的に割り当てるか、パスを使用してボリュームマウントポイントを自動的に割り当てるかを選択します。

Auto assign volume mount point under path ：マウントポイントを作成する特定のディレクトリのパスを指定できます。このオプションを選択する場合は、ディレクトリが空であることを事前に確認しておく必要があります。ディレクトリにバックアップが格納されている場合、そのバックアップはマウント処理後に無効な状態になります。



 a| 
アーカイブの場所
 a| 
セカンダリバックアップをクローニングする場合は、アーカイブの場所を選択します。

|===
. スクリプトページで、実行するプリスクリプトまたはポストスクリプトを指定します。
+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。

