---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: SnapCenter を使用すると、ファイルシステムのバックアップをリストアできます。ファイルシステムのリストアは、指定したバックアップのすべてのデータをファイルシステムの元の場所にコピーする複数の段階からなるプロセスです。 
---
= Windowsファイルシステムのバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用すると、ファイルシステムのバックアップをリストアできます。ファイルシステムのリストアは、指定したバックアップのすべてのデータをファイルシステムの元の場所にコピーする複数の段階からなるプロセスです。

.開始する前に
* ファイルシステムをバックアップしておく必要があります。
* ファイルシステムに対してバックアップ処理などのスケジュールされた処理が現在実行中の場合は、リストア処理を開始する前にその処理をキャンセルする必要があります。
* ファイルシステムのバックアップは元の場所にのみリストアでき、別のパスにはリストアできません。
+
リストアされたファイルシステムはファイルシステムの元の場所のデータを上書きするため、バックアップから単一のファイルをリストアすることはできません。ファイルシステムのバックアップから単一ファイルをリストアするには、バックアップをクローニングし、クローン内のファイルにアクセスする必要があります。

* システムボリュームまたはブートボリュームを復元することはできません。
* SnapCenter では、クラスタグループをオフラインにすることなく、 Windows クラスタのファイルシステムをリストアできます。


.タスクの内容
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

* SnapMirrorのアクティブな同期のリストア処理では、プライマリの場所からバックアップを選択する必要があります。
* ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。


.手順
. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. リソースのリストをフィルタリングするには、 [ ファイルシステム（ File System ） ] および [ リソースグループ（ Resource Group ） ] オプションを選択します。
. リストからリソースグループを選択し、 * リストア * をクリックします。
. バックアップページで、プライマリストレージシステムとセカンダリストレージシステムのどちらからリストアするかを選択し、リストアするバックアップを選択します。
. リストアウィザードでオプションを選択します。
. リストア処理の実行前や実行後に SnapCenter で実行するプリスクリプトやポストスクリプトのパスと引数を入力できます。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信などを行うスクリプトを実行できます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

. [ 通知 ] ページで、次のいずれかのオプションを選択します。
+
|===
| フィールド | 操作 


 a| 
SnapCenter サーバイベントをストレージシステムの syslog に記録します
 a| 
SnapCenter サーバのイベントをストレージ・システムの syslog に記録する場合は、このオプションを選択します。



 a| 
失敗した処理に関するAutoSupport通知をストレージシステムに送信
 a| 
失敗した処理に関する情報を AutoSupport を使用してネットアップに送信する場合は、このオプションを選択します。



 a| 
Eメール設定
 a| 
バックアップのリストア後に受信者にメールを送信するには、「 * Always * 」、「 * On Failure * 」、または「 * on failure or warning * 」を選択します。SMTPサーバ、Eメールのデフォルトの件名、送信先と送信元のEメールアドレスを入力します。

|===
. 概要を確認し、 [ 完了 ] をクリックします。
. 操作の進行状況を監視するには、 * Monitor * > * Jobs * をクリックします。



IMPORTANT: リストアしたファイルシステムにデータベースが含まれている場合は、データベースもリストアする必要があります。データベースをリストアしないと、データベースが無効な状態になっている可能性があります。データベースのリストアの詳細については、そのデータベースのデータ保護ガイドを参照してください。
