---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: 'SnapCenterの[ホストの追加]ページを使用して、Windowsホストを追加できます。SnapCenter Plug-in for Microsoft Windowsは、指定したホストに自動的にインストールされます。プラグインのインストールには、この方法を推奨します。ホストの追加とプラグインのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストを追加してSnapCenter Plug-in for Microsoft Windowsをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[ホストの追加]ページを使用して、Windowsホストを追加できます。SnapCenter Plug-in for Microsoft Windowsは、指定したホストに自動的にインストールされます。プラグインのインストールには、この方法を推奨します。ホストの追加とプラグインのインストールは、ホストごとまたはクラスタごとに実行できます。

.開始する前に
* SnapCenter ServerホストのオペレーティングシステムがWindows 2019で、プラグインホストのオペレーティングシステムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windowsホストにプラグインをインストールするときに、組み込みでないクレデンシャルを指定した場合やユーザがローカルワークグループに属している場合は、ホストのUACを無効にする必要があります。
* SnapCenter ユーザーは 'Windows Server のサービスとしてログオンロールに追加する必要があります
* メッセージキューサービスがrunning状態であることを確認する必要があります。
* グループ管理サービスアカウント（gMSA）を使用する場合は、管理Privilegesを使用してgMSAを設定する必要があります。
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016以降でのWindowsファイルシステム用のグループ管理サービスアカウントの設定"]



.タスクの内容
* SnapCenterサーバをプラグインホストとして別のSnapCenterサーバに追加することはできません。
* Windowsプラグイン
+
** Microsoft Windows
** Microsoft Exchange Server
** Microsoft SQL Server
** SAP HANA
** カスタムプラグイン


* クラスタへのプラグインのインストール
+
クラスタ（WSFC、Oracle RAC、またはExchange DAG）にプラグインをインストールすると、クラスタのすべてのノードにインストールされます。

* Eシリーズストレージ
+
E シリーズストレージに接続された Windows ホストに Plug-in for Windows をインストールすることはできません。




NOTE: SnapCenterでは、すでにワークグループに属していて別のドメインに変更されたホスト（プラグインホスト）をSnapCenterに追加することはできません。その逆も同様です。同じホストを追加する場合は、SnapCenterからホストを削除して再度追加する必要があります。

.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] が選択されていることを確認します。
. [追加]*をクリックします。
. [Hosts]ページで、次の手順を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
Windows * タイプのホストを選択します。

SnapCenter Server によってホストが追加され、 Plug-in for Windows がまだホストにインストールされていない場合はインストールされます。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。

SnapCenter は、 DNS の適切な設定によって異なります。そのため、Fully Qualified Domain Name（FQDN；完全修飾ドメイン名）を入力することを推奨します。

次のいずれかのIPアドレスまたはFQDNを入力できます。

** スタンドアロンホスト
** Windows Serverフェイルオーバークラスタリング（WSFC）
+
SnapCenter を使用してホストを追加する際、ホストがサブドメインの一部である場合は、 FQDN を指定する必要があります。





 a| 
クレデンシャル
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

ユーザ名、ドメイン、ホストタイプなどのクレデンシャルの詳細は、指定したクレデンシャル名にカーソルを合わせると表示されます。


NOTE: 認証モードは、[ホスト追加]ウィザードで指定するホストタイプによって決まります。

|===
. [Select Plug-ins to Install]セクションで、インストールするプラグインを選択します。
+
新規導入の場合は、プラグインパッケージは表示されません。

. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は8145です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
デフォルトのパスはC：\Program Files\NetApp\SnapCenterです。

必要に応じてパスをカスタマイズできます。SnapCenter Plug-ins Package for Windowsの場合、デフォルトパスはC：\Program Files\NetApp\SnapCenterです。ただし、必要に応じて、デフォルトのパスをカスタマイズできます。



 a| 
クラスタ内のすべてのホストを追加
 a| 
WSFC内のすべてのクラスタノードを追加するには、このチェックボックスをオンにします。



 a| 
インストール前チェックをスキップ
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行
 a| 
グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行する場合は、このチェックボックスを選択します。

gMSA 名を _domainName\accountName$_ の形式で指定します。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [Submit （送信） ] をクリックします。
+
[事前チェックをスキップ]*チェックボックスを選択していない場合、プラグインをインストールするための要件を満たしているかどうかを確認するためにホストが検証されます。 ディスクスペース、RAM、PowerShellのバージョン、 ネットバージョンと場所は、最小要件に照らして検証されます。最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたはRAMに関連している場合は、WebAppにあるweb.configファイルを更新してデフォルト値を変更できます `C:\Program Files\NetApp\SnapCenter` 。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HAセットアップでweb.configファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. インストールの進行状況を監視します。

