---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: SnapCenter のホストの追加ページを使用して、 Windows ホストを追加できます。指定したホストには、 SnapCenter Plug-in for Microsoft Windows が自動的にインストールされます。これはプラグインのインストールに推奨される方法です。ホストを追加してプラグインをインストールするには、個々のホストまたはクラスタを使用します。 
---
= ホストを追加し、 SnapCenter Plug-in for Microsoft Windows をインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter のホストの追加ページを使用して、 Windows ホストを追加できます。指定したホストには、 SnapCenter Plug-in for Microsoft Windows が自動的にインストールされます。これはプラグインのインストールに推奨される方法です。ホストを追加してプラグインをインストールするには、個々のホストまたはクラスタを使用します。

.作業を開始する前に
* SnapCenter ServerホストのオペレーティングシステムがWindows 2019で、プラグインホストのオペレーティングシステムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* SnapCenter ユーザーは 'Windows Server のサービスとしてログオンロールに追加する必要があります
* メッセージキューイングサービスが実行中状態であることを確認する必要があります。
* Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用している場合は、管理者権限を持つ gMSA を設定する必要があります。
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016以降でWindowsファイルシステム用にグループ管理サービスアカウントを設定する"]



.このタスクについて
* SnapCenter サーバをプラグインホストとして別の SnapCenter サーバに追加することはできません。
* Windows プラグイン
+
** Microsoft Windows の場合
** Microsoft Exchange Server の略
** Microsoft SQL Server の場合
** SAP HANA のサポート
** カスタムプラグイン


* クラスタへのプラグインのインストール
+
クラスタ（ WSFC 、 Oracle RAC 、または Exchange DAG ）にプラグインをインストールすると、クラスタのすべてのノードにインストールされます。

* E-Series ストレージ
+
E シリーズストレージに接続された Windows ホストに Plug-in for Windows をインストールすることはできません。




NOTE: SnapCenterでは、すでにワークグループに属していて別のドメインに変更されたホスト（プラグインホスト）をSnapCenterに追加することはできません。その逆も同様です。
同じホストを追加する場合は、SnapCenterからホストを削除して再度追加する必要があります。

.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] が選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の手順を実行します。
+
|===
| フィールド | 手順 


 a| 
ホストタイプ
 a| 
Windows * タイプのホストを選択します。

SnapCenter Server によってホストが追加され、 Plug-in for Windows がまだホストにインストールされていない場合はインストールされます。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。

SnapCenter は、 DNS の適切な設定によって異なります。そのため、ベストプラクティスは Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を入力することです。

次のいずれかの IP アドレスまたは FQDN を入力できます。

** スタンドアロンホスト
** Windows Server フェイルオーバークラスタリング（ WSFC ）
+
SnapCenter を使用してホストを追加する際、ホストがサブドメインの一部である場合は、 FQDN を指定する必要があります。





 a| 
クレデンシャル
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

ユーザ名、ドメイン、ホストタイプなど、クレデンシャルの詳細は、指定したクレデンシャル名にカーソルを合わせると表示されます。


NOTE: 認証モードは、ホストの追加ウィザードで指定したホストタイプによって決まります。

|===
. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
+
新規導入の場合、プラグインパッケージは表示されません。

. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 手順 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は 8145 です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
デフォルトパスは C ： \Program Files\NetApp\SnapManager です。

必要に応じて、パスをカスタマイズできます。SnapCenter Plug-ins Package for Windows のデフォルトパスは C ： \Program Files\NetApp\SnapManager です。ただし、必要に応じて、デフォルトパスをカスタマイズできます。



 a| 
クラスタ内のすべてのホストを追加します
 a| 
WSFC のすべてのクラスタノードを追加するには、このチェックボックスを選択します。



 a| 
インストール前のチェックをスキップします
 a| 
プラグインを手動でインストール済みで、プラグインのインストール要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
プラグインサービスを実行するには、 Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用します
 a| 
グループ管理サービスアカウント（ GMSA ）を使用してプラグインサービスを実行する場合は、このチェックボックスをオンにします。

gMSA 名を _domainName\accountName$_ の形式で指定します。


NOTE: gMSA は、 SnapCenter Plug-in for Windows サービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [Submit （送信） ] をクリックします。
+
「 * 事前確認をスキップ」チェックボックスを選択していない場合、プラグインのインストール要件をホストが満たしているかどうかが検証されます。ディスクスペース、 RAM 、 PowerShell のバージョン、 .NET のバージョン、および場所が、最小要件に照らして検証されます。最小要件を満たしていない場合は、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたは RAM に関連している場合は、「 C ： \Program Files\NetApp\SnapCenter ’ WebApp 」にある web.config ファイルを更新して、デフォルト値を変更できます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HA セットアップで web.config ファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. インストールの進行状況を監視します。

