---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: バックアップを作成する前にバックアップ戦略を定義しておくと、ファイルシステムの正常なリストアやクローニングに必要なバックアップを作成できます。バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。 
---
= Windowsファイルシステムのバックアップ戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを作成する前にバックアップ戦略を定義しておくと、ファイルシステムの正常なリストアやクローニングに必要なバックアップを作成できます。バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。

SLAは、期待されるサービスレベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RTOは、サービスの停止後にビジネスプロセスをリストアする必要がある時間です。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義します。SLA、RTO、RPOは、データ保護戦略に影響します。



== Windowsファイルシステムのバックアップスケジュール

バックアップ頻度はポリシーで指定され、バックアップスケジュールはリソースグループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは1時間ごとにバックアップし、使用頻度の低いリソースは1日に1回バックアップすることもできます。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAは、期待されるサービスレベルと、サービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOはデータ保護戦略に影響します。

使用頻度の高いリソースであっても、フルバックアップを1日に1~2回以上実行する必要はありません。

バックアップスケジュールには、次の2つの部分があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインでは _ schedule type__ と呼ばれます。たとえば、毎時、毎日、毎週、または毎月としてバックアップ頻度を設定したり、「 * なし」を指定してオンデマンドのみのポリシーにすることができます。ポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行されるタイミング）は、リソースグループ設定の一部です。たとえば、リソースグループのポリシーで週単位のバックアップが設定されている場合は、毎週木曜日の午後10時にバックアップが実行されるようにスケジュールを設定できます。リソースグループのスケジュールにアクセスするには、 * リソース * > * リソースグループ * をクリックします。





== Windowsフアイルシステムニヒツヨウナハツクアツフノスウ

必要なバックアップの数を決定する要因には、Windowsファイルシステムのサイズ、使用されているボリュームの数、ファイルシステムの変更率、サービスレベルアグリーメント（SLA）などがあります。



== Windowsファイルシステムのバックアップ命名規則

Windowsファイルシステムのバックアップでは、Snapshotのデフォルトの命名規則が使用されます。デフォルトのバックアップ命名規則では、Snapshot名にタイムスタンプが追加されるため、コピーがいつ作成されたかを確認できます。

Snapshotでは、次のデフォルトの命名規則が使用されます。resourcegroupname_hostname_timestamp

バックアップリソースグループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* `dts1` は、リソースグループ名です。
* `mach1x88` はホスト名です。
* `03-12-2016_23.17.26` は日付とタイムスタンプです。


バックアップの作成時に、バックアップを識別するためのタグを追加することもできます。一方、カスタマイズしたバックアップ命名規則を使用する場合は、バックアップ処理の完了後にバックアップの名前を変更する必要があります。



== バックアップ保持オプション

バックアップコピーを保持する日数を選択することも、保持するバックアップコピーの数（ONTAPの最大コピー数255）を指定することもできます。たとえば、組織で、10日分のバックアップコピーや130個のバックアップコピーを保持する必要があるとします。

ポリシーの作成時に、バックアップタイプとスケジュールタイプの保持オプションを指定できます。

SnapMirrorレプリケーションを設定すると、デスティネーションボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、保持されているバックアップの保持ラベルがスケジュールタイプと一致する場合には、バックアップを削除します。リソースまたはリソースグループのスケジュールタイプを変更した場合、古いスケジュールタイプラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップコピーを長期にわたって保持する場合は、SnapVaultバックアップを使用する必要があります。
