---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: SnapCenter Plug-in for Microsoft Windows を複数のホストに一度にインストールする場合は、 Install-SmHostPackage PowerShell コマンドレットを使用します。 
---
= PowerShellコマンドレットを使用した、複数のリモートホストへのSnapCenter Plug-in for Microsoft Windowsのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft Windowsを複数のホストに一度にインストールする場合は、PowerShellコマンドレットを使用し `Install-SmHostPackage` ます。

プラグインをインストールする各ホストで、ローカル管理者の権限を持つドメインユーザとして SnapCenter にログインしている必要があります。

.手順
. PowerShellを起動します。
. SnapCenterサーバホストで、コマンドレットを使用してセッションを確立し `Open-SmConnection` 、クレデンシャルを入力します。
. コマンドレットと必要なパラメータを使用して、スタンドアロンホストまたはクラスタをSnapCenterに追加します `Add-SmHost` 。
+
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。

. コマンドレットと必要なパラメータを使用して、複数のホストにプラグインをインストールし `Install-SmHostPackage` ます。
+
オプションは、プラグインを手動でインストールしたあとに、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合に使用でき `-skipprecheck` ます。


