---
permalink: protect-scw/task_determine_resource_availability_for_windows_file_systems.html 
sidebar: sidebar 
keywords: availability 
summary: リソースとは、インストールしたプラグインで管理されるファイルシステム内のLUNや類似のコンポーネントのことです。これらのリソースをリソースグループに追加すると、複数のリソースに対してデータ保護ジョブを実行できますが、その前に使用可能なリソースを特定しておく必要があります。使用可能なリソースを検出すると、プラグインのインストールが正常に完了したことも確認されます。 
---
= Windowsファイルシステムの使用可能なリソースを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースとは、インストールしたプラグインで管理されるファイルシステム内のLUNや類似のコンポーネントのことです。これらのリソースをリソースグループに追加すると、複数のリソースに対してデータ保護ジョブを実行できますが、その前に使用可能なリソースを特定しておく必要があります。使用可能なリソースを検出すると、プラグインのインストールが正常に完了したことも確認されます。

.開始する前に
* SnapCenterサーバのインストール、ホストの追加、Storage Virtual Machine（SVM）接続の作成、クレデンシャルの追加などのタスクを完了しておく必要があります。
* ファイルがVMware RDM LUNまたはVMDKにある場合は、SnapCenter Plug-in for VMware vSphereを導入してSnapCenterに登録する必要があります。詳細については、を参照してください https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphereのドキュメント"^]。


.手順
. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. リソースページで、リストから * ファイルシステム * を選択します。
. ホストを選択してリソースのリストをフィルタリングし、 * リソースの更新 * をクリックします。
+
新しく追加、名前変更、または削除されたファイルシステムは、SnapCenterサーバインベントリに更新されます。

+

IMPORTANT: SnapCenter以外でデータベースの名前が変更された場合は、リソースを更新する必要があります。


