---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。 
---
= Windowsファイルシステムのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して Windows ファイルシステムをバックアップする前に、リソースの新しいバックアップポリシーを作成することができます。また、リソースグループの作成時やリソースのバックアップ時に新しいバックアップポリシーを作成することもできます。

.開始する前に
* バックアップ戦略を定義しておく必要があります。 link:task_define_a_backup_strategy_for_windows_file_systems.html["詳細"^]
* データ保護の準備が完了している必要があります。
+
データ保護の準備として、SnapCenterのインストール、ホストの追加、リソースの検出、Storage Virtual Machine（SVM）接続の作成などのタスクを完了する必要があります。

* Snapshotをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートする場合は、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にSVMを割り当てておく必要があります。
* プリスクリプトとポストスクリプトでPowerShellスクリプトを実行する場合は、web.configファイルでusePowershellProcessforScriptsパラメータの値をtrueに設定する必要があります。
+
デフォルト値はfalseです。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、を参照してください https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"]。


.タスクの内容
* scripts_pathは、プラグインホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、api/4.7/configsettingsを介してスワッガーから表示できます

+
GET APIを使用すると、キーの値を表示できます。Set APIはサポートされていません。

* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。




.手順
. 左側のナビゲーションペインで、*[設定]*を選択します。
. [設定]ページで、*[ポリシー]*を選択します。
. [New]*を選択します。
. [Name]ページで、ポリシーの名前と詳細を入力します。
. [Backup and Replication]ページで、次のタスクを実行します。
+
.. バックアップ設定を選択します。
+
|===
| オプション | 説明 


 a| 
ファイルシステム整合性バックアップ
 a| 
ファイルシステムが配置されたディスクドライブをバックアップ処理の開始前に SnapCenter で休止し、バックアップ処理の終了後に再開する場合は、このオプションを選択します。



 a| 
ファイルシステムクラッシュ整合性バックアップ
 a| 
ファイルシステムが配置されたディスクドライブを SnapCenter で休止しない場合は、このオプションを選択します。

|===
.. スケジュール頻度（ポリシータイプ）を選択します。
+
ポリシーではバックアップの頻度のみを指定します。バックアップの具体的な保護スケジュールは、リソースグループで定義します。そのため、複数のリソースグループで同じポリシーとバックアップ頻度を共有していても、バックアップスケジュールが異なる場合があります。

+

NOTE: 午前2時にスケジュールを設定している場合、夏時間（DST）中はスケジュールはトリガーされません。

.. ポリシーラベルを選択します。
+
選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。

+

NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



. [Select secondary replication options]セクションで、次のセカンダリレプリケーションオプションの一方または両方を選択します。
+
|===
| フィールド | 操作 


 a| 
ローカルSnapshotコピーの作成後にSnapMirrorを更新する
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（SnapMirror）は、このオプションを選択します。

このオプションは、SnapSnapMirrorのアクティブな同期に対して有効にする必要があります。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

を参照して link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["[Topology]ページで関連するバックアップとクローンを表示する"]



 a| 
Snapshotコピーの作成後にSnapVaultを更新
 a| 
ディスクツーディスクのバックアップレプリケーションを実行する場合は、このオプションを選択します。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

SnapLockがONTAPのセカンダリ（SnapLock Vault）にのみ設定されている場合は、[Topology]ページの[Refresh]ボタンをクリックすると、ONTAPから取得したセカンダリのロック期間が更新されます。

SnapLock Vaultの詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["SnapVaultデスティネーションでSnapshotコピーをWORM状態にコミットする"]



 a| 
エラー時の再試行回数
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。

. [Retention settings]ページで、オンデマンドバックアップおよび選択したスケジュール頻度の保持設定を指定します。
+
|===
| オプション | 説明 


 a| 
保持するSnapshotコピーの総数
 a| 
SnapCenterストアのSnapshot数を指定してからSnapshotを自動的に削除する場合は、このオプションを選択します。



 a| 
Snapshotコピーの保持期間
 a| 
SnapCenter がバックアップコピーを保持する日数を指定する場合は、このオプションを選択します。指定した日数を過ぎると削除されます。



 a| 
スナップショットコピーのロック期間
 a| 
スナップショットのロック期間を選択し、期間を日数、月数、または年数で指定します。

SnapLock保持期間は100年未満にする必要があります。

|===
+

IMPORTANT: 保持数は2以上に設定する必要があります。保持数の最小値は2です。

+

NOTE: 最大保持値は 1018 です。保持期間がONTAPバージョンでサポートされている値よりも高い値に設定されている場合、バックアップは失敗します。

. スクリプトページで、 SnapCenter サーバでバックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと、 SnapCenter がスクリプトの実行を待機してからタイムアウトするまでの時間を入力します。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信を行うスクリプトを実行できます。

+

NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。

