---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトを使用すると、データ保護ジョブの実行前または実行後に自動化を実行できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。 
---
= プリスクリプトとポストスクリプト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトを使用すると、データ保護ジョブの実行前または実行後に自動化を実行できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。



== サポートされるスクリプトタイプ

Windowsでは、次の種類のスクリプトがサポートされています。

* バッチファイル
* PowerShellスクリプト
* Perlスクリフト


UNIXでは、次の種類のスクリプトがサポートされています。

* Perlスクリフト
* Pythonスクリプト
* シェルスクリプト
+

NOTE: デフォルトのbashシェルに加えて、sh-shell、k-shell、c-shellのような他のシェルもサポートされています。





== スクリプトパス

仮想化されていないストレージシステムおよび仮想化されたストレージシステムでSnapCenter処理の一環として実行されるプリスクリプトとポストスクリプトは、すべてプラグインホストで実行されます。

* Windowsスクリプトがプラグインホストにある必要があります。



NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

* UNIXスクリプトがプラグインホスト上にある必要があります。



NOTE: スクリプトパスは実行時に検証されます。



== スクリプトを指定する場所

スクリプトはバックアップポリシーで指定されます。バックアップジョブが開始されると、ポリシーによってスクリプトがバックアップ対象のリソースに自動的に関連付けられます。バックアップポリシーの作成時に、プリスクリプトとポストスクリプトの引数を指定できます。


NOTE: 複数のスクリプトを指定することはできません。



== スクリプトのタイムアウト

デフォルトでは、タイムアウトは60秒に設定されています。タイムアウト値は変更できます。



== スクリプト出力

Windowsプリスクリプトとポストスクリプトの出力ファイルのデフォルトのディレクトリは、Windows\System32です。

UNIXのプリスクリプトとポストスクリプトのデフォルトの場所はありません。出力ファイルは任意の場所にリダイレクトできます。
