---
permalink: concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter ディザスタリカバリ機能を使用すると、リソースの破損やサーバクラッシュなどの災害が発生した場合に SnapCenter サーバをリカバリできます。 
---
= ディザスタリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ディザスタリカバリ機能を使用すると、リソースの破損やサーバクラッシュなどの災害が発生した場合に SnapCenter サーバをリカバリできます。SnapCenter リポジトリ、サーバスケジュール、およびサーバ構成コンポーネントをリカバリできます。

また、 SnapCenter Plug-in for SQL Server および SnapCenter Plug-in for SQL Server ストレージをリカバリすることもできます。

ディザスタリカバリ（ DR ）のタイプは次のとおりです。

* * SnapCenter サーバ DR *
+
SnapCenter サーバのデータは、 SnapCenter サーバでプラグインが追加されているか管理されているかに関係なく、バックアップおよびリカバリされます。

+
セカンダリSnapCenter サーバは、プライマリSnapCenter サーバと同じインストールディレクトリと同じポートにインストールする必要があります。

+
多要素認証（MFA）の場合は、SnapCenter サーバに対してDRリストアが実行されたあとに、ブラウザのすべてのタブを閉じてブラウザを開き直し、再度ログインします。これにより、既存またはアクティブなセッションCookieがクリアされ、正しい設定データが更新されます。

+
SnapCenter のディザスタリカバリ機能では、 REST API を使用して SnapCenter サーバをバックアップします。

+
link:../sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html["SnapCenter サーバのディザスタリカバリ用の REST API のワークフロー"]

* * SnapCenter プラグインと Storage DR *
+
DR は、 SnapCenter Plug-in for SQL Server でのみサポートされます。SnapCenter Plug-in for SQL Server がダウンしたときに、別の SQL ホストに切り替えてデータをリカバリする手順はいくつかあります。

+
link:../protect-scsql/task_disaster_recovery_scsql.html["SnapCenter Plug-in for SQL Server のディザスタリカバリ"]



SnapCenter は、 ONTAP の SnapMirror テクノロジを使用してデータをレプリケートします。DR 用にセカンダリサイトにデータをレプリケートして同期し続けることができます。フェイルオーバーは、 SnapMirror のレプリケーション関係を解除することによって開始できます。フェイルバック中に、同期を反転させて DR サイトのデータをプライマリサイトにレプリケートすることができます。
