---
permalink: concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery 
summary: SnapCenterディザスタリカバリ機能を使用すると、リソースの破損やサーバのクラッシュなどの災害が発生した場合にSnapCenterサーバをリカバリできます。 
---
= SnapCenter ディザスタリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ディザスタリカバリ（DR）機能を使用すると、リソースの破損やサーバのクラッシュなどの災害が発生した場合にSnapCenter サーバをリカバリできます。SnapCenterリポジトリ、サーバスケジュール、およびサーバ構成コンポーネントをリカバリできます。SnapCenter Plug-in for SQL ServerおよびSnapCenter Plug-in for SQL Serverストレージをリカバリすることもできます。

ここでは、SnapCenter での2種類のディザスタリカバリ（DR）について説明します。

.SnapCenter サーバDR
* SnapCenter サーバのデータはバックアップされ、SnapCenter サーバにプラグインを追加したり、管理したりすることなくリカバリできます。
* セカンダリSnapCenterサーバは、プライマリSnapCenterサーバと同じインストールディレクトリと同じポートにインストールする必要があります。
* 多要素認証（MFA）の場合、SnapCenter サーバDR中にブラウザのすべてのタブを閉じ、ブラウザを再度開いて再度ログインします。これにより、既存またはアクティブなセッションCookieがクリアされ、正しい設定データが更新されます。
* SnapCenterのディザスタリカバリ機能では、REST APIを使用してSnapCenterサーバをバックアップします。を参照して link:../tech-refresh/task_tech_refresh_server_host.html["SnapCenterサーバのディザスタリカバリ用のREST APIワークフロー"]
* 監査設定関連の構成ファイルは、リストア処理後にDRバックアップにもDRサーバにもバックアップされません。監査ログの設定を手動で繰り返す必要があります。


.SnapCenter プラグインとストレージDR
DRはSnapCenter Plug-in for SQL Serverでのみサポートされます。SnapCenter Plug-in for SQL Serverが停止したら、別のSQLホストに切り替えて、いくつかの手順を実行してデータをリカバリします。を参照して link:../protect-scsql/task_disaster_recovery_scsql.html["SnapCenter Plug-in for SQL Serverのディザスタリカバリ"]

SnapCenterでは、ONTAP SnapMirrorテクノロジを使用してデータをレプリケートします。DR用にセカンダリサイトにデータをレプリケートし、同期を維持するために使用できます。フェイルオーバーは、SnapMirrorのレプリケーション関係を解除することで開始できます。フェイルバック中は同期を元に戻し、DRサイトのデータをプライマリサイトにレプリケートできます。
