---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトにより、データ保護ジョブの前後の処理を自動化できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。 
---
= プリスクリプトとポストスクリプト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトにより、データ保護ジョブの前後の処理を自動化できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。



== サポートされているスクリプトタイプ

次のタイプのスクリプトがサポートされています。

* バッチファイル
* PowerShell スクリプト
* Perl スクリプト




== スクリプトパス

プラグインホストで、非仮想化ストレージシステムおよび仮想ストレージシステム上で SnapCenter 処理の一部として実行されるすべてのプリスクリプトとポストスクリプトが実行されます。そのため、スクリプトはプラグインホスト、またはプラグインホストからアクセス可能な SMB 共有に配置する必要があります。


NOTE: スクリプトパスは、スクリプト実行時に検証されます。



== スクリプトを指定する場所

スクリプトはバックアップポリシーに指定します。バックアップジョブが開始されると、ポリシーによってスクリプトがバックアップ対象のリソースに自動的に関連付けられます。バックアップポリシーを作成する際には、プリスクリプトとポストスクリプトの引数を指定できます。

複数のスクリプトを指定するには、スクリプトパスの入力後に * Enter キーを押し、スクリプトごとに改行します。セミコロン（ ; ）は使用できません。プリスクリプトとポストスクリプトをそれぞれ複数指定できます。1 つのスクリプトをプリスクリプトとポストスクリプトの両方として作成し、そのスクリプトから他のスクリプトを呼び出すことができます。



== スクリプトのタイムアウト

バックアップスクリプトのタイムアウトは 15 分です。この値は変更できません。



== スクリプトの出力

プリスクリプトとポストスクリプトの出力ファイルのデフォルトディレクトリは、 Windows\System32 です。
