---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトにより、データ保護ジョブの前後の処理を自動化できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。 
---
= プリスクリプトとポストスクリプト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カスタムのプリスクリプトとポストスクリプトをデータ保護処理の一部として使用することができます。これらのスクリプトにより、データ保護ジョブの前後の処理を自動化できます。たとえば、データ保護ジョブのエラーや警告を自動的に通知するスクリプトを組み込むことができます。プリスクリプトとポストスクリプトを設定する前に、スクリプトを作成するための要件を理解しておく必要があります。



== サポートされているスクリプトタイプ

Windowsでは、次の種類のスクリプトがサポートされています。

* バッチファイル
* PowerShell スクリプト
* Perl スクリプト


UNIXでは、次のタイプのスクリプトがサポートされています。

* Perl スクリプト
* Pythonスクリプト
* シェルスクリプト
+

NOTE: デフォルトのbashシェルに加えて、sh-sshell、k-sshell、c-shellなどの他のシェルもサポートされています。





== スクリプトパス

プラグインホストで、非仮想化ストレージシステムおよび仮想ストレージシステム上で SnapCenter 処理の一部として実行されるすべてのプリスクリプトとポストスクリプトが実行されます。

* Windowsスクリプトはプラグインホストに配置する必要があります。



NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathに対する相対パスでなければなりません。

* UNIXスクリプトはプラグインホストに配置する必要があります。



NOTE: スクリプトパスは実行時に検証されます。



== スクリプトを指定する場所

スクリプトはバックアップポリシーに指定します。バックアップジョブが開始されると、ポリシーによってスクリプトがバックアップ対象のリソースに自動的に関連付けられます。バックアップポリシーを作成する際には、プリスクリプトとポストスクリプトの引数を指定できます。

Windowsの場合のみ、複数のスクリプトを指定できます。各スクリプトパスのあとに「* Enter」キーを押すと、スクリプトが1行に表示されます。セミコロン（ ; ）は使用できません。プリスクリプトとポストスクリプトをそれぞれ複数指定できます。1 つのスクリプトをプリスクリプトとポストスクリプトの両方として作成し、そのスクリプトから他のスクリプトを呼び出すことができます。


NOTE: UNIXの場合は、複数のスクリプトを指定することはできません。



== スクリプトのタイムアウト

Windowsの場合、タイムアウトは15分に設定され、変更できません。

UNIXの場合、タイムアウトはデフォルトで60秒に設定されます。タイムアウト値を変更できます。



== スクリプトの出力

Windowsのプリスクリプトとポストスクリプトの出力ファイルのデフォルトディレクトリは、Windows\System32です。

UNIXのプリスクリプトとポストスクリプトには、デフォルトの場所はありません。出力ファイルは任意の場所にリダイレクトできます。
