---
permalink: concept/reference_role_based_access_control_permissions_and_roles.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions 
summary: SnapCenter のロールベースアクセス制御（ RBAC ）では、ロールを作成して権限を追加し、そのロールにユーザやそのグループを割り当てることができます。これにより、 SnapCenter 管理者は環境を一元的に管理しながら、アプリケーション管理者はデータ保護ジョブを管理できます。SnapCenter には、事前定義されたロールと権限がいくつか付属してい 
---
= RBACの権限とロール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterのRole-Based Access Control（RBAC；ロールベースアクセス制御）を使用すると、ロールを作成して権限を割り当て、そのロールにユーザまたはユーザグループを割り当てることができます。これにより、 SnapCenter 管理者は環境を一元的に管理しながら、アプリケーション管理者はデータ保護ジョブを管理できます。SnapCenter には、事前定義されたロールと権限がいくつか付属してい



== SnapCenter ロール

SnapCenter には、次のロールがあらかじめ定義されています。これらのロールにユーザやグループを割り当てて使用できるほか、新しいロールを作成することもできます。

ロールをユーザに割り当てると、 SnapCenter Admin ロールを割り当てていない限り、そのユーザに関連するジョブだけが Jobs ページに表示されます。

* アプリケーションのバックアップとクローンの管理
* バックアップ/クローンビューア
* インフラ管理者
* SnapCenterAdmin




== SnapCenter Plug-in for VMware vSphere のロール

VM、VMDK、およびデータストアのVMと整合性のあるデータ保護を管理するために、SnapCenter Plug-in for VMware vSphereでは次のロールがvCenterで作成されます。

* SCV管理者
* SCVビュー
* SCV バックアップ
* SCV Restore （ SCV リストア）
* SCVゲストファイルのリストア


詳細については、を参照してください。 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["SnapCenter Plug-in for VMware vSphereユーザ向けのRBACのタイプ"^]

|===


| * ベストプラクティス： * SnapCenter Plug-in for VMware vSphere の処理用に ONTAP ロールを 1 つ作成し、必要な権限をすべて割り当てることを推奨します。 
|===


== SnapCenter 権限

SnapCenter から提供される権限は次のとおりです。

* リソースグループ
* ポリシー
* バックアップ
* ホスト
* ストレージ接続
* クローン
* Provision（Microsoft SQLデータベースのみ）
* ダッシュボード
* レポート
* リストア
+
** Full Volume Restore （ Custom Plug-ins のみ）


* リソース
+
管理者以外のユーザがリソース検出処理を実行する場合、管理者からプラグインの権限が求められます。

* プラグインのインストールまたはアンインストール
+

NOTE: Plug-in Installation権限を有効にする場合は、Host権限も変更して読み取りと更新を有効にする必要があります。

* 移行
* Mount（Oracleデータベースのみ）
* unmount（Oracleデータベースのみ）
* ジョブモニタ
+
Job Monitor権限を使用すると、さまざまなロールのメンバーは、割り当てられているすべてのオブジェクトに対する処理を確認できます。


