---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: SnapCenter サーバインストーラの実行ファイルを使用して、 SnapCenter サーバをアップグレードできます。 
---
= WindowsホストでのSnapCenterサーバのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバインストーラの実行ファイルを使用して、 SnapCenter サーバをアップグレードできます。

.開始する前に
* SnapCenterサーバホストにWindowsの更新プログラムが適用されていて、システムの再起動が保留されていないことが必要です。
* アップグレード処理を開始する前に、他の処理が実行されていないことを確認する必要があります。
* 実行中のジョブがないことを確認したら、SnapCenterリポジトリ（MySQL）データベースをバックアップする必要があります。これは、SnapCenterサーバおよびExchangeプラグインをアップグレードする前に推奨されます。
+
詳細については、を参照してください link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenterリポジトリのバックアップ"^]。

* SnapCenter サーバホストまたはプラグインホストで変更した SnapCenter 構成ファイルをすべてバックアップしておく必要があります。
+
SnapCenter 構成ファイルの例： SnapDrive Service.exe.config 、 SMCoreServiceHost.exe.config など。



.タスクの内容
* アップグレード中に、SQLスクリプトが実行されてNSMデータベース内のExchangeデータが更新され、DAGとホストのショートネームがFQDNに変換されます。これは、SnapCenter ServerとExchangeプラグインを併用している場合にのみ該当します。
* アップグレード処理を開始する前に、サーバホストを手動でメンテナンスモードにした場合は、アップグレード後に*[ホスト]*>*[スケジュールのアクティブ化]*をクリックして、サーバホストを手動でメンテナンスモードを終了する必要があります。
* SnapCenter Plug-in for Microsoft SQL Server、SnapCenter Plug-in for Microsoft Exchange Server、およびSnapCenter Plug-in for Microsoft Windowsでは、scripts_pathを実行するために、サーバとプラグインホストの両方をバージョン4.7にアップグレードすることを推奨します。
+
ポリシーでプリスクリプトとポストスクリプトが有効になっている既存のバックアップスケジュールと検証スケジュールの場合、バックアップ処理はアップグレード後も引き続き機能します。

+
［*ジョブの詳細*］ページで、スクリプトをscripts_pathにコピーし、ポリシーを編集してscripts_pathに対するパスを指定するように警告メッセージが表示されます。クローンライフサイクルジョブの場合は、サブジョブレベルで警告メッセージが表示されます。



.手順
. NetApp Support Siteから SnapCenter サーバインストールパッケージをダウンロードします。
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. C：\Program Files\NetApp\SnapCenter WebAppにあるweb.configのコピーを作成します。
. Windows タスクスケジュールからプラグインホストに関連する SnapCenter スケジュールをエクスポートして、アップグレードが失敗した場合にプラグインホストを使用してスケジュールをリストアできるようにします。
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. リポジトリのバックアップが設定されていない場合は、 SnapCenter MySQL データベースダンプを作成します。
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
プロンプトが表示されたら、パスワードを入力します。

. ダウンロードした.exeファイルをダブルクリックして、SnapCenterサーバのアップグレードを開始します。
+
アップグレードを開始するとすべての事前確認が実行され、最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。警告メッセージは無視してインストールを続行できます。ただし、エラーは修正する必要があります。

+

NOTE: SnapCenter では、以前のバージョンの SnapCenter Server のインストール時に提供された既存の MySQL Server リポジトリデータベースのパスワードが引き続き使用されます。

. [* アップグレード ] をクリックします。
+
どの段階でも、 *Cancel* ボタンをクリックすると、アップグレードワークフローがキャンセルされます。SnapCenter サーバを以前の状態にロールバックしません。

+
|===


| * ベストプラクティス： * SnapCenter からログアウトしてログインするか、新しいブラウザを開いて SnapCenter GUI にアクセスしてください。 
|===


.終了後
* sudoユーザを使用してプラグインをインストールする場合は、_C：\ProgramData\NetApp\SnapCenter\Package Repository\SC_UNIX_plugins_checksum.txt_にあるsha224キーをコピーして、_/etc/sudoers_fileを更新する必要があります。
* サーバホスト上のリソースの新規検出を実行する必要があります。
+
サーバホストのステータスが停止と表示されている場合は、しばらく待ってから新しい検出を実行できます。また、 *HostRefreshInterval* パラメータの値（デフォルト値は 3600 秒）を 10 分を超える任意の値に変更することもできます。

* アップグレードに失敗した場合は、失敗したインストールをクリーンアップし、以前のバージョンの SnapCenter を再インストールして、 NSM データベースを以前の状態にリストアする必要があります。
* サーバホストをアップグレードしたら、ストレージシステムを追加する前にプラグインもアップグレードする必要があります。

