---
permalink: protect-hana/concept_how_resources_resource_groups_and_policies_are_used_for_protecting_sap_hana_databases.html 
sidebar: sidebar 
keywords: SAP HANA databases 
summary: SnapCenter を使用する前に、実行するバックアップ、クローニング、およびリストアの処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、さまざまな処理のリソース、リソースグループ、およびポリシーを操作します。 
---
= SAP HANAデータベースの保護でのリソース、リソースグループ、ポリシーの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用する前に、実行するバックアップ、クローニング、およびリストアの処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、さまざまな処理のリソース、リソースグループ、およびポリシーを操作します。

* リソースとは、通常は SnapCenter でバックアップまたはクローニングする SAP HANA データベースのことです。
* SnapCenterリソースグループは、ホスト上のリソースの集まりです。
+
リソースグループに対して処理を実行すると、リソースグループに指定したスケジュールに従って、リソースグループに定義されているリソースに対してその処理が実行されます。

+
単一のリソースまたはリソースグループをオンデマンドでバックアップできます。単一のリソースおよびリソースグループに対してスケジュールされたバックアップを実行することもできます。

* ポリシーは、バックアップ頻度、レプリケーション、スクリプト、およびデータ保護処理のその他の特性を指定します。
+
リソースグループを作成するときに、そのグループのポリシーを1つ以上選択します。単一のリソースに対してオンデマンドでバックアップを実行する場合にも、ポリシーを選択できます。



リソースグループは、保護する対象と保護するタイミング（日時）を定義するものと考えてください。ポリシーは、保護方法を定義するものと考えてください。たとえば、すべてのデータベースをバックアップする場合は、ホストのすべてのデータベースを含むリソースグループを作成します。そのあとに、日次ポリシーと時間次ポリシーの2つのポリシーをリソースグループに適用できます。リソースグループを作成してポリシーを適用する際に、フルバックアップを毎日実行するようにリソースグループを設定できます。
