---
permalink: protect-hana/concept_snapcenter_plug_in_for_sap_hana_database_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter Plug-in for SAP HANA Database は、 SAP HANA データベースに対応したデータ保護管理を提供する、 NetApp SnapCenter ソフトウェアのホスト側コンポーネントです。Plug-in for SAP HANA Database は、 SnapCenter 環境での SAP HANA データベースのバックアップ、リストア、およびクローニングを自動化します。 
---
= SnapCenter Plug-in for SAP HANA Databaseの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for SAP HANA Database は、 SAP HANA データベースに対応したデータ保護管理を提供する、 NetApp SnapCenter ソフトウェアのホスト側コンポーネントです。Plug-in for SAP HANA Database は、 SnapCenter 環境での SAP HANA データベースのバックアップ、リストア、およびクローニングを自動化します。

SnapCenterは、単一コンテナとマルチテナントデータベースコンテナ（MDC）をサポートします。Plug-in for SAP HANA Databaseは、WindowsとLinuxのどちらの環境でも使用できます。HANAデータベース ホストにインストールされていないプラグインは、一元化されたホスト プラグインと呼ばれます。一元化されたホスト プラグインでは、異なるホストにまたがる複数のHANAデータベースを管理できます。

Plug-in for SAP HANA Databaseがインストールされている場合は、SnapCenterとNetApp SnapMirrorテクノロジを使用して、バックアップセットのミラーコピーを別のボリュームに作成できます。また、本プラグインをNetApp SnapVaultテクノロジとともに使用して、標準への準拠を目的としたディスクツーディスクのバックアップ・レプリケーションを実行することもできます。

Plug-in for SAP HANA Databaseは、SnapMirrorのアクティブな同期（当初はSnapMirror Business Continuity [SM-BC]としてリリース）をサポートしています。この同期機能を使用すると、サイト全体に障害が発生してもビジネスサービスの運用を継続でき、アプリケーションがセカンダリコピーを使用して透過的にフェイルオーバーできるようになります。SnapMirror Active Syncでフェイルオーバーをトリガーするために、手動操作や追加のスクリプト作成は必要ありません。
