---
permalink: protect-hana/concept_auto_discovery_of_resources_on_linux_host.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'リソースとは、SnapCenterで管理されているLinuxホスト上のSAP HANAデータベースとデータボリューム以外のボリュームです。SnapCenter Plug-in for SAP HANA Databaseプラグインをインストールすると、そのLinuxホスト上のSAP HANAデータベースが自動的に検出されて[リソース]ページに表示されます。' 
---
= Linuxホスト上のリソースの自動検出
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースとは、SnapCenterで管理されているLinuxホスト上のSAP HANAデータベースとデータボリューム以外のボリュームです。SnapCenter Plug-in for SAP HANA Databaseプラグインをインストールすると、そのLinuxホスト上のSAP HANAデータベースが自動的に検出されて[リソース]ページに表示されます。

自動検出は、次のSAP HANAリソースでサポートされています。

* 単一のコンテナ
+
プラグインのインストールまたはアップグレード後、一元化されたホストプラグインにある単一コンテナリソースは、手動で追加したリソースとして続行されます。

+
プラグインをインストールまたはアップグレードすると、SnapCenterに直接登録されているSAP HANA LinuxホストでのみSAP HANAデータベースが自動的に検出されます。

* マルチテナントデータベースコンテナ（MDC）
+
プラグインのインストールまたはアップグレード後、一元化されたホストプラグインにあるMDCリソースは、手動で追加したリソースとして続行されます。

+
SnapCenter 4.3にアップグレードしたあとも、一元化されたホストプラグインにMDCリソースを手動で追加する必要があります。

+
SnapCenterに直接登録されているSAP HANA Linuxホストの場合、プラグインをインストールまたはアップグレードすると、ホスト上のリソースの自動検出がトリガーされます。プラグインをアップグレードすると、プラグインホストに配置されていたすべてのMDCリソースについて、別のGUID形式で別のMDCリソースが自動的に検出されてSnapCenterに登録されます。新しいリソースはロック状態になります。

+
たとえば、SnapCenter 4.2では、E90MDCリソースがプラグインホストにあり、手動で登録されている場合、SnapCenter 4.3へのアップグレード後に、別のGUIDを持つ別のE90MDCリソースが検出されてSnapCenterに登録されます。



自動検出は、次の構成ではサポートされません。

* RDMとVMDKのレイアウト
+

NOTE: 上記のリソースが検出された場合、それらのリソースではデータ保護処理がサポートされません。

* HANAマルチホスト構成
* 同じホスト上の複数のインスタンス
* マルチティアスケールアウトHANAシステムレプリケーション
* システムレプリケーションモードでのカスケードレプリケーション環境

