---
permalink: protect-hana/reference_prerequisites_for_using_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter Plug-in for SAP HANA Database を使用するには、 SnapCenter 管理者が事前に SnapCenter サーバをインストールして設定し、前提条件となるタスクを実行する必要があります。 
---
= SnapCenter Plug-in for SAP HANA Databaseを使用するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for SAP HANA Database を使用するには、 SnapCenter 管理者が事前に SnapCenter サーバをインストールして設定し、前提条件となるタスクを実行する必要があります。

* SnapCenterサーバをインストールして設定します。
* SnapCenterサーバにログインします。
* 必要に応じて、ストレージシステム接続を追加し、クレデンシャルを作成してSnapCenter環境を設定します。
* LinuxホストまたはWindowsホストにJava 11をインストールします。
+
Javaのパスは、ホストマシンの環境パス変数で設定する必要があります。

* バックアップレプリケーションが必要な場合は、SnapMirrorとSnapVaultをセットアップします。
* Plug-in for SAP HANA Database をインストールするホストに HDBSQL クライアントをインストールします。
+
このホストで管理するSAP HANAノードのユーザストアキーを設定します。

* SAP HANAデータベース2.0SPS05でSAP HANAデータベースユーザアカウントを使用している場合は、SnapCenter Serverでバックアップ、リストア、クローニングの処理を実行するための次の権限があることを確認してください。
+
** バックアップ管理者
** カタログの読み取り
** データベースバックアップ管理者
** データベースリカバリオペレータ



