---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。SnapCenter Plug-in for SAP HANA Database は、 Windows と Linux のどちらの環境でも使用できます。 
---
= ホストを追加して SnapCenter Plug-in for SAP HANA Database をインストールするための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。SnapCenter Plug-in for SAP HANA Database は、 Windows と Linux のどちらの環境でも使用できます。

* ホストに Java 1.8 64 ビットがインストールされている必要があります。
+

NOTE: IBM Javaはサポートされていません。

* SAP HANA データベースの対話型端末（ HDBSQL クライアント）をホストにインストールしておく必要があります。
* Windows の場合は、「 LocalSystem 」 Windows ユーザを使用してプラグインの Creator Service が実行されている必要があります。これは、 Plug-in for SAP HANA Database がドメイン管理者としてインストールされている場合のデフォルトの動作です。
* Windows の場合は、ユーザストアキーを SYSTEM ユーザとして作成する必要があります。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。SnapCenter Plug-in for Microsoft Windows は、 Windows ホストに SAP HANA プラグインを使用してデフォルトで導入されます。
* Linux ホストの場合は、 HDB Secure User Store キーに HDBSQL OS ユーザとしてアクセスします。
* SnapCenter サーバが、 Plug-in for SAP HANA Database ホストの 8145 ポートまたはカスタムポートにアクセスできる必要があります。




== Windows ホスト

* ローカル管理者権限を持つドメインユーザがあり、リモートホストに対してローカルログイン権限が付与されている必要があります。
* Plug-in for SAP HANA Database を Windows ホストにインストールする際に、 SnapCenter Plug-in for Microsoft Windows が自動的にインストールされます。
* root ユーザまたは root 以外のユーザ用にパスワードベースの SSH 接続を有効にしておく必要があります。
* Windows ホストに Java 1.8 64 ビットがインストールされている必要があります。
+
http://www.java.com/en/download/manual.jsp["すべてのオペレーティングシステム用の Java のダウンロード"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"]





== Linux ホスト

* root ユーザまたは root 以外のユーザ用にパスワードベースの SSH 接続を有効にしておく必要があります。
* Linux ホストに Java 1.8 64 ビットがインストールされている必要があります。
+
http://www.java.com/en/download/manual.jsp["すべてのオペレーティングシステム用の Java のダウンロード"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"]

* Linux ホストで実行されている SAP HANA データベースを Plug-in for SAP HANA Database のインストール時にインストールすると、 SnapCenter Plug-in for UNIX が自動的にインストールされます。
* プラグインのインストールには、デフォルトのシェルとして* bash *が必要です。




== 補助コマンド

SnapCenter Plug-in for SAP HANAで補足コマンドを実行するには、 `allowed_commands.config` ファイル。

`allowed_commands.config` ファイルは、SnapCenter Plug-in for SAP HANAディレクトリの「etc」サブディレクトリにあります。

.Windows ホスト
デフォルト： `C:\Program Files\NetApp\SnapCenter\HANA\etc\allowed_commands.config`

カスタムパス： `<Custome_Directory>\NetApp\SnapCenter\HANA\etc\allowed_commands.config`
Windowsホスト：

.Linux ホスト
デフォルト： `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

カスタムパス： `<Custome_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

プラグインホストで追加のコマンドを許可するには、 `allowed_commands.config` エディタ内のファイル。各コマンドを別 々 の行に入力します。大文字と小文字は区別されません。
例：

コマンド:mount

コマンド：umount

完全修飾パス名を指定してください。パス名にスペースが含まれている場合は、パス名を引用符（"）で囲みます。
例：

コマンド："C：\Program Files\NetApp\SnapCreator commands\sdcli.exe"

コマンド：myscript.bat

状況に応じて `allowed_commands.config` ファイルが存在しません。コマンドまたはスクリプトの実行はブロックされ、次のエラーでワークフローが失敗します。

"[/mnt/mount-a]の実行は許可されていません。プラグインホストのファイル%sにコマンドを追加して許可します。"

コマンドまたはスクリプトが `allowed_commands.config`をクリックすると、コマンドまたはスクリプトの実行がブロックされ、次のエラーでワークフローが失敗します。

"[/mnt/mount-a]の実行は許可されていません。プラグインホストのファイル%sにコマンドを追加して許可します。"


NOTE: ワイルドカードエントリ（*）を使用してすべてのコマンドを許可しないでください。
