---
permalink: protect-hana/task_clone_sap_hana_database_backups_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: クローニングワークフローには、計画、クローニング処理の実行、および処理の監視が含まれます。 
---
= PowerShell コマンドレットを使用して SAP HANA データベースのバックアップをクローニングする
:icons: font
:imagesdir: ../media/


[role="lead"]
クローニングワークフローには、計画、クローニング処理の実行、および処理の監視が含まれます。

PowerShell コマンドレットを実行できるように PowerShell 環境を準備しておく必要があります。

コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。

* 手順 *

. Open-SmConnection コマンドレットを使用して、指定したユーザの SnapCenter サーバとの接続セッションを開始します。
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Get-SmBackup コマンドレットを使用して、クローニング処理を実行するバックアップを取得します。
+
この例では、クローニングできるバックアップが 2 つあります。

+
[listing]
----
 C:\PS> Get-SmBackup

        BackupId                      BackupName                    BackupTime                    BackupType
        --------                      ----------                    ----------                    ----------
         1                     Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM          Full Backup
         2                     Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
. 既存のバックアップからクローニング処理を開始し、クローニングされたボリュームをエクスポートする NFS エクスポートの IP アドレスを指定します。
+
この例では、 NFSExportIPs のアドレスを 10.232.206.169 と指定してバックアップをクローニングしています。

+
[listing]
----
New-SmClone -AppPluginCode hana -BackupName scsccore1_sccore_test_com_hana_H73_scsccore1_06-07-2017_02.54.29.3817 -Resources @{"Host"="scsccore1.sccore.test.com";"Uid"="H73"}  -CloneToInstance shivscc4.sccore.test.com -mountcommand 'mount 10.232.206.169:%hana73data_Clone /hana83data' -preclonecreatecommands '/home/scripts/scpre_clone.sh' -postclonecreatecommands '/home/scripts/scpost_clone.sh'
----
+

NOTE: NFSExportIPs を指定しない場合、デフォルトでクローンターゲットホストにエクスポートされます。

. Get-SmCloneReport コマンドレットを使用してクローニングジョブの詳細を表示し、バックアップが正常にクローニングされたことを確認します。
+
クローン ID 、開始日時、終了日時などの詳細を確認できます。

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

    SmCloneId           : 1
    SmJobId             : 186
    StartDateTime       : 8/3/2015 2:43:02 PM
    EndDateTime         : 8/3/2015 2:44:08 PM
    Duration            : 00:01:06.6760000
    Status              : Completed
    ProtectionGroupName : Draper
    SmProtectionGroupId : 4
    PolicyName          : OnDemand_Clone
    SmPolicyId          : 4
    BackupPolicyName    : OnDemand_Full_Log
    SmBackupPolicyId    : 1
    CloneHostName       : SCSPR0054212005.mycompany.com
    CloneHostId         : 4
    CloneName           : Draper__clone__08-03-2015_14.43.53
    SourceResources     : {Don, Betty, Bobby, Sally}
    ClonedResources     : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER, Sally_DRAPER}
    SmJobError          :
----

