---
permalink: protect-hana/task_import_CA_certificates.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: SnapCenter サーバと Windows ホストプラグインの CA 証明書をインポートします 
---
= CA 証明書をインポートする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft の管理コンソール（ MMC ）を使用して、 SnapCenter サーバと Windows ホストプラグインに CA 証明書をインポートする必要があります。

* 手順 *

. Microsoft 管理コンソール (MMC) に移動し、 [ * ファイル * ] 、 [ スナップインの追加と削除 ] の順にクリックします。
. [ スナップインの追加と削除 ] ウィンドウで、 [*Certificates*] を選択し、 [*Add*] をクリックします。
. [ 証明書 ] スナップインウィンドウで、 [*Computer account*] オプションを選択し、 [ 完了 *] をクリックします。
. [ * コンソールルート *>* 証明書–ローカルコンピュータ *>* 信頼されたルート証明機関 *>* 証明書 *] をクリックします。
. [ 信頼されたルート証明機関 ] フォルダを右クリックし、 [ すべてのタスク *>*Import* ] を選択してインポートウィザードを開始します。
. 次の手順でウィザードを完了します。
+
|===
| ウィザードウィンドウ | 実行する処理 


 a| 
秘密鍵をインポートします
 a| 
オプション * はい * を選択し、秘密鍵をインポートして、 * 次へ * をクリックします。



 a| 
インポートファイル形式
 a| 
変更せずに、 * 次へ * をクリックします。



 a| 
セキュリティ
 a| 
エクスポートされた証明書に使用する新しいパスワードを指定し、 * Next * をクリックします。



 a| 
証明書のインポートウィザードを完了しています
 a| 
概要を確認し、 [ 完了 ] をクリックしてインポートを開始します。

|===
+

NOTE: 証明書のインポートは、秘密鍵にバンドルされている必要があります（サポートされている形式は、*.pfx、*.p12、および*.p7b）。

. 「 Personal 」フォルダについて、手順 5 を繰り返します。

