---
permalink: protect-hana/task_define_a_backup_strategy_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA\ ）、目標復旧時間（ RTO\ ）、および目標復旧時点（ RPO\ ）によって決まります。 
---
= SAP HANA データベースのバックアップ戦略を定義する
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA ）、目標復旧時間（ RTO ）、および目標復旧時点（ RPO ）によって決まります。

* このタスクについて *

SLA では、サービスの可用性やパフォーマンスなど、サービス関連の多くの問題に対処するために必要なサービスレベルを定義します。RTO は、サービスの停止からビジネスプロセスの復旧までに必要となる時間です。RPO は、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA 、 RTO 、および RPO は、データ保護戦略に関与します。

* 手順 *

. リソースをバックアップするタイミングを決定します。
. 必要なバックアップジョブの数を決定します。
. バックアップの命名方法を決定します。
. Snapshot コピーベースのポリシーを作成してアプリケーションと整合性のあるデータベースの Snapshot コピーをバックアップするかどうかを決定します。
. データベースの整合性を検証するかどうかを決定します。
. レプリケーションのために NetApp SnapMirror テクノロジを使用するか、または長期保持のために NetApp SnapVault テクノロジを使用するかを決定します。
. ソースストレージシステムおよび SnapMirror デスティネーションでの Snapshot コピーの保持期間を確認します。
. バックアップ処理の前後にコマンドを実行するかどうかを決定し、実行する場合はプリスクリプトまたはポストスクリプトを用意します。

