---
permalink: protect-hana/task_install_the_snapcenter_plug_in_for_sap_hana_database_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter Plug-in for SAP HANA Databaseは、SnapCenterのユーザインターフェイス（UI）を使用してインストールする必要があります。環境でSnapCenter UIからプラグインのリモートインストールが許可されていない場合は、コマンドラインインターフェイス（CLI 1）を使用して、コンソールモードまたはサイレントモードでPlug-in for SAP HANA Databaseをインストールできます。 
---
= コマンドラインインターフェイスを使用して、LinuxホストにSnapCenter Plug-in for SAP HANA Databaseをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ユーザインターフェイス（ UI ）を使用して、 SnapCenter Plug-in for SAP HANA Database をインストールする必要があります。環境で SnapCenter UI からプラグインのリモートインストールが許可されていない場合は、コマンドラインインターフェイス（ CLI ）を使用して、 Plug-in for SAP HANA Database をコンソールモードまたはサイレントモードでインストールできます。

.開始する前に
* Plug-in for SAP HANA Databaseは、HDBSQLクライアントが配置されている各Linuxホストにインストールする必要があります。
* SnapCenter Plug-in for SAP HANA Database をインストールする Linux ホストは、依存するソフトウェア、データベース、オペレーティングシステムの要件を満たしている必要があります。
+
サポートされる構成の最新情報については、Interoperability Matrix Tool（IMT）を参照してください。

+
https://imt.netapp.com/matrix/imt.jsp?components=121029;&solution=1259&isHWU&src=IMT[]

* SnapCenter Plug-in for SAP HANA Databaseは、SnapCenter Plug-ins Package for Linuxに含まれています。SnapCenter Plug-ins Package for Linuxをインストールする前に、SnapCenterをWindowsホストにインストールしておく必要があります。


.手順
. SnapCenter Plug-ins Package for SnapCenterのインストールファイル（SAP_Linux_host_plugin.bin）をC：\ProgramData\SAP\Package RepositoryからPlug-in for NetApp SnapCenterデータベースをインストールするホストにコピーします。
+
このパスには、SnapCenterサーバがインストールされているホストからアクセスできます。

. コマンドプロンプトで、インストールファイルをコピーしたディレクトリに移動します。
. プラグインをインストールします。 `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -dport には、 SMCore HTTPS 通信ポートを指定します。
** - DSERVER_IP は、 SnapCenter サーバの IP アドレスを指定します。
** - DSERVER_HTTPS_PORT には、 SnapCenter サーバの HTTPS ポートを指定します。
** -duser_install_DIR - SnapCenter Plug-ins Package for Linux をインストールするディレクトリを指定します
** DINSTALL_LOG_name は、ログファイルの名前を指定します。


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. 次のコマンドを入力して、 =<installation directory>/NetApp/snapcenter /cscc /etc/SC_SMS_Services.properties ファイルを編集し、 plugins/enabled=hana ： 3.0 パラメータを追加します。
. Add-Smhostコマンドレットと必要なパラメータを使用して、SnapCenterサーバにホストを追加します。
+
コマンドで使用できるパラメータとその説明については、 RUNNING Get Help command_name _ を使用して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。


