---
permalink: protect-hana/task_back_up_databases_using_powershell_cmdlets_sap_hana.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: データベースをバックアップするときは、 SnapCenter サーバとの接続を確立してから、リソースの追加、ポリシーの追加、バックアップリソースグループの作成を行って、バックアップを実行します。 
---
= PowerShell コマンドレットを使用してデータベースをバックアップします
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースをバックアップするときは、 SnapCenter サーバとの接続を確立してから、リソースの追加、ポリシーの追加、バックアップリソースグループの作成を行って、バックアップを実行します。

* 必要なもの *

* PowerShell コマンドレットを実行できるように PowerShell 環境を準備しておく必要があります。
* ストレージシステム接続を追加し、クレデンシャルを作成しておく必要があります。


* 手順 *

. Open-SmConnection コマンドレットを使用して、指定したユーザの SnapCenter サーバとの接続セッションを開始します。
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
ユーザ名とパスワードのプロンプトが表示されます。

. Add-SmResources コマンドレットを使用してリソースを追加します。
+
この例は、 SingleContainer タイプの SAP HANA データベースを追加する方法を示しています。

+
[listing]
----
C:\PS> Add-SmResource -HostName '10.232.204.42' -PluginCode 'HANA' -DatabaseName H10 -ResourceType SingleContainer -StorageFootPrint (@{"VolumeName"="HanaData10";"StorageSystem"="vserver_scauto_primary"}) -SID 'H10' -filebackuppath '/tmp/HanaFileLog' -userstorekeys 'HS10' -osdbuser 'h10adm' -filebackupprefix 'H10_'
----
+
この例は、 MultipleContainers タイプの SAP HANA データベースを追加する方法を示しています。

+
[listing]
----
C:\PS> Add-SmResource -HostName 'vp-hana2.gdl.englab.netapp.com' -PluginCode 'HANA' -DatabaseName MDC_MT -ResourceType MultipleContainers -StorageFootPrint (@{"VolumeName"="VP_HANA2_data";"StorageSystem"="buck.gdl.englab.netapp.com"}) -sid 'A12' -userstorekeys 'A12KEY' -TenantType 'MultiTenant'
----
+
次の例は、データボリューム以外のリソースを作成する方法を示しています。

+
[listing]
----
C:\PS> Add-SmResource -HostName 'SNAPCENTERN42.sccore.test.com' -PluginCode 'hana' -ResourceName NonDataVolume -ResourceType NonDataVolume -StorageFootPrint (@{"VolumeName"="ng_pvol";"StorageSystem"="vserver_scauto_primary"}) -sid 'S10'
----
. Add-SmPolicy コマンドレットを使用してバックアップポリシーを作成します。
+
この例では、 Snapshot コピーベースのバックアップのバックアップポリシーを作成しています。

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName hana_snapshotbased -PolicyType Backup -PluginPolicyType hana -BackupType SnapShotBasedBackup
----
+
この例では、ファイルベースのバックアップのバックアップポリシーを作成しています。

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName hana_Filebased -PolicyType Backup -PluginPolicyType hana -BackupType FileBasedBackup
----
. Add-SmResourceGroup コマンドレットを使用して、リソースを保護するか、新しいリソースグループを SnapCenter に追加します。
+
この例では、単一コンテナのリソースを保護しています。

+
[listing]
----
C:\PS> Add-SmProtectResource -PluginCode HANA  -Policies hana_snapshotbased,hana_Filebased
 -Resources @{"Host"="host.example.com";"UID"="SID"} -Description test -usesnapcenterwithoutfilesystemconsistency
----
+
この例では、複数コンテナのリソースを保護しています。

+
[listing]
----
C:\PS> Add-SmProtectResource -PluginCode HANA  -Policies hana_snapshotbased,hana_Filebased
 -Resources @{"Host"="host.example.com";"UID"="MDC\SID"} -Description test -usesnapcenterwithoutfilesystemconsistency
----
+
この例では、ポリシーとリソースを指定して新しいリソースグループを作成しています。

+
[listing]
----
C:\PS> Add-SmResourceGroup -ResourceGroupName 'ResourceGroup_with_SingleContainer_MultipleContainers_Resources' -Resources @(@{"Host"="sccorelinux61.sccore.test.com";"Uid"="SID"},@{"Host"="sccorelinux62.sccore.test.com";"Uid"="MDC\SID"})
  -Policies hana_snapshotbased,hana_Filebased  -usesnapcenterwithoutfilesystemconsistency  -plugincode 'HANA'
----
+
この例では、データボリューム以外のリソースグループを作成しています。

+
[listing]
----
C:\PS> Add-SmResourceGroup -ResourceGroupName 'Mixed_RG_backup_when_Remove_Backup_throguh_BackupName_windows' -Resources @(@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="H11";"PluginName"="hana"},@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="MDC\H31";"PluginName"="hana"},@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="NonDataVolume\S10\NonDataVolume";"PluginName"="hana"}) -Policies hanaprimary
----
. New-SmBackup コマンドレットを使用して、新しいバックアップジョブを開始する。
+
この例は、リソースグループをバックアップする方法を示しています。

+
[listing]
----
C:\PS> New-SMBackup -ResourceGroupName 'ResourceGroup_with_SingleContainer_MultipleContainers_Resources'  -Policy hana_snapshotbased
----
+
この例では、保護されたリソースをバックアップしています。

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.232.204.42";"Uid"="MDC\SID";"PluginName"="hana"} -Policy hana_Filebased
----
. Get-smJobSummaryReport コマンドレットを使用して、ジョブのステータス（実行中、完了、または失敗）を監視します。
+
[listing]
----
PS C:\> Get-smJobSummaryReport -JobID 123
----
. Get-SmBackupReport コマンドレットを使用して、リストア処理やクローニング処理を実行するバックアップ ID とバックアップ名など、バックアップジョブの詳細を監視します。
+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----


コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
