---
permalink: protect-hana/task_define_a_backup_strategy_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA\ ）、目標復旧時間（ RTO\ ）、および目標復旧時点（ RPO\ ）によって決まります。 
---
= SAP HANAデータベースのバックアップ戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。

.タスクの内容
SLAは、期待されるサービスレベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RTOは、サービスの停止後にビジネスプロセスをリストアする必要がある時間です。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義します。SLA、RTO、RPOは、データ保護戦略に影響します。

.手順
. リソースをバックアップするタイミングを決定します。
. 必要なバックアップジョブの数を決定します。
. バックアップの命名方法を決定します。
. アプリケーションと整合性のあるデータベースのSnapshotをバックアップするSnapshotコピーベースのポリシーを作成するかどうかを決定します。
. データベースの整合性を検証するかどうかを決定します。
. レプリケーションにNetApp SnapMirrorテクノロジを使用するか、長期保持にNetApp SnapVaultテクノロジを使用するかを決定します。
. ソースストレージシステムとSnapMirrorデスティネーションのSnapshotの保持期間を決定します。
. バックアップ処理の前後にコマンドを実行するかどうかを決定し、実行する場合はプリスクリプトまたはポストスクリプトを用意します。

