---
permalink: protect-hana/task_restore_sap_hana_database_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: SAP HANA データベースのバックアップをリストアするときは、 SnapCenter サーバとの接続セッションを開始し、バックアップをリストしてバックアップ情報を取得し、バックアップをリストアします。 
---
= PowerShell コマンドレットを使用して SAP HANA データベースをリストアする
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP HANA データベースのバックアップをリストアするときは、 SnapCenter サーバとの接続セッションを開始し、バックアップをリストしてバックアップ情報を取得し、バックアップをリストアします。

* 必要なもの *

PowerShell コマンドレットを実行できるように PowerShell 環境を準備しておく必要があります。

* 手順 *

. Open-SmConnection コマンドレットを使用して、指定したユーザの SnapCenter サーバとの接続セッションを開始します。
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Get-SmBackup コマンドレットと Get-SmBackupReport コマンドレットを使用して、リストアするバックアップを特定します。
+
この例では、リストアできるバックアップが 2 つあります。

+
[listing]
----
 PS C:\> Get-SmBackup

        BackupId    BackupName                    BackupTime            BackupType
        --------    ----------                    ----------            ----------
         1          Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM  Full Backup
         2          Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
+
この例では、 2015 年 1 月 29 日から 2015 年 2 月 3 日までのバックアップに関する詳細な情報を示しています。

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. HANA Studio でリカバリプロセスを開始します。
+
データベースがシャットダウンされます。

. Restore-SmBackup コマンドレットを使用して、バックアップからデータをリストアします。
+

NOTE: AppObjectId は「 Host\Plugin\UID 」です。 UID=SID は単一コンテナタイプのリソース用で、 UID=MDC\SID は複数コンテナのリソース用です。ResourceID は、 Get-smResources コマンドレットから取得できます。

+
[listing]
----
Get-smResources  -HostName cn24.sccore.test.com  -PluginCode HANA
----
+
この例は、プライマリストレージからデータベースをリストアする方法を示しています。

+
[listing]
----
Restore-SmBackup -PluginCode HANA -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 3
----
+
この例は、セカンダリストレージからデータベースをリストアする方法を示しています。

+
[listing]
----
Restore-SmBackup -PluginCode 'HANA' -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 399 -Confirm:$false  -Archive @( @{"Primary"="<Primary Vserver>:<PrimaryVolume>";"Secondary"="<Secondary Vserver>:<SecondaryVolume>"})
----
+
バックアップが HANA Studio でリカバリに使用できるようになります。



コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
