---
permalink: protect-hana/task_configure_CA_certificate_for_saphana_on_windows_host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Windowsホスト上のSnapCenterカスタムプラグインサービス用のCA証明書の設定 
---
= Windowsホスト上のSnapCenter SAP HANAプラグインサービス用のCA証明書の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カスタムプラグインキーストアとその証明書のパスワードの管理、 CA 証明書の設定、カスタムプラグインの信頼ストアへのルート証明書または中間証明書の設定、 SnapCenter Custom Plug-ins の信頼ストアを使用したカスタムプラグインの信頼ストアへの CA 署名キーペアの設定、インストールされたデジタル証明書のアクティブ化が必要です。

カスタムプラグインは、 _ C ： \Program Files\NetApp\SnapManager \Snapcenter Plug-in Creator\etc_both にある file_keystore.JKS_を 信頼ストアおよびキーストアとして使用します。



== カスタムプラグインキーストアのパスワードと使用中のCA署名キーペアのエイリアスを管理します。

.手順
. カスタムプラグインキーストアのデフォルトパスワードは、カスタムプラグインエージェントのプロパティファイルから取得できます。
+
key_keystore.pass_ に対応する値です。

. キーストアのパスワードを変更します。
+
_keytool -storepasswd -keystore keystore.JKS_

+

NOTE: Windowsコマンドプロンプトで「keytool」コマンドが認識されない場合は、keytoolコマンドを完全なパスに置き換えます。

+
_C ： \Program Files\Java\<JDK_version >\bin\keytool .exe "-storepasswd -keystore keystore.JKS_

. キーストア内の秘密鍵エントリのすべてのエイリアスのパスワードを、キーストアと同じパスワードに変更します。
+
_keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.JKS_

+
_agent.properties_ ファイル内のキー keystore.pass に対しても同じキーを更新します。

. パスワードを変更したら、サービスを再起動します。
+

NOTE: カスタムプラグインキーストアのパスワードと、秘密鍵に関連付けられているすべてのエイリアスパスワードを同じにする必要があります。





== カスタムプラグインの信頼ストアへのルート証明書または中間証明書の設定

ルート証明書または中間証明書は、カスタムプラグインの信頼ストアに秘密鍵なしで設定する必要があります。

.手順
. カスタムプラグインの keystore _C ： \Program Files\NetApp\Virtual \SnapCenter \Snapcenter Plug-in Creator\etc\備え ているフォルダに移動します
. 「keystore.jks」ファイルを探します。
. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. ルート証明書または中間証明書を追加します。
+
_keytool -import-trustcacerts -alias myRootCA -file/root/USERTrustRSA_Root.cer -keystore keystore.JKS_

. カスタムプラグインの信頼ストアにルート証明書または中間証明書を設定したら、サービスを再起動します。



NOTE: ルートCA証明書のあとに中間CA証明書を追加する必要があります。



== カスタムプラグインの信頼ストアへのCA署名キーペアの設定

カスタムプラグインの信頼ストアにCA署名キーペアを設定する必要があります。

.手順
. カスタムプラグインの keystore _C ： \Program Files\NetApp\Virtual \SnapCenter \Snapcenter Plug-in Creator\etc\備え ているフォルダに移動します
. file_keystore.JKS_</Z1> を探します。
. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. 秘密鍵と公開鍵の両方が設定されたCA証明書を追加します。
+
_keytool -importkeystore -srckeystore.root/ snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.JKS -deststoretype JKS_

. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. キーストアに追加された新しいCA証明書に対応するエイリアスがキーストアに含まれていることを確認します。
. CA証明書に追加した秘密鍵のパスワードをキーストアのパスワードに変更します。
+
デフォルトのカスタムプラグインキーストアパスワードは、agent.propertiesファイルのキーkeystore_passの値です。

+
_keytool -keypasswd -alias "alias_name_in_ca_cert" -keystore keystore.JKS__

. _agent.properties_ ファイルの CA 証明書からエイリアス名を設定します。
+
この値をSCC_CERTIFICATE_ALIASキーに対して更新します。

. カスタムプラグインの信頼ストアにCA署名キーペアを設定したら、サービスを再起動します。




== SnapCenterカスタムプラグインの証明書失効リスト（CRL）を設定する

.タスクの内容
* 関連するCA証明書の最新のCRLファイルをダウンロードするには、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["SnapCenter CA 証明書の証明書失効リストファイルを更新する方法"]。
* SnapCenterカスタムプラグインは、事前に設定されたディレクトリでCRLファイルを検索します。
* SnapCenter カスタムプラグインの CRL ファイルのデフォルトディレクトリは、 _'C:\Program Files\NetApp\SnapCenter \Snapcenter Plug-in Creator\etc\crl'_ です。


.手順
. _agent.properties_ ファイルのデフォルトディレクトリを、キー crl_path に対して変更および更新できます。
. このディレクトリには、複数のCRLファイルを配置できます。
+
受信証明書は、各CRLに対して検証されます。


