---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenterを使用してSAP HANAデータベースのリソースをバックアップする前に、バックアップ対象のリソースまたはリソースグループのバックアップポリシーを作成する必要があります。バックアップポリシーは、バックアップを管理、スケジュール、および保持する方法を規定する一連のルールです。 
---
= SAP HANAデータベースのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してSAP HANAデータベースのリソースをバックアップする前に、バックアップ対象のリソースまたはリソースグループのバックアップポリシーを作成する必要があります。バックアップポリシーは、バックアップを管理、スケジュール、および保持する方法を規定する一連のルールです。

.開始する前に
* バックアップ戦略を定義しておく必要があります。
+
詳細については、SAP HANAデータベースのデータ保護戦略の定義に関する情報を参照してください。

* データ保護の準備として、SnapCenterのインストール、ホストの追加、ストレージシステム接続のセットアップ、リソースの追加などのタスクを実行しておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートする場合は、ソースボリュームとデスティネーションボリュームの両方に対応するSVMをSnapCenter管理者がユーザに割り当てておく必要があります。
+
また、レプリケーション、スクリプト、およびアプリケーションの設定をポリシーで指定することもできます。これらのオプションを使用することで、別のリソースグループにポリシーを再利用して時間を節約できます。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳しくは、を参照してください https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"]。


.タスクの内容
* SAP HANAシステムレプリケーション
+
** プライマリSAP HANAシステムを保護し、すべてのデータ保護処理を実行できます。
** セカンダリSAP HANAシステムは保護できますが、バックアップを作成することはできません。
+
フェイルオーバー後は、セカンダリSAP HANAシステムがプライマリSAP HANAシステムになるため、すべてのデータ保護処理を実行できます。

+
SAP HANAデータボリュームのバックアップを作成することはできませんが、SnapCenterはデータ以外のボリューム（NDV）の保護を継続します。



* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。




.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [Name]ページで、ポリシーの名前と詳細を入力します。
. [Policy type]ページで、次の手順を実行します。
+
** ストレージタイプを選択
** バックアップタイプを選択：
+
|===
| 状況 | 操作 


 a| 
Snapshotテクノロジを使用したバックアップの作成
 a| 
「 * Snapshot Based * 」を選択します。



 a| 
データベースの整合性チェックの実行
 a| 
ファイルベースのバックアップ * を選択します。アクティブなテナントのみがバックアップされます。

|===


. [Snapshot and Replication]ページで、次の手順を実行します。
+
** スケジュールタイプを指定するには、「 * on demand * 」、「 * Hourly * 」、「 * Daily * 」、「 * Weekly * 」、または「 * Monthly * 」を選択します。
+

NOTE: リソースグループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定できます。これにより、ポリシーとバックアップ頻度が同じであるリソースグループを作成できますが、各ポリシーに異なるバックアップスケジュールを割り当てることもできます。

+

NOTE: 午前2時にスケジュールを設定している場合、夏時間（DST）中はスケジュールはトリガーされません。



. [Snapshot and Replication]ページで、[Backup Type]ページで選択したバックアップタイプとスケジュールタイプの保持設定を指定します。
+
|===
| 状況 | 作業 


 a| 
一定数のSnapshotを保持
 a| 
[保持するコピー数]*を選択し、保持するSnapshotの数を指定します。

Snapshotの数が指定した数を超えると、最も古いコピーから順にSnapshotが削除されます。


NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持数を使用しているONTAPバージョンでサポートされる値よりも大きい値に設定すると、バックアップは失敗します。


IMPORTANT: SnapshotコピーベースのバックアップでSnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗する可能性があります。


NOTE: SAP HANAシステムレプリケーションでは、SAP HANAシステムのすべてのリソースを1つのリソースグループに追加することを推奨します。これにより、適切な数のバックアップが保持されます。


NOTE: SAP HANAシステムレプリケーションでは、作成されたSnapshotの合計数はリソースグループに設定された保持数と同じになります。最も古いSnapshotの削除は、最も古いSnapshotが配置されているノードに基づいて行われます。たとえば、SAP HANAシステムレプリケーションプライマリとSAP HANAシステムレプリケーションセカンダリを含むリソースグループの保持期間は7に設定されます。一度に作成できるSnapshotの数は、SAP HANAシステムレプリケーションプライマリとSAP HANAシステムレプリケーションセカンダリの両方を含め、最大7つです。



 a| 
Snapshotを特定の日数だけ保持
 a| 
[コピーを保持する期間]*を選択し、Snapshotを削除するまでの日数を指定します。



 a| 
プライマリSnapshotコピーロック期間
 a| 
Snapshotコピーのロック期間を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。



 a| 
セカンダリSnapshotコピーのロック期間
 a| 
[Secondary snapshot copy locking period]*を選択し、[Days]、[Months]、または[Years]を選択します。

このオプションを有効にするには、次のタスクを実行する必要があります。

** [Primary snapshot copy locking period]*を選択します。
** セカンダリレプリケーションオプションの一方または両方を選択します。


|===
. Snapshotラベルを選択します。
+
選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。

+

NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。

. Snapshotコピーベースのバックアップの場合は、[Select secondary replication options]セクションで、次のセカンダリレプリケーションオプションの一方または両方を選択します。
+

NOTE: *セカンダリSnapshotコピーのロック期間*を有効にするには、セカンダリレプリケーションオプションを選択する必要があります。

+
|===
| フィールド | 操作 


 a| 
* ローカル Snapshot コピー作成後に SnapMirror を更新 *
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

このオプションは、SnapMirrorのアクティブな同期に対して有効にする必要があります。

ONTAPの保護関係のタイプがミラーとバックアップの場合、このオプションのみを選択すると、プライマリで作成されたSnapshotはデスティネーションに転送されず、デスティネーションのリストに表示されます。このSnapshotをリストア処理の対象としてデスティネーションで選択すると、「Secondary Location is not available for the selected vaulted/mirrored backup」というエラーメッセージが表示されます。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。

[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

を参照して link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["[Topology]ページでのSAP HANAデータベースのバックアップとクローンの表示"]



 a| 
* ローカル Snapshot コピー作成後に SnapVault を更新 *
 a| 
ディスクツーディスクのバックアップレプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

SnapLockがONTAPのセカンダリ（SnapLock Vault）にのみ設定されている場合、[Topology]ページの*[Refresh]*ボタンをクリックすると、ONTAPから取得したセカンダリのロック期間が更新されます。

SnapLock Vaultの詳細については、を参照してください。 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["SnapVaultデスティネーションでSnapshotコピーをWORM状態にコミットする"]

を参照して link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["[Topology]ページでのSAP HANAデータベースのバックアップとクローンの表示"]



 a| 
* エラー再試行回数 *
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。

