---
permalink: protect-hana/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_sap_hana.html 
sidebar: sidebar 
keywords: credentials 
summary: 'SnapCenterの[ホストを追加]ページを使用してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインはリモートホストに自動的にインストールされます。ホストの追加とプラグインパッケージのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストを追加してリモートホストにプラグインパッケージをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[ホストを追加]ページを使用してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインはリモートホストに自動的にインストールされます。ホストの追加とプラグインパッケージのインストールは、ホストごとまたはクラスタごとに実行できます。

.開始する前に
* SnapCenter ServerホストのオペレーティングシステムがWindows 2019で、プラグインホストのオペレーティングシステムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windowsホストにプラグインをインストールするときに、組み込みでないクレデンシャルを指定する場合や、ユーザがローカルワークグループに属している場合は、ホストのUACを無効にする必要があります。
* メッセージキューサービスが実行されていることを確認する必要があります。
* ホストの管理については、管理に関するドキュメントを参照してください。
* グループ管理サービスアカウント（gMSA）を使用する場合は、管理Privilegesを使用してgMSAを設定する必要があります。
+
link:../protect-hana/task_configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016 以降で SAP HANA 用のグループマネージドサービスアカウントを設定します"^]



.タスクの内容
* SnapCenterサーバをプラグインホストとして別のSnapCenterサーバに追加することはできません。
* SAP HANA システムレプリケーションでプライマリシステムとセカンダリシステムの両方のリソースを検出する場合は、 root ユーザまたは sudo ユーザを使用してプライマリシステムとセカンダリシステムの両方を追加することを推奨します。


.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] タブが選択されていることを確認します。
. [追加]*をクリックします。
. [Hosts]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
ホストのタイプを選択します。

** ウィンドウ
** Linux
+

NOTE: Plug-in for SAP HANAはHDBSQLクライアントホストにインストールされます。このホストはWindowsシステムでもLinuxシステムでもかまいません。





 a| 
ホスト名
 a| 
通信ホスト名を入力します。ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。SnapCenter は、 DNS の適切な設定によって異なります。そのため、FQDNを入力することを推奨します。

HDBSQLクライアントとHDBUserStoreをこのホストに設定する必要があります。



 a| 
クレデンシャル
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

指定したクレデンシャルの名前にカーソルを合わせると、クレデンシャルの詳細を確認できます。


NOTE: クレデンシャルの認証モードは、ホスト追加ウィザードで指定するホストタイプによって決まります。

|===
. [Select Plug-ins to Install]セクションで、インストールするプラグインを選択します。
. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。デフォルトのポート番号は8145です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
Plug-in for SAP HANAはHDBSQLクライアントホストにインストールされます。このホストはWindowsシステムでもLinuxシステムでもかまいません。

** Windows 用 SnapCenter Plug-ins パッケージのデフォルトパスは C ： \Program Files\NetApp\SnapManager です。必要に応じて、パスをカスタマイズできます。
** Linux 用 SnapCenter Plug-ins パッケージのデフォルトパスは /opt/NetApp/SnapCenter です。必要に応じて、パスをカスタマイズできます。




 a| 
インストール前チェックをスキップ
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行
 a| 
Windowsホストで、グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行する場合は、このチェックボックスをオンにします。


NOTE: gMSA名をdomainName\accountName$の形式で指定してください。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [Submit （送信） ] をクリックします。
+
[Skip prechecks]チェック ボックスを選択していない場合、プラグインをインストールするための要件をホストが満たしているかどうかを検証するためにホストが検証されます。ディスク スペース、RAM、PowerShellのバージョン、.NETのバージョン、場所（Windowsプラグインの場合）、Javaのバージョン（Linuxプラグインの場合）が最小要件に照らして検証されます。最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたはRAMに関連している場合は、C：\Program Files\NetApp\SnapCenter WebAppにあるweb.configファイルを更新してデフォルト値を変更できます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HAセットアップでweb.configファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. ホストタイプが Linux の場合は、フィンガープリントを確認し、 * Confirm and Submit * をクリックします。
+
クラスタセットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

+

NOTE: 同じホストを以前に SnapCenter に追加し、フィンガープリントを確認した場合でも、フィンガープリントの検証は必須です。

. インストールの進行状況を監視します。
+
インストール固有のログファイルは、/custom_location / SnapCenter / logsにあります。


