---
permalink: protect-scc/concept_develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter サーバを使用すると、 SnapCenter へのプラグインとしてアプリケーションを導入および管理できます。 
---
= 概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバを使用すると、 SnapCenter へのプラグインとしてアプリケーションを導入および管理できます。データ保護機能と管理機能を備えた SnapCenter サーバに、お好みのアプリケーションを接続できます。

SnapCenter では、さまざまなプログラミング言語を使用してカスタムプラグインを開発できます。Perl 、 Java 、バッチ、またはその他のスクリプト言語を使用してカスタムプラグインを開発できます。

SnapCenter でカスタムプラグインを使用するには、次のタスクを実行する必要があります。

* このガイドの手順に従って、使用するアプリケーション用のプラグインを作成します
* 概要ファイルを作成します
* カスタムプラグインをエクスポートして SnapCenter ホストにインストールする
* プラグインの zip ファイルを SnapCenter サーバにアップロードします




== すべての API 呼び出しでの汎用プラグインの処理

[role="lead"]
すべての API 呼び出しについて、次の情報を使用します。

* プラグインパラメータ
* 終了コード
* エラーメッセージを記録します
* データの整合性




=== プラグインパラメータを使用します

一連のパラメータは、作成されたすべての API 呼び出しの一環としてプラグインに渡されます。次の表に、パラメータの具体的な情報を示します。

|===
| パラメータ | 目的 


 a| 
アクション
 a| 
ワークフロー名を指定します。たとえば、 discover 、 backup 、 fileOrVolRestore 、または cloneVolAndLun などです



 a| 
リソース
 a| 
保護対象のリソースが表示されます。リソースは UID とタイプで識別されます。次の形式でプラグインに表示されます。

「 <UID> 、 <type>; <UID> 、 <type> 」のように入力します。例：「 Instance1 、 Instance ； Instance2\\DB1 、 Database 」



 a| 
APP_NAME を使用している
 a| 
使用するプラグインを指定します。たとえば、 db2 、 mysql のように指定します。SnapCenter サーバには、リストされているアプリケーションに対するサポートが組み込まれています。このパラメータでは大文字と小文字が区別されます。



 a| 
APP_IGNORE_ERROR
 a| 
（ Y または N ）これにより、アプリケーションエラーが発生した場合、 SnapCenter が終了するか、終了しません。これは、複数のデータベースをバックアップする場合に、単一障害でバックアップ処理を停止しないようにする場合に便利です。



 a| 
<resource_name> ____APP_INSTANY_USERNAME
 a| 
SnapCenter クレデンシャルは、リソースに対して設定されます。



 a| 
<resource_name> _APP_INSTANY_PASSWORD
 a| 
SnapCenter クレデンシャルは、リソースに対して設定されます。



 a| 
<resource_name> _<custom_param> です
 a| 
すべてのリソースレベルのカスタムキー値は、先頭に「 <resource_name>_ 」を付けたプラグインで使用できます。たとえば、カスタムキーが「 MySQLDB 」という名前のリソースの「 MASTER_SLAVE 」である場合、このキーは MySQLDB_MASTER_SLAVE として使用できます

|===


=== 終了コードを使用します

プラグインは、終了コードを使用して処理のステータスをホストに戻します。各コードには特定の意味があり、プラグインは正しい終了コードを使用して同じことを示します。

次の表に、エラーコードとその意味を示します。

|===
| 終了コード | 目的 


 a| 
0
 a| 
処理に成功しました。



 a| 
99
 a| 
要求された処理はサポートされていないか実装されて



 a| 
100
 a| 
処理に失敗しました。休止解除をスキップして終了します。デフォルトでは休止解除が実行されます。



 a| 
101
 a| 
処理に失敗しました。バックアップ処理を続行してください。



 a| 
その他
 a| 
処理に失敗しました。休止解除を実行して終了します。

|===


=== エラーメッセージを記録します

エラーメッセージは、プラグインから SnapCenter サーバーに渡されます。メッセージには、メッセージ、ログレベル、およびタイムスタンプが含まれます。

次の表に、レベルとその目的を示します。

|===
| パラメータ | 目的 


 a| 
情報
 a| 
情報メッセージ



 a| 
警告
 a| 
警告メッセージ



 a| 
エラー
 a| 
エラーメッセージです



 a| 
デバッグ
 a| 
デバッグメッセージ



 a| 
トレース
 a| 
メッセージをトレースします

|===


=== データの整合性を維持

カスタムプラグインでは、同じワークフローの実行操作間でデータが保持されます。たとえば、プラグインは休止の終了時にデータを格納でき、休止解除処理に使用できます。

保持するデータはプラグインによって Result オブジェクトの一部として設定されます。具体的な形式で記述され、プラグイン開発の各形式で詳しく説明されています。
