---
permalink: protect-scc/create_policies_for_custom_plug_in_resources.html 
sidebar: sidebar 
keywords: create policies, custom plug-in 
summary: SnapCenterを使用してカスタムプラグイン固有のリソースをバックアップする前に、バックアップするリソースまたはリソースグループのバックアップポリシーを作成する必要があります。 
---
= カスタムプラグインリソースのポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してカスタムプラグイン固有のリソースをバックアップする前に、バックアップするリソースまたはリソースグループのバックアップポリシーを作成する必要があります。

.開始する前に
* バックアップ戦略を定義しておく必要があります。
+
詳細については、カスタムプラグインのデータ保護戦略の定義に関する情報を参照してください。

* データ保護の準備が完了している必要があります。
+
データ保護の準備作業には、 SnapCenter のインストール、ホストの追加、ストレージシステム接続の作成、リソースの追加などがあります。

* ミラー処理またはバックアップ処理を実行するには、Storage Virtual Machine（SVM）を割り当てる必要があります。
+
Snapshotをミラーまたはバックアップにレプリケートする場合は、ソースボリュームとデスティネーションボリュームの両方に対応するSVMをSnapCenter管理者がユーザに割り当てておく必要があります。

* 保護するリソースを手動で追加しておく必要があります。


.タスクの内容
* バックアップポリシーは、バックアップを管理、スケジュール、および保持する方法を規定する一連のルールです。レプリケーション、スクリプト、アプリケーション設定を指定することもできます。
* ポリシーでオプションを指定することで、別のリソースグループにポリシーを再利用して時間を節約できます。
* SnapLock
+
** [バックアップコピーを特定の日数だけ保持する]オプションを選択した場合は、SnapLockの保持期間を指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、保持されるSnapshotの数がポリシーで指定されている数よりも多くなる可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLockヴォールトSnapshotから作成されたクローンにSnapLockヴォールトの有効期限が継承されます。SnapLockの有効期限が過ぎた時点で、ストレージ管理者がクローンを手動でクリーンアップする必要があります。




.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [Name]ページで、ポリシーの名前と詳細を入力します。
. [Policy type]ページで、次の手順を実行します。
+
.. ストレージタイプを選択します。
.. [Custom backup settings]セクションで、プラグインに渡す必要がある特定のバックアップ設定をキーと値の形式で指定します。
+
プラグインに渡すキー値は複数指定できます。



. [Snapshot and Replication]ページで、次の手順を実行します。
+
.. スケジュールタイプを指定するには、「 * on demand * 」、「 * Hourly * 」、「 * Daily * 」、「 * Weekly * 」、または「 * Monthly * 」を選択します。
+

NOTE: リソースグループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定できます。これにより、ポリシーとバックアップ頻度が同じであるリソースグループを作成できますが、各ポリシーに異なるバックアップスケジュールを割り当てることができます。

+

NOTE: 午前2時にスケジュールを設定している場合、夏時間（DST）中はスケジュールはトリガーされません。

.. [Snapshot settings]セクションで、*[Backup Type]*ページで選択したバックアップタイプとスケジュールタイプの保持設定を指定します。
+
|===
| 状況 | 作業 


 a| 
一定数のSnapshotを保持
 a| 
[保持するコピー数]*を選択し、保持するSnapshotの数を指定します。

Snapshotの数が指定した数を超えると、最も古いコピーから順にSnapshotが削除されます。


NOTE: SnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗する可能性があります。


NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持数を使用しているONTAPバージョンでサポートされる値よりも大きい値に設定すると、バックアップは失敗します。



 a| 
Snapshotを特定の日数だけ保持
 a| 
[コピーを保持する期間]*を選択し、Snapshotを削除するまでの日数を指定します。



 a| 
プライマリSnapshotコピーロック期間
 a| 
[Snapshot locking period]を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。



 a| 
セカンダリSnapshotコピーのロック期間
 a| 
[Secondary snapshot copy locking period]*を選択し、[Days]、[Months]、または[Years]を選択します。

このオプションを有効にするには、次のタスクを実行する必要があります。

*** [Primary snapshot copy locking period]*を選択します。
*** セカンダリレプリケーションオプションの一方または両方を選択します。


|===
.. Snapshotラベルを選択します。
+
選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。

+

NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



. [Select secondary replication options]セクションで、次のセカンダリレプリケーションオプションの一方または両方を選択します。
+

NOTE: *セカンダリSnapshotコピーのロック期間*を有効にするには、セカンダリレプリケーションオプションを選択する必要があります。

+
|===
| フィールド | 操作 


 a| 
* ローカル Snapshot コピー作成後に SnapMirror を更新 *
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

ONTAPの保護関係のタイプがミラーとバックアップの場合、このオプションのみを選択すると、プライマリで作成されたSnapshotはデスティネーションに転送されませんが、デスティネーションのリストに表示されます。このSnapshotをリストア処理の対象としてデスティネーションで選択すると、「Secondary Location is not available for the selected vaulted/mirrored backup」というエラーメッセージが表示されます。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。

[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

を参照して link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["[Topology]ページで、カスタムプラグインリソースに関連するバックアップとクローンを表示する"]



 a| 
* ローカル Snapshot コピー作成後に SnapVault を更新 *
 a| 
ディスクツーディスクのバックアップレプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。

セカンダリレプリケーションでは、SnapLockの有効期限によってプライマリSnapLockの有効期限がロードされます。[Topology]ページの[Refresh]*ボタンをクリックすると、ONTAPから取得されたセカンダリおよびプライマリのSnapLock有効期限が更新されます。

SnapLockがONTAPのセカンダリ（SnapLock Vault）にのみ設定されている場合、[Topology]ページの*[Refresh]*ボタンをクリックすると、ONTAPから取得したセカンダリのロック期間が更新されます。

SnapLock Vaultの詳細については、「SnapVaultデスティネーションでSnapshotをWORM状態にコミットする」を参照してください。

を参照して link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["[Topology]ページで、カスタムプラグインリソースに関連するバックアップとクローンを表示する"]



 a| 
* エラー再試行回数 *
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。

. 概要を確認し、 [ 完了 ] をクリックします。

