---
permalink: protect-scc/custom_plugins_in_snapcenter.html 
sidebar: sidebar 
keywords: Custom plug-in 
summary: SnapCenter サーバを使用して作成したカスタムプラグインをホストにインストールすると、アプリケーションのデータ保護を有効にすることができます。 
---
= SnapCenterのカスタムプラグイン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== SnapCenterのカスタムプラグイン

Java、Perl、またはネイティブ形式で作成したカスタムプラグインをSnapCenterサーバを使用してホストにインストールし、アプリケーションのデータ保護を有効にすることができます。このチュートリアルで説明する手順に従って、プラグインをエクスポートしてSnapCenterホストにインストールしておく必要があります。



=== プラグイン記述ファイルの作成

作成するプラグインごとに、説明ファイルが必要です。定義ファイルには、プラグインの詳細が定義されています。ファイル名はPlugin_descriptor.xmlである必要があります。



==== プラグイン記述子ファイルの属性と重要度の使用

|===
| 属性 | 説明 


 a| 
名前
 a| 
プラグインの名前。英数字を使用できます。例：DB2、MySQL、MongoDB

ネイティブ形式で作成されたプラグインの場合は、ファイルの拡張子を指定しないでください。たとえば、プラグイン名がMongoDB.shの場合は、名前をMongoDBと指定します。



 a| 
バージョン
 a| 
プラグインのバージョン。メジャーバージョンとマイナーバージョンの両方を含めることができます。例：1.0、1.1、2.0、2.1



 a| 
DisplayName
 a| 
SnapCenter サーバに表示されるプラグインの名前。同じプラグインの複数のバージョンが書き込まれている場合は、表示名がすべてのバージョンで同じであることを確認してください。



 a| 
プラグインタイプ
 a| 
プラグインの作成に使用した言語。サポートされている値は、Perl、Java、およびNativeです。ネイティブプラグインタイプには、UNIX/Linuxシェルスクリプト、Windowsスクリプト、Python、またはその他のスクリプト言語が含まれます。



 a| 
OSNAME
 a| 
プラグインがインストールされているホストOSの名前。有効な値は Windows と Linux です。1つのプラグインを複数のOSタイプ（Perlタイプのプラグインなど）に導入することができます。



 a| 
osVersion
 a| 
プラグインがインストールされているホストOSのバージョン。



 a| 
リソース名
 a| 
プラグインがサポートできるリソースタイプの名前。たとえば、データベース、インスタンス、コレクションなどです。



 a| 
親
 a| 
場合、 ResourceName は階層的に別のリソースタイプに依存し、 Parent は親のリソースタイプを決定します。

たとえば、DB2プラグインの場合、ResourceNameの「Database」には親の「Instance」があります。



 a| 
RequireFileSystemPlugin
 a| 
YesまたはNo リストアウィザードにリカバリタブを表示するかどうかを指定します。



 a| 
ResourceRequiresAuthentication
 a| 
YesまたはNo ストレージの検出後にデータ保護処理を実行するために、自動検出されたリソースと自動検出されなかったリソースのどちらにクレデンシャルが必要かを指定します。



 a| 
RequireFileSystemClone
 a| 
YesまたはNo クローンワークフローでファイルシステムプラグインの統合が必要かどうかを指定します。

|===
カスタムプラグインDB2のPlugin_descriptor.xmlファイルの例を次に示します。

....
<Plugin>
<SMSServer></SMSServer>
<Name>DB2</Name>
<Version>1.0</Version>
<PluginType>Perl</PluginType>
<DisplayName>Custom DB2 Plugin</DisplayName>
<SupportedOS>
<OS>
<OSName>windows</OSName>
<OSVersion>2012</OSVersion>
</OS>
<OS>
<OSName>Linux</OSName>
<OSVersion>7</OSVersion>
</OS>
</SupportedOS>
<ResourceTypes>
<ResourceType>
<ResourceName>Database</ResourceName>
<Parent>Instance</Parent>
</ResourceType>
<ResourceType>
<ResourceName>Instance</ResourceName>
</ResourceType>
</ResourceTypes>
<RequireFileSystemPlugin>no</RequireFileSystemPlugin>
<ResourceRequiresAuthentication>yes</ResourceRequiresAuthentication>
<SupportsApplicationRecovery>yes</SupportsApplicationRecovery>
</Plugin>
....


=== ZIPファイルの作成

プラグインが開発されて記述子ファイルが作成されたら、プラグインファイルと Plugin_descriptor.xml ファイルをフォルダに追加して zip する必要があります。

ZIPファイルを作成する前に、次の点を考慮する必要があります。

* スクリプト名はプラグイン名と同じにする必要があります。
* Perl プラグインの場合、 ZIP フォルダにスクリプトファイルが格納されているフォルダと、記述ファイルがこのフォルダの外部にある必要があります。フォルダ名はプラグイン名と同じである必要があります。
* Perl プラグイン以外のプラグインを使用する場合は、 ZIP フォルダに記述子とスクリプトファイルが含まれている必要があります。
* OSのバージョンは数字である必要があります。


例：

* DB2プラグイン：db2.pmファイルとPlugin_descriptor.xmlファイルを「db2.zip」に追加します。
* Java を使用して開発されたプラグイン： jar ファイル、依存する jar ファイル、 Plugin_descriptor.xml ファイルをフォルダに追加して zip ファイルを保存します。




=== プラグインのZIPファイルのアップロード

プラグインを目的のホストに導入できるように、プラグインの ZIP ファイルを SnapCenter サーバにアップロードする必要があります。

UIまたはコマンドレットを使用してプラグインをアップロードできます。

* UI ： *

* プラグインの ZIP ファイルを * Add * または * Modify Host * ワークフローウィザードの一部としてアップロードします
* [ 選択 ] をクリックしてカスタムプラグインをアップロードします。 *


* PowerShell ： *

* Upload-SmPluginPackageコマンドレット
+
例：PS>Upload -SmPluginPackage -AbsolutePath c:\DB2_1.zip

+
PowerShell コマンドレットの詳細については、 SnapCenter のコマンドレットのヘルプを使用するか、コマンドレットのリファレンス情報を参照してください。



https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]です。



=== カスタムプラグインの導入

アップロードしたカスタムプラグインを、 * Add * および * Modify Host * ワークフローの一環として、目的のホストに導入できるようになりました。SnapCenter サーバに複数のバージョンのプラグインをアップロードして、特定のホストに導入するバージョンを選択できます。

プラグインをアップロードする方法の詳細については、を参照してください。 link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["ホストを追加してリモートホストにプラグインパッケージをインストールする"]
