---
permalink: protect-scc/define_a_backup_strategy.html 
sidebar: sidebar 
keywords: backup strategy 
summary: バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、サービスレベルアグリーメント（ SLA\ ）、目標復旧時間（ RTO\ ）、および目標復旧時点（ RPO\ ）によって決まります。 
---
= バックアップ戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを確実に作成できます。バックアップ戦略の大部分は、Service Level Agreement（SLA；サービスレベルアグリーメント）、Recovery Time Objective（RTO；目標復旧時間）、Recovery Point Objective（RPO；目標復旧時点）によって決まります。

.タスクの内容
SLAは、期待されるサービスレベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対処方法を定義したものです。RTOは、サービスの停止後にビジネスプロセスをリストアする必要がある時間です。RPOは、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義します。SLA、RTO、RPOは、データ保護戦略に影響します。

.手順
. リソースをバックアップするタイミングを決定します。
. 必要なバックアップジョブの数を決定します。
. バックアップの命名方法を決定します。
. 整合グループSnapshotが必要かどうかを決定し、整合グループSnapshotを削除するための適切なオプションを決定します。
. レプリケーションのために NetApp SnapMirror テクノロジを使用するか、または長期保持のために NetApp SnapVault テクノロジを使用するかを決定します。
. ソースストレージシステムとSnapMirrorデスティネーションのSnapshotの保持期間を決定します。
. バックアップ処理の前後にコマンドを実行するかどうかを決定し、実行する場合はプリスクリプトまたはポストスクリプトを用意します。

