---
permalink: protect-scc/develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords: overview snapcenter 
summary: SnapCenterサーバを使用すると、アプリケーションをSnapCenterのプラグインとして導入および管理できます。 
---
= 概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterサーバを使用すると、アプリケーションをSnapCenterのプラグインとして導入および管理できます。データ保護機能と管理機能を備えた SnapCenter サーバに、お好みのアプリケーションを接続できます。

SnapCenterでは、さまざまなプログラミング言語を使用してカスタムプラグインを開発できます。Perl 、 Java 、バッチ、またはその他のスクリプト言語を使用してカスタムプラグインを開発できます。

SnapCenterでカスタムプラグインを使用するには、次のタスクを実行する必要があります。

* このガイドの手順に従って、アプリケーション用のプラグインを作成します。
* 記述ファイルの作成
* カスタムプラグインをエクスポートしてSnapCenterホストにインストールする
* プラグインのzipファイルをSnapCenterサーバにアップロードする




== すべてのAPI呼び出しでの汎用プラグインの処理

API呼び出しごとに、次の情報を使用します。

* プラグインパラメータ
* 終了コード
* エラーメッセージをログに記録
* データの整合性




=== プラグインパラメータを使用

API呼び出しごとに一連のパラメータがプラグインに渡されます。次の表に、各パラメータの具体的な情報を示します。

|===
| パラメータ | 目的 


 a| 
アクション
 a| 
ワークフロー名を指定します。たとえば、 discover 、 backup 、 fileOrVolRestore 、または cloneVolAndLun などです



 a| 
リソース
 a| 
保護するリソースを一覧表示します。リソースはUIDとタイプで識別されます。リストは次の形式でプラグインに表示されます。

「 <UID> 、 <type>; <UID> 、 <type> 」のように入力します。例：「 Instance1 、 Instance ； Instance2\\DB1 、 Database 」



 a| 
app_name
 a| 
使用しているプラグインを指定します。たとえば、DB2、MySQLなどです。SnapCenterサーバには、リストされているアプリケーションのサポートが組み込まれています。このパラメータでは大文字と小文字が区別されます。



 a| 
APP_IGNORE_ERROR
 a| 
（YまたはN）これにより、アプリケーションエラーが発生したときにSnapCenterが終了するか、終了しません。これは、複数のデータベースをバックアップする場合に、単一障害でバックアップ処理を停止しないようにする場合に便利です。



 a| 
<resource_name> ____APP_INSTANY_USERNAME
 a| 
リソースに対してSnapCenterクレデンシャルが設定されている。



 a| 
<resource_name> _APP_INSTANY_PASSWORD
 a| 
リソースに対してSnapCenterクレデンシャルが設定されている。



 a| 
<resource_name> _<custom_param> です
 a| 
すべてのリソースレベルのカスタムキー値は、先頭に「 <resource_name>_ 」を付けたプラグインで使用できます。たとえば、カスタムキーが「 MySQLDB 」という名前のリソースの「 MASTER_SLAVE 」である場合、このキーは MySQLDB_MASTER_SLAVE として使用できます

|===


=== 終了コードを使用する

プラグインは、終了コードを使用して処理のステータスをホストに返します。各コードには特定の意味があり、プラグインは正しい終了コードを使用して同じことを示します。

次の表に、エラーコードとその意味を示します。

|===
| 終了コード | 目的 


 a| 
0
 a| 
処理に成功しました。



 a| 
99
 a| 
要求された操作はサポートされていないか、



 a| 
100
 a| 
処理に失敗しました。休止解除をスキップして終了します。デフォルトでは休止解除が選択されます。



 a| 
101
 a| 
処理に失敗しました。バックアップ処理を続行してください。



 a| 
その他
 a| 
処理に失敗しました。休止解除を実行して終了します。

|===


=== エラーメッセージをログに記録

エラー・メッセージは、プラグインからSnapCenterサーバに渡されます。メッセージには、メッセージ、ログレベル、およびタイムスタンプが含まれます。

次の表に、レベルとその目的を示します。

|===
| パラメータ | 目的 


 a| 
情報
 a| 
情報メッセージ



 a| 
警告
 a| 
警告メッセージ



 a| 
エラー
 a| 
エラーメッセージ



 a| 
デバッグ
 a| 
デバッグメッセージ



 a| 
トレース
 a| 
トレースメッセージ

|===


=== データの整合性を維持

カスタムプラグインでは、同じワークフローを実行してもデータが保持されます。たとえば、プラグインは休止の終了時にデータを格納でき、休止解除処理に使用できます。

保持するデータは、プラグインによって結果オブジェクトの一部として設定されます。 特定の形式に従っており、プラグイン開発の各スタイルで詳細に説明されています。
