---
permalink: protect-scc/reference_backup_schedules_of_custom_plug_in_resources.html 
sidebar: sidebar 
keywords:  
summary: バックアップのスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率です。リソースをバックアップする回数が多いほど、リストア時に SnapCenter で使用する必要のあるアーカイブログの数が少なくなります。これにより、リストア処理の時間を短縮できます。 
---
= カスタムプラグインリソースのバックアップスケジュール
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップのスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率です。リソースをバックアップする回数が多いほど、リストア時に SnapCenter で使用する必要のあるアーカイブログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

使用頻度の高いリソースは 1 時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは 1 日に 1 回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービスレベルアグリーメント（ SLA ）、目標復旧時点（ RPO ）などがあります。

SLA は、サービスのレベルを定義し、サービスの可用性やパフォーマンスなど、サービス関連の多くの問題に対処します。RPO は、障害発生後に通常処理を再開するためにバックアップストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA と RPO はデータ保護戦略に関与します。

バックアップスケジュールには、次の 2 つの要素があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインではスケジュールタイプとも呼ばれます。たとえば、毎時、毎日、毎週、または毎月としてバックアップ頻度を設定できます。SnapCenter GUI でポリシーにアクセスするには、 * Settings * > * Policies * をクリックします。

* バックアップスケジュール
+
バックアップスケジュール（バックアップが実行される日時）は、リソースまたはリソースグループの設定の一部です。たとえば、リソースグループのポリシーで週に 1 回のバックアップが設定されている場合は、毎週木曜日の午後 10 時にバックアップが実行されるようにスケジュールを設定できますSnapCenter GUI でリソースグループのスケジュールにアクセスするには、 [* リソース ] をクリックし、適切なプラグインを選択して、 [* 表示 *>] 、 [* リソースグループ *] の順にクリックします。


