---
sidebar: sidebar 
permalink: sc-automation/concept_rest_web_services_foundation.html 
keywords: uri endpoints, http messages, json format 
summary: REST は、分散 Web アプリケーションを作成するためのスタイルです。WebサービスAPIの設計に適用すると、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、SnapCenterを管理するための柔軟な基盤を提供します。 
---
= 基盤となるREST Webサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Representational State Transfer（REST）は、分散Webアプリケーションを作成するための形式です。WebサービスAPIの設計に適用すると、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、SnapCenterを管理するための柔軟な基盤を提供します。



== リソースと状態の表示

リソースは、Webベースシステムの基本コンポーネントです。REST Webサービスアプリケーションを作成する際の初期設計タスクには、次のものがあります。



=== システムまたはサーバベースのリソースの識別

すべてのシステムはリソースを使用し、維持します。リソースには、ファイル、ビジネストランザクション、プロセス、または管理エンティティがあります。REST Webサービスに基づいてアプリケーションを設計する際の最初のタスクの1つは、リソースを特定することです。



=== リソースの状態および関連する状態操作の定義

リソースは常に有限数の状態のいずれかにあります。状態、および状態の変化に影響を与えるために使用される関連操作は、明確に定義する必要があります。



== URIエンドポイント

すべてのRESTリソースは、明確に定義されたアドレス指定方式を使用して定義および利用可能にする必要があります。リソースが配置され、識別されるエンドポイントでは、Uniform Resource Identifier（URI）が使用されます。

URIは、ネットワーク内の各リソースに一意の名前を作成するための一般的なフレームワークを提供します。Uniform Resource Locator（URL）は、リソースを識別してアクセスするためにWebサービスで使用されるURIの一種です。リソースは通常、ファイルディレクトリに似た階層構造で公開されます。



== HTTP メッセージ

Hypertext Transfer Protocol（HTTP）は、Webサービスのクライアントとサーバがリソースに関する要求と応答のメッセージを交換するために使用するプロトコルです。

Webサービスアプリケーションの設計の一環として、HTTPメソッドはリソースおよび対応する状態管理アクションにマッピングされます。HTTPはステートレスです。したがって、関連する一連の要求と応答を1つのトランザクションの一部として関連付けるには、要求と応答のデータフローで伝送されるHTTPヘッダーに追加情報を含める必要があります。



== JSONの形式

Webサービスのクライアントとサーバの間で情報を構造化して転送する方法はいくつかありますが、最も一般的な方法はJavaScript Object Notation（JSON）です。

JSONは、単純なデータ構造をプレーンテキストで表現するための業界標準であり、リソースを記述する状態情報の転送に使用されます。SnapCenter REST APIは、JSONを使用して、各HTTP要求と応答の本文で伝送されるデータをフォーマットします。
