---
permalink: sc-automation/reference_supported_rest_apis.html 
sidebar: sidebar 
keywords: REST API categories 
summary: SnapCenter REST API で使用できるリソースは、 SnapCenter API ドキュメントページに表示されるカテゴリ別に分類されています。 
---
= サポートされている REST API
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter REST API で使用できるリソースは、 SnapCenter API ドキュメントページに表示されるカテゴリ別に分類されています。以下に、各リソースの簡単な概要とベースリソースパスを示し、使用に際しての追加の考慮事項がある場合はその情報も示します。



== 認証

この API 呼び出しは、 SnapCenter サーバにログインする際に使用できます。この API は、以降の要求の認証に使用するユーザ認証トークンを返します。



== ドメイン

次の API 呼び出しを使用して次の処理を実行できます。

* すべてのドメインを取得します
* 特定のドメインの詳細を取得します
* ドメインを登録または登録解除します
* ドメインを変更します




== ジョブ

次の API 呼び出しを使用して次の処理を実行できます。

* すべてのジョブを取得します
* ジョブのステータスを取得します
* ジョブをキャンセルまたは停止します




== 設定

次の API 呼び出しを使用して次の処理を実行できます。

* クレデンシャルを登録、表示、変更、または削除します
* 通知を設定します




== ホスト

次の API 呼び出しを使用して次の処理を実行できます。

* ホストの詳細を取得します
* インストールされているプラグインとそのリソースの詳細を取得します
* プラグインホストを追加、削除、または変更する
* プラグインをインストールまたはアップグレードする




== リソース

次の API 呼び出しを使用して次の処理を実行できます。

* リソースの読み出し
* リソースを作成、変更、または削除する
* リソースを保護する
* リソースのバックアップ、リストア、クローニング




== バックアップ

次の API 呼び出しを使用して次の処理を実行できます。

* バックアップの詳細を取得します
* バックアップの名前変更または削除




== クローン

次の API 呼び出しを使用して次の処理を実行できます。

* クローンの詳細を取得します
* クローンを削除します。




== それ

次の API 呼び出しを使用して次の処理を実行できます。

* クローンスプリット処理のステータスを取得します
* クローンスプリット処理を開始または停止します




== リソースグループ

次の API 呼び出しを使用して次の処理を実行できます。

* リソースグループの詳細を取得する
* リソースグループを作成、変更、または削除する
* リソースグループをバックアップする




== ポリシー

次の API 呼び出しを使用して次の処理を実行できます。

* ポリシーの詳細を取得します
* ポリシーを作成、変更、または削除する




== ストレージ

次の API 呼び出しを使用して次の処理を実行できます。

* ストレージの詳細を取得します
* ストレージを作成、変更、または削除する
* ストレージ上のリソースを検出
* ストレージ上に共有を作成するか、削除します




== 共有

次の API 呼び出しを使用して次の処理を実行できます。

* 共有の詳細を取得します
* ストレージ上に共有を作成するか、削除します




== プラグイン

これらの API 呼び出しは、ホスト上のすべてのプラグインを取得し、さまざまな処理を実行するために使用できます。



== レポート

次の API 呼び出しを使用して次の処理を実行できます。

* バックアップ、リストア、クローニング、およびプラグインのレポートを生成する
* スケジュールを追加、実行、削除、または変更します




== アラート

次の API 呼び出しを使用して次の処理を実行できます。

* すべてのアラートを取得します
* アラートを削除します




== RBAC

次の API 呼び出しを使用して次の処理を実行できます。

* ユーザ、グループ、およびロールの詳細を取得します
* ユーザを追加します
* ロールを作成、変更、または削除します
* ロールおよびグループを割り当てまたは割り当て解除します




== 設定

次の API 呼び出しを使用して次の処理を実行できます。

* 構成設定を表示します
* 設定を変更します




== CertificateSettings

次の API 呼び出しを使用して次の処理を実行できます。

* 証明書のステータスを表示します
* 証明書の設定を変更します




== リポジトリ

次の API 呼び出しを使用して次の処理を実行できます。

* NSM リポジトリをバックアップしてリストアします
* NSM リポジトリを保護し、保護を解除します
* フェイルオーバー
* NSM リポジトリをリビルドします

