---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter のディザスタリカバリ機能では、 REST API を使用して SnapCenter サーバをバックアップします。 
---
= ディザスタリカバリ（DR）REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]


SnapCenter ディザスタリカバリ（ DR ）機能では、 REST API を使用して SnapCenter サーバをバックアップします。DR REST APIを使用する前に、次の手順を実行します。

* 手順 *

. DRバックアップREST APIを使用して、指定したサーバDRバックアップからSnapCenter サーバをリストアする新しいサーバDRバックアップを作成します。 `/4.5/disasterrecovery/server/backup`
. セカンダリサーバマシンを起動しますが、セカンダリサーバにSnapCenter サーバをインストールする前に、前提条件を満たしておく必要があります。
+
** 代替サーバのホスト名/ホストのFQDNはプライマリサーバのホスト名と同じである必要がありますが、IPアドレスは同じであってもかまいません。
** セカンダリサーバのバージョンは、プライマリサーバと同じである必要があります。
** セカンダリSnapCenter は、プライマリと同じ場所と同じポートにインストールする必要があります。


. サーバのDRリストア処理を開始する前に、災害後にDRバックアップが保存されるターゲットパスまたはパスを起動する必要があります。
+
** 次のコマンドを使用して、DRバックアップファイルが新しいSnapCenter サーバにコピーされていることを確認します。
`xcopy <Ssource_Path> \\<Destination_Server_IP>\<Folder_Path> /O /X /E /H /K {ex : xcopy C:\DRBackup \\10.225.81.114\c$\DRBackup /O /X /E /H /K}`


. セカンダリマシンにSnapCenter サーバをインストールします。
+
** DRリストア処理の実行中は、SnapCenter サーバに関連するジョブが実行されていないことを確認する必要があります。


. セカンダリSnapCenter サーバをプライマリサーバと同じ場所に、同じポートにインストールします。
+
** DRリストアAPIを使用して、サーバDRリストア処理を実行します。  `/4.5/disasterrecovery/server/restore`
+
プラグインがサーバのホスト名を解決できない場合は、各プラグインホストにログインし、新しいIPのetc/hostエントリを<New IP> SC_Server_Name形式で追加します。例： `10.225.81.35 SCServer1`

+
サーバの /etc/hosts エントリはリストアされません。DR バックアップフォルダから手動でリストアできます。






NOTE: F5セットアップの場合、リストア処理はスタンドアロンとして実行されます。F5を再度作成するには、一連のコマンドを実行する必要があります。を参照してください。リンク： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Migrate_SnapCenter_migrate_to_another_Server["SnapCenter を別のサーバに移行する方法"^]


NOTE: DRのリストア後にホストが追加されますが、プラグインを手動でインストールする必要があります。


NOTE: リポジトリのバックアップスケジュールは、SnapCenter Plug-in for WindowsをインストールしてサーバマシンにネットアップLUNを接続した場合にのみリストアされます。



== SnapCenter サーバのディザスタリカバリでサポートされる REST API

REST API を使用すると、 REST API Swagger ページで次の処理を実行できます。Swagger ページへのアクセス方法については、を参照してください link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["swagger API Web ページを使用して REST API にアクセスする方法"]。

* 必要なもの *

* SnapCenter 管理者ユーザとしてログインする必要があります。
* DR リストア API を実行するには、 SnapCenter サーバが稼働している必要があります。


* このタスクについて *

SnapCenter Server DR はすべてのプラグインをサポートします。

|===
| 説明 | REST API | HTTP メソッド 


 a| 
既存の SnapCenter サーバ DR バックアップを取得します


NOTE: DRバックアップを格納するターゲットパスを指定する必要があります。
 a| 
`/4.5/disasterrecovery/sa/backup?TargetPath={path}`
 a| 
取得



 a| 
新しいサーバ DR バックアップを作成します。
 a| 
「 /4.5/disasterrecovery/sa/backup 」
 a| 
投稿（ Post ）



 a| 
指定したサーバ DR バックアップから SnapCenter サーバをリストアします。
 a| 
「 /4.5/disasterrecovery/sa/restore 」
 a| 
投稿（ Post ）



 a| 
バックアップ名に基づいて Server DR バックアップを削除します。
 a| 
`/4.5/disasterrecovery/sa/backup``
 a| 
削除



 a| 
ストレージ DR を有効または無効にします
 a| 
「 /4.5/disasterrecovery/sstorage 」
 a| 
投稿（ Post ）

|===
詳細については、を参照してください https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["ディザスタリカバリ API"^] ビデオ：
