---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter のディザスタリカバリ機能では、 REST API を使用して SnapCenter サーバをバックアップします。 
---
= SnapCenter サーバのディザスタリカバリでサポートされる REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter ディザスタリカバリ（ DR ）機能では、 REST API を使用して SnapCenter サーバをバックアップします。REST API を使用すると、 REST API Swagger ページで次の処理を実行できます。Swagger ページへのアクセス方法については、を参照してください link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["swagger API Web ページを使用して REST API にアクセスする方法"]。

* 必要なもの *

* SnapCenter 管理者ユーザとしてログインする必要があります。
* DR リストア API を実行するには、 SnapCenter サーバが稼働している必要があります。


* このタスクについて *

SnapCenter Server DR はすべてのプラグインをサポートします。

[cols="10,40,50,10"]
|===
| ステップ | 説明 | REST API | HTTP メソッド 


 a| 
1.
 a| 
既存の SnapCenter サーバ DR バックアップを取得します


NOTE: DR バックアップを格納するバックアップの名前とターゲットパスを指定する必要があります。
 a| 
`/4.5/disasterrecovery/sa/backup?TargetPath={path}`
 a| 
取得



 a| 
2.
 a| 
新しいサーバ DR バックアップを作成します。指定したサーバ DR バックアップから SnapCenter サーバをリストアします。
 a| 
「 /4.5/disasterrecovery/sa/backup 」
 a| 
投稿（ Post ）



 a| 
3.
 a| 
指定したサーバ DR バックアップから SnapCenter サーバをリストアします。

* 前提条件 *

* 代替サーバのホスト名はプライマリサーバと同じにする必要がありますが、 IP アドレスは異なっていてもかまいません。
* サーバのバージョンはプライマリサーバと同じである必要があります。
* ホスト名はプライマリサーバと同じにする必要があります。
* 次のコマンドを使用して、 DR バックアップファイルが新しい SnapCenter サーバにコピーされていることを確認します。
+
xcopy <Ssource_Path>\< インストール先サーバー _ip>\< フォルダパス >/O/X/E/H/K {ex:xcopy C:\DRBackup\\10.225.81.114\c$\DRBackup/O/X/H/X/K}`



プラグインがサーバのホスト名を解決できない場合は、各プラグイン・ホストにログインし、新しい IP の /etc/hosts エントリを「 <New IP> SC_Server_Name 」の形式で追加します

たとえば、 10.225.81.35 SCServer1 と入力します

サーバの /etc/hosts エントリはリストアされません。DR バックアップフォルダから手動でリストアできます。
 a| 
「 /4.5/disasterrecovery/sa/restore 」
 a| 
投稿（ Post ）



 a| 
4.
 a| 
バックアップ名に基づいて Server DR バックアップを削除します。
 a| 
`/4.5/disasterrecovery/sa/backup``
 a| 
削除



 a| 
5.
 a| 
ストレージ DR を有効または無効にします
 a| 
「 /4.5/disasterrecovery/sstorage 」
 a| 
投稿（ Post ）

|===
詳細については、を参照してください https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["ディザスタリカバリ API"^] ビデオ：
