---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: REST APIはSwagger Webページから利用できます。Swagger Web ページにアクセスして SnapCenter サーバ REST API を表示したり、 API を手動で問題呼び出したりできます。REST API を使用して、 SnapCenter サーバの管理やデータ保護処理を行うことができます。 
---
= Swagger API Webページを使用してREST APIにアクセスする方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST APIはSwagger Webページから利用できます。Swagger Web ページにアクセスして SnapCenter サーバ REST API を表示したり、 API を手動で問題呼び出したりできます。REST API を使用して、 SnapCenter サーバの管理やデータ保護処理を行うことができます。

REST APIを実行するSnapCenterサーバの管理IPアドレスまたはドメイン名を確認しておく必要があります。

REST APIクライアントを実行するために特別な権限は必要ありません。すべてのユーザがSwagger Webページにアクセスできます。REST API経由でアクセスされるオブジェクトに対する権限は、REST APIにログインするためのトークンを生成したユーザに基づきます。

.手順
. ブラウザで、「_\ https：//<SnapCenter_IP_address_or_name>：<SnapCenter_port>/swagger/_」の形式でWebページにアクセスするためのURLを入力します。
+

NOTE: REST API URL に、 + 、 . 、 % 、 & の文字が含まれていないことを確認してください。

. SwaggerのExplore *フィールドに、Swagger APIドキュメントが自動的に表示されない場合は、次のように入力します。_\https：//<SnapCenter_IP_address_or_name>：<SnapCenter_port>/Content/swagger/SnapCenter.yaml_
. [* Explore] をクリックします。
+
APIリソースタイプまたはカテゴリのリストが表示されます。

. APIリソースタイプをクリックすると、そのリソースタイプのAPIが表示されます。


SnapCenter REST API の実行時に予期しない動作が発生した場合は、ログファイルを使用して原因を特定し、問題を解決することができます。SnapCenter ユーザー・インターフェイスからログ・ファイルをダウンロードするには、 * Monitor * > * Logs * > * Download * をクリックします。
