= 
:allow-uri-read: 


PowerShellコマンドレットを使用してデータ保護処理を実行するには、Storage Virtual Machine（SVM）接続とクレデンシャルを作成しておく必要があります。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージ接続を作成するには、Infrastructure Adminロールに必要な権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ホスト・プラグインのインストールは ' ストレージ・システム接続の追加中は実行しないでくださいホスト・キャッシュが更新されず ' データベース・ステータスが SnapCenter GUI に表示される場合がありますこれは ' バックアップには使用できませんまたは NetApp ストレージには使用できません

* ストレージシステム名は一意である必要があります。
+
SnapCenter では、異なるクラスタに同じ名前のストレージシステムを複数配置することはサポートされていません。SnapCenterでサポートする各ストレージシステムには、一意の名前と一意の管理LIF IPアドレスが必要です。



.手順
. Open-SmConnectionコマンドレットを使用して、PowerShell Core接続セッションを開始します。
+
この例では、PowerShellセッションを開きます。

+
[listing]
----
PS C:\> Open-SmConnection
----
. Add-SmStorageConnectionコマンドレットを使用して、ストレージシステムへの新しい接続を作成します。
+
新しいストレージシステム接続を作成する例を次に示します。

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Add-SmCredentialコマンドレットを使用して、新しいクレデンシャルを作成します。
+
この例では、Windowsクレデンシャルを使用してFinanceAdminという新しいクレデンシャルを作成します。

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
