---
permalink: protect-azure/add-hosts-install-plugin-for-oracle.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, oracle, database 
summary: ホストを追加してプラグインパッケージをインストールしてください。 
---
= ホストを追加してSnapCenter Plug-in for Oracle Databaseをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの追加ページを使用してホストを追加し、 SnapCenter Plug-ins Package for Linux または SnapCenter Plug-ins Package for AIX をインストールできます。プラグインは、自動的にリモートホストにインストールされます。

ホストの追加とプラグインパッケージのインストールは、個々のホストまたはクラスタに対して実行できます。クラスタ（Oracle RAC）にプラグインをインストールする場合、プラグインはクラスタのすべてのノードにインストールされます。Oracle RAC One Node の場合、このプラグインはアクティブノードとパッシブノードの両方にインストールする必要があります。

.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. [管理対象ホスト]*タブが選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の操作を実行します。
+
.. [Host Type]フィールドで、ホストタイプを選択します。
.. [Host name]フィールドに、ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。
.. [Credentials]フィールドに、作成したクレデンシャルを入力します。


. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
. （オプション）*[その他のオプション]*をクリックし、詳細を指定します。
. [Submit （送信） ] をクリックします。
. 指紋を確認し、 * 確認して送信 * をクリックします。
+
クラスタセットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

. インストールの進行状況を監視します。

