---
permalink: protect-azure/add-hosts-install-plugin-for-sap-hana.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SAP HANA 
summary: ホストを追加してプラグインパッケージをインストールしてください。 
---
= ホストを追加してSnapCenter Plug-in for SAP HANA Databaseをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの追加ページを使用 SnapCenter してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインは、自動的にリモートホストにインストールされます。

.作業を開始する前に
* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* 一元化されたホストにインストールする場合は、SAP HANAクライアントソフトウェアがそのホストにインストールされていることを確認し、SAP HANAデータベースホストで必要なポートを開いてHDB SQLクエリをリモートで実行します。


.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. [管理対象ホスト]*タブが選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の操作を実行します。
+
.. [Host Type]フィールドで、ホストタイプを選択します。
.. [Host name]フィールドに、ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。
.. [Credentials]フィールドに、作成したクレデンシャルを入力します。


. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
. （オプション）*[その他のオプション]*をクリックし、詳細を指定します。
. [Submit （送信） ] をクリックします。
. ホストタイプが Linux の場合は、フィンガープリントを確認し、 * Confirm and Submit * をクリックします。
+
クラスタセットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

. インストールの進行状況を監視します。

