---
permalink: protect-azure/create-backup-policies-oracle.html 
sidebar: sidebar 
keywords: create policies, Oracle, backup policies 
summary: バックアップするリソースまたはリソースグループのバックアップポリシーを作成します。 
---
= Oracleデータベースのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して Oracle データベースリソースをバックアップする前に、バックアップ対象のリソースまたはリソースグループのバックアップポリシーを作成する必要があります。

.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ドロップダウンリストから[Oracle Database]を選択します。
. [ 新規作成（ New ） ] をクリックする。
. [ 名前 ] ページで、ポリシー名と概要を入力します。
. [Backup Type] ページで、次の手順を実行します。
+
.. バックアップタイプとして、オンラインバックアップまたはオフラインバックアップを選択します。
.. スケジュール頻度を指定します。
.. Oracle Recovery Manager （ RMAN ）を使用してバックアップをカタログ化する場合は、 [* Catalog backup with Oracle Recovery Manager （ RMAN ） * ] を選択します。
.. バックアップ後にアーカイブ・ログのプルーニングを行う場合は、バックアップ後にアーカイブ・ログをプルーニング * を選択します。
.. アーカイブログの削除設定を指定します。


. [Retention]ページで、保持設定を指定します。
. スクリプトページで、バックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
. [Verification]ページで、検証処理を実行するバックアップスケジュールを選択し、検証処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
. 概要を確認し、 [ 完了 ] をクリックします。

