---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: SnapCenterでAzureクレデンシャルを作成し、Azure NetAppアカウントにアクセスします。 
---
= SnapCenterでAzureクレデンシャルを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetAppアカウントにアクセスするには、SnapCenterでAzureクレデンシャルを作成する必要があります。

.開始する前に
* Azureでサービスプリンシパルを作成したことを確認します。
* サービスプリンシパルに関連付けられたテナントID、クライアントID、およびシークレットキーが使用可能であることを確認します。
+
** テナントIDは、Azureポータルの[Entra ID]の[Overview]ページで確認できます。
** クライアントIDは、エンタープライズアプリケーション/サービスプリンシパルのアプリケーションIDとも呼ばれます。これは、SnapCenterのサービスプリンシパルとして機能するために作成したエンタープライズアプリケーションの[Overview]ページにあるAzureポータルで確認できます。
** クライアントシークレットキーは、シークレット値とも呼ばれます。このクライアントシークレットをAzure Portalで作成するには、[Entra ID]の*[App registrations]*に移動します。作成したエンタープライズアプリを選択したら、*[証明書とシークレット]*に移動し、*[新しいクライアントシークレット]*に移動します。
+

NOTE: シークレット値は、作成時にのみアクセスできます。あとからアクセスすることはできません。

** サービスプリンシパルに権限を付与する必要があります。Contributorのロールにより、サービスプリンシパルはAzureで必要なアクションを実行できます。これは、[サブスクリプション]ページの[アクセス制御（IAM）]ページから付与できます。




.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* 資格情報 ] をクリックします。
. [ 新規作成（ New ） ] をクリックする。
. [クレデンシャル]ページで、クレデンシャルの作成に必要な次の情報を指定します。
+
|===
| フィールド | 操作 


 a| 
クレデンシャル名
 a| 
クレデンシャルの名前を入力します。



 a| 
認証モード
 a| 
ドロップダウンリストから*[Azure Credential]*を選択します。



 a| 
テナントID
 a| 
テナントIDを入力します。



 a| 
クライアントID
 a| 
クライアントIDを入力します。



 a| 
クライアントシークレットキー
 a| 
クライアントシークレットキーを入力します。

|===
. [OK]*をクリックします。

