---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: SnapCenterには、システムの健全性と処理の成功を監視および管理するためのさまざまなレポートオプションが用意されています。 
---
= SnapCenterのレポート機能の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterには、システムの健全性と処理の成功を監視および管理するためのさまざまなレポートオプションが用意されています。

|===
| レポートタイプ | 説明 


 a| 
バックアップレポート
 a| 
バックアップレポートには、SnapCenter環境のバックアップ傾向に関する全体的なデータ、バックアップの成功率、および指定した期間に実行された各バックアップに関する情報が表示されます。バックアップが削除された場合、そのバックアップのステータス情報はレポートに表示されません。Backup Detail Report には、指定したバックアップジョブに関する詳細情報に加え、バックアップに成功したリソースと失敗したリソースの一覧が表示されます。



 a| 
クローンレポート
 a| 
Clone Report には、 SnapCenter 環境のクローニング状況に関する全体的なデータ、クローニングの成功率、および指定した期間に実行された各クローニングジョブに関する情報が表示されます。クローンが削除された場合、そのクローンのステータス情報はレポートに表示されません。Clone Detail Report には、指定したクローン、クローニングホスト、クローニングジョブタスクのステータスに関する詳細情報が表示されます。タスクが失敗した場合は、 Clone Detail Report にその情報が表示されます。



 a| 
リストアレポート
 a| 
Restore Report には、リストアジョブに関する全体的な情報が表示されます。Restore Detail Report には、指定したリストアジョブについて、ホスト名、バックアップ名、ジョブの開始日時と期間、個々のジョブタスクのステータスなどの詳細情報が表示されます。タスクが失敗した場合は、 Restore Detail Report にその情報が表示されます。



 a| 
保護レポート
 a| 
これらのレポートには、すべての SnapCenter プラグインインスタンスで管理されているリソースの保護の詳細が表示されます。このレポートには、すべてのプラグインインスタンスで管理されているリソースについて、保護の詳細が表示されます。概要のほか、保護されていないリソース、レポートの生成時にバックアップされていないリソース、バックアップ処理に失敗したリソースグループのリソース、およびSnapVaultのステータスを確認できます。



 a| 
スケジュール済みレポート
 a| 
これらのレポートは、毎日、毎週、毎月のように定期的に実行されるようにスケジュールされています。レポートは指定された日時に自動的に生成され、電子メールで各ユーザーに送信されます。スケジュールは、有効化、無効化、変更、または削除できます。有効なスケジュールは、 [ 今すぐ実行 ] ボタンをクリックして、オンデマンドで実行できます。管理者は任意のスケジュールを実行できますが、生成されるレポートには、スケジュールを作成したユーザから提供された権限に基づいたデータが含まれます。

Administrator以外のユーザは、権限に基づいてスケジュールを表示または変更できます。 [ロールの追加]ページで[このロールのすべてのメンバーが他のメンバーのオブジェクトを表示できる]オプションが選択されている場合は、そのロールの他のメンバーが表示および変更できます。

|===


== レポートへのアクセス

SnapCenter のダッシュボードを使用すると、システムヘルスの概要を簡単に確認できます。ダッシュボードでは、詳細をドリルダウンできます。または、詳細レポートに直接アクセスすることもできます。

次のいずれかの方法でレポートにアクセスできます。

* 左側のナビゲーションペインで、 * ダッシュボード * をクリックし、 * 前回の保護の概要 * 円グラフをクリックして、レポートページに詳細を表示します。
* 左側のナビゲーションペインで、 * Reports * をクリックします。




== レポートのフィルタ

必要な情報の詳細レベルと期間に応じて、パラメータの範囲に基づいてレポートデータをフィルタリングできます。

* 手順 *

. 左側のナビゲーションペインで、 * Reports * をクリックします。
. パラメータービューが表示されていない場合は、レポートツールバーの * パラメーター領域の切り替え * アイコンをクリックします。
. レポートを実行する時間範囲を指定します。+ 終了日を省略すると、使用可能なすべての情報が取得されます。
. 次のいずれかの条件に基づいてレポート情報をフィルタリングします。
+
** リソースグループ
** ホスト
** ポリシー
** リソース
** ステータス
** プラグイン名


. [ 適用（ Apply ） ] をクリックします。




== レポートのエクスポートまたは印刷

SnapCenter レポートをエクスポートすると、さまざまな形式でレポートを表示できます。レポートを印刷することもできます。

* 手順 *

. 左側のナビゲーションペインで、 * Reports * をクリックします。
. レポートツールバーから、次のいずれかを実行します。
+
** プリント可能なレポートをプレビューするには、 * プリントプレビューの切り替え * アイコンをクリックします。
** レポートを別の形式にエクスポートするには、 * Export * icon ドロップダウンリストから形式を選択します。


. レポートを印刷するには、 * 印刷 * アイコンをクリックします。
. 特定のレポートサマリーを表示するには、レポートの該当するセクションまでスクロールします。




== Eメール通知用のSMTPサーバの設定

データ保護ジョブのレポートを自分や他のユーザに送信する際に使用するSMTPサーバを指定できます。テスト用Eメールを送信して設定を確認することもできます。この設定は、 E メール通知を設定したすべての SnapCenter ジョブにグローバルに適用されます。

このオプションは、すべてのデータ保護ジョブレポートを送信するためのSMTPサーバを設定します。ただし、特定のリソースに対する SnapCenter データ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソースグループの作成時に SnapCenter レポートを E メールで送信するオプションを設定できます。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. 設定ページで、 * グローバル設定 * をクリックします。
. SMTP サーバーを入力し、 * 保存 * をクリックします。
. テスト用 E メールを送信するには、 E メールの送信元と送信先の E メールアドレスを入力し、件名を入力して、「 * 送信 * 」をクリックします。




== レポートをEメールで送信するオプションの設定

SnapCenter データ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソースグループの作成時に SnapCenter レポートを E メールで送信するオプションを設定します。

.開始する前に
[設定]の[グローバル設定]ページでSMTPサーバを設定しておく必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. 表示するリソースのタイプを選択し、 * 新規リソースグループ * をクリックするか、既存のリソースグループを選択して * 変更 * をクリックし、既存のリソースグループの E メールレポートを設定します。
. 新しいリソースグループウィザードの通知パネルで、レポートを常に受信するか、エラーが発生したか、またはエラーや警告を受信するかをプルダウンメニューから選択します。
. Eメールの送信元アドレス、Eメールの送信先アドレス、およびEメールの件名を入力します。

