---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords:  
summary: リソースまたはリソースグループからポリシーの適用を解除したり、ポリシーの変更、削除、表示、コピーを行ったりすることができます。 
---
= ポリシーを管理する
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースまたはリソースグループからポリシーの適用を解除したり、ポリシーの変更、削除、表示、コピーを行ったりすることができます。



== ポリシーを変更する

リソースまたはリソースグループにポリシーが適用されている場合は、レプリケーションのオプション、 Snapshot コピーの保持の設定、エラーの再試行回数、またはスクリプトの情報を変更できます。スケジュールタイプ（頻度）は、ポリシーを適用解除しないと変更できません。

* このタスクについて *

SnapCenter サーバでは、リソースまたはリソースグループにポリシーが適用されるときにのみスケジュールタイプが登録されるため、ポリシーのスケジュールタイプを変更するには追加の手順が必要です。

|===
| 状況 | 作業 


 a| 
新しいスケジュールタイプを追加します
 a| 
新しいポリシーを作成し、必要なリソースまたはリソースグループに適用します。

たとえば、リソースグループポリシーで毎時バックアップのみが指定されている場合に、日次バックアップの追加が必要となったときは、日次スケジュールタイプを設定したポリシーを作成してリソースグループに追加できます。リソースグループには、「 hourly 」と「 daily 」の 2 つのポリシーが設定されます。



 a| 
スケジュールタイプを削除または変更
 a| 
次の手順を実行します。

. そのポリシーを使用するすべてのリソースとリソースグループからポリシーを適用解除します。
. スケジュールタイプを変更
. すべてのリソースとリソースグループにポリシーを適用し直します。


たとえば、ポリシーで毎時バックアップが指定されている場合に、これを日次バックアップに変更するには、まずポリシーを適用解除する必要があります。

|===
* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ポリシーを選択し、 * 変更 * をクリックします。
. 情報を変更して、 [ 完了 ] をクリックします。




== ポリシーを適用解除

リソースのデータ保護を管理するポリシーが不要となった場合は、リソースまたはリソースグループからいつでもポリシーの適用を解除できます。ポリシーを削除する場合やスケジュールタイプを変更する場合は、事前にポリシーの適用を解除する必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * リソースグループの変更 * をクリックします。
. リソースグループの変更ウィザードのポリシーページで、ドロップダウンリストから、適用解除するポリシーの横にあるチェックマークをオフにします。
. ウィザードの残りの部分でリソースグループに追加の変更を加えてから、 [ 完了 ] をクリックします。




== ポリシーを削除する

不要になったポリシーは削除することができます。

* 必要なもの *

ポリシーがいずれかのリソースまたはリソースグループに関連付けられている場合は、リソースまたはリソースグループからポリシーの適用を解除する必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ポリシーを選択し、 * 削除 * をクリックします。
. 「 * はい * 」をクリックします。

