---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords:  
summary: ストレージシステムを追加したあとで、ストレージシステムの設定や接続を変更したり、ストレージシステムを削除したりできます。 
---
= ストレージシステムを管理
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムを追加したあとで、ストレージシステムの設定や接続を変更したり、ストレージシステムを削除したりできます。



== ストレージシステム構成を変更する

ユーザ名、パスワード、プラットフォーム、ポート、プロトコルを変更する場合、 SnapCenter を使用してストレージシステムの設定を変更できます。 タイムアウト時間、優先 IP アドレス、またはメッセージングオプション。

* このタスクについて *

個々のユーザまたはグループのストレージ接続を変更できます。同じストレージシステムに対する権限を持つ 1 つ以上のグループに所属している場合は、ストレージ接続リストにストレージ接続名が複数回表示されます。ストレージシステムへの権限を持つ各グループに対して 1 回ずつ表示されます。

* 手順 *

. 左側のナビゲーションペインで、 * ストレージシステム * をクリックします。
. Storage Systems （ストレージシステム）ページの * Type （タイプ） * ドロップダウンから、次のいずれかの操作を実行します。
+
|===
| 選択するオプション | 手順 


 a| 
ONTAP SVMs
 a| 
追加されたすべての Storage Virtual Machine （ SVM ）を表示し、必要な SVM の設定を変更するには、次の手順を実行します。

.. ストレージ接続ページで、適切な SVM 名をクリックします。
.. 次のいずれかを実行します。
+
*** SVM がどのクラスタにも含まれていない場合は、ストレージシステムの変更ページで、ユーザ名、パスワード、 EMS および AutoSupport の設定、プラットフォーム、プロトコル、ポート、タイムアウト、 優先 IP アドレスを指定します。
*** SVM がクラスタの一部である場合は、ストレージシステムの変更ページで「 SVM の個別管理」を選択し、ユーザ名、パスワード、 EMS および AutoSupport の設定、プラットフォーム、プロトコル、ポート、タイムアウト、 優先 IP アドレスを指定します。
+
SVM を個別に管理できるように変更した場合は、クラスタから SVM を削除し、 * 再検出 * をクリックしてください。SVM が ONTAP クラスタに追加されます。

+

NOTE: SnapCenter GUI でストレージシステムのパスワードが更新された場合、更新されたパスワードが SMCore に反映されないために、該当するプラグインまたはサーバホストの SMCore サービスを再起動する必要があります。この場合、バックアップジョブが誤ったクレデンシャルエラーで失敗します。







 a| 
ONTAP クラスタ
 a| 
追加されたすべてのクラスタを表示し、必要なクラスタ設定を変更するには、次の手順を実行します。

.. [ ストレージ接続 ] ページで、クラスタ名をクリックします。
.. Modify Storage System ページで、 Username の横の編集アイコンをクリックして、ユーザ名とパスワードを変更します。
.. EMS と AutoSupport の設定を選択またはクリアします。
.. [ * その他のオプション * ] をクリックして、プラットフォーム、プロトコル、ポート、タイムアウト、優先 IP などの他の設定を変更します。


|===
. [Submit （送信） ] をクリックします。




== ストレージシステムを削除

SnapCenter を使用して、使用していないストレージシステムを削除できます。

* このタスクについて *

個々のユーザまたはグループのストレージ接続を削除できます。同じストレージシステムに対する権限を持つ 1 つ以上のグループに所属している場合は、ストレージシステム名がストレージ接続リストに複数回表示されます。ストレージシステムへの権限を持つ各グループに 1 回ずつ表示されます。


IMPORTANT: ストレージシステムを削除すると、そのストレージシステムで実行されているすべての処理が失敗します。

* 手順 *

. 左側のナビゲーションペインで、 * ストレージシステム * をクリックします。
. ストレージシステムページの * タイプドロップダウンから、 * ONTAP SVM * または * ONTAP クラスタ * のいずれかを選択します。
. ストレージ接続ページで、 SVM の横にあるチェックボックスまたは削除するクラスタを選択します。
+

NOTE: クラスタに含まれる SVM は選択できません。

. [ 削除（ Delete ） ] をクリックします。
. Delete Storage System Connection Settings （ストレージシステム接続設定の削除）ページで、 * OK * をクリックします。
+

NOTE: ONTAP GUI を使用して ONTAP クラスタから SVM を削除した場合は、 SnapCenter GUI で * Rediscover* をクリックして SVM リストを更新します。


