---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: 'SnapCenterの左側のナビゲーションペインから[Dashboard]にアクセスすると、最近のジョブアクティビティ、アラート、保護の概要、Storage Efficiencyと使用状況、SnapCenterジョブのステータス（バックアップ、クローン、リストア\）、スタンドアロンホストとWindowsクラスタホストの設定ステータスなど、システムの健常性の概要を確認できます。 SnapCenterで管理しているStorage Virtual Machine（SVM）の数とライセンス容量。' 
---
= ダッシュボードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter の左側のナビゲーションペインで、ダッシュボードを使用すると、最近のジョブアクティビティ、アラート、保護の概要、ストレージの効率性と使用状況、 SnapCenter ジョブのステータス（バックアップ、クローン、リストア）、スタンドアロンおよび Windows クラスタホストの構成ステータスなど、システムの健全性を一目で把握できます。 SnapCenter で管理されている Storage Virtual Machine （ SVM ）の数とライセンス容量。

ダッシュボードビューに表示される情報は、 SnapCenter に現在ログインしているユーザに割り当てられたロールによって異なります。ユーザにその情報を表示する権限がない場合、一部のコンテンツが表示されないことがあります。

多くの場合、 * i * にカーソルを合わせると、ディスプレイに関する詳細情報を表示できます。状況によっては、リソース、モニタ、レポートなどの SnapCenter GUI ページの詳細なソース情報にダッシュボードの情報がリンクされていることがあります。



== 最近のジョブアクティビティ

[最近のジョブアクティビティ]タイルには、アクセス可能なバックアップ、リストア、クローンジョブの最新のジョブアクティビティが表示されます。この表示のジョブには、完了、警告、失敗、実行中、キューに登録済み、 キャンセルされました。

ジョブにカーソルを合わせると、詳細が表示されます。ジョブ番号をクリックすると[監視]ページにリダイレクトされ、その他のジョブ情報を表示できます。そこからジョブの詳細またはログ情報を取得し、そのジョブに固有のレポートを生成できます。

すべての SnapCenter ジョブの履歴を表示するには、 * すべて表示 * をクリックします。



== アラート

[アラート]タイルには、ホストおよびSnapCenterサーバに関する未解決の重大アラートと警告アラートの最新情報が表示されます。

重大アラートと警告アラートの総数が画面上部に表示されます。重大または警告の合計をクリックすると、[アラート]ページにリダイレクトされ、[アラート]ページで特定のフィルタが適用されます。

特定のアラートをクリックすると、そのアラートの詳細が表示される[アラート]ページにリダイレクトされます。ディスプレイの下部にある [*See All*]( すべてを表示 ) をクリックすると、 [Alerts] ページにすべてのアラートのリストが表示されます。



== 最新の保護サマリ

[最新の保護サマリ]タイルには、アクセス可能なすべてのエンティティの保護ステータスが表示されます。デフォルトでは、すべてのプラグインのステータスが表示されます。ステータス情報は、Snapshotとしてプライマリストレージにバックアップされたリソース、およびSnapMirrorテクノロジとSnapVaultテクノロジを使用してセカンダリストレージにバックアップされたリソースについて提供されます。セカンダリストレージの保護ステータス情報が表示されるかどうかは、選択したプラグインタイプによって決まります。


NOTE: mirror-vault保護ポリシーを使用している場合は、保護概要のカウンタがSnapVaultの概要グラフに表示され、SnapMirrorのグラフには表示されません。

ドロップダウンメニューからプラグインを選択すると、個 々 のプラグインの保護ステータスを確認できます。ドーナツチャートには、選択したプラグインで保護されているリソースの割合が表示されます。 ドーナツチャートのスライスをクリックすると、*[レポート]*>*[プラグイン]*ページにリダイレクトされます。このページには、指定したプラグインのすべてのプライマリストレージとセカンダリストレージのアクティビティに関する詳細なレポートが表示されます。


IMPORTANT: セカンダリストレージに関するレポートはSnapVaultにのみ適用されます。SnapMirrorレポートはサポートされません。


NOTE: SAP HANAは、Snapshotのプライマリストレージとセカンダリストレージの保護ステータス情報を提供します。ファイルベースのバックアップでは、プライマリストレージの保護ステータスのみを使用できます。

|===
| 保護ステータス | プライマリストレージ | セカンダリストレージ 


 a| 
失敗
 a| 
バックアップに失敗したリソースグループに属しているエンティティの数。
 a| 
セカンダリデスティネーションへのバックアップの転送に失敗したエンティティの数。



 a| 
成功
 a| 
バックアップに成功したリソースグループに所属しているエンティティの数。
 a| 
セカンダリデスティネーションへのバックアップの転送が完了したエンティティの数。



 a| 
未設定
 a| 
いずれのリソースグループにも属しておらず、バックアップされていないエンティティの数。
 a| 
バックアップをセカンダリデスティネーションに転送するように設定されていないリソースグループに属しているエンティティの数。



 a| 
未開始
 a| 
リソースグループに属しているが、バックアップが実行されていないエンティティの数。
 a| 
該当なし。

|===

NOTE: SnapCenter Server 4.2 以前のバージョンのプラグイン（ 4.2 より前）を使用してバックアップを作成している場合、最新の保護概要 * タイルには、これらのバックアップの SnapMirror 保護ステータスは表示されません。



== ジョブ

[ジョブ]タイルには、アクセス可能なバックアップ、リストア、およびクローニングジョブの概要が表示されます。ドロップダウンメニューを使用して、レポートの期間をカスタマイズできます。期間のオプションは、過去24時間、過去7日間、および過去30日間に固定されています。デフォルトのレポートには、過去7日間に実行されたデータ保護ジョブが表示されます。

バックアップ、リストア、およびクローニングジョブの情報がドーナツチャートに表示されます。ドーナツチャートのスライスをクリックすると[モニタ]ページにリダイレクトされ、選択したジョブにフィルタが適用されます。

|===
| ジョブステータス | 説明 


 a| 
失敗
 a| 
失敗したジョブ数。



 a| 
警告
 a| 
エラーが発生したジョブ数。



 a| 
成功
 a| 
正常に完了したジョブ数。



 a| 
実行中
 a| 
実行中のジョブ数。

|===


== ストレージ

[ストレージ]タイルには、90日間に保護ジョブで使用されたプライマリストレージとセカンダリストレージが表示されます。消費傾向とプライマリストレージの削減量が図で示されます。ストレージ情報は、24時間ごとに午前12時に更新されます。

この日の合計消費量は、 SnapCenter で使用できるバックアップの合計数と、これらのバックアップが占有するサイズで構成され、画面の上部に表示されます。1つのバックアップに複数のSnapshotが関連付けられている場合、その数には同じSnapshotが含まれます。これは、プライマリSnapshotとセカンダリSnapshotの両方に該当します。たとえば、バックアップを10個作成し、そのうちの2個はポリシーベースのバックアップ保持に基づいて削除され、1個はユーザが明示的に削除したとします。したがって、バックアップ数が7個と、これら7個のバックアップが占有するサイズが表示されます。

プライマリストレージのストレージ削減率は、プライマリストレージの物理容量に対する論理容量（クローンとSnapshotによる削減量とストレージ消費量の合計）の比率です。棒グラフはストレージ削減量を示しています。

折れ線グラフには、過去90日間のプライマリストレージとセカンダリストレージの日単位の消費量が表示されます。グラフにカーソルを合わせると、1日ごとの詳細な結果が表示されます。


NOTE: SnapCenter Server 4.2 以前のバージョンのプラグイン（ 4.2 より前）を使用してバックアップを作成する場合、「ストレージ」タイルには、バックアップ数、バックアップで消費されるストレージ容量、 Snapshot の削減量、クローンの削減量、および Snapshot のサイズは表示されません。



== 構成

[設定]タイルには、SnapCenterで管理していてアクセス可能なすべてのアクティブなスタンドアロンホストとWindowsクラスタホストのステータス情報が統合されて表示されます。これには、ホストに関連付けられているプラグインのステータス情報も含まれます。

[Hosts]の横にある数字をクリックすると、[Hosts]ページの[Managed Hosts]セクションにリダイレクトされます。そこから、選択したホストの詳細情報を取得できます。

さらに、 SnapCenter で管理しているスタンドアロンの ONTAP ONTAP とクラスタ SVM の合計と、アクセス権があることが表示されます。[SVM]の横にある数字をクリックすると、[ストレージシステム]ページにリダイレクトされます。そこから、選択したSVMの詳細情報を取得できます。

ホストの構成状態は、赤（重大）、黄（警告）、緑（アクティブ）のほか、各状態のホスト数も表示されます。状態ごとにステータスメッセージが表示されます。

|===
| 設定ステータス | 説明 


 a| 
アップグレードが必要
 a| 
サポートされていないプラグインを実行していてアップグレードが必要なホストの数。サポートされていないプラグインは、このバージョンのSnapCenterと互換性がありません。



 a| 
移行が必要
 a| 
実行しているプラグインがサポートされておらず、移行が必要なホストの数。サポートされていないプラグインは、このバージョンのSnapCenterと互換性がありません。



 a| 
プラグインがインストールされていません
 a| 
追加されたがプラグインのインストールが必要なホスト、またはプラグインのインストールに失敗したホストの数。



 a| 
中断
 a| 
スケジュールが中断されてメンテナンス中のホストの数。



 a| 
停止
 a| 
稼働しているがプラグインサービスが実行されていないホストの数。



 a| 
ホスト停止
 a| 
停止しているか到達できないホストの数。



 a| 
アップグレード可能（オプション）
 a| 
新しいバージョンのプラグインパッケージにアップグレード可能なホストの数。



 a| 
移行可能（オプション）
 a| 
新しいバージョンのプラグインを移行可能なホストの数。



 a| 
ログディレクトリの設定
 a| 
SCSQLでトランザクションログバックアップを作成するためにログディレクトリの設定が必要なホストの数。



 a| 
VMware プラグインを設定
 a| 
SnapCenter Plug-in for VMware vSphereを追加する必要があるホストの数。



 a| 
不明
 a| 
登録されているがインストールがまだ開始されていないホストの数。



 a| 
実行中
 a| 
稼働していてプラグインが実行されているホストの数。SCSQLプラグインの場合は、ログディレクトリとハイパーバイザーが設定されています。



 a| 
プラグインをインストール中/アンインストール中
 a| 
プラグインのインストールまたはアンインストールを実行中のホストの数。

|===