---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: リソースまたはリソースグループからポリシーの適用解除、変更、削除、表示、コピーを行うことができます。 
---
= ポリシーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースまたはリソースグループからポリシーの適用解除、変更、削除、表示、コピーを行うことができます。



== ポリシーの変更

リソースまたはリソースグループにポリシーが適用されている場合は、レプリケーションオプション、Snapshotの保持設定、エラーの再試行回数、またはスクリプトの情報を変更できます。スケジュールタイプ（頻度）を変更するには、ポリシーを適用解除する必要があります。

* このタスクについて *

SnapCenter サーバでは、リソースまたはリソースグループにポリシーが適用されるときにのみスケジュールタイプが登録されるため、ポリシーのスケジュールタイプを変更するには追加の手順が必要です。

|===
| 状況 | 作業 


 a| 
スケジュールタイプを追加する
 a| 
新しいポリシーを作成し、必要なリソースまたはリソースグループに適用します。

たとえば、リソースグループポリシーで毎時バックアップのみが指定されている場合に、日次バックアップも追加するには、dailyスケジュールタイプのポリシーを作成してリソースグループに追加します。リソースグループには、hourlyとdailyの2つのポリシーが設定されます。



 a| 
スケジュールタイプを削除または変更する
 a| 
次の手順を実行します。

. そのポリシーを使用するすべてのリソースとリソースグループからポリシーの適用を解除します。
. スケジュールタイプを変更します。
. すべてのリソースとリソースグループにポリシーを再度適用します。


たとえば、ポリシーで毎時バックアップが指定されている場合に、それを日次バックアップに変更するには、最初にポリシーの適用を解除する必要があります。

|===
* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ポリシーを選択し、 * 変更 * をクリックします。
. 情報を変更して、 [ 完了 ] をクリックします。




== ポリシーの適用解除

リソースのデータ保護を管理するポリシーが不要になった場合は、リソースまたはリソースグループからいつでもポリシーの適用を解除できます。ポリシーを削除する前、またはスケジュールタイプを変更する前に、ポリシーの適用を解除する必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * リソースグループの変更 * をクリックします。
. リソースグループの変更ウィザードのポリシーページで、ドロップダウンリストから、適用解除するポリシーの横にあるチェックマークをオフにします。
. ウィザードの残りの部分でリソースグループに追加の変更を加えてから、 [ 完了 ] をクリックします。




== ポリシーの削除

不要になったポリシーは削除することができます。

.開始する前に
ポリシーがリソースまたはリソースグループに関連付けられている場合は、ポリシーの適用を解除する必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ポリシーを選択し、 * 削除 * をクリックします。
. 「 * はい * 」をクリックします。

