---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords: SnapCenter Server 
summary: SnapCenter から実行される各種の処理に関する情報は、 SnapCenter サーバのデータベースリポジトリに格納されます。SnapCenter サーバをデータ損失から保護するには、リポジトリのバックアップを作成する必要があります。 
---
= SnapCenterサーバリポジトリの管理
:allow-uri-read: 


[role="lead"]
SnapCenter から実行される各種の処理に関する情報は、 SnapCenter サーバのデータベースリポジトリに格納されます。SnapCenter サーバをデータ損失から保護するには、リポジトリのバックアップを作成する必要があります。

SnapCenter サーバリポジトリは、NSMデータベースと呼ばれることもあります。使用可能なすべてのコマンドレットの詳細については、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]を参照してください。



== SnapCenter リポジトリを保護するための前提条件

SnapCenterリポジトリを保護するには、環境が一定の前提条件を満たしている必要があります。

* Storage Virtual Machine（SVM）接続の管理
+
ストレージクレデンシャルを設定する必要があります。

* ホストのプロビジョニング
+
SnapCenter リポジトリのホストに、ネットアップストレージディスクが少なくとも 1 つ必要です。SnapCenter リポジトリのホストにネットアップディスクがない場合は作成する必要があります。

+
ホストの追加、 SVM 接続のセットアップ、およびホストのプロビジョニングの詳細については、インストール手順を参照してください。

* iSCSI LUNまたはVMDKのプロビジョニング
+
ハイアベイラビリティ（HA）構成の場合は、いずれかのSnapCenter ServerでiSCSI LUNまたはVMDKのいずれかをプロビジョニングできます。





== SnapCenterリポジトリのバックアップ

SnapCenter サーバリポジトリをバックアップすると、データ損失からデータを保護できます。リポジトリをバックアップするには、 `Protect-SmRepository` コマンドレットを実行します。

.タスクの内容
 `Protect-SmRepository`コマンドレットは、次のタスクを実行します：

* リソースグループとポリシーを作成
* SnapCenter リポジトリのバックアップスケジュールを作成します


.手順
. PowerShellを起動します。
. SnapCenter サーバーホストで、 `Open-SmConnection` コマンドレットを使用してセッションを確立し、クレデンシャルを入力します。
. リポジトリをバックアップするには、次の必須パラメータを受け取る `Protect-SmRepository` コマンドレットを使用します：
+
.. `-HostName (String)`：SnapCenter リポジトリが配置されているサーバーのホスト名を指定します。
.. `-Path (String)`：リポジトリのバックアップが保存されるNetAppストレージシステム上のファイルシステムパスを指定します。
.. `-Schedule (Hashtable)`：リポジトリのバックアップスケジュールを定義します。一般的にはハッシュテーブルとして定義されます。
.. `-RetentionCount (Int32)`：保持するリポジトリバックアップの数を指定します。バックアップの数がこの上限を超えると、最も古いバックアップが削除されます。






== SnapCenterリポジトリのバックアップの表示

 `Get-SmRepositoryBackups`コマンドレットを実行すると、SnapCenter サーバデータベースリポジトリのバックアップのリストを表示できます。詳細については、 https://docs.netapp.com/us-en/snapcenter-cmdlets/Get-SmRepositoryBackups.html["SnapCenter software コマンドレットリファレンスガイド - Get-SmRepositoryBackups"^]を参照してください。

リポジトリのバックアップは、 `Protect-SmRepository`コマンドレットで指定されたスケジュールに従って作成されます。

.手順
. PowerShellを起動します。
. コマンドプロンプトから、 `Open-SmConnection` コマンドレットを入力し、SnapCenter サーバに接続するための認証情報を指定します。
.  `Get-SmRepositoryBackups`コマンドレットを使用して、使用可能なすべてのSnapCenterデータベースバックアップをリストします。




== SnapCenterデータベースリポジトリのリストア

SnapCenterリポジトリを復元するには、 `Restore-SmRepositoryBackup`コマンドレットを実行します。

SnapCenterリポジトリを復元する際は、リストア処理中にリポジトリデータベースにアクセスできないため、実行中の他のSnapCenter処理に影響が出ます。

.手順
. PowerShellを起動します。
. コマンドプロンプトから、 `Open-SmConnection` コマンドレットを入力し、SnapCenter サーバに接続するための認証情報を指定します。
.  `Restore-SmRepositoryBackup` コマンドレットを使用してリポジトリのバックアップをリストアします。
+
次のコマンドレットでは、 iSCSI LUN または VMDK にあるバックアップから SnapCenter MySQL データベースリポジトリをリストアします。

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
バックアップファイルがiSCSI LUNから誤って削除された場合に、SnapCenterのMySQLデータベースをリストアするコマンドレットの例を次に示します。VMDKの場合は、ONTAPスナップショットからバックアップを手動でリストアします。

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----



NOTE: リストア処理の実行後にリポジトリバックアップが取得されると、リポジトリのリストア処理に使用されたバックアップはリストに表示されません。



== SnapCenterリポジトリを移行する

SnapCenter サーバのデータベースリポジトリをデフォルトの場所から別のディスクに移行することができます。リポジトリは、より多くのスペースがあるディスクに再配置する場合に移行できます。

.手順
. WindowsでMYSQL57サービスを停止します。
. MySQLのデータディレクトリを探します。
+
通常、データディレクトリはC:\ProgramData\MySQL\MySQL Server 5.7\Dataにあります。

. MySQLデータディレクトリを新しい場所（E：\Data\nsmなど）にコピーします。
. 新しいディレクトリを右クリックし、 * プロパティ * > * セキュリティ * を選択して、ネットワークサービスローカルサーバーアカウントを新しいディレクトリに追加し、アカウントにフルコントロールを割り当てます。
. 元のデータベースディレクトリ（nsm_copyなど）の名前を変更します。
. Windows のコマンドプロンプトで、 _mklink_command を使用してディレクトリのシンボリックリンクを作成します。
+
`"mklink /d "C:\ProgramData\MySQL\MySQL Server 5.7\Data\nsm" "E:\Data\nsm" "`

. WindowsでMYSQL57サービスを開始します。
. SnapCenter にログインしてリポジトリのエントリを確認するか、 MySQL ユーティリティにログインして新しいリポジトリに接続して、データベースの場所が正しく変更されたことを確認します。
. 名前を変更した元のデータベースリポジトリディレクトリ（nsm_copy）を削除します。




== SnapCenterリポジトリのパスワードをリセットする

MySQL Server リポジトリデータベースのパスワードは、 SnapCenter 4.2 以降の SnapCenter Server のインストール時に自動的に生成されます。この自動生成されたパスワードは、 SnapCenter ユーザにはいかなる時点でも知られていません。リポジトリデータベースにアクセスする場合は、パスワードをリセットする必要があります。

.開始する前に
パスワードをリセットするには、 SnapCenter 管理者の権限が必要です。

.手順
. PowerShellを起動します。
. コマンドプロンプトから、 `Open-SmConnection` コマンドレットを入力し、SnapCenter サーバに接続するための認証情報を指定します。
.  `Set-SmRepositoryPassword` コマンドレットを使用してリポジトリのパスワードをリセットします。
+
次のコマンドは、リポジトリパスワードをリセットします。

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


.関連情報
コマンドレットで使用できるパラメータとその説明に関する情報は、 `Get-Help command_name`コマンドを実行することで取得できます。または、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]を参照してください。
