---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords: Monitor jobs, schedules, events, logs 
summary: '[監視]ページでは、ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、イベントやログの確認を行うことができます。' 
---
= ジョブ、スケジュール、イベント、ログの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[監視]ページでは、ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、イベントやログの確認を行うことができます。



== ジョブの監視

SnapCenter のバックアップ、クローニング、リストア、検証の各ジョブに関する情報を表示できます。このビューは、開始日と終了日、ジョブのタイプ、リソース グループ、ポリシー、またはSnapCenterプラグインでフィルタできます。また、指定したジョブの詳細情報やログ ファイルを取得することもできます。

SnapMirror処理とSnapVault処理に関連するジョブを監視することもできます。


NOTE: 監視できるのは、SnapCenter管理者または別のスーパーユーザロールが割り当てられている場合を除き、自分が作成したジョブと自分に関連するジョブだけです。

ジョブの監視に関連して次のタスクを実行できます。

* バックアップ、クローニング、リストア、検証の各処理を監視する。
* ジョブの詳細とレポートを表示します。
* スケジュールされたジョブを停止する。




=== スケジュールされたバックアップジョブの管理

SnapCenter 6.0.1リリース以降では、新しいパラメータ* JobConcurrencyThreshold *が導入されました。このパラメータは、任意の時点で実行できるスケジュール済みジョブの数にしきい値を設定します。これにより、システムのハードウェア構成に基づいて実行するバックアップの数を制御できます。

JobConcurrencyThreshold *に割り当てられるデフォルト値は0で、無効になっています。スケジュール・バックアップ・ウィンドウ中にパフォーマンスの低下が見られた場合は'値を割り当てることによって有効にすることができます


NOTE: 同時ジョブを管理するために* JobConcurrencyThreshold *を有効にすると、SnapCenterではバックアップの順序を制御できず、スケジュールで指定した時刻にバックアップがトリガーされないことがあります。

.手順
. _C：\Program Files\WebApp\Web.UI.dll.config_にある_JobConcurrencyThreshold_parameterの値を設定しますNetApp SnapCenter SnapManager。
. [IIS]、[アプリケーションプール]、[ SnapCenter ]、[再起動]の順にクリックして、SnapCenterアプリケーションプールをリサイクルします。
. [IIS]、[サイト]、[ SnapCenter ]、[再起動]の順にクリックして、SnapCenter Webサービスを再起動します。




=== 古いジョブの管理

古いジョブは、SnapCenterの中断または不適切なジョブの更新によって作成されます。SnapCenter 6.0.1リリース以降では、72時間以上停止している古いジョブをクリーンアップするための事前定義されたスケジュールが導入されています。スケジュール頻度を変更するには、設定可能なパラメータ* CleanUpStaleJobsIntervalHours *を編集します。

オンデマンドでクリーンアップをトリガーするには、* Monitor *>* Schedules *>* SnapCenter _ StaleJobCleanUp *からスケジュールを実行します。

.手順
. _C:\Program NetApp SnapCenter WebApp\Web.UI.dll.config_にある_CleanUpStaleJobsIntervalHours_parameterの値を設定しますSnapManager。
. [IIS]、[アプリケーションプール]、[ SnapCenter ]、[再起動]の順にクリックして、SnapCenterアプリケーションプールをリサイクルします。
. [IIS]、[サイト]、[ SnapCenter ]、[再起動]の順にクリックして、SnapCenter Webサービスを再起動します。




== スケジュールの監視

現在のスケジュールを表示して、処理の開始日時、前回の実行日時、および次回の実行日時を確認できます。また、処理を実行するホスト、および処理のリソースグループとポリシーの情報を確認することもできます。

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * スケジュール * ] をクリックします。
. リソースグループとスケジュールタイプを選択します。
. スケジュールされた処理のリストを表示します。




== イベントを監視する

ユーザによるリソースグループの作成、システムによるアクティビティの開始、スケジュールされたバックアップの作成など、システム内の SnapCenter イベントのリストを表示できます。イベントを表示して、バックアップやリストアなどの処理が実行中かどうかを確認できます。

* このタスクについて *

[ イベント ] ページにすべてのジョブ情報が表示されます。たとえば ' バックアップ・ジョブが開始されると 'backup start' イベントが表示されますバックアップが完了すると ' backup complete イベントが表示されます

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * イベント * ] をクリックします。
. （任意） [ フィルタ ] ボックスに、開始日または終了日、イベントのカテゴリ（バックアップ、リソースグループ、ポリシーなど）、および重大度レベルを入力し、 [ 適用 *] をクリックします。または、検索ボックスに文字を入力します。
. イベントのリストを表示します。




== ログの監視

SnapCenter サーバログ、 SnapCenter ホストエージェントログ、およびプラグインログを表示およびダウンロードできます。ログを表示してトラブルシューティングに役立てることができます。

* このタスクについて *

フィルタを使用して、特定の重大度レベルのログだけを表示するように絞り込むことができます。

* デバッグ
* 情報
* 警告
* エラー
* 致命的


ジョブレベルのログ（バックアップジョブが失敗した理由のトラブルシューティングに役立つログなど）を取得することもできます。ジョブ・レベル・ログの場合は、 * Monitor * > * Jobs * オプションを使用します。

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [Jobs]ページで、ジョブを選択し、[Download logs]をクリックします。
+
ダウンロードしたzipフォルダには、ジョブログと共通のログが含まれています。zip形式のフォルダ名には、選択したジョブIDとジョブタイプが含まれています。

. [ モニター ] ページで、 [ * ログ * ] をクリックします。
. ログタイプ、ホスト、およびインスタンスを選択します。
+
ログタイプとして* plugin *を選択した場合は、ホストまたはSnapCenterプラグインを選択できます。 ログタイプが* server *の場合、この操作はできません。

. 特定のソース、メッセージ、またはログレベルでログをフィルタリングするには、列見出しの上部にあるフィルタアイコンをクリックします。
+
すべてのログを表示するには、レベルとして*以上*を選択します `Debug` 。

. [* 更新 * ] をクリックします。
. ログの一覧を確認します。
. ログをダウンロードするには、 * Download * をクリックします。
+
ダウンロードしたzipフォルダには、ジョブログと共通のログが含まれています。zip形式のフォルダ名には、選択したジョブIDとジョブタイプが含まれています。



大規模な構成でパフォーマンスを最適化するには、PowerShellコマンドレットを使用して、SnapCenterのログ設定を最小レベルに設定します。

`Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`


NOTE: フェイルオーバージョブの完了後に健常性や設定の情報にアクセスするには、コマンドレットを実行し `Get-SmRepositoryConfig`ます。



== SnapCenterからのジョブとログの削除

バックアップ、リストア、クローニング、および検証の各ジョブとそのログを SnapCenter から削除できます。SnapCenter では、ジョブの成否にかかわらず、削除しないかぎりログは永久に保存されます。ジョブのログを削除することで、ストレージの空きを増やすことができます。

* このタスクについて *

実行中のジョブがないことを確認してください。ジョブIDを指定して特定のジョブを削除することも、指定した期間内にジョブを削除することもできます。

ジョブを削除するためにホストをメンテナンスモードにする必要はありません。

* 手順 *

. PowerShellを起動します。
. コマンドプロンプトで、次のように入力します。 `Open-SMConnection`
. コマンドプロンプトで、次のように入力します。 `Remove-SmJobs`
. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * ジョブ * ] をクリックします。
. [Jobs]ページで、ジョブのステータスを確認します。


.関連情報
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
