---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter の左側のナビゲーションペインで、ダッシュボードには、最近のジョブアクティビティ、アラート、保護の概要、ストレージの効率性と使用状況、 SnapCenter ジョブのステータス（バックアップ、クローン、リストア）、スタンドアロンおよび Windows クラスタホストの構成ステータスなど、システムの健全性が一目でわかります。 SnapCenter で管理されている Storage Virtual Machine （ SVM ）の数とライセンス容量。 
---
= ダッシュボードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter の左側のナビゲーションペインで、ダッシュボードを使用すると、最近のジョブアクティビティ、アラート、保護の概要、ストレージの効率性と使用状況、 SnapCenter ジョブのステータス（バックアップ、クローン、リストア）、スタンドアロンおよび Windows クラスタホストの構成ステータスなど、システムの健全性を一目で把握できます。 SnapCenter で管理されている Storage Virtual Machine （ SVM ）の数とライセンス容量。

ダッシュボードビューに表示される情報は、 SnapCenter に現在ログインしているユーザに割り当てられたロールによって異なります。ユーザにその情報を表示する権限がない場合、一部のコンテンツが表示されないことがあります。

多くの場合、 * i * にカーソルを合わせると、ディスプレイに関する詳細情報を表示できます。状況によっては、リソース、モニタ、レポートなどの SnapCenter GUI ページの詳細なソース情報にダッシュボードの情報がリンクされていることがあります。



== 最近のジョブアクティビティ

[ 最近のジョブアクティビティ ] タイルには、アクセス可能なバックアップ、リストア、クローンジョブの最新のジョブアクティビティが表示されます。この表示のジョブには、完了、警告、失敗、実行中、キューに登録済み、 キャンセルされました。

ジョブにカーソルを合わせると、詳細が表示されます。特定のジョブ番号をクリックすると、追加のジョブ情報が表示されます。これにより、 [ モニタ ] ページにリダイレクトされます。そこからジョブの詳細またはログ情報を取得し、そのジョブに固有のレポートを生成できます。

すべての SnapCenter ジョブの履歴を表示するには、 * すべて表示 * をクリックします。



== アラート

アラートタイルには、ホストおよび SnapCenter サーバに関する最新の未解決の重大アラートと警告アラートが表示されます。

重大および警告カテゴリのアラートの総数が、ディスプレイの上部に表示されます。[Critical] または [Warning] の合計をクリックすると、 [Alerts] ページに特定のフィルタが適用された状態で [Alerts] ページにリダイレクトされます。

特定のアラートをクリックすると、そのアラートの詳細が [Alerts] ページに表示されます。ディスプレイの下部にある [*See All*]( すべてを表示 ) をクリックすると、 [Alerts] ページにすべてのアラートのリストが表示されます。



== 最新の保護の概要

最新の保護サマリタイルには、アクセス可能なすべてのエンティティの保護ステータスが表示されます。デフォルトでは、すべてのプラグインにステータスが表示されるように設定されています。ステータス情報は、プライマリストレージに Snapshot コピーとしてバックアップされたリソース、および SnapMirror テクノロジと SnapVault テクノロジを使用してセカンダリストレージに提供されます。セカンダリストレージの保護ステータス情報は、選択したプラグインタイプに基づいています。


NOTE: ミラーバックアップ保護ポリシーを使用している場合は、 SnapMirror チャートではなく、保護の概要のカウンタが SnapVault の概要チャートに表示されます。

ドロップダウンメニューからプラグインを選択すると、個々のプラグインの保護ステータスを確認できます。ドーナツグラフには、選択したプラグインの保護されているリソースの割合が表示されます。ドーナツスライスをクリックすると、 *Reports*>*Plug-In * ページに移動します。このページには、指定されたプラグインのすべてのプライマリおよびセカンダリストレージアクティビティの詳細なレポートが表示されます。


IMPORTANT: セカンダリストレージに関するレポートは SnapVault のみに適用されます。 SnapMirror レポートはサポートされません。


NOTE: SAP HANA は、 Snapshot コピーのプライマリストレージとセカンダリストレージの保護ステータス情報を提供します。ファイルベースのバックアップでは、プライマリストレージの保護ステータスのみを使用できます。

|===
| 保護ステータス | プライマリストレージ | セカンダリストレージ 


 a| 
失敗しました
 a| 
リソースグループに属しているエンティティの数。リソースグループでバックアップが実行されましたが、バックアップは失敗しました。
 a| 
セカンダリデスティネーションへのバックアップの転送に失敗したエンティティの数。



 a| 
成功しました
 a| 
リソースグループが正常にバックアップされた、リソースグループ内のエンティティの数。
 a| 
バックアップがセカンダリデスティネーションに正常に転送されたエンティティの数。



 a| 
未設定
 a| 
いずれのリソースグループにも属しておらず、バックアップされていないエンティティの数。
 a| 
1 つ以上のリソースグループに属しており、セカンダリデスティネーションにバックアップを転送するように設定されていないエンティティの数。



 a| 
開始されていません
 a| 
リソースグループに属しているが、バックアップが実行されていないエンティティの数。
 a| 
該当なし。

|===

NOTE: SnapCenter Server 4.2 以前のバージョンのプラグイン（ 4.2 より前）を使用してバックアップを作成している場合、最新の保護概要 * タイルには、これらのバックアップの SnapMirror 保護ステータスは表示されません。



== ジョブ

Jobs タイルには、アクセス可能なバックアップ、リストア、およびクローニングのジョブの概要が表示されます。ドロップダウンメニューを使用して、レポートの期間をカスタマイズできます。期間のオプションは、過去 24 時間、過去 7 日間、および過去 30 日間で固定されます。デフォルトのレポートには、過去 7 日間に実行されたデータ保護ジョブが表示されます。

バックアップ、リストア、およびクローニングのジョブ情報がドーナツグラフに表示されます。ドーナツスライスをクリックすると、選択項目にあらかじめ適用されているジョブフィルタを含む [ モニタ ] ページに移動します。

|===
| ジョブステータス | 説明 


 a| 
失敗しました
 a| 
失敗したジョブの数。



 a| 
警告
 a| 
エラーが発生したジョブの数。



 a| 
成功しました
 a| 
正常に完了したジョブの数。



 a| 
実行中です
 a| 
現在実行中のジョブの数。

|===


== ストレージ

ストレージタイルには、 90 日間の保護ジョブで使用されるプライマリストレージとセカンダリストレージが表示され、消費傾向をグラフィカルに表示して、プライマリストレージの削減量を計算します。ストレージ情報は、 24 時間ごとに午前 12 時に更新されます

この日の合計消費量は、 SnapCenter で使用できるバックアップの合計数と、これらのバックアップが占有するサイズで構成され、画面の上部に表示されます。1 つのバックアップに複数の Snapshot コピーが関連付けられることがあり、その数は同じになります。これは、プライマリとセカンダリの両方の Snapshot コピーに当てはまります。たとえば、バックアップを 10 個作成し、そのうち 2 個はポリシーベースのバックアップ保持のために削除され、 1 個はユーザが明示的に削除するように設定したとします。したがって、この 7 つのバックアップが占有している数と 7 個のバックアップが表示されます。

プライマリストレージのストレージ削減率係数は、プライマリストレージの物理容量に対する論理容量（クローンと Snapshot コピーによる削減量とストレージ消費量）の比率です。棒グラフは、ストレージの削減量を示します。

このグラフには、連続した 90 日間におけるプライマリとセカンダリのストレージ消費量が 1 日単位で表示されます。グラフにカーソルを合わせると、詳細な日単位の結果が表示されます。


NOTE: SnapCenter Server 4.2 以前のバージョンのプラグイン（ 4.2 より前）を使用してバックアップを作成する場合、「ストレージ」タイルには、バックアップ数、バックアップで消費されるストレージ容量、 Snapshot の削減量、クローンの削減量、および Snapshot のサイズは表示されません。



== 設定

[ 構成 ] タイルには、 SnapCenter が管理しているすべてのアクティブなスタンドアロンホストと Windows クラスタホストのステータス情報が統合されて表示され、にアクセスできます。これには、ホストに関連付けられているプラグインのステータス情報も含まれます。

Hosts （ホスト）の横にある数字をクリックすると、 Hosts （ホスト）ページの Managed Hosts （管理対象ホスト）セクションにリダイレクトされます。このページから、選択したホストの詳細情報を取得できます。

さらに、 SnapCenter で管理しているスタンドアロンの ONTAP ONTAP とクラスタ SVM の合計と、アクセス権があることが表示されます。SVM の横にある番号をクリックすると、ストレージシステムのページに移動します。このページから、選択した SVM の詳細情報を取得できます。

ホストの構成状態は、それぞれの状態のホストの数に加えて、赤（重大）、黄（警告）、緑（アクティブ）で表示されます。ステータスメッセージは各状態について表示されます。

|===
| 設定ステータス | 説明 


 a| 
アップグレードは必須です
 a| 
サポートされていないプラグインを実行していてアップグレードが必要なホストの数。サポートされていないプラグインは、このバージョンの SnapCenter と互換性がありません。



 a| 
移行は必須です
 a| 
サポート対象外のプラグインを実行し、移行が必要なホストの数。サポートされていないプラグインは、このバージョンの SnapCenter と互換性がありません。



 a| 
プラグインがインストールされていません
 a| 
正常に追加されたがプラグインのインストールが必要なホストの数、またはプラグインのインストールが失敗したホストの数。



 a| 
中断しました
 a| 
スケジュールが一時停止されている、かつメンテナンス中のホストの数。



 a| 
停止しました
 a| 
稼働しているホストのうち、プラグインサービスが実行されていないホストの数。



 a| 
ホストが停止しています
 a| 
停止しているか到達できないホストの数。



 a| 
アップグレード可能（オプション）
 a| 
新しいバージョンのプラグインパッケージをアップグレードに使用できるホストの数。



 a| 
移行を利用可能（オプション）
 a| 
新しいバージョンのプラグインを移行可能なホストの数。



 a| 
ログディレクトリを設定します
 a| 
SCSQL がトランザクションログバックアップを実行するようにログディレクトリを設定する必要があるホストの数。



 a| 
VMware プラグインを設定
 a| 
SnapCenter Plug-in for VMware vSphere を追加する必要のあるホストの数。



 a| 
不明です
 a| 
登録されているがインストールがまだトリガーされていないホストの数。



 a| 
実行中です
 a| 
稼働しているホストおよびプラグインの数。また、 SCSQL プラグインの場合は、ログディレクトリとハイパーバイザーが設定されます。



 a| 
プラグインのインストール / アンインストール
 a| 
プラグインのインストールまたはアンインストールを実行中のホストの数。

|===


== ライセンス容量

Licensed Capacity タイルには、 SnapCenter の標準容量ベースのライセンスの合計ライセンス容量、使用済み容量、容量しきい値アラート、およびライセンスの有効期限に関する情報が表示されます。


NOTE: この画面が表示されるのは、 Cloud Volumes ONTAP または ONTAP Select プラットフォームで SnapCenter の容量ベースのライセンスを使用している場合のみです。FAS プラットフォームまたは AFF プラットフォームの場合、 SnapCenter ライセンスはコントローラベースであり、容量無制限のライセンスです。容量ライセンスは必要ありません。

|===
| ライセンスステータス | 説明 


 a| 
使用中
 a| 
現在使用中の容量。



 a| 
通知
 a| 
容量のしきい値。ダッシュボードに通知が表示され、設定している場合は E メール通知が送信されます。



 a| 
使用許諾
 a| 
ライセンスに設定されている容量。



 a| 
オーバー
 a| 
ライセンスの容量を超えた容量。

|===