---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords:  
summary: 'ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、およびイベントとログの確認は、 [ 監視 ] ページから実行できます。' 
---
= ジョブ、スケジュール、イベント、およびログを監視する
:icons: font
:imagesdir: ../media/


[role="lead"]
ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、およびイベントとログの確認は、 [ 監視 ] ページから実行できます。



== ジョブを監視する

SnapCenter のバックアップ、クローニング、リストア、検証の各ジョブに関する情報を表示できます。開始日と終了日、ジョブのタイプ、リソースグループ、ポリシー、または SnapCenter プラグインに基づいて、表示される情報を絞り込むことができます。指定したジョブの詳細情報やログファイルを確認することもできます。

SnapMirror 処理と SnapVault 処理に関連するジョブも監視できます。


NOTE: SnapCenter Admin ロールまたはその他のスーパーユーザロールが割り当てられている場合を除き、監視できるのは自分で作成したジョブと自分に関連するジョブだけです。

ジョブの監視に関連して次のタスクを実行できます。

* バックアップ、クローニング、リストア、検証の各処理を監視する。
* ジョブの詳細とレポートを表示します。
* スケジュールされたジョブを停止する。




== スケジュールを監視

現在のスケジュールを表示して、処理の開始日時、前回の実行日時、および次回の実行日時を確認できます。処理が実行されるホストのほか、処理のリソースグループやポリシーに関する情報も確認できます。

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * スケジュール * ] をクリックします。
. リソースグループとスケジュールタイプを選択します。
. スケジュールされた処理のリストを表示します。




== イベントを監視する

ユーザによるリソースグループの作成、システムによるアクティビティの開始、スケジュールされたバックアップの作成など、システム内の SnapCenter イベントのリストを表示できます。イベントを表示して、バックアップやリストアなどの処理が現在実行中であるかどうかを確認できます。

* このタスクについて *

[ イベント ] ページにすべてのジョブ情報が表示されます。たとえば ' バックアップ・ジョブが開始されると 'backup start' イベントが表示されますバックアップが完了すると ' backup complete イベントが表示されます

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * イベント * ] をクリックします。
. （任意） [ フィルタ ] ボックスに、開始日または終了日、イベントのカテゴリ（バックアップ、リソースグループ、ポリシーなど）、および重大度レベルを入力し、 [ 適用 *] をクリックします。または、検索ボックスに文字を入力します。
. イベントのリストを表示します。




== ログを監視する

SnapCenter サーバログ、 SnapCenter ホストエージェントログ、およびプラグインログを表示およびダウンロードできます。ログを表示してトラブルシューティングに役立てることができます。

* このタスクについて *

フィルタを使用して、特定の重大度レベルのログだけを表示するように絞り込むことができます。

* デバッグ
* 情報
* 警告
* エラー
* 致命的


バックアップジョブが失敗した理由を特定する目的で、ジョブレベルのログを取得することもできます。ジョブ・レベル・ログの場合は、 * Monitor * > * Jobs * オプションを使用します。

* 手順 *

. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ ジョブ ] ページでジョブを選択し、 [ ログのダウンロード ] をクリックします。
+
ダウンロードされた zip 形式のフォルダには、ジョブログと一般的なログが含まれています。zip 形式のフォルダ名には、選択したジョブ ID とジョブタイプが含まれています。

. [ モニター ] ページで、 [ * ログ * ] をクリックします。
. ログタイプ、ホスト、およびインスタンスを選択します。
+
ログタイプとして * plugin * を選択すると、ホストまたは SnapCenter プラグインを選択できます。ログタイプが * server * の場合、この処理は実行できません。

. 特定のソース、メッセージ、またはログレベルでログをフィルタリングするには、列見出しにあるフィルタアイコンをクリックします。
+
すべてのログを表示するには、「バグ」レベルとして「 * 以上」または「 * 」を選択します。

. [* 更新 * ] をクリックします。
. ログの一覧を確認します。
. ログをダウンロードするには、 * Download * をクリックします。
+
ダウンロードされた zip 形式のフォルダには、ジョブログと一般的なログが含まれています。zip 形式のフォルダ名には、選択したジョブ ID とジョブタイプが含まれています。



大規模な構成で最適なパフォーマンスを実現するには、 PowerShell コマンドレットを使用して、 SnapCenter のログ設定を最小レベルに設定する必要があります。

「 Set-SmLogSettings - LogLevel All - MaxFileSize 10MB-MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB-Server 」を実行します


NOTE: フェイルオーバー・ジョブの完了後にヘルスまたは構成情報にアクセスするには 'Get-SmRepositoryConfig' コマンドレットを実行します



== SnapCenter からジョブとログを削除します

バックアップ、リストア、クローニング、および検証の各ジョブとそのログを SnapCenter から削除できます。SnapCenter では、ジョブの成否にかかわらず、削除しないかぎりログは永久に保存されます。ジョブのログを削除することで、ストレージの空きを増やすことができます。

* このタスクについて *

実行中のジョブがないことを確認してください。特定のジョブを削除するには、ジョブ ID を指定するか、指定した期間内にジョブを削除します。

ジョブを削除する際、ホストをメンテナンスモードにする必要はありません。

* 手順 *

. PowerShell を起動します。
. コマンドプロンプトで、「 Open-SMConnection 」と入力します
. コマンドプロンプトで「 Remove-SmJobs 」と入力します
. 左側のナビゲーションペインで、 *Monitor* をクリックします。
. [ モニター ] ページで、 [ * ジョブ * ] をクリックします。
. [ ジョブ ] ページで、ジョブのステータスを確認します。


* 詳細はこちら *

コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。
