---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter には、システムの健常性や処理の状況を監視および管理するためのさまざまなレポートオプションが用意されています。 
---
= SnapCenter のレポート機能の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter には、システムの健常性や処理の状況を監視および管理するためのさまざまなレポートオプションが用意されています。

|===
| レポートタイプ | 説明 


 a| 
バックアップレポート
 a| 
Backup Report には、 SnapCenter 環境のバックアップ状況に関する全体的なデータ、バックアップの成功率、および指定した期間に実行された各バックアップに関する情報が表示されます。バックアップが削除された場合、そのバックアップのステータス情報はレポートに表示されません。Backup Detail Report には、指定したバックアップジョブに関する詳細情報に加え、バックアップに成功したリソースと失敗したリソースの一覧が表示されます。



 a| 
クローンレポート
 a| 
Clone Report には、 SnapCenter 環境のクローニング状況に関する全体的なデータ、クローニングの成功率、および指定した期間に実行された各クローニングジョブに関する情報が表示されます。クローンが削除された場合、そのクローンのステータス情報はレポートに表示されません。Clone Detail Report には、指定したクローン、クローニングホスト、クローニングジョブタスクのステータスに関する詳細情報が表示されます。タスクが失敗した場合は、 Clone Detail Report にその情報が表示されます。



 a| 
リストアレポート
 a| 
Restore Report には、リストアジョブに関する全体的な情報が表示されます。Restore Detail Report には、指定したリストアジョブについて、ホスト名、バックアップ名、ジョブの開始日時と期間、個々のジョブタスクのステータスなどの詳細情報が表示されます。タスクが失敗した場合は、 Restore Detail Report にその情報が表示されます。



 a| 
保護レポート
 a| 
これらのレポートには、すべての SnapCenter プラグインインスタンスで管理されているリソースの保護の詳細が表示されます。このレポートには、すべてのプラグインインスタンスで管理されているリソースの保護の詳細が表示されます。概要、保護されていないリソースの詳細、レポート生成時にバックアップされなかったリソース、バックアップ処理が失敗したリソースグループのリソース、および SnapVault のステータスを確認できます。



 a| 
スケジュールされたレポート
 a| 
これらのレポートは、毎日、毎週、または毎月のように定期的に実行されるようにスケジュールされています。レポートは、指定した日時に自動的に生成され、レポートは電子メールを介して各ユーザーに送信されますスケジュールを有効化、無効化、変更、または削除できます。有効なスケジュールは、 [ 今すぐ実行 ] ボタンをクリックして、オンデマンドで実行できます。管理者は任意のスケジュールを実行できますが、生成されるレポートには、スケジュールを作成したユーザから割り当てられた権限に基づいてデータが含まれます。

Administrator 以外のユーザは、権限に基づいてスケジュールを表示または変更できます。このロールのすべてのメンバーが [ ロールの追加 ] ページで [ 他のメンバーのオブジェクトを表示できる ] オプションを選択すると、そのロールの他のメンバーは表示および変更できます。

|===


== レポートにアクセスする

SnapCenter のダッシュボードを使用すると、システムヘルスの概要を簡単に確認できます。ダッシュボードで詳細にドリルダウンできます。または、詳細レポートに直接アクセスすることもできます。

レポートには、次のいずれかの方法でアクセスできます。

* 左側のナビゲーションペインで、 * ダッシュボード * をクリックし、 * 前回の保護の概要 * 円グラフをクリックして、レポートページに詳細を表示します。
* 左側のナビゲーションペインで、 * Reports * をクリックします。




== レポートをフィルタします

必要な情報や期間に応じて、パラメータの範囲に基づいてレポートデータをフィルタリングできます。

* 手順 *

. 左側のナビゲーションペインで、 * Reports * をクリックします。
. パラメータービューが表示されていない場合は、レポートツールバーの * パラメーター領域の切り替え * アイコンをクリックします。
. レポートを実行する時間範囲を指定します。+ 終了日を省略すると、使用可能なすべての情報が取得されます。
. 次のいずれかの条件に基づいて、レポート情報をフィルタリングします。
+
** リソースグループ
** ホスト
** ポリシー
** リソース
** ステータス
** プラグイン名


. [ 適用（ Apply ） ] をクリックします。




== レポートをエクスポートまたは印刷します

SnapCenter レポートをエクスポートすると、さまざまな形式でレポートを表示できます。レポートを印刷することもできます。

* 手順 *

. 左側のナビゲーションペインで、 * Reports * をクリックします。
. レポートツールバーで、次のいずれかを実行します。
+
** プリント可能なレポートをプレビューするには、 * プリントプレビューの切り替え * アイコンをクリックします。
** レポートを別の形式にエクスポートするには、 * Export * icon ドロップダウンリストから形式を選択します。


. レポートを印刷するには、 * 印刷 * アイコンをクリックします。
. 特定のレポートの概要を表示するには、レポートの該当するセクションまでスクロールします。




== E メール通知に使用する SMTP サーバを設定します

データ保護ジョブのレポートを自分または他のユーザに送信するときに使用する SMTP サーバを指定できます。テスト E メールを送信して設定を確認することもできます。この設定は、 E メール通知を設定したすべての SnapCenter ジョブにグローバルに適用されます。

このオプションは、すべてのデータ保護ジョブレポートの送信に使用する SMTP サーバを設定します。ただし、特定のリソースに対する SnapCenter データ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソースグループの作成時に SnapCenter レポートを E メールで送信するオプションを設定できます。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. 設定ページで、 * グローバル設定 * をクリックします。
. SMTP サーバーを入力し、 * 保存 * をクリックします。
. テスト用 E メールを送信するには、 E メールの送信元と送信先の E メールアドレスを入力し、件名を入力して、「 * 送信 * 」をクリックします。




== レポートを E メールで送信するオプションを設定します

SnapCenter データ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソースグループの作成時に SnapCenter レポートを E メールで送信するオプションを設定します。

* 必要なもの *

SMTP サーバーは、 [ 設定 ] の [ グローバル設定 ] ページで設定しておく必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. 表示するリソースのタイプを選択し、 * 新規リソースグループ * をクリックするか、既存のリソースグループを選択して * 変更 * をクリックし、既存のリソースグループの E メールレポートを設定します。
. 新しいリソースグループウィザードの通知パネルで、レポートを常に受信するか、エラーが発生したか、またはエラーや警告を受信するかをプルダウンメニューから選択します。
. E メールの送信元アドレス、 E メールの送信先アドレス、および E メールの件名を入力します。

