---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords:  
summary: リソースグループに対してさまざまな処理を実行できます。 
---
= リソースグループの管理
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースグループに対してさまざまな処理を実行できます。

リソースグループに関連して次のタスクを実行できます。

* リソースグループを変更するには、リソースグループを選択し、 * リソースグループの変更 * をクリックして、リソースグループの作成時に指定した情報を編集します。
+

NOTE: リソースグループを変更する際にスケジュールを変更することができます。ただし、スケジュールタイプを変更するには、ポリシーを変更する必要があります。

+

NOTE: リソースグループからリソースを削除した場合、リソースグループに現在適用されているポリシーに定義されたバックアップ保持の設定は、削除したリソースに引き続き適用されます。

* リソースグループのバックアップを作成する。
* バックアップのクローンを作成します。
+
クローニングは、 SQL 、 Oracle 、 Windows の各ファイルシステムのバックアップ、カスタムアプリケーションのバックアップ、および SAP HANA データベースのリソースまたはリソースグループのバックアップから実行できます。

* リソースグループのクローンを作成する。
+
この処理は、 SQL リソースグループ（データベースのみを含むグループ）でのみサポートされます。リソースグループのクローニングのスケジュール（クローニングライフサイクル）を設定することができます。

* リソースグループでスケジュールされている処理が開始されないようにする。
* リソースグループを削除する。




== リソースグループに対する処理を停止および再開する

スケジュールされた処理を一時的に無効にして、リソースグループで開始されないように設定できます必要に応じて、あとからこれらの処理を有効にすることができます。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * Maintenance * （メンテナンス）をクリックします。
. [OK] をクリックします。


保守モードにしたリソースグループの操作を再開する場合は ' リソースグループを選択して ' 本番環境をクリックします



== リソースグループを削除する

リソースグループ内のリソースを保護する必要がなくなった場合は、リソースグループを削除することができます。SnapCenter からプラグインを削除する前に、リソースグループを削除する必要があります。

* このタスクについて *

リソースグループ内のリソースに対して作成されたすべてのクローンを手動で削除する必要があります。必要に応じて、リソースグループに関連付けられているすべてのバックアップ、メタデータ、ポリシー、 Snapshot コピーを強制的に削除することができます。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * 削除 * をクリックします。
. オプション：リソースグループに関連付けられたバックアップ、メタデータ、ポリシー、 Snapshot コピーをすべて削除するには、 * このリソースグループに関連付けられたバックアップとバックアップポリシーの削除 * チェックボックスを選択します。
. [OK] をクリックします。

