---
permalink: admin/task_manage_rbac.html 
sidebar: sidebar 
keywords: modify RBAC, role, users, groups 
summary: SnapCenterでは、ロール、ユーザ、およびグループを変更できます。 
---
= RBACの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、ロール、ユーザ、およびグループを変更できます。



== ロールを変更します。

SnapCenter ロールを変更して、ユーザまたはグループを削除したり、そのロールに関連付けられている権限を変更したりできます。ロール全体で使用されている権限を変更または削除する場合は、ロールを変更すると特に便利です。

.開始する前に
「SnapCenterAdmin」ロールでログインする必要があります。


NOTE: SnapCenterAdminロールの権限を変更または削除することはできません。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. 設定ページで、 * 役割 * をクリックします。
. [ロール名]フィールドで、変更するロールをクリックします。
. [ロールの詳細]ページで、必要に応じて権限を変更するか、メンバーの割り当てを解除します。
. このロールのすべてのメンバーは、他のメンバーのオブジェクトを表示できます * を選択すると、そのロールの他のメンバーは、リソースリストの更新後にボリュームやホストなどのリソースを参照できます。
+
このロールのメンバーに他のメンバーが割り当てられているオブジェクトが表示されないようにするには、このオプションの選択を解除します。

+

NOTE: このオプションを有効にすると、オブジェクトまたはリソースを作成したユーザと同じロールに属するユーザにオブジェクトまたはリソースへのアクセス権を割り当てる必要はありません。

. [Submit （送信） ] をクリックします。




== ユーザとグループの変更

SnapCenter のユーザまたはグループを変更して、ロールとアセットを変更できます。

.開始する前に
SnapCenter 管理者としてログインする必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* ユーザーとアクセス * ] をクリックします。
. [ユーザ名またはグループ名]リストで、変更するユーザまたはグループをクリックします。
. [ユーザまたはグループの詳細]ページで、ロールとアセットを変更します。
. [Submit （送信） ] をクリックします。

