---
permalink: admin/task_manage_rbac.html 
sidebar: sidebar 
keywords: modify RBAC, role, users, groups 
summary: SnapCenter では、ロール、ユーザ、およびグループを変更できます。 
---
= RBAC を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter では、ロール、ユーザ、およびグループを変更できます。



== ロールを変更します

SnapCenter ロールを変更して、ユーザまたはグループを削除したり、そのロールに関連付けられている権限を変更したりできます。ロールの変更は、ロール全体で使用される権限を変更または削除する場合に特に便利です。

* 必要なもの *

「 SnapCenterAdmin 」ロールでログインする必要があります。


NOTE: SnapCenterAdmin ロールの権限は変更または削除できません。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. 設定ページで、 * 役割 * をクリックします。
. [ 役割名 ] フィールドで、変更する役割をクリックします。
. [ 役割の詳細 ] ページで、権限を変更するか、必要に応じてメンバーの割り当てを解除します。
. このロールのすべてのメンバーは、他のメンバーのオブジェクトを表示できます * を選択すると、そのロールの他のメンバーは、リソースリストの更新後にボリュームやホストなどのリソースを参照できます。
+
他のメンバーが割り当てられているオブジェクトをこのロールのメンバーに表示しない場合は、このオプションを選択解除します。

+

NOTE: このオプションを有効にすると、オブジェクトまたはリソースを作成したユーザと同じロールにユーザが属している場合に、オブジェクトまたはリソースへのアクセスをユーザに割り当てる必要がなくなります。

. [Submit （送信） ] をクリックします。




== ユーザとグループを変更します

SnapCenter のユーザまたはグループを変更して、ロールとアセットを変更できます。

* 必要なもの *

SnapCenter 管理者としてログインする必要があります。

* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [* ユーザーとアクセス * ] をクリックします。
. [ ユーザ名またはグループ名 ] リストで、変更するユーザまたはグループをクリックします。
. [ ユーザーまたはグループの詳細 ] ページで、役割とアセットを変更します。
. [Submit （送信） ] をクリックします。

