---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: リソースグループに対してさまざまな処理を実行できます。 
---
= リソースグループの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースグループに対してさまざまな処理を実行できます。

リソースグループに関連して次のタスクを実行できます。

* リソースグループを変更するには、リソースグループを選択し、 * リソースグループの変更 * をクリックして、リソースグループの作成時に指定した情報を編集します。
+

NOTE: スケジュールはリソースグループの変更時に変更できます。ただし、スケジュールタイプを変更するには、ポリシーを変更する必要があります。

+

NOTE: リソースグループからリソースを削除した場合、リソースグループに現在関連付けられているポリシーに定義されているバックアップ保持設定が、削除したリソースに引き続き適用されます。

* リソースグループのバックアップを作成する。
* バックアップのクローンを作成します。
+
クローニングは、SQL、Oracle、Windowsファイルシステム、カスタムアプリケーション、SAP HANAデータベースのリソースまたはリソースグループの既存のバックアップから実行できます。

* リソースグループのクローンを作成します。
+
この処理は、（データベースのみを含む）SQLリソースグループに対してのみサポートされます。リソースグループのクローニングのスケジュール（クローンライフサイクル）を設定できます。

* リソースグループに対してスケジュールされた処理が開始されないようにする。
* リソースグループを削除する。




== リソースグループに対する処理の停止と再開

スケジュールされた処理がリソースグループで開始されないように一時的に無効にすることができます。これらの処理は、必要に応じてあとで有効にすることができます。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * Maintenance * （メンテナンス）をクリックします。
. [OK]*をクリックします。


保守モードにしたリソースグループの操作を再開する場合は ' リソースグループを選択して ' 本番環境をクリックします



== リソースグループの削除

リソースグループ内のリソースを保護する必要がなくなった場合は、リソースグループを削除できます。SnapCenter からプラグインを削除する前に、リソースグループを削除する必要があります。

* このタスクについて *

リソースグループ内のいずれかのリソースに対して作成されたすべてのクローンを手動で削除する必要があります。必要に応じて、リソースグループに関連付けられているすべてのバックアップ、メタデータ、ポリシー、およびSnapshotを強制的に削除することができます。

* 手順 *

. 左側のナビゲーションペインで、 * リソース * をクリックし、リストから適切なプラグインを選択します。
. [ リソース ] ページで、 [ * 表示 ] リストから [ * リソースグループ * ] を選択します。
. リソースグループを選択し、 * 削除 * をクリックします。
. オプション：リソースグループに関連付けられているバックアップ、メタデータ、ポリシー、およびSnapshotをすべて削除する場合は、*[Delete backups and detach policies associated with this Resource Group]*チェックボックスを選択します。
. [OK]*をクリックします。

