---
permalink: protect-postgresql/clone-postgresql-backups-using-powershell-cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: クローニングワークフローには、計画、クローニング処理の実行、および処理の監視が含まれます。 
---
= PowerShellコマンドレットを使用したPostgreSQLクラスタバックアップのクローニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローニングワークフローには、計画、クローニング処理の実行、および処理の監視が含まれます。

PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。

コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。

.手順
. Open-SmConnectionコマンドレットを使用して、指定したユーザのSnapCenterサーバとの接続セッションを開始します。
+
[listing]
----
PS C:\> Open-SmConnection
----
. Get-SmBackupコマンドレットを使用して、クローニング処理を実行するバックアップを取得します。
+
この例では、クローニングに2つのバックアップを使用できます。

+
[listing]
----
 C:\PS> Get-SmBackup

        BackupId                      BackupName                    BackupTime                    BackupType
        --------                      ----------                    ----------                    ----------
         1                     Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM          Full Backup
         2                     Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
. 既存のバックアップからクローニング処理を開始し、クローニングされたボリュームをエクスポートするNFSエクスポートのIPアドレスを指定します。
+
この例では、NFSExportIPsアドレスが10.32.212.14であるバックアップをクローニングしています。

+
PostgreSQLクラスタの場合：

+
[listing]
----
PS C:\> New-SmClone -AppPluginCode PostgreSQL -BackupName " scpostgresql01_ openenglab_netapp_com_PostgreSQL_postgres_5432_06-26-2024_00_33_41_1570" -Resources @{"Host"=" 10.32.212.13";"Uid"="postgres_5432"} -port 2345 -CloneToHost 10.32.212.14
----
+

NOTE: NFSExportIPsを指定しない場合、デフォルトでクローンターゲットホストにエクスポートされます。

. Get-SmCloneReportコマンドレットを使用してクローンジョブの詳細を表示し、バックアップが正常にクローニングされたことを確認します。
+
クローンID、開始日時、終了日時などの詳細を確認できます。

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

    SmCloneId           : 1
    SmJobId             : 186
    StartDateTime       : 8/3/2015 2:43:02 PM
    EndDateTime         : 8/3/2015 2:44:08 PM
    Duration            : 00:01:06.6760000
    Status              : Completed
    ProtectionGroupName : Draper
    SmProtectionGroupId : 4
    PolicyName          : OnDemand_Clone
    SmPolicyId          : 4
    BackupPolicyName    : OnDemand_Full_Log
    SmBackupPolicyId    : 1
    CloneHostName       : SCSPR0054212005.mycompany.com
    CloneHostId         : 4
    CloneName           : Draper__clone__08-03-2015_14.43.53
    SourceResources     : {Don, Betty, Bobby, Sally}
    ClonedResources     : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER, Sally_DRAPER}
    SmJobError          :
----

