---
permalink: protect-postgresql/snapcenter-plug-in-for-postgresql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: SnapCenter Plug-in for PostgreSQLは、PostgreSQLクラスタに対するアプリケーション対応のデータ保護管理を可能にする、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。Plug-in for PostgreSQLクラスタは、SnapCenter環境でのPostgreSQLクラスタのバックアップ、リストア、クローニングを自動化します。 
---
= SnapCenter Plug-in for PostgreSQLの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for PostgreSQLクラスタは、PostgreSQLクラスタに対するアプリケーション対応のデータ保護管理を可能にする、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。Plug-in for PostgreSQLクラスタは、SnapCenter環境でのPostgreSQLクラスタのバックアップ、リストア、クローニングを自動化します。

SnapCenterは、単一クラスタとマルチクラスタのPostgreSQLセットアップをサポートしています。Plug-in for PostgreSQL Clustersは、Linux環境とWindows環境の両方で使用できます。Windows環境では、PostgreSQLは手動リソースとしてサポートされます。

Plug-in for PostgreSQLクラスタがインストールされている場合は、SnapCenterとNetApp SnapMirrorテクノロジを使用して、バックアップセットのミラーコピーを別のボリュームに作成できます。また、本プラグインをNetApp SnapVaultテクノロジとともに使用して、標準への準拠を目的としたディスクツーディスクのバックアップ・レプリケーションを実行することもできます。

SnapCenter Plug-in for PostgreSQLは、ONTAPおよびAzure NetAppのファイルストレージレイアウトでNFSとSANをサポートします。

VMDK、VVol、およびRDMの仮想ストレージレイアウトがサポートされます。
