---
permalink: protect-postgresql/storage-types-supported-by-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: storage types, 
summary: SnapCenter は、物理マシンと仮想マシン（ VM ）の両方でさまざまなストレージタイプをサポートしています。SnapCenter Plug-in for PostgreSQLをインストールする前に、ストレージタイプがサポートされていることを確認する必要があります。 
---
= SnapCenter Plug-in for PostgreSQLでサポートされるストレージタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter は、物理マシンと仮想マシン（ VM ）の両方でさまざまなストレージタイプをサポートしています。SnapCenter Plug-in for PostgreSQLをインストールする前に、ストレージタイプがサポートされていることを確認する必要があります。

|===
| マシン | ストレージタイプ 


 a| 
物理サーバ
 a| 
* FCセツソクLUN
* iSCSIセツソクLUN
* NFS接続ボリューム




 a| 
VMware ESXi
 a| 
* FCまたはiSCSI ESXi HBAで接続されたRDM LUN Host Bus Adapter（HBA；ホストバスアダプタ）のスキャンは、SnapCenterがホストに存在するすべてのホストバスアダプタをスキャンするため、完了までに時間がかかることがあります。
+
/opt/NetApp/SnapCenter /spl/plugins/SCU/scucore /modules/SCU/ConfigU/Config_に ある * LinuxConfig.pm * ファイルを編集して、 * scsi_hosts _optimized_rescan * パラメーターの値を 1 に設定し、 ha_driver_names にリストされている HBA のみを再スキャンすることができます。

* iSCSIイニシエータによってゲストシステムに直接接続されたiSCSI LUN
* NFSデータストア上のVMDK
* VMFS上のVMDK
* ゲストシステムに直接接続されたNFSボリューム
* NFSとSANの両方にVVOLデータストアを配置
+
VVOLデータストアは、ONTAP Tools for VMware vSphereでのみプロビジョニングできます。



|===