---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: データ保護処理を実行する前に、ストレージ接続をセットアップし、 SnapCenter サーバおよび SnapCenter プラグインで使用するクレデンシャルを追加する必要があります。 
---
= ストレージ接続およびクレデンシャル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護処理を実行する前に、ストレージ接続をセットアップし、 SnapCenter サーバおよび SnapCenter プラグインで使用するクレデンシャルを追加する必要があります。

* * ストレージ接続 *
+
ストレージ接続を使用すると、 SnapCenter サーバおよび SnapCenter プラグインから ONTAP ストレージにアクセスできるようになります。この接続のセットアップには、 AutoSupport 機能と Event Management System （ EMS ；イベント管理システム）機能の設定も含まれます。

* * 資格情報 *
+
** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者、または SnapCenter プラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。Username フィールドの有効な形式は次のとおりです。

+
*** NETBIOS_USERNAME_
*** _ ドメイン FQDN\ ユーザ名 _
*** _Username@UPN_


** ローカル管理者（ワークグループのみ）
+
ワークグループに属するシステムの場合は、 SnapCenter プラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザアカウントに昇格された権限がある場合、またはホストシステムでユーザアクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカルユーザアカウントを指定できます。

+
Username フィールドの有効な形式は、 _username_ です

** 個々のリソースグループのクレデンシャル
+
個々のリソースグループのクレデンシャルを設定していて、ユーザ名にフル管理者権限がない場合は、少なくともリソースグループとバックアップ権限をユーザ名に割り当てる必要があります。




