---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: クレデンシャルで使用される認証方法は、アプリケーションや環境に応じて異なります。クレデンシャルで認証されたユーザは、 SnapCenter の処理を実行できます。プラグインのインストールに使用するクレデンシャルとデータ保護処理に使用するクレデンシャルをそれぞれ1組ずつ作成する必要があります。 
---
= クレデンシャルの認証方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クレデンシャルで使用される認証方法は、アプリケーションや環境に応じて異なります。クレデンシャルで認証されたユーザは、 SnapCenter の処理を実行できます。プラグインのインストールに使用するクレデンシャルとデータ保護処理に使用するクレデンシャルをそれぞれ1組ずつ作成する必要があります。



== Windows認証

Windows認証方式は、Active Directoryに照らして認証します。Windows 認証の場合、 Active Directory は SnapCenter の外部で設定されます。SnapCenter の認証に追加の設定は必要ありません。Windowsクレデンシャルは、ホストの追加、プラグインパッケージのインストール、ジョブのスケジュール設定などのタスクを実行する際に必要になります。



== 信頼されていないドメイン認証

SnapCenter では、信頼されていないドメインに属するユーザとグループを使用して Windows クレデンシャルを作成できます。認証を成功させるには、信頼されていないドメインを SnapCenter に登録する必要があります。



== ローカルワークグループ認証

SnapCenter では、ローカルのワークグループユーザとグループを使用して Windows クレデンシャルを作成できます。ローカルワークグループのユーザとグループに対するWindows認証は、Windowsクレデンシャルの作成時に実行されるのではなく、ホストの登録やその他のホスト処理が実行されるまで保留されます。



== SQL Server認証

SQL認証方式は、SQL Serverインスタンスに照らして認証します。つまり、 SnapCenter で SQL Server インスタンスが検出されている必要があります。そのため、SQLクレデンシャルを追加する前に、ホストの追加とプラグインパッケージのインストールを完了し、リソースを更新する必要があります。SQL Server認証は、SQL Serverでのスケジュール設定やリソースの検出などの処理を実行する際に必要になります。



== Linux認証

Linux認証方式は、Linuxホストに照らして認証します。Linux認証は、SnapCenter GUIからリモートでLinuxホストを追加してSnapCenter Plug-ins Package for Linuxをインストールする最初のステップで必要になります。



== AIX認証

AIX認証方式は、AIXホストに照らして認証します。AIX認証は、AIXホストを追加し、SnapCenter Plug-ins Package for AIXをSnapCenter GUIからリモートでインストールする最初のステップで必要になります。



== Oracleデータベース認証

Oracleデータベース認証方式は、Oracleデータベースに照らして認証します。データベースホストでオペレーティングシステム（OS）認証が無効になっている場合は、Oracleデータベースで処理を実行するためにOracleデータベース認証が必要になります。そのため、Oracleデータベースのクレデンシャルを追加する前に、Oracleデータベースでsysdba権限を持つOracleユーザを作成しておく必要があります。



== Oracle ASM認証

Oracle ASM認証方式は、Oracle Automatic Storage Management（ASM）インスタンスに照らして認証します。Oracle ASMインスタンスにアクセスする必要があり、データベースホストでオペレーティングシステム（OS）認証が無効になっている場合は、Oracle ASM認証が必要です。そのため、Oracle ASMのクレデンシャルを追加する前に、ASMインスタンスでSYSASM権限を持つOracleユーザを作成しておく必要があります。



== RMANカタログ認証

RMANカタログ認証方式は、Oracle Recovery Manager（RMAN）カタログデータベースに照らして認証します。外部カタログメカニズムを設定し、データベースをカタログデータベースに登録した場合は、RMANカタログ認証を追加する必要があります。
