---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: Storage Virtual Machine （ SVM ）上に SMB3 共有を設定するには、 SnapCenter ユーザインターフェイスまたは PowerShell コマンドレットを使用できます。 
---
= SMB 共有を作成および管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine （ SVM ）上に SMB3 共有を設定するには、 SnapCenter ユーザインターフェイスまたは PowerShell コマンドレットを使用できます。

|===


| * ベストプラクティス： * SnapCenter に付属のテンプレートを利用して共有の設定を自動化できるため、コマンドレットの使用を推奨します。 
|===
テンプレートには、ボリュームおよび共有の設定に関するベストプラクティスが組み込まれています。テンプレートは、 SnapCenter Plug-ins Package for Windows のインストールフォルダの Templates フォルダにあります。


TIP: 必要に応じて、提供されているモデルに従って独自のテンプレートを作成できます。カスタムテンプレートを作成する場合は、コマンドレットのドキュメントでパラメータを確認してください。



== SMB 共有を作成

SnapCenter 共有ページを使用すると、 Storage Virtual Machine （ SVM ）に SMB3 共有を作成できます。

SnapCenter を使用して、 SMB 共有上のデータベースをバックアップすることはできません。SMB のサポートはプロビジョニングのみに限定されます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. ホストページで、 * 共有 * をクリックします。
. Storage Virtual Machine * ドロップダウンリストから SVM を選択します。
. [ 新規作成（ New ） ] をクリックする。
+
[ 新しい共有 ] ダイアログが開きます。

. [ 新しい共有 ] ダイアログで、共有を定義します。
+
|===
| フィールド | 手順 


 a| 
説明
 a| 
共有の説明を入力します。



 a| 
共有名
 a| 
共有名を入力します（例： test_share ）。

入力した共有の名前はボリューム名としても使用されます。

共有名：

** UTF-8 文字列である必要があります。
** 0x00 から 0x1F までの制御文字、 0x22 （二重引用符）、および特殊文字の「 \ / [ ] ：（縦棒） <> + = ；、？」は使用できません




 a| 
共有パス
 a| 
** フィールド内をクリックして、新しいファイルシステムパス（ / など）を入力します。
** フィールドをダブルクリックして、既存のファイルシステムパスのリストから選択します。


|===
. 入力に問題がなければ、「 * OK * 」をクリックします。
+
SnapCenter により、 SVM に SMB 共有が作成されます。





== SMB 共有を削除する

不要になった SMB 共有は削除できます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. ホストページで、 * 共有 * をクリックします。
. 共有ページで、 * Storage Virtual Machine * フィールドをクリックして、ドロップダウンと使用可能な Storage Virtual Machine （ SVM ）のリストを表示し、削除する共有の SVM を選択します。
. SVM 上の共有のリストから削除する共有を選択し、 * Delete * をクリックします。
. 共有の削除ダイアログボックスで、 * OK * をクリックします。
+
SnapCenter によって SVM から SMB 共有が削除されます。


