---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: クレデンシャルは、アプリケーションや環境に応じて異なる認証方式を使用します。クレデンシャルで認証されたユーザは、 SnapCenter の処理を実行できます。プラグインのインストール用とデータ保護処理用に 1 組のクレデンシャルを作成する必要があります。 
---
= クレデンシャルの認証方式を指定します
:icons: font
:imagesdir: ../media/


[role="lead"]
クレデンシャルは、アプリケーションや環境に応じて異なる認証方式を使用します。クレデンシャルで認証されたユーザは、 SnapCenter の処理を実行できます。プラグインのインストール用とデータ保護処理用に 1 組のクレデンシャルを作成する必要があります。



== Windows 認証

Windows 認証方式は、 Active Directory に照らして認証します。Windows 認証の場合、 Active Directory は SnapCenter の外部で設定されます。SnapCenter の認証に追加の設定は必要ありません。Windows クレデンシャルは、ホストの追加、プラグインパッケージのインストール、ジョブのスケジュール設定などのタスクを実行する際に必要になります。



== 信頼されないドメイン認証です

SnapCenter では、信頼されていないドメインに属するユーザとグループを使用して Windows クレデンシャルを作成できます。認証を成功させるには、信頼されていないドメインを SnapCenter に登録する必要があります。



== ローカルワークグループ認証

SnapCenter では、ローカルのワークグループユーザとグループを使用して Windows クレデンシャルを作成できます。ローカルワークグループのユーザとグループの Windows 認証は、 Windows クレデンシャルの作成時には行われませんが、ホストの登録やその他のホスト処理が実行されるまで保留されます。



== SQL Server 認証

SQL 認証方式は、 SQL Server インスタンスに照らして認証します。つまり、 SnapCenter で SQL Server インスタンスが検出されている必要があります。そのため、 SQL クレデンシャルを追加する前に、ホストの追加とプラグインパッケージのインストールを行って、リソースを更新しておく必要があります。SQL Server 認証は、 SQL Server でのスケジュールの設定やリソースの検出などの処理を実行する際に必要になります。



== Linux 認証

Linux 認証方式は、 Linux ホストに照らして認証します。Linux 認証は、 SnapCenter の GUI からリモートで Linux ホストを追加して SnapCenter Plug-ins Package for Linux をインストールする最初のステップで必要になります。



== AIX 認証

AIX 認証方式は、 AIX ホストに照らして認証します。AIX 認証は、 SnapCenter の GUI からリモートで AIX ホストを追加して SnapCenter Plug-ins Package for AIX をインストールする最初のステップで必要になります。



== Oracle データベース認証

Oracle データベース認証方式は、 Oracle データベースに照らして認証します。データベースホストでオペレーティングシステム（ OS ）認証が無効な場合、 Oracle データベースに対して処理を実行するには、 Oracle データベース認証が必要です。そのため、 Oracle データベースのクレデンシャルを追加する前に、 Oracle データベースで sysdba 権限を持つ Oracle ユーザを作成しておく必要があります。



== Oracle ASM 認証

Oracle ASM 認証方式は、 Oracle Automatic Storage Management （ ASM ）インスタンスに照らして認証します。Oracle ASM 認証は、 Oracle ASM インスタンスにアクセスする際、データベースホストでオペレーティングシステム（ OS ）認証が無効になっている場合に必要になります。したがって、 Oracle ASM クレデンシャルを追加する前に、 ASM インスタンスで SYSASM 権限を持つ Oracle ユーザを作成する必要があります。



== RMAN カタログ認証

RMAN カタログ認証方式は、 Oracle Recovery Manager （ RMAN ）カタログデータベースに照らして認証します。外部のカタログメカニズムを設定し、データベースをカタログデータベースに登録している場合は、 RMAN カタログ認証を追加する必要があります。
