---
permalink: install/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter でデータ保護処理を有効にするには、複数のライセンスが必要です。インストールする SnapCenter ライセンスのタイプは、ストレージ環境および使用する機能によって異なります。 
---
= SnapCenter ライセンス
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter では、アプリケーション、データベース、ファイルシステム、および仮想マシンのデータを保護するために、複数のライセンスが必要になります。インストールする SnapCenter ライセンスのタイプは、ストレージ環境および使用する機能によって異なります。

|===
| 使用許諾 | 必要に応じて 


 a| 
SnapCenter 標準のコントローラベース
 a| 
FAS または AFF ストレージコントローラの場合は必須です

SnapCenter Standard ライセンスはコントローラベースのライセンスで、 Premium Bundle に含まれています。SnapManager スイートのライセンスをお持ちの場合は、 SnapCenter Standard のライセンスもご利用いただけます。FAS または AFF ストレージを使用した SnapCenter の試用版をインストールする場合は、営業担当者にお問い合わせください。


NOTE: SnapCenter は、データ保護バンドルの一部としても提供されます。A400 以降を購入している場合は、データ保護バンドルを購入する必要があります。



 a| 
SnapCenter - 容量ベース
 a| 
ONTAP Select および Cloud Volumes ONTAP で必要です

Cloud Volumes ONTAP または ONTAP Select を使用している場合は、 SnapCenter で管理するデータに基づいて、容量ベースのライセンスを 1TB 単位で購入する必要があります。デフォルトでは、 SnapCenter には 90 日間の 100TB SnapCenter の標準容量ベースの試用版ライセンスが組み込まれています。その他の詳細については、営業担当者にお問い合わせください。



 a| 
SnapMirror または SnapVault
 a| 
ONTAP

SnapCenter でレプリケーションを有効にする場合は、 SnapMirror または SnapVault のライセンスが必要です。



 a| 
SnapRestore
 a| 
バックアップのリストアおよび検証に必要です。

プライマリストレージシステム

* リモート検証に加えてバックアップからのリストアを実行するには、 SnapVault デスティネーションシステムに必要です。
* リモート検証を実行する場合は、 SnapMirror デスティネーションシステムに必要です。




 a| 
FlexClone
 a| 
データベースのクローニングおよび検証処理に必要です。

プライマリストレージシステムおよびセカンダリストレージシステム。

* セカンダリ SnapVault バックアップからクローンを作成する場合、 SnapVault デスティネーションシステムに必要です。
* セカンダリ SnapMirror バックアップからクローンを作成するには、 SnapMirror デスティネーションシステムに必要です。




 a| 
プロトコル
 a| 
* LUN 用の iSCSI または FC ライセンス
* SMB 共有の CIFS ライセンス
* NFS タイプの VMDK 用の NFS ライセンスです
* VMFS タイプの VMDK 用の iSCSI または FC ライセンス


ソースボリュームを利用できない場合に SnapMirror デスティネーションシステムからデータを提供するには、 SnapMirror デスティネーションシステムに必要です。



 a| 
SnapCenter 標準ライセンス（オプション）
 a| 
セカンダリデスティネーション


NOTE: セカンダリデスティネーションに SnapCenter Standard ライセンスを追加することを推奨しますが、必須ではありません。セカンダリデスティネーションで SnapCenter 標準ライセンスが有効になっていない場合、フェイルオーバー処理の実行後に、 SnapCenter を使用してセカンダリデスティネーションのリソースをバックアップすることはできません。ただし、クローニング処理と検証処理を実行するには、セカンダリデスティネーションに FlexClone ライセンスが必要です。

|===

NOTE: SnapCenter Advanced および SnapCenter NAS ファイルサービスのライセンスは廃止され、現在は提供されていません。

1 つ以上の SnapCenter ライセンスをインストールする必要があります。ライセンスの追加方法については、を参照してください link:..//install/concept_snapcenter_standard_controller_based_licenses.html["SnapCenter の標準コントローラベースのライセンスを追加します"] または 。



== Single Mailbox Recovery （ SMBR ）ライセンス

SnapCenter Plug-in for Exchange を使用して Microsoft Exchange Server データベースと Single Mailbox Recovery （ SMBR ）を管理している場合は、 SMBR のライセンスが追加で必要です。 SMBR の場合は、ユーザのメールボックスに基づいて別途購入する必要があります。

メールボックスが 1 、 000 、 5000 、 15000 、 25000 個という単位で提供されている SMBR ライセンスを購入する場合は、ネットアップの営業担当者にお問い合わせください。SKU の購入後、の手順に従ってライセンスを取得できます https://library.netapp.com/ecm/ecm_download_file/ECMLP2863893["SMBR リリースノート"^]。

ライセンスキーのリクエストを送信すると、 Kroll Ontrack は問題 50 メールボックスライセンスキーを送信します。資格に基づいて、 Kroll Ontrack は検証後にメールボックスのライセンスをアップグレードします。
