---
permalink: install/concept_configure_lun_storage.html 
sidebar: sidebar 
keywords: LUN storage, iSCSI, 
summary: SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を設定できます。SnapCenter を使用して、既存の LUN を Windows ホストに接続することもできます。 
---
= LUNストレージの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を設定できます。SnapCenter を使用して、既存の LUN を Windows ホストに接続することもできます。

LUNは、SAN構成におけるストレージの基本単位です。Windowsホストは、システム上のLUNを仮想ディスクとして認識します。詳細については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html["ONTAP 9 SAN構成ガイド"^]。



== iSCSIセッションを確立する

iSCSIを使用してLUNに接続する場合は、LUNを作成して通信を有効にする前にiSCSIセッションを確立する必要があります。

* 始める前に *

* ストレージシステムノードをiSCSIターゲットとして定義しておく必要があります。
* ストレージシステムでiSCSIサービスを開始しておく必要があります。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["詳細"^]


* このタスクについて *

iSCSIセッションは、同じバージョンのIP間（IPv6とIPv6、またはIPv4とIPv4）でのみ確立できます。

リンクローカルIPv6アドレスは、iSCSIセッションの管理や、ホストとターゲットの両方が同じサブネット内にある場合にのみ使用できます。

iSCSIイニシエータの名前を変更すると、iSCSIターゲットへのアクセスに影響します。名前を変更した場合、新しい名前が認識されるように、イニシエータがアクセスするターゲットの再設定が必要になることがあります。iSCSIイニシエータの名前を変更した場合は、ホストを再起動する必要があります。

ホストに複数の iSCSI インターフェイスがある場合、最初のインターフェイスで IP アドレスを使用して SnapCenter への iSCSI セッションを確立したあとで、別の IP アドレスを使用して別のインターフェイスから iSCSI セッションを確立することはできません。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * iSCSI Session （ iSCSI セッション） * をクリックします。
. Storage Virtual Machine * ドロップダウンリストから、 iSCSI ターゲットの Storage Virtual Machine （ SVM ）を選択します。
. [*Host*] ドロップダウン・リストから ' セッションのホストを選択します
. [ セッションの確立 ] をクリックします。
+
セッションの確立ウィザードが表示されます。

. Establish Session ウィザードで ' ターゲットを指定します
+
|===
| フィールド | 入力するコマンド 


 a| 
ターゲットノード名
 a| 
iSCSIターゲットのノード名

既存のターゲットノード名がある場合は、その名前が読み取り専用形式で表示されます。



 a| 
ターゲットポータルアドレス
 a| 
ターゲットネットワークポータルのIPアドレス



 a| 
ターゲットポータルポート
 a| 
ターゲットネットワークポータルのTCPポート



 a| 
イニシエータポータルアドレス
 a| 
イニシエータネットワークポータルのIPアドレス

|===
. 入力が完了したら、 * 接続 * をクリックします。
+
SnapCenter が iSCSI セッションを確立します。

. この手順を繰り返して、ターゲットごとにセッションを確立します。




== iSCSIセッションの切断

複数のセッションを使用しているターゲットからiSCSIセッションの切断が必要になる場合があります。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * iSCSI Session （ iSCSI セッション） * をクリックします。
. Storage Virtual Machine * ドロップダウンリストから、 iSCSI ターゲットの Storage Virtual Machine （ SVM ）を選択します。
. [*Host*] ドロップダウン・リストから ' セッションのホストを選択します
. iSCSI セッションのリストから、切断するセッションを選択し、 * セッションの切断 * をクリックします。
. [ セッションの切断 ] ダイアログボックスで、 [OK] をクリックします。
+
SnapCenter によって iSCSI セッションが切断されます。


