---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: 双方向SSL通信を設定して、Linuxホスト上のSnapCenterサーバとプラグインの間の相互通信を保護する必要があります。 
---
= Linuxホストでの双方向SSL通信の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
双方向SSL通信を設定して、Linuxホスト上のSnapCenterサーバとプラグインの間の相互通信を保護する必要があります。

.開始する前に
* LinuxホストのCA証明書を設定しておく必要があります。
* すべてのプラグインホストとSnapCenterサーバで双方向SSL通信を有効にしておく必要があります。


.手順
. certificate.pem *を_/etc/pki/ca-trust/source/anchors/_にコピーします。
. Linuxホストの信頼リストに証明書を追加します。
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. 証明書が信頼リストに追加されたかどうかを確認します。
`trust list | grep "<CN of your certificate>"`
. SnapCenter * nginx *ファイルの* ssl_certificate *と* ssl_certificate_key *を更新して再起動してください。
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. SnapCenterサーバGUIリンクを更新します。
. _/<installation path>/NetApp/snapcenter/SnapManagerWeb_および* SMCoreServiceHost.dll.config *（_/<installation path>/NetApp/snapcenter/SMCore_）で次のキーの値を更新します。
+
** <add key="SERVICE_CERTIFICATE_PATH" value="<path of certificate.pfx>" />
** <add key="SERVICE_CERTIFICATE_PASSWORD" value="<password>"/>


. 次のサービスを再起動します。
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. 証明書がSnapManager Webポートに接続されていることを確認します。
`openssl s_client -connect localhost:8146 -brief`
. 証明書がsmcoreポートに接続されていることを確認します。
`openssl s_client -connect localhost:8145 -brief`
. SPLキーストアとエイリアスのパスワードを管理します。
+
.. SPLプロパティファイルの* spl_keystore_pass *キーに割り当てられたSPLキーストアのデフォルトパスワードを取得します。
.. キーストアのパスワードを変更します。
`keytool -storepasswd -keystore keystore.jks`
.. 秘密鍵エントリのすべてのエイリアスのパスワードを変更します。
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. _spl.properties_のキー* spl_keystore_pass *と同じパスワードを更新します。
.. サービスを再起動します。


. プラグインLinuxホストで、SPLプラグインのキーストアにルート証明書と中間証明書を追加します。
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... keystore.jksのエントリを確認します。
`keytool -list -v -keystore <path to keystore.jks>`
... 必要に応じてエイリアスの名前を変更します。
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. _spl.properties_ファイルの* spl_certificate_alias *の値を_keystore.jks_に格納されている* certificate.pfx *のエイリアスで更新し、SPLサービスを再起動します。 `systemctl restart spl`
. 証明書がsmcoreポートに接続されていることを確認します。
`openssl s_client -connect localhost:8145 -brief`

