---
permalink: install/create-svm-roles-minimum-privileges.html 
sidebar: sidebar 
keywords: svm role, privileges 
summary: ONTAP の SVM を SnapCenter で使用するように設定し、 vsadmin ロールを使用したくない場合、 SVM ロールを作成する必要があります。 
---
= 最小権限を持つ SVM ロールを作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP で新しい SVM ユーザのロールを作成する場合、実行する必要がある ONTAP CLI コマンドがいくつかあります。ONTAP 内の SVM を SnapCenter で使用するように設定し、 vsadmin ロールを使用したくない場合、このロールが必要です。

* 手順 *

. ストレージシステムで、ロールを作成し、そのロールにすべての権限を割り当てます。
+
「 security login role create – vserver <svm_name> -role <svm_role_Name\> -cmddirname <permission\>`

+

NOTE: このコマンドは権限ごとに実行する必要があります。

. ユーザを作成し、そのユーザにロールを割り当てます。
+
「 security login create -user <user_name\> -vserver <svm_name> -application ontapi -authmethod password -role <svm_Role_Name\>` 」のように設定します

. ユーザのロックを解除します。
+
'security login unlock -user <user_name\> -vserver <svm_name\>`





== SVM ロールの作成および権限の割り当てに使用する ONTAP CLI コマンド

SVM ロールを作成して権限を割り当てるには、いくつかの ONTAP CLI コマンドを実行する必要があります。

* 「 security login role create -role SVM_SVM_SVM_Role_Name -cmddirname 」「 snapmirror list -destinations 」 -vserver SVM_name -access all 」
* 「 security login role create -role SVM_SVM_SVM_Role_Name -cmddirname 」 event generate-autosupport-log 「 -vserver svm_name -access all 」
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_Role_Name -cmddirname 」 job history show 「 -access all 」
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_Role_Name -cmddirname "job stop " -access all"
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_SVM_SVM_Role_name -cmddirname "LUN" -access all" 」
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun delete -access all を指定します
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun igroup add 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun igroup create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun igroup delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」「 lun igroup rename 」 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun igroup show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun mapping add-reporting-nodes 「 -access all 」
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_Role_Name -cmddirname "LUN mapping create " -access all"
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun mapping delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun mapping remove-reporting-nodes 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun mapping show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun modify 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun move-in -volume 」 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "LUN offline" -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "LUN online " -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "LUN resize " -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "LUN serial" -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 lun show 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_Role_Name -cmddirname " network interface " -access readonly 」
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 snapmirror policy add-rule -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 snapmirror policy modify -rule 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 snapmirror policy remove-rule 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 snapmirror policy show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "snapmirror restore" -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "snapmirror show " -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname "snapmirror update" -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 snapmirror update ls -set 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」「 version 」 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 volume clone create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume clone show 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 volume clone split start 「 -access all 」に設定されています
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume clone split stop 「 -access all 」に設定されています
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume create コマンド -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume destroy -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume file clone create 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 volume file show -disk -usage 「 -access all 」に設定されています
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume modify コマンド -access all `
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume offline 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume online 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume qtree create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume qtree delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume qtree modify 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume qtree show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume restrict 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume show コマンド「 -access all 」
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot modify 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 volume snapshot rename 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot restore コマンド -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot restore -file 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume snapshot show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 volume unmount 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver cifs share create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver cifs share delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver cifs share show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver cifs show 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver export-policy create 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver export-policy delete 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver export-policy rule create 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 vserver export-policy rule show 「 -access all 」
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver export-policy show 「 -access all 」 * の securitylogin role create -vserver SVM_name -role SVM_SVM_Role_Name -cmddirname 「 vserver iscsi connection show 」 -access all 」
* 「 security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname 」 vserver 「 -access readonly
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver export-policy 「 -access all
* 「 security login role create -vserver svm_name -role SVM_Role_Name -cmddirname 」 vserver iscsi 「 -access all
* 「 security login role create -vserver SVM_name -role SVM_SVM_SVM_Role_name -cmddirname 」「 volume clone split status 」 -access all 」

