---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6.1は、SANのみのお客様のニーズに合わせてシンプルな操作性を実現するASA R2システムをサポートしています。 
---
= SnapCenterでのASA R2システムのサポートについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6.1は、SANのみのお客様のニーズに合わせてシンプルな操作性を実現するASA R2システムをサポートしています。

ASA R2システムは、単一のHAペア環境ですべてのSANプロトコル（iSCSI、FC、NVMe over TCP/IP）をサポートします。SCSI（iSCSIおよびFC）プロトコルは、ホストとストレージの間のすべてのパスがアクティブ/最適化されるように、マルチパスに対称アクティブ/アクティブアーキテクチャを使用します。iSCSIプロトコルとNVMe/TCPプロトコルは、ホストとストレージ間の直接パスをサポートします。


NOTE: SnapCenterでは、ASA R2システムでVMware Virtual Machine File System（VMFS）のみがサポートされます。

ASA R2システムでは、ストレージユニットとコンシステンシグループを使用できます。

* ストレージユニットを使用すると、SANホストでデータ処理に使用できるストレージスペースが確保されます。ストレージユニットとは、SCSIホストの場合はLUN、NVMeホストの場合はNVMeネームスペースを指します。
* 整合グループは、1つのユニットとして管理されるストレージユニットの集まりです。


ASA R2システムは、ストレージユニットとコンシステンシグループを使用して、ストレージ管理とデータ保護を簡素化します。たとえば、10個のストレージユニットで構成されるデータベースが整合グループ内にあり、データベース全体をバックアップする必要があるとします。各ストレージユニットを個別にバックアップする代わりに、整合グループをバックアップすることでデータベース全体を保護できます。

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。



== ASA R2システム用のSnapCenter 6.1でサポートされる機能

ASA R2ストレージシステムを使用している場合、SnapCenterでは、SnapCenterでサポートされるすべてのアプリケーションに対して次の処理を実行できます。

* VMDK経由でのアプリケーションのプライマリバックアップの作成
* セカンダリストレージシステムへの整合グループSnapshotの転送
* バックアップのリストアと代替保存場所からのリストア
+
** VMware vMotionを使用したプライマリストレージとセカンダリストレージの両方からのIn Placeリストア
** プライマリストレージとセカンダリストレージの両方からの接続とコピーリストア


* バックアップのクローニングと別の場所へのクローニング




== ASA R2システム用のSnapCenter 6.1でサポートされない機能

* rawデバイスマッピング（RDM）
* Oracleヨウノアプリケーションホリユウム
* SAP HANA NDV
* LockVault
* 改ざん防止スナップショット
* フレックスグループ
* 階層整合グループ
* ONTAP 9.xからASA R2システムへの移行
* スナップショットの名前変更
* SQLプラグインホストのログディレクトリのセカンダリプロビジョニングは、SnapCenterでサポートされていません。は、ONTAP CLIまたはSystem Managerを使用して手動で設定する必要があります。

