---
permalink: install/reference_features_enabled_on_your_windows_host_during_installation.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: SnapCenter Server インストーラを使用すると、インストール中に Windows ホストで Windows の機能とロールが有効になります。これらは、トラブルシューティングやホストシステムのメンテナンスに役立つ場合があります。 
---
= インストール時にWindowsホストで有効になる機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Server インストーラを使用すると、インストール中に Windows ホストで Windows の機能とロールが有効になります。これらは、トラブルシューティングやホストシステムのメンテナンスに役立つ場合があります。

|===
| カテゴリ | 機能 


 a| 
Webサーバ
 a| 
* インターネットインフォメーションサービス
* World Wide Webサービス
* 一般的なHTTP機能
+
** 既定のドキュメント
** ディレクトリの参照
** HTTPエラー
** HTTPリダイレクション
** 静的なコンテンツ
** WebDAV発行


* 健全性と診断
+
** カスタムログ
** HTTPロギング
** ログツール
** リクエストモニター
** トレース


* パフォーマンス機能
+
** 静的なコンテンツの圧縮


* セキュリティ
+
** IPセキュリティ
** Basic Authentication の略
** 一元化されたSSL証明書のサポート
** クライアント証明書マッピング認証
** IIS クライアント証明書マッピング認証
** IPおよびドメインの制限
** 要求フィルタリング
** URL認証
** Windows認証


* アプリケーション開発機能
+
** です。 NET拡張性4.5
** アプリケーションの初期化
** ASP.NET Core Hosting Bundle（バージョン8.0.5以降、以降のすべての.NET 8パッチを含む）
** サーバー側インクルード
** WebSocketプロトコル


* 管理ツール
+
** IIS管理コンソール






 a| 
IIS管理スクリプトとツール
 a| 
* IIS管理サービス
* Web管理ツール




 a| 
+.NET Framework 8.0.5の機能+
 a| 
* .NET Frameworkバージョン8.0.5以降、以降のすべての.NET 8パッチを含む
* ASP.NETバージョン8.0.5以降、以降のすべての.NET 8パッチを含む
* Windows Communication Foundation (WCF) HTTPアクティブ化45
+
** TCPのアクティブ化
** HTTPアクティブ化




用。 NET固有のトラブルシューティング情報。を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["インターネットに接続されていないレガシーシステムでは、SnapCenter のアップグレードまたはインストールが失敗します"^]



 a| 
メッセージキュー
 a| 
* メッセージキューサービス
+

NOTE: SnapCenter が作成および管理する MSMQ サービスを他のアプリケーションが使用していないことを確認します。

* RabbitMQ




 a| 
Windowsプロセスアクティブ化サービス
 a| 
* プロセスモデル




 a| 
セツテイAPI
 a| 
すべて

|===