---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: SnapCenter サーバとアプリケーションまたはデータベースのプラグインをインストールする前に、接続とポートの要件が満たされていることを確認する必要があります。 
---
= 接続とポートの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバとアプリケーションまたはデータベースのプラグインをインストールする前に、接続とポートの要件が満たされていることを確認する必要があります。

* アプリケーションは1つのポートを共有できません。
+
各ポートは、適切なアプリケーション専用にする必要があります。

* デフォルトのポートを使用しない場合は、インストール時にカスタムポートを選択できます。
+
プラグインポートは、インストール後にホストの変更ウィザードを使用して変更できます。

* 固定ポートの場合は、デフォルトのポート番号を受け入れる必要があります。
* ファイアウォール
+
** ファイアウォール、プロキシ、またはその他のネットワークデバイスが接続に干渉しないようにしてください。
** SnapCenter のインストール時にカスタムポートを指定した場合は、プラグインホストに、 SnapCenter Plug-in Loader のそのポート用のファイアウォールルールを追加する必要があります。




次の表に、各ポートとそのデフォルト値を示します。

|===
| ポート名 | ポート番号 | プロトコル | 方向 | 説明 


 a| 
SnapCenterポート
 a| 
8146
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SnapCenterクライアント（SnapCenterユーザ）とSnapCenterサーバの間の通信に使用され、プラグインホストからSnapCenterサーバへの通信にも使用されます。

ポート番号はカスタマイズできます。



 a| 
SnapCenter SMCore通信ポート
 a| 
8145
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SnapCenter サーバとSnapCenter プラグインがインストールされているホストの間の通信に使用されます。

ポート番号はカスタマイズできます。



 a| 
スケジューラサービスポート
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
このポートは、SnapCenterサーバホスト内で管理されるすべてのプラグインのSnapCenterスケジューラワークフローを一元的にオーケストレーションするために使用されます。

ポート番号はカスタマイズできます。



 a| 
RabbitMQポート
 a| 
5672
 a| 
TCP
 a| 
 a| 
これはRabbitMQがリッスンするデフォルトポートで、スケジューラサービスとSnapCenter間のパブリッシャ/サブスクライバモデル通信に使用されます。



 a| 
MySQLのポート
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
このポートは、SnapCenterリポジトリデータベースとの通信に使用されます。SnapCenterサーバからMySQLサーバへのセキュアな接続を確立できます。 link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["詳細"]



 a| 
Windowsプラグインホスト
 a| 
135、445
 a| 
TCP
 a| 
 a| 
このポートは、SnapCenterサーバとプラグインがインストールされているホストの間の通信に使用されます。Microsoftが指定した追加のダイナミックポート範囲もオープンにする必要があります。



 a| 
LinuxまたはAIXプラグインホスト
 a| 
22
 a| 
SSH
 a| 
単方向
 a| 
このポートは、SnapCenterサーバとホスト間の通信に使用され、サーバからクライアントホストに開始されます。



 a| 
Windows、Linux、AIX向けSnapCenterプラグインパッケージ
 a| 
8145
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SMCoreとプラグインパッケージがインストールされているホストの間の通信に使用されます。カスタマイズ可能。

ポート番号はカスタマイズできます。



 a| 
SnapCenter Plug-in for Oracle Database
 a| 
27216
 a| 
 a| 
 a| 
デフォルトのJDBCポートは、Oracleデータベースへの接続にOracle用プラグインで使用されます。



 a| 
SnapCenter Plug-in for Exchangeデータベース
 a| 
909
 a| 
 a| 
 a| 
デフォルトのNETです。 TCPポートは、Plug-in for WindowsでExchange VSSコールバックに接続するために使用されます。



 a| 
NetAppでサポートされるSnapCenter用プラグイン
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
カスタムプラグインホストでのみ使用される内部ポートです。ファイアウォールの例外は必要ありません。

SnapCenterサーバとカスタムプラグインの間の通信は、ポート8145を介してルーティングされます。



 a| 
ONTAPクラスタまたはSVMの通信ポート
 a| 
* 443（HTTPS）
* 80（HTTP）

 a| 
* HTTPS
* HTTP

 a| 
双方向
 a| 
このポートは、SnapCenterサーバを実行するホストとSVMの間の通信にSAL（ストレージ抽象化レイヤ）で使用されます。現在、このポートは、SnapCenterプラグインホストとSVMの間の通信にSnapCenter for Windows Plug-inホストのSALでも使用されています。



 a| 
SAP HANAデータベース向けSnapCenterプラグイン
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
双方向
 a| 
マルチテナントデータベースコンテナ（MDC）のシングルテナントの場合、ポート番号は13で終わります。MDC以外の場合、ポート番号は15で終わります。

ポート番号はカスタマイズできます。



 a| 
PostgreSQL向けSnapCenterプラグイン
 a| 
5432
 a| 
 a| 
 a| 
このポートは、PostgreSQL用プラグインによるPostgreSQLクラスタへの通信に使用されるデフォルトのPostgreSQLポートです。

ポート番号はカスタマイズできます。

|===
ポートの詳細を変更するには、を参照してください link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["プラグインホストの変更"]。
