---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: SnapCenter サーバをインストールする前に、スペースとサイジングの要件を十分に理解しておく必要があります。また、利用可能なシステムおよびセキュリティの更新も適用する必要があります。 
---
= スペースとサイジングの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバをインストールする前に、スペースとサイジングの要件を十分に理解しておく必要があります。また、利用可能なシステムおよびセキュリティの更新も適用する必要があります。

|===
| 項目 | Windowsホストノヨウケン | Linux ホストの要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows の場合

サポートされているのは、英語版、ドイツ語版、日本語版、簡体字中国語版のオペレーティングシステムのみです。

サポートされているバージョンの最新情報については、を参照してください
https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。
 a| 
* Red Hat Enterprise Linux（RHEL）8および9
* SUSE Linux Enterprise Server（SLES）15


サポートされているバージョンの最新情報については、を参照してください
https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
最小 CPU 数
 a| 
4 コア
 a| 
4 コア



 a| 
最小 RAM
 a| 
8 GB


NOTE: MySQL Server のバッファプールでは、 RAM の合計の 20% が使用されます。
 a| 
8 GB



 a| 
SnapCenter サーバソフトウェアおよびログ用のハードドライブの最小容量
 a| 
7 GB


NOTE: SnapCenterサーバがインストールされているドライブと同じドライブにSnapCenterリポジトリがある場合は、15 GBを使用することを推奨します。
 a| 
15 GB



 a| 
SnapCenter リポジトリ用のハードドライブの最小容量
 a| 
8 GB


NOTE: メモ： SnapCenter リポジトリがインストールされているドライブに SnapCenter サーバがある場合は、 15 GB にすることを推奨します。
 a| 
該当なし



 a| 
必要なソフトウェアパッケージ
 a| 
* Microsoft .NET Framework 4.7.2以降
* ASP。 Net Core Hosting Bundle（8.0.5以降）
* PowerShell 7.4.2以降


.NET固有のトラブルシューティング情報については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["インターネットに接続されていないレガシーシステムでは、SnapCenter のアップグレードまたはインストールが失敗します"^]。
 a| 
* ASP。 Net Core Runtime 8.0.5以降
* PowerShell 7.4.2以降
* nginxはリバースプロキシとして使用できるWebサーバ
* PAM -デベル
+
PAM（Pluggable Authentication Modules）は、システム管理者が認証を行うプログラムを再コンパイルすることなく認証ポリシーを設定できるシステムセキュリティツールです。



|===