---
permalink: install/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version 
summary: サポートされるストレージシステム、アプリケーション、およびデータベースを確認しておく必要があります。 
---
= サポートされるストレージシステムおよびアプリケーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サポートされるストレージシステム、アプリケーション、およびデータベースを確認しておく必要があります。

* SnapCenter では、データを保護するために ONTAP 9.12.1 以降がサポートされています。
* SnapCenter は、 ONTAP ソフトウェア 4.5 P1 パッチリリースからデータを保護するために、 NetApp SnapCenter 用の Amazon FSX をサポートしています。
+
NetApp ONTAP に Amazon FSX を使用している場合、データ保護処理を実行するには、 SnapCenter サーバホストプラグインを 4.5 P1 以降にアップグレードする必要があります。

+
Non-Volatile Memory Express（NVMe）over Transport Control Protocol（TCP）をサポートします。

+
NetApp ONTAP の Amazon FSX の詳細については、を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP のドキュメント"^]。

* SnapCenter では、さまざまなアプリケーションやデータベースの保護がサポートされます。
+
サポートされているアプリケーションおよびデータベースの詳細については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。

* SnapCenter 4.9 P1以降では、Amazon Web Services（AWS）のSoftware-Defined Data Center（SDDC）環境上のVMware Cloudで、OracleとMicrosoft SQLのワークロードの保護がサポートされます。
+
詳細については、を参照してください https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["VMware Cloud on AWS SDDC環境でNetApp SnapCenterを使用してOracleやMS SQLのワークロードを保護"]。


