---
permalink: install/register_enable_software_access.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, register, new customer, NetApp account, enable, Amazon FSx for NetApp ONTAP, Azure NetApp Files 
summary: 既存のNetAppアカウントをお持ちでない場合は、次の手順に従ってソフトウェアにアクセスするために登録する必要があります。 
---
= 登録してSnapCenterソフトウェアにアクセス
:allow-uri-read: 


[role="lead"]
Amazon FSx for NetApp ONTAPまたはAzure NetApp Filesを初めて使用し、既存のNetAppアカウントを持っていない場合は、SnapCenterソフトウェアにアクセスするために登録する必要があります。

.開始する前に
* 会社のEメールIDにアクセスできる必要があります。
* Azure NetApp Filesを使用している場合は、AzureサブスクリプションIDが必要です。
* Amazon FSx for NetApp ONTAPを使用している場合は、FSx for ONTAPファイルシステムのファイルシステムIDが必要です。


.タスクの内容
登録には情報が検証されることがあります。新しいNetAppサポートサイト（NSS）アカウントの確認とアップグレードが完了するまでに最大1日かかる場合があります。

.手順
. をクリックし https://mysupport.netapp.com/site/user/registration[] て登録します。
. 企業のEメールIDを入力し、キャプチャを完了し、NetAppのプライバシーポリシーに同意して、*送信*をクリックします。
. EメールIDに送信されたOTPを入力して登録を認証し、* Continue *をクリックします。
. 登録完了ページで、以下の詳細を入力して登録を完了します。
+
.. NetApp Customer/End User *を選択します。
.. シリアル番号フィールドに、Azure NetApp Filesを使用している場合はAzureサブスクリプションID、Amazon FSx for NetApp ONTAPを使用している場合はファイルシステムIDを入力します。





NOTE: 登録中に問題が発生した場合、またはステータスを確認する場合は、でチケットを発行できます https://mysupport.netapp.com/site/help[] 。
