---
permalink: install/requirements-to-install-snapcenter-server.html 
sidebar: sidebar 
keywords: active directory domain, workgroups, multi-domain forests, cross-domain, cross-forest domains, browsers, chrome, IE, Edge, ports, port requirements, host utilities, Microsoft DSM, Windows MPIO 
summary: SnapCenterサーバをインストールする前に、すべての要件が満たされていることを確認する必要があります。 
---
= SnapCenterサーバをインストールするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WindowsホストまたはLinuxホストにSnapCenterサーバをインストールする前に、環境のすべての要件を確認し、満たしていることを確認する必要があります。



== Windowsホストノドメイントワアククルウフノヨウケン

SnapCenterサーバは、ドメインまたはワークグループ内のWindowsホストにインストールできます。

管理Privilegesを持つユーザは、SnapCenterサーバをインストールできます。

* Active Directoryドメイン：ローカル管理者の権限を持つドメインユーザを使用する必要があります。ドメインユーザは、Windowsホストのローカル管理者グループのメンバーである必要があります。
* ワークグループ：ローカル管理者の権限を持つローカルアカウントを使用する必要があります。


ドメイントラスト、マルチドメインフォレスト、およびクロスドメイントラストはサポートされますが、クロスフォレストドメインはサポートされません。詳細については、Active Directoryドメインと信頼に関するMicrosoftのドキュメントを参照してください。


NOTE: SnapCenter サーバをインストールしたあとに、 SnapCenter ホストが配置されているドメインを変更しないでください。SnapCenter サーバをインストールした時点のドメインから SnapCenter サーバホストを削除して、 SnapCenter サーバをアンインストールしようとすると、アンインストール処理は失敗します。



== スペースとサイジングの要件

スペースとサイジングの要件を把握しておく必要があります。

|===
| 項目 | Windowsホストノヨウケン | Linux ホストの要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows

英語版、ドイツ語版、日本語版、簡体字中国語版のみがサポートされています。

サポートされているバージョンの最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]。
 a| 
* Red Hat Enterprise Linux（RHEL）8および9
* SUSE Linux Enterprise Server（SLES）15


サポートされているバージョンの最新情報については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]。



 a| 
最小CPU数
 a| 
4コア
 a| 
4コア



 a| 
最小RAM
 a| 
8GB


NOTE: MySQL Serverのバッファプールは、RAMの合計容量の20%を使用します。
 a| 
8GB



 a| 
SnapCenter サーバソフトウェアおよびログ用のハードドライブの最小容量
 a| 
7GB


NOTE: SnapCenterサーバがインストールされているドライブと同じドライブにSnapCenterリポジトリがある場合は、15 GBを使用することを推奨します。
 a| 
15GB



 a| 
SnapCenterリポジトリ用の最小ハードドライブ容量
 a| 
8GB


NOTE: メモ： SnapCenter リポジトリがインストールされているドライブに SnapCenter サーバがある場合は、 15GB にすることを推奨します。
 a| 
該当なし



 a| 
必要なソフトウェアパッケージ
 a| 
* ASP.NET Core Runtime 8.0.12（およびそれ以降のすべての8.0.xパッチ）Hosting Bundle
* PowerShell 7.4.2以降


用。 NET固有のトラブルシューティング情報。を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["インターネットに接続されていないレガシーシステムでは、SnapCenter のアップグレードまたはインストールが失敗します"^]
 a| 
* .NET Framework 8.0.12（およびそれ以降のすべての8.0.xパッチ）
* PowerShell 7.4.2以降
* nginxはリバースプロキシとして使用できるWebサーバ
* PAM -デベル
+
PAM（Pluggable Authentication Modules）は、システム管理者が認証を行うプログラムを再コンパイルすることなく認証ポリシーを設定できるシステムセキュリティツールです。



|===

NOTE: ASP.NETコアは、Windows上のSnapCenterサーバーの一時ファイルシステムにアクセスするためにIIS_IUSRSを必要とします。



== SANホストの要件

SnapCenterにはHost UtilitiesもDSMも含まれていません。SnapCenterホストがSAN（FC / iSCSI）環境の一部である場合は、SnapCenterサーバホストに追加のソフトウェアをインストールして設定する必要があります。

* Host Utilities：Host UtilitiesはFCとiSCSIをサポートしており、WindowsサーバでMPIOを使用することができます。 https://docs.netapp.com/us-en/ontap-sanhost/hu_sanhost_index.html["詳細"^]です。
* Microsoft DSM for Windows MPIO：このソフトウェアは、Windows MPIOドライバと連携して、NetAppとWindowsホストコンピュータ間の複数のパスを管理します。ハイアベイラビリティ構成にはDSMが必要です。
+

NOTE: ONTAP DSMを使用していた場合は、Microsoft DSMに移行する必要があります。詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Data_ONTAP_DSM_for_Windows_MPIO/How_to_migrate_from_Data_ONTAP_DSM_4.1p1_to_Microsoft_native_DSM["ONTAP DSM から Microsoft DSM への移行方法"^]。





== ブラウザ要件

SnapCenterソフトウェアは、Chrome 125以降とMicrosoft Edge 110.0.1587.17以降をサポートしています。



== ポートの要件

SnapCenterソフトウェアは、異なるコンポーネント間の通信に異なるポートを必要とします。

* アプリケーションは1つのポートを共有できません。
* デフォルトのポートを使用しない場合は、インストール時にカスタムポートを選択できます。
* 固定ポートの場合は、デフォルトのポート番号を受け入れる必要があります。
* ファイアウォール
+
** ファイアウォール、プロキシ、またはその他のネットワークデバイスが接続に干渉しないようにしてください。
** SnapCenter のインストール時にカスタムポートを指定した場合は、プラグインホストに、 SnapCenter Plug-in Loader のそのポート用のファイアウォールルールを追加する必要があります。




次の表に、各ポートとそのデフォルト値を示します。

|===
| ポート名 | ポート番号 | プロトコル | 方向 | 説明 


 a| 
SnapCenterポート
 a| 
8146
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SnapCenterクライアント（SnapCenterユーザ）とSnapCenterサーバの間の通信に使用され、プラグインホストからSnapCenterサーバへの通信にも使用されます。

ポート番号はカスタマイズできます。



 a| 
SnapCenter SMCore通信ポート
 a| 
8145
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SnapCenter サーバとSnapCenter プラグインがインストールされているホストの間の通信に使用されます。

ポート番号はカスタマイズできます。



 a| 
スケジューラサービスポート
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
このポートは、SnapCenterサーバホスト内で管理されるすべてのプラグインのSnapCenterスケジューラワークフローを一元的にオーケストレーションするために使用されます。

ポート番号はカスタマイズできます。



 a| 
RabbitMQポート
 a| 
5672
 a| 
TCP
 a| 
 a| 
これはRabbitMQがリッスンするデフォルトポートで、スケジューラサービスとSnapCenter間のパブリッシャ/サブスクライバモデル通信に使用されます。



 a| 
MySQLのポート
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
このポートは、SnapCenterリポジトリデータベースとの通信に使用されます。SnapCenterサーバからMySQLサーバへのセキュアな接続を確立できます。 link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["詳細"]



 a| 
Windowsプラグインホスト
 a| 
135、445
 a| 
TCP
 a| 
 a| 
このポートは、SnapCenterサーバとプラグインがインストールされているホストの間の通信に使用されます。Microsoftが指定した追加のダイナミックポート範囲もオープンにする必要があります。



 a| 
LinuxまたはAIXプラグインホスト
 a| 
22
 a| 
SSH
 a| 
単方向
 a| 
このポートは、SnapCenterサーバとホスト間の通信に使用され、サーバからクライアントホストに開始されます。



 a| 
Windows、Linux、AIX向けSnapCenterプラグインパッケージ
 a| 
8145
 a| 
HTTPS
 a| 
双方向
 a| 
このポートは、SMCoreとプラグインパッケージがインストールされているホストの間の通信に使用されます。カスタマイズ可能。

ポート番号はカスタマイズできます。



 a| 
SnapCenter Plug-in for Oracle Database
 a| 
27216
 a| 
 a| 
 a| 
デフォルトのJDBCポートは、Oracleデータベースへの接続にOracle用プラグインで使用されます。



 a| 
SnapCenter Plug-in for Exchangeデータベース
 a| 
909
 a| 
 a| 
 a| 
デフォルトのNETです。 TCPポートは、Plug-in for WindowsでExchange VSSコールバックに接続するために使用されます。



 a| 
NetAppでサポートされるSnapCenter用プラグイン
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
これはプラグイン ホストでのみ使用される内部ポートであり、ファイアウォールの例外は必要ありません。

SnapCenter サーバーとプラグイン間の通信は、ポート 8145 を介してルーティングされます。



 a| 
ONTAPクラスタまたはSVMの通信ポート
 a| 
* 443（HTTPS）
* 80（HTTP）

 a| 
* HTTPS
* HTTP

 a| 
双方向
 a| 
このポートは、SnapCenterサーバを実行するホストとSVMの間の通信にSAL（ストレージ抽象化レイヤ）で使用されます。現在、このポートは、SnapCenterプラグインホストとSVMの間の通信にSnapCenter for Windows Plug-inホストのSALでも使用されています。



 a| 
SAP HANAデータベース向けSnapCenterプラグイン
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
双方向
 a| 
マルチテナントデータベースコンテナ（MDC）のシングルテナントの場合、ポート番号は13で終わります。MDC以外の場合、ポート番号は15で終わります。

ポート番号はカスタマイズできます。



 a| 
PostgreSQL向けSnapCenterプラグイン
 a| 
5432
 a| 
 a| 
 a| 
このポートは、PostgreSQL用プラグインによるPostgreSQLクラスタへの通信に使用されるデフォルトのPostgreSQLポートです。

ポート番号はカスタマイズできます。

|===