---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windowsホストは、ストレージシステム上のLUNを仮想ディスクとして認識します。SnapCenterを使用して、FC接続LUNまたはiSCSI接続LUNを作成および設定できます。 
---
= ディスクの作成と管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windowsホストは、ストレージシステム上のLUNを仮想ディスクとして認識します。SnapCenterを使用して、FC接続LUNまたはiSCSI接続LUNを作成および設定できます。

* SnapCenterはベーシックディスクのみをサポートします。ダイナミックディスクはサポートされていません。
* GPTの場合は1つのデータパーティションのみ、MBRの場合は1つのプライマリパーティションが許可されます。このパーティションには、NTFSまたはCSVFSでフォーマットされた1つのボリュームと、1つのマウントパスがあります。
* サポートされるパーティションスタイル： GPT 、 MBR 。 VMware UEFI VM では、 iSCSI ディスクのみがサポートされます



NOTE: SnapCenter では、ディスク名の変更はサポートされていません。SnapCenter で管理しているディスクの名前を変更すると、 SnapCenter 処理は正常に終了しません。



== ホスト上のディスクの表示

SnapCenter で管理している各 Windows ホスト上のディスクを表示できます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。





== クラスタ化ディスクの表示

SnapCenterで管理しているクラスタ上のクラスタディスクを表示できます。クラスタ化されたディスクは、[Hosts]ドロップダウンからクラスタを選択した場合にのみ表示されます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからクラスタを選択します
+
ディスクのリストが表示されます。





== iSCSIセッションを確立する

iSCSIを使用してLUNに接続する場合は、LUNを作成して通信を有効にする前にiSCSIセッションを確立する必要があります。

* 始める前に *

* ストレージシステムノードをiSCSIターゲットとして定義しておく必要があります。
* ストレージシステムでiSCSIサービスを開始しておく必要があります。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["詳細"^]


* このタスクについて *

iSCSIセッションは、同じバージョンのIP間（IPv6とIPv6、またはIPv4とIPv4）でのみ確立できます。

リンクローカルIPv6アドレスは、iSCSIセッションの管理や、ホストとターゲットの両方が同じサブネット内にある場合にのみ使用できます。

iSCSIイニシエータの名前を変更すると、iSCSIターゲットへのアクセスに影響します。名前を変更した場合、新しい名前が認識されるように、イニシエータがアクセスするターゲットの再設定が必要になることがあります。iSCSIイニシエータの名前を変更した場合は、ホストを再起動する必要があります。

ホストに複数の iSCSI インターフェイスがある場合、最初のインターフェイスで IP アドレスを使用して SnapCenter への iSCSI セッションを確立したあとで、別の IP アドレスを使用して別のインターフェイスから iSCSI セッションを確立することはできません。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * iSCSI Session （ iSCSI セッション） * をクリックします。
. Storage Virtual Machine * ドロップダウンリストから、 iSCSI ターゲットの Storage Virtual Machine （ SVM ）を選択します。
. [*Host*] ドロップダウン・リストから ' セッションのホストを選択します
. [ セッションの確立 ] をクリックします。
+
セッションの確立ウィザードが表示されます。

. Establish Session ウィザードで ' ターゲットを指定します
+
|===
| フィールド | 入力するコマンド 


 a| 
ターゲットノード名
 a| 
iSCSIターゲットのノード名

既存のターゲットノード名がある場合は、その名前が読み取り専用形式で表示されます。



 a| 
ターゲットポータルアドレス
 a| 
ターゲットネットワークポータルのIPアドレス



 a| 
ターゲットポータルポート
 a| 
ターゲットネットワークポータルのTCPポート



 a| 
イニシエータポータルアドレス
 a| 
イニシエータネットワークポータルのIPアドレス

|===
. 入力が完了したら、 * 接続 * をクリックします。
+
SnapCenter が iSCSI セッションを確立します。

. この手順を繰り返して、ターゲットごとにセッションを確立します。




== FC接続またはiSCSI接続のLUNまたはディスクを作成する

Windowsホストは、ストレージシステム上のLUNを仮想ディスクとして認識します。SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を作成および設定できます。

SnapCenter以外でディスクを作成してフォーマットする場合は、NTFSファイルシステムとCSVFSファイルシステムのみがサポートされます。

.開始する前に
* ストレージシステム上にLUN用のボリュームを作成しておく必要があります。
+
このボリュームには、 SnapCenter で作成した LUN のみを格納します。

+

NOTE: SnapCenter で作成したクローンボリュームには、クローンがすでにスプリットされている場合を除き、 LUN を作成することはできません。

* ストレージシステムでFCサービスまたはiSCSIサービスを開始しておく必要があります。
* iSCSIを使用している場合は、ストレージシステムとのiSCSIセッションを確立しておく必要があります。
* SnapCenter Plug-ins Package for Windowsは、ディスクを作成するホストにのみインストールする必要があります。


* このタスクについて *

* Windows Serverフェイルオーバークラスタ内のホストでLUNを共有しないかぎり、LUNを複数のホストに接続することはできません。
* Cluster Shared Volume（CSV；クラスタ共有ボリューム）を使用するWindows Serverフェイルオーバークラスタ内のホストでLUNを共有する場合は、クラスタグループを所有するホストにディスクを作成する必要があります。


* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
. [ 新規作成（ New ） ] をクリックする。
+
Create Disk（ディスクの作成）ウィザードが開きます。

. [LUN Name]ページで、LUNを特定します。
+
|===
| フィールド | 操作 


 a| 
ストレージシステム
 a| 
LUN の SVM を選択します。



 a| 
LUNパス
 a| 
「 * Browse * 」をクリックして、 LUN を含むフォルダのフルパスを選択します。



 a| 
LUN名
 a| 
LUN の名前を入力します。



 a| 
クラスタサイズ
 a| 
クラスタのLUNブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティングシステムとアプリケーションによって異なります。



 a| 
LUNラベル
 a| 
必要に応じて、LUNの説明を入力します。

|===
. [Disk Type]ページで、ディスクタイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
専用ディスク
 a| 
LUNにアクセスできるホストは1つだけです。

[* リソースグループ * ] フィールドは無視してください。



 a| 
共有ディスク
 a| 
Windows Serverフェイルオーバークラスタ内のホストでLUNを共有します。

[ * リソースグループ * ] フィールドにクラスタリソースグループの名前を入力します。ディスクは、フェイルオーバークラスタ内の1つのホストにのみ作成する必要があります。



 a| 
クラスタ共有ボリューム（CSV）
 a| 
CSVを使用するWindows Serverフェイルオーバークラスタ内のホストでLUNを共有します。

[ * リソースグループ * ] フィールドにクラスタリソースグループの名前を入力します。ディスクを作成するホストがクラスタグループの所有者であることを確認します。

|===
. [Drive Properties]ページで、ドライブのプロパティを指定します。
+
|===
| プロパティ | 説明 


 a| 
マウントポイントを自動割り当て
 a| 
SnapCenter では、システムドライブに基づいてボリュームマウントポイントが自動的に割り当てられます。

たとえば、システムドライブが C: の場合、自動割り当てでは C: ドライブ (C:\scmnpt) の下にボリュームマウントポイントが作成されます。自動割り当ては共有ディスクではサポートされません。



 a| 
ドライブ文字の割り当て
 a| 
ドロップダウンリストで選択したドライブにディスクをマウントします。



 a| 
ボリュームマウントポイントを使用する
 a| 
フィールドで指定したドライブパスにディスクをマウントします。

ボリュームマウントポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
ドライブレターまたはボリュームマウントポイントを割り当てない
 a| 
Windowsでディスクを手動でマウントする場合は、このオプションを選択します。



 a| 
LUNサイズ
 a| 
LUNサイズを指定します（150MB以上）。

ドロップダウンリストでMB、GB、またはTBを選択します。



 a| 
このLUNをホストするボリュームにシンプロビジョニングを使用する
 a| 
LUNをシンプロビジョニングします。

シンプロビジョニングでは、一度に必要な量のストレージスペースのみが割り当てられるため、LUNは使用可能な最大容量まで効率的に拡張されます。

必要になると思われるすべてのLUNストレージを格納できるだけの十分なスペースがボリュームにあることを確認してください。



 a| 
パーティションタイプを選択
 a| 
GUIDパーティションテーブルの場合はGPTパーティション、マスターブートレコードの場合はMBRパーティションを選択します。

MBRパーティションは、Windows Serverフェイルオーバークラスタでミスアライメントの問題を引き起こす可能性があります。


NOTE: Unified Extensible Firmware Interface（UEFI）パーティションディスクはサポートされていません。

|===
. [Map LUN]ページで、ホスト上のiSCSIイニシエータまたはFCイニシエータを選択します。
+
|===
| フィールド | 操作 


 a| 
ホスト
 a| 
クラスタグループ名をダブルクリックしてドロップダウンリストに表示されたクラスタに属するホストの一覧から、イニシエータのホストを選択します。

このフィールドは、Windows Serverフェイルオーバークラスタ内のホストでLUNを共有している場合にのみ表示されます。



 a| 
ホストイニシエータを選択
 a| 
Fibre Channel * または * iSCSI * を選択し、ホスト上のイニシエータを選択します。

FCでMultipath I/O（MPIO；マルチパスI/O）を使用している場合は、FCイニシエータを複数選択できます。

|===
. [Group Type]ページで、既存のigroupをLUNにマッピングするか新しいigroupを作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータ用に新しいigroupを作成
 a| 
選択したイニシエータ用に新しいigroupを作成します。



 a| 
選択したイニシエータ用に既存のigroupを選択するか、新しいigroupを指定する
 a| 
選択したイニシエータ用に既存のigroupを指定するか、指定した名前で新しいigroupを作成します。

igroup name * フィールドに igroup 名を入力します。既存のigroup名の最初の数文字を入力すると、このフィールドに自動的に入力されます。

|===
. [ 概要 ] ページで選択内容を確認し、 [ 完了 ] をクリックします。
+
SnapCenter によって LUN が作成され、ホスト上の指定したドライブまたはドライブパスに接続されます。





== ディスクのサイズ変更

ストレージシステムのニーズの変化に応じて、ディスクのサイズを増減できます。

* このタスクについて *

* シンプロビジョニングLUNの場合、ONTAP LUNジオメトリのサイズが最大サイズとして表示されます。
* シックプロビジョニングLUNの場合、拡張可能なサイズ（ボリューム内の利用可能なサイズ）が最大サイズとして表示されます。
* MBRパーティション形式のLUNのサイズの上限は2TBです。
* GPTパーティション形式のLUNのストレージシステムサイズの上限は16TBです。
* LUNのサイズを変更する前にSnapshotを作成しておくことを推奨します。
* LUNのサイズ変更前に作成されたSnapshotからLUNをリストアする必要がある場合は、SnapCenterによってLUNのサイズがSnapshotのサイズに自動的に変更されます。
+
リストア処理後、サイズ変更後にLUNに追加されたデータを、サイズ変更後に作成されたSnapshotからリストアする必要があります。



* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [Host]ドロップダウンリストからホストを選択します。
+
ディスクのリストが表示されます。

. サイズを変更するディスクを選択し、 * サイズ変更 * をクリックします。
. [ディスクのサイズ変更]ダイアログボックスで、スライダツールを使用してディスクの新しいサイズを指定するか、[サイズ]フィールドに新しいサイズを入力します。
+

NOTE: サイズを手動で入力する場合は、[縮小]または[展開]ボタンを適切に有効にする前に、[サイズ]フィールドの外側をクリックする必要があります。また、単位を指定するには、 MB 、 GB 、または TB をクリックする必要があります。

. 入力内容に問題がなければ、必要に応じて、 [ * 縮小（ * Shrink ） ] または [ * 展開（ * Expand ） ] をクリックします。
+
SnapCenter はディスクのサイズを変更します。





== ディスクの接続

[Connect Disk]ウィザードを使用して、既存のLUNをホストに接続したり、切断されたLUNを再接続したりできます。

.開始する前に
* ストレージシステムでFCサービスまたはiSCSIサービスを開始しておく必要があります。
* iSCSIを使用している場合は、ストレージシステムとのiSCSIセッションを確立しておく必要があります。
* Windows Serverフェイルオーバークラスタ内のホストでLUNを共有しないかぎり、LUNを複数のホストに接続することはできません。
* Cluster Shared Volume（CSV；クラスタ共有ボリューム）を使用するWindows Serverフェイルオーバークラスタ内のホストでLUNを共有する場合は、クラスタグループを所有するホストにディスクを接続する必要があります。
* Plug-in for Windows をインストールする必要があるのは、ディスクを接続するホストだけです。


* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
. [ 接続 ] をクリックします。
+
[Connect Disk]ウィザードが開きます。

. [LUN Name]ページで、接続先のLUNを特定します。
+
|===
| フィールド | 操作 


 a| 
ストレージシステム
 a| 
LUN の SVM を選択します。



 a| 
LUNパス
 a| 
[* Browse] をクリックして、 LUN を含むボリュームの完全パスを選択します。



 a| 
LUN名
 a| 
LUN の名前を入力します。



 a| 
クラスタサイズ
 a| 
クラスタのLUNブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティングシステムとアプリケーションによって異なります。



 a| 
LUNラベル
 a| 
必要に応じて、LUNの説明を入力します。

|===
. [Disk Type]ページで、ディスクタイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
専用ディスク
 a| 
LUNにアクセスできるホストは1つだけです。



 a| 
共有ディスク
 a| 
Windows Serverフェイルオーバークラスタ内のホストでLUNを共有します。

ディスクはフェイルオーバークラスタ内の1つのホストにのみ接続する必要があります。



 a| 
クラスタ共有ボリューム（CSV）
 a| 
CSVを使用するWindows Serverフェイルオーバークラスタ内のホストでLUNを共有します。

ディスクに接続するホストがクラスタグループの所有者であることを確認します。

|===
. [Drive Properties]ページで、ドライブのプロパティを指定します。
+
|===
| プロパティ | 説明 


 a| 
自動割り当て
 a| 
システムドライブに基づいて、 SnapCenter で自動的にボリュームマウントポイントを割り当てます。

たとえば、システムドライブが C: の場合、自動割り当てプロパティは C: ドライブ (C:\scmnpt) の下にボリュームマウントポイントを作成します。自動割り当てプロパティは共有ディスクではサポートされていません。



 a| 
ドライブ文字の割り当て
 a| 
ドロップダウンリストで選択したドライブにディスクをマウントします。



 a| 
ボリュームマウントポイントを使用する
 a| 
フィールドで指定したドライブパスにディスクをマウントします。

ボリュームマウントポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
ドライブレターまたはボリュームマウントポイントを割り当てない
 a| 
Windowsでディスクを手動でマウントする場合は、このオプションを選択します。

|===
. [Map LUN]ページで、ホスト上のiSCSIイニシエータまたはFCイニシエータを選択します。
+
|===
| フィールド | 操作 


 a| 
ホスト
 a| 
クラスタグループ名をダブルクリックしてドロップダウンリストに表示されたクラスタに属するホストのうち、イニシエータに使用するホストを選択します。

このフィールドは、Windows Serverフェイルオーバークラスタ内のホストでLUNを共有している場合にのみ表示されます。



 a| 
ホストイニシエータを選択
 a| 
Fibre Channel * または * iSCSI * を選択し、ホスト上のイニシエータを選択します。

FCでMPIOを使用している場合は、FCイニシエータを複数選択できます。

|===
. [Group Type]ページで、既存のigroupをLUNにマッピングするか新しいigroupを作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータ用に新しいigroupを作成
 a| 
選択したイニシエータ用に新しいigroupを作成します。



 a| 
選択したイニシエータ用に既存のigroupを選択するか、新しいigroupを指定する
 a| 
選択したイニシエータ用に既存のigroupを指定するか、指定した名前で新しいigroupを作成します。

igroup name * フィールドに igroup 名を入力します。既存のigroup名の最初の数文字を入力すると、自動的に入力されます。

|===
. [ 概要 ] ページで選択内容を確認し、 [ 完了 ] をクリックします。
+
SnapCenter は、ホスト上の指定したドライブまたはドライブパスに LUN を接続します。





== ディスクの切断

LUN は内容を残したままホストから切断できます。ただし、スプリットせずにクローンを切断した場合、クローンの内容は失われます。

.開始する前に
* LUNがどのアプリケーションでも使用されていないことを確認します。
* LUNが監視ソフトウェアで監視されていないことを確認します。
* LUN が共有されている場合は、 LUN からクラスタリソースの依存関係を解除し、クラスタ内のすべてのノードの電源がオンで正常に機能しており、 SnapCenter からアクセスできることを確認します。


* このタスクについて *

SnapCenter が作成した FlexClone ボリュームの LUN を切断した場合、そのボリュームに他の LUN が接続されていなければ、 SnapCenter はボリュームを削除します。この場合、 LUN が切断される前に、 FlexClone ボリュームが削除される可能性があることを警告するメッセージが SnapCenter に表示されます。

FlexCloneボリュームが自動的に削除されないようにするには、最後のLUNを切断する前にボリュームの名前を変更する必要があります。ボリュームの名前を変更するときは、最後の文字だけでなく、複数の文字を変更してください。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。

. 切断するディスクを選択し、 * 切断 * をクリックします。
. [ ディスクの切断 ] ダイアログボックスで、 [OK] をクリックします。
+
SnapCenter によってディスクが切断されます。





== ディスクの削除

不要になったディスクは削除できます。削除したディスクは復元できません。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。

. 削除するディスクを選択し、 * 削除 * をクリックします。
. [ ディスクの削除 ] ダイアログボックスで、 [OK] をクリックします。
+
SnapCenter によってディスクが削除されます。


