---
permalink: install/task_establish_an_iscsi_session.html 
sidebar: sidebar 
keywords: iSCSI session 
summary: iSCSI を使用して LUN に接続する場合は、 LUN を作成して通信を有効にする前に、 iSCSI セッションを確立する必要があります。 
---
= iSCSI セッションを確立します
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI を使用して LUN に接続する場合は、 LUN を作成して通信を有効にする前に、 iSCSI セッションを確立する必要があります。

* 始める前に *

* ストレージシステムのノードを iSCSI ターゲットとして定義しておく必要があります。
* ストレージシステムで iSCSI サービスを開始しておく必要があります。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["詳細はこちら。"^]


* このタスクについて *

iSCSI セッションは、 IPv6 と IPv6 のどちらか、または IPv4 と IPv4 の同じ IP バージョンの間でのみ確立できます。

iSCSI セッションの管理、およびホストとターゲットの間の通信には、両方が同じサブネット内にある場合にのみ、リンクローカル IPv6 アドレスを使用できます。

iSCSI イニシエータの名前を変更すると、 iSCSI ターゲットへのアクセスに影響します。名前を変更した場合、新しい名前が認識されるように、イニシエータがアクセスするターゲットの再設定が必要になることがあります。iSCSI イニシエータの名前を変更した場合、ホストを必ず再起動してください。

ホストに複数の iSCSI インターフェイスがある場合、最初のインターフェイスで IP アドレスを使用して SnapCenter への iSCSI セッションを確立したあとで、別の IP アドレスを使用して別のインターフェイスから iSCSI セッションを確立することはできません。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * iSCSI Session （ iSCSI セッション） * をクリックします。
. Storage Virtual Machine * ドロップダウンリストから、 iSCSI ターゲットの Storage Virtual Machine （ SVM ）を選択します。
. [*Host*] ドロップダウン・リストから ' セッションのホストを選択します
. [ セッションの確立 ] をクリックします。
+
セッションの確立ウィザードが表示されます。

. Establish Session ウィザードで ' ターゲットを指定します
+
|===
| フィールド | 入力するコマンド 


 a| 
ターゲットノード名
 a| 
iSCSI ターゲットのノード名

既存のターゲットノード名がある場合は、その名前が読み取り専用形式で表示されます。



 a| 
ターゲットポータルのアドレス
 a| 
ターゲットネットワークポータルの IP アドレス



 a| 
ターゲットポータルポート
 a| 
ターゲットネットワークポータルの TCP ポート



 a| 
イニシエータポータルのアドレス
 a| 
イニシエータネットワークポータルの IP アドレス

|===
. 入力が完了したら、 * 接続 * をクリックします。
+
SnapCenter が iSCSI セッションを確立します。

. この手順を繰り返して、各ターゲットのセッションを確立します。

