---
permalink: install/task_add_an_rbac_role_using_security_login_commands.html 
sidebar: sidebar 
keywords: RBAC roles, add, NetApp ONTAP RBAC role, storage system 
summary: ストレージシステムでclustered NetApp ONTAPを実行している場合は、security loginコマンドを使用してNetApp ONTAP RBACロールを追加できます。 
---
= security loginコマンドを使用してNetApp ONTAP RBACロールを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムでclustered ONTAPを実行している場合は、security loginコマンドを使用してNetApp ONTAP RBACロールを追加できます。

.開始する前に
* 実行するタスク (1 つまたは複数) と、それらのタスクを実行するために必要な権限を特定します。
* コマンドおよびコマンドディレクトリ（あるいはその両方）に権限を付与します。
+
各コマンド/コマンドディレクトリには、フルアクセスと読み取り専用の2つのアクセスレベルがあります。

+
フルアクセス権限は必ず最初に割り当てる必要があります。

* ユーザにロールを割り当てます。
* SnapCenter プラグインがクラスタ全体の Cluster Administrator IP に接続されているか、クラスタ内の SVM に直接接続されているかに応じて構成を識別します。


.タスクの内容
ストレージ システムでのこれらのロールの構成を簡素化するには、NetApp コミュニティ フォーラムに掲載されている NetApp ONTAP ツール用の RBAC User Creator を使用できます。

このツールは、ONTAP Privilegesの正しく設定を自動的に処理します。たとえば、RBAC User Creator for NetApp ONTAPツールでは、フルアクセスのPrivilegesが最初に表示されるように、Privilegesが正しい順序で自動的に追加されます。最初に読み取り専用Privilegesを追加してからフルアクセスPrivilegesを追加すると、ONTAPはフルアクセスPrivilegesを重複としてマークし、無視します。


NOTE: SnapCenterまたはONTAPをあとからアップグレードする場合は、RBAC User Creator for NetApp ONTAPツールを再実行して、以前に作成したユーザロールを更新する必要があります。以前のバージョンのSnapCenterまたはONTAP用に作成されたユーザロールは、アップグレード後のバージョンでは正常に機能しません。ツールを再実行すると、アップグレードが自動的に処理されます。ロールを再作成する必要はありません。

ONTAP RBACロールの設定の詳細については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-adm-auth-rbac/home.html["ONTAP 9管理者認証とRBACパワーガイド"^]。

.手順
. ストレージシステムで、次のコマンドを入力して新しいロールを作成します。
+
`security login role create <role_name\> -cmddirname "command" -access all –vserver <svm_name\>`

+
** svm_nameには、SVMの名前を指定します。空白のままにすると、デフォルトでクラスタ管理者が設定されます。
** role_nameは、ロールに指定する名前です。
** commandはONTAP機能です。
+

NOTE: このコマンドは権限ごとに繰り返す必要があります。フルアクセスコマンドは、読み取り専用コマンドの前に指定する必要があります。

+
権限のリストについては、を参照してください link:../install/task_create_an_ontap_cluster_role_with_minimum_privileges.html#ontap-cli-commands-for-creating-cluster-roles-and-assigning-permissions["ロールの作成と権限の割り当てに使用するONTAP CLIコマンド"^]。



. 次のコマンドを入力して、ユーザ名を作成します。
+
`security login create -username <user_name\> -application ontapi -authmethod <password\> -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`

+
** user_nameは、作成するユーザの名前です。
** <password> は、パスワードです。パスワードを指定しないと、パスワードの入力を求めるプロンプトが表示されます。
** svm_nameには、SVMの名前を指定します。


. 次のコマンドを入力して、ユーザにロールを割り当てます。
+
`security login modify username <user_name\> –vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`

+
** <user_name> は、手順 2 で作成したユーザの名前です。このコマンドでは、ロールに関連付けるユーザを変更できます。
** <svm_name> は SVM の名前です。
** <role_name> は、手順 1 で作成したロールの名前です。
** <password> は、パスワードです。パスワードを指定しないと、パスワードの入力を求めるプロンプトが表示されます。


. 次のコマンドを入力して、ユーザが正しく作成されたことを確認します。
+
`security login show –vserver <svm_name\> -user-or-group-name <user_name\>`

+
user_nameは、手順3で作成したユーザの名前です。


