---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard, features enabled 
summary: SnapCenterサーバインストーラの実行可能ファイルを実行して、SnapCenterサーバをインストールできます。 
---
= WindowsホストへのSnapCenterサーバのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterサーバインストーラの実行可能ファイルを実行して、SnapCenterサーバをインストールできます。

必要に応じて、PowerShellコマンドレットを使用して、いくつかのインストールと設定の手順を実行できます。PowerShell 7.4.2以降を使用している必要があります。


NOTE: コマンドラインからのSnapCenterサーバのサイレントインストールはサポートされていません。

.開始する前に
* SnapCenterサーバホストにWindowsの更新プログラムが適用されていて、システムの再起動が保留されていないことが必要です。
* SnapCenterサーバをインストールするホストにMySQLサーバがインストールされていないことを確認しておく必要があります。
* Windowsインストーラのデバッグを有効にしておく必要があります。
+
を有効にする方法については、MicrosoftのWebサイトを参照して https://support.microsoft.com/kb/223300["Windows インストーラのログ"^]ください。

+

NOTE: SnapCenter サーバは、 Microsoft Exchange サーバ、 Active Directory サーバ、またはドメインネームサーバが配置されたホストにはインストールしないでください。



.手順
. からSnapCenterサーバインストールパッケージをダウンロードし https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetAppサポートサイト"^]ます。
. ダウンロードした.exeファイルをダブルクリックして、SnapCenterサーバのインストールを開始します。
+
インストールを開始すると、すべての事前確認が実行され、最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
警告メッセージは無視してインストールを続行できますが、エラーは修正する必要があります。

. SnapCenterサーバのインストールに必要な値があらかじめ入力されていることを確認し、必要に応じて変更します。
+
MySQL Serverリポジトリデータベースのパスワードを指定する必要はありません。SnapCenterサーバのインストール中に、パスワードが自動的に生成されます。

+

NOTE: パスに特殊文字「%」が含まれ%`" is not supported in the custom path for the repository database. If you include "`ていると、インストールが失敗します。

. [ 今すぐインストール ] をクリックします。
+
無効な値を指定した場合は、該当するエラーメッセージが表示されます。値を再入力してからインストールを開始してください。

+

NOTE: [Cancel] * ボタンをクリックすると、実行中のステップが完了し、ロールバック操作が開始されます。SnapCenter サーバがホストから完全に削除されます。

+
ただし、「 SnapCenter サーバサイトの再起動」または「 SnapCenter サーバの起動を待機中」の処理が実行されているときに「 * キャンセル」をクリックすると、処理はキャンセルされずにインストールが続行されます。

+
ログファイルは常に、管理者ユーザの%temp%フォルダに（古いものから順に）表示されます。ログの場所をリダイレクトする場合は、コマンドプロンプトから次のコマンドを実行してSnapCenterサーバのインストールを開始します。``C:\installer_location\installer_name.exe /log"C:\"``





== インストール中に Windows ホストで有効になる機能

SnapCenter Serverインストーラは、インストール中にWindowsホスト上でWindowsの機能とロールを有効にします。これらは、ホストシステムのトラブルシューティングやメンテナンスに役立つ場合があります。

|===
| カテゴリ | 機能 


 a| 
Webサーバ
 a| 
* インターネットインフォメーションサービス
* World Wide Webサービス
* 一般的なHTTP機能
+
** 既定のドキュメント
** ディレクトリの参照
** HTTPエラー
** HTTPリダイレクション
** 静的なコンテンツ
** WebDAV発行


* 健全性と診断
+
** カスタムログ
** HTTPロギング
** ログツール
** リクエストモニター
** トレース


* パフォーマンス機能
+
** 静的なコンテンツの圧縮


* セキュリティ
+
** IPセキュリティ
** Basic Authentication の略
** 一元化されたSSL証明書のサポート
** クライアント証明書マッピング認証
** IIS クライアント証明書マッピング認証
** IPおよびドメインの制限
** 要求フィルタリング
** URL認証
** Windows認証


* アプリケーション開発機能
+
** です。 NET拡張性4.5
** アプリケーションの初期化
** ASP.NET Core Runtime 8.0.12（およびそれ以降のすべての8.0.xパッチ）Hosting Bundle
** サーバー側インクルード
** WebSocketプロトコル


* 管理ツール
+
** IIS管理コンソール






 a| 
IIS管理スクリプトとツール
 a| 
* IIS管理サービス
* Web管理ツール




 a| 
+.NET Framework 8.0.12の機能+
 a| 
* ASP.NET Core Runtime 8.0.12（およびそれ以降のすべての8.0.xパッチ）Hosting Bundle
* Windows Communication Foundation (WCF) HTTPアクティブ化45
+
** TCPのアクティブ化
** HTTPアクティブ化




用。 NET固有のトラブルシューティング情報。を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["インターネットに接続されていないレガシーシステムでは、SnapCenter のアップグレードまたはインストールが失敗します"^]



 a| 
Windowsプロセスアクティブ化サービス
 a| 
プロセスモデル



 a| 
セツテイAPI
 a| 
すべて

|===