---
permalink: install/task_create_an_ontap_cluster_role_with_minimum_privileges.html 
sidebar: sidebar 
keywords: ONTAP cluster role, privileges 
summary: 最小限の権限で ONTAP クラスタロールを作成して、 SnapCenter の admin ロールを使用して ONTAP で処理を実行する必要がないようにする必要があります。ONTAP のいくつかの CLI コマンドを実行して、 ONTAP クラスタロールを作成し、最小限の権限を割り当てることができます。 
---
= 最小限の権限で ONTAP クラスタロールを作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
最小限の権限で ONTAP クラスタロールを作成して、 SnapCenter の admin ロールを使用して ONTAP で処理を実行する必要がないようにする必要があります。ONTAP のいくつかの CLI コマンドを実行して、 ONTAP クラスタロールを作成し、最小限の権限を割り当てることができます。

* 手順 *

. ストレージシステムで、ロールを作成し、そのロールにすべての権限を割り当てます。
+
「 security login role create – vserver <cluster_name> -role <role_name\> -cmddirname <permission\>` 」

+

NOTE: このコマンドは権限ごとに実行する必要があります。

. ユーザを作成し、そのユーザにロールを割り当てます。
+
「 securitylogin create -user <user_name\> -vserver <cluster_name\> -application ontapi -authmethod password -role <role_name\> 」のようになります

. ユーザのロックを解除します。
+
「 securitylogin unlock -user <user_name\\> -vserver <cluster_name\\> 」のようになります





== ロールの作成および権限の割り当てに使用する ONTAP CLI コマンド

ロールを作成して権限を割り当てるには、いくつかの ONTAP CLI コマンドを実行する必要があります。

* 「 securitylogin role create -role Role_Name -cmddirname 」 cluster identity modify -vserver SVM_name or cluster_name -access all ’
* 「 securitylogin role create -role Role_Name -cmddirname 」 cluster identity show -vserver SVM_name or Cluster_name -access all
* 「 securitylogin role create -role Role_Name -cmddirname 」 cluster modify -vserver SVM_name or Cluster_name -access all
* 「 securitylogin role create -role Role_Name -cmddirname 」 cluster peer show -vserver SVM_name or Cluster_name -access all
* 「 securitylogin role create -role Role_Name -cmddirname 」 cluster show -vserver SVM_name or Cluster_name -access all
* 「 securitylogin role create -role Role_Name -cmddirname 」 event generate-autosupport-log 「 -vserver SVM_name or cluster_name -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 job history show 「 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 job stop 「 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "LUN" -access all
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "LUN create " -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "lun delete " -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun igroup add 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun igroup create 「 -access all
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "lun igroup delete " -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun igroup modify 「 -access all
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "LUN igroup rename " -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun igroup show 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun mapping add-reporting-nodes 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun mapping create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun mapping delete 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun mapping remove-reporting-nodes 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 lun mapping show 「 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 lun modify 「 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 lun move-in -volume 」 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "LUN offline" -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "LUN online " -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 lun persistent-reservation clear コマンド -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "LUN resize " -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "LUN serial" -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "lun show " -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 network interface create 「 -access readonly
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 network interface delete 「 -access readonly 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 network interface modify 「 -access readonly 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 network interface show 「 -access readonly 」を指定します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 security login 「 -access readonly
* 「 securitylogin role create -role Role_Name -cmddirname 」 -vserver SVM_name or Cluster_name -access all
* 「 securitylogin role create -role Role_Name -cmddirname 」「 snapmirror list -destinations 」 -vserver SVM_name または cluster_name -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 snapmirror policy add -rule 「 -access all 」に設定されています
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "snapmirror policy create " -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "snapmirror policy delete " -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 snapmirror policy modify 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 snapmirror policy modify -rule 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 snapmirror policy remove-rule 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "snapmirror policy show " -access all 」を実行します
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "snapmirror restore" -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "snapmirror show " -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "snapmirror show -history" -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "snapmirror update" -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 snapmirror update-ls-set 「 -access all
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」「 version 」 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume clone create 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume clone show 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 volume clone split start 「 -access all 」に設定されています
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」「 volume clone split stop 」 -access all 」に相当します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume clone split status 「 -access all 」を指定します
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "volume create " -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume destroy " -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume file clone create 「 -access all
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname 」 volume file show -disk usage 「 -access all 」に指定します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 volume modify 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname "volume offline " -access all 」を実行します
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "volume online " -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume qtree create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume qtree delete -access all を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume qtree modify 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume qtree show 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 volume restrict 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume show 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot create 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot delete 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot modify 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot promote 「 -access all 」に設定されています
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot rename 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot restore コマンド -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot restore -file 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 volume snapshot show 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 volume unmount 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs delete -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs share modify 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs share create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs share delete 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs share modify 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs share show 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver cifs show 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy delete 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy rule create 「 -access all
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy rule delete 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy rule modify 「 -access all 」を指定します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy rule show 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy show 「 -access all 」を実行します
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver iscsi connection show 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 vserver 「 -access readonly
* 「 security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname 」 vserver modify 「 -access readonly
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver show 「 -access readonly
* 「 security login role create -vserver svm_name or cluster_name -role Role_Name -cmddirname 」 vserver export-policy 「 -access all 」を実行します
* 「 security login role create -vserver SVM_name or cluster_name -role Role_Name -cmddirname "vserver iscsi " -access all

