---
permalink: install/task_register_untrusted_active_directory_domains.html 
sidebar: sidebar 
keywords: Active Directory 
summary: 信頼されていない複数のActive Directoryドメインのホスト、ユーザ、およびグループを管理するには、Active DirectoryをSnapCenterサーバに登録する必要があります。 
---
= 信頼されていないActive Directoryドメインの登録
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信頼されていない複数のActive Directoryドメインのホスト、ユーザ、およびグループを管理するには、Active DirectoryをSnapCenterサーバに登録する必要があります。

.開始する前に
* LDAP および LDAPS プロトコル *

* 信頼されていないActive Directoryドメインは、LDAPまたはLDAPSプロトコルを使用して登録できます。
* プラグインホストとSnapCenterサーバの間の双方向の通信を有効にしておく必要があります。
* DNSによる解決は、SnapCenterサーバからプラグインホストへ（またはその逆）設定する必要があります。


* LDAPプロトコル*

* 完全修飾ドメイン名（FQDN）をSnapCenterサーバから解決できる必要があります。
+
信頼されていないドメインはFQDNを使用して登録できます。FQDNをSnapCenterサーバから解決できない場合は、ドメインコントローラのIPアドレスを使用して登録できます。このアドレスはSnapCenterサーバから解決できる必要があります。



* LDAPSプロトコル*

* CA証明書は、Active Directory通信中にLDAPSでエンドツーエンドの暗号化を提供するために必要です。
+
link:task_configure_CA_client_certificate_for_LDAPS.html["LDAPS用のCAクライアント証明書の設定"]

* ドメインコントローラのホスト名（DCHostName）にSnapCenterサーバから到達できる必要があります。


* このタスクについて *

* 信頼されていないドメインは、SnapCenterユーザインターフェイス、PowerShellコマンドレット、またはREST APIを使用して登録できます。


* 手順 *

. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. 設定ページで、 * グローバル設定 * をクリックします。
. [ グローバル設定 ] ページで、 [* ドメイン設定 * ] をクリックします。
. をクリックして新しいドメインを登録します。
. [ 新しいドメインの登録 ] ページで、 *LDAP* または *LDAPS * のいずれかを選択します。
+
.. 「 * ldap * 」を選択した場合は、 LDAP の信頼されていないドメインを登録するために必要な情報を指定します。
+
|===
| フィールド | 操作 


 a| 
ドメイン名
 a| 
ドメインのNetBIOS名を指定します。



 a| 
ドメインFQDN
 a| 
FQDN を指定し、 * resolve * をクリックします。



 a| 
ドメインコントローラのIPアドレス
 a| 
ドメイン FQDN を SnapCenter サーバから解決できない場合は、ドメインコントローラの IP アドレスを 1 つ以上指定します。

詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_does_not_allow_to_add_Domain_Controller_IP_for_untrusted_domain_from_GUI["GUI から信頼できないドメインのドメインコントローラ IP を追加します"^]。

|===
.. 「 * LDAPS * 」を選択した場合は、 LDAPS の信頼されていないドメインの登録に必要な情報を指定します。
+
|===
| フィールド | 操作 


 a| 
ドメイン名
 a| 
ドメインのNetBIOS名を指定します。



 a| 
ドメインFQDN
 a| 
FQDNを指定します。



 a| 
トメインコントロオラメイ
 a| 
1 つまたは複数のドメインコントローラ名を指定し、 * Resolve.* をクリックします。



 a| 
ドメインコントローラのIPアドレス
 a| 
ドメインコントローラ名をSnapCenterサーバから解決できない場合は、DNSの解決を修正する必要があります。

|===


. [OK]*をクリックします。

