---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: ソフトウェアプラットフォームおよびそれらのプラットフォームで実行されているすべてのソフトウェアのセキュリティイベントをログに記録するようにを設定できます。 
---
= 監査ログを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログは、SnapCenter サーバのすべてのアクティビティについて生成されます。デフォルトでは、監査ログはインストールされているデフォルトの場所である_ C：\Program Files\NetApp\Virtual \SnapCenter WebApp\audit\_にあります。

監査ログは、各監査イベントに対してデジタル署名されたダイジェストを生成することで保護され、不正な変更から保護されます。生成されたダイジェストは個別の監査チェックサムファイルに保持され、の定期的な整合性チェックでコンテンツの整合性を確保します。

「 SnapCenterAdmin 」ロールでログインする必要があります。

* このタスクについて *

* アラートは次のシナリオで送信されます。
+
** 監査ログの整合性チェックのスケジュール、またはsyslogサーバが有効または無効になっています
** 監査ログの整合性チェック、監査ログ、またはsyslogサーバのログに障害が発生しました
** ディスクスペースが不足しています


* 整合性チェックが失敗した場合にのみ、電子メールが送信されます。
* 監査ログディレクトリと監査チェックサムログディレクトリの両方のパスを一緒に変更する必要があります。変更できるのはどちらか一方だけです。
* 監査ログディレクトリと監査チェックサムログディレクトリのパスが変更された場合、以前の場所にある監査ログに対して整合性チェックを実行することはできません。
* 監査ログディレクトリと監査チェックサムログディレクトリのパスは、SnapCenter サーバのローカルドライブにある必要があります。
+
共有ドライブまたはネットワークマウントドライブはサポートされません。

* syslogサーバ設定でUDPプロトコルが使用されている場合、ポートが停止しているか使用できないことによるエラーは、SnapCenter ではエラーまたはアラートとしてキャプチャできません。
* Set-SmAuditSettingsコマンドとGet-SmAuditSettingsコマンドを使用して、監査ログを構成できます。
+
コマンドレットで使用できるパラメータとその説明については、 Get-Help コマンドレットを実行して確認できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。



* 手順 *

. [*設定*]ページで、[*設定*]>[*グローバル設定*]>[*監査ログ設定*]の順に選択します。
. 監査ログセクションに詳細を入力します。
. 監査ログ・ディレクトリ*および*監査チェックサム・ログ・ディレクトリ*を入力します
+
.. 最大ファイルサイズを入力します
.. 最大ログファイル数を入力します
.. アラートを送信するためのディスクスペース使用率を入力します


. （任意）*Log UTC time *をイネーブルにします。
. （オプション）* Audit Log Integrity Check Schedule *を有効にし、* Start Integrity Check * for On Demand integrity checkをクリックします。
+
また、*Start-SmAuditIntegrityCheck*コマンドを実行して、必要に応じて整合性チェックを開始することもできます。

. （任意）転送された監査ログをリモートsyslogサーバに対してイネーブルにし、Syslogサーバの詳細を入力します。
+
syslogサーバからTLS 1.2プロトコルの「信頼されたルート」に証明書をインポートする必要があります。

+
.. 「Syslog Server Host」と入力します
.. 「Syslog Server Port」と入力します
.. 「Syslog Server Protocol」と入力します
.. RFC形式を入力します


. [ 保存（ Save ） ] をクリックします。
. 監査整合性チェックとディスク領域チェックは、* Monitor *>* Jobs *をクリックすると表示できます。

