---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM 
summary: データ保護処理とプロビジョニング処理を実行するには、 ONTAP ストレージへの SnapCenter アクセスを付与するストレージシステムをセットアップする必要があります。スタンドアロンの SVM を追加するか、複数の SVM で構成されるクラスタを追加することができます。 
---
= ストレージシステムを追加
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護処理とプロビジョニング処理を実行するためには、 ONTAP ストレージまたは NetApp ONTAP 用の Amazon FSX に SnapCenter アクセスを付与するストレージシステムをセットアップする必要があります。

スタンドアロンの SVM を追加したり、複数の SVM で構成されるクラスタを追加したりできます。NetApp ONTAP に Amazon FSX を使用している場合は、 SnapCenter 4.5 P1 の fsxadmin アカウントを使用して複数の SVM で構成される FSX 管理 LIF を追加するか、 SnapCenter に FSX SVM を追加できます。

* 必要なもの *

* ストレージ接続を作成するには、 Infrastructure Admin ロールに必要な権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ホスト・プラグインのインストールは ' ストレージ・システム接続の追加中は実行しないでくださいホスト・キャッシュが更新されず ' データベース・ステータスが SnapCenter GUI に表示される場合がありますこれは ' バックアップには使用できませんまたは NetApp ストレージには使用できません

* ストレージシステム名は一意である必要があります。
+
SnapCenter では、異なるクラスタに同じ名前のストレージシステムを複数配置することはサポートされていません。SnapCenter でサポートされるストレージシステムには、それぞれ一意の名前およびデータ LIF の IP アドレスを割り当てる必要があります。



* このタスクについて *

* ストレージシステムを設定する際に、 Event Management System （ EMS ；イベント管理システム）と AutoSupport の機能を有効にすることもできます。AutoSupport ツールは、システムの健常性に関するデータを収集し、そのデータをシステムのトラブルシューティング用にネットアップテクニカルサポートに自動的に送信します。
+
これらの機能を有効にすると、リソースが保護されたとき、リストアまたはクローニング処理が正常に完了したとき、または処理が失敗したときに、 SnapCenter からストレージシステムに AutoSupport 情報が、ストレージシステムの syslog に EMS メッセージが送信されます。

* SnapMirror デスティネーションまたは SnapVault デスティネーションに Snapshot コピーをレプリケートする場合は、デスティネーション SVM またはクラスタとソース SVM またはクラスタへのストレージシステム接続をセットアップする必要があります。



NOTE: ストレージシステムのパスワードを変更すると、スケジュールされたジョブ、オンデマンドバックアップ、およびリストア処理が失敗する場合があります。ストレージ・システムのパスワードを変更した後、 Storage （ストレージ）タブで * Modify （変更） * をクリックしてパスワードを更新できます。

* 手順 *

. 左側のナビゲーションペインで、 * ストレージシステム * をクリックします。
. [ ストレージシステム ] ページで、 [ 新規作成 ] をクリックします。
. Add Storage System （ストレージシステムの追加）ページで、次の情報を入力します。
+
|===
| フィールド | 手順 


 a| 
ストレージシステム
 a| 
ストレージシステムの名前または IP アドレスを入力します。


NOTE: ドメイン名を含まないストレージ・システム名は、 15 文字以内で、名前を解決できる必要があります。15 文字を超える名前のストレージシステム接続を作成するには、 Add-SmStorageConnectionPowerShell コマンドレットを使用します。


NOTE: MetroCluster 構成（ MCC ）を使用するストレージシステムでは、ノンストップオペレーションを実現するためにローカルクラスタとピアクラスタの両方を登録することを推奨します。

SnapCenter では、異なるクラスタにある同じ名前の SVM は複数サポートされません。SnapCenter でサポートされる SVM には、それぞれ一意の名前を付ける必要があります。


NOTE: SnapCenter へのストレージ接続の追加後は、 ONTAP を使用して SVM またはクラスタの名前を変更しないでください。


NOTE: SVM に短い名前または FQDN を追加した場合は、 SnapCenter とプラグインホストの両方から解決できる必要があります。



 a| 
ユーザ名 / パスワード
 a| 
ストレージシステムにアクセスするために必要な権限を持つストレージユーザのクレデンシャルを入力します。



 a| 
Event Management System （ EMS ；イベント管理システム）および AutoSupport の設定
 a| 
保護適用、リストア処理の完了、または処理の失敗のために AutoSupport メッセージをストレージシステムに送信する場合は、該当するチェックボックスを選択します。

AutoSupport 通知を有効にするには AutoSupport メッセージが必要であるため、 ［ * 失敗した処理に対する SnapCenter 通知をストレージ・システムに送信する * ］ チェックボックスをオンにすると、 ［ * サーバ・イベントを syslog に記録する * ］ チェックボックスもオンになります。

|===
. プラットフォーム、プロトコル、ポート、およびタイムアウトに割り当てられたデフォルト値を変更する場合は、 [ その他のオプション *] をクリックします。
+
.. プラットフォームで、ドロップダウンリストからいずれかのオプションを選択します。
+
SVM がバックアップ関係のセカンダリストレージシステムの場合は、 * Secondary * チェックボックスを選択します。[* Secondary] オプションを選択すると、 SnapCenter はすぐにライセンスチェックを実行しません。

.. プロトコルで、 SVM またはクラスタのセットアップ時に設定したプロトコル（通常は HTTPS ）を選択します。
.. ストレージシステムが受け入れるポートを入力します。
+
通常、デフォルトポート 443 は使用可能です。

.. 通信が中断されるまでの経過時間を秒単位で入力します。
+
デフォルト値は 60 秒です。

.. SVM に複数の管理インターフェイスがある場合は、「 * 優先 IP 」チェックボックスを選択し、 SVM 接続用の優先 IP アドレスを入力します。
.. [ 保存（ Save ） ] をクリックします。


. [Submit （送信） ] をクリックします。


* 結果 *

Storage Systems （ストレージシステム）ページの * Type （タイプ） * ドロップダウンから、次のいずれかの操作を実行します。

* 追加されたすべての ONTAP を表示する場合は、「 * SVM SVM * 」を選択します。
+
FSX SVM を追加した場合は、ここに FSX SVM が表示されます。

* 追加されたすべてのクラスタを表示するには、「 * ONTAP クラスタ * 」を選択します。
+
fsxadmin を使用して FSX クラスタを追加した場合、 FSX クラスタがここに表示されます。

+
クラスタ名をクリックすると、クラスタに含まれるすべての SVM が SVM セクションに表示されます。

+
ONTAP の GUI を使用して ONTAP クラスタに新しい SVM を追加した場合は、 * Rediscover* をクリックすると、新しく追加した SVM が表示されます。



* 終了後 *

クラスタ管理者は、ストレージシステムのコマンドラインから次のコマンドを実行して、各ストレージシステムノードで AutoSupport を有効にし、 SnapCenter がアクセス可能なすべてのストレージシステムから E メール通知を送信する必要があります。

AutoSupport trigger modify -node nodename autosupport.message client.app.info enable -noteto enable `


NOTE: Storage Virtual Machine （ SVM ）管理者には AutoSupport へのアクセス権はありません。
