---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: WindowsホストのSnapCenterサイトでCA証明書を設定する必要があります。 
---
= SnapCenterサイトでCA証明書を設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WindowsホストのSnapCenterサイトでCA証明書を設定する必要があります。

* 手順 *

. SnapCenter がインストールされている Windows サーバーで IIS マネージャーを開きます。
. 左側のナビゲーションペインで、 * 接続 * をクリックします。
. サーバー名と * Sites * を展開します。
. SSL証明書をインストールするSnapCenter Webサイトを選択します。
. [* アクション * （ Actions * ） ] > [* サイトの編集 * （ * Edit Site * ） ] に移動し、 [ * バインド * （ Bind
. バインディングページで、「 https * のバインディング」を選択します。
. [ 編集（ Edit ） ] をクリックします。
. [SSL証明書]ドロップダウンリストから、最近インポートしたSSL証明書を選択します。
. [OK]*をクリックします。
+

NOTE: SnapCenterスケジューラサイト（デフォルトポート：8154、HTTPS）には自己署名証明書が設定されています。このポートはSnapCenterサーバホスト内で通信しており、CA証明書を使用してを設定する必要はありません。ただし、CA証明書の使用が必要な環境の場合は、SnapCenterスケジューラサイトを使用して手順5から9を繰り返します。




NOTE: 最近導入したCA証明書がドロップダウンメニューに表示されない場合は、CA証明書が秘密鍵に関連付けられているかどうかを確認します。


IMPORTANT: 証明書が次のパスを使用して追加されていることを確認します。 * コンソールルート > 証明書–ローカルコンピュータ > 信頼されたルート証明機関 > 証明書 * 。
