---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM 
summary: データ保護処理とプロビジョニング処理を実行するには、 ONTAP ストレージへの SnapCenter アクセスを付与するストレージシステムをセットアップする必要があります。スタンドアロンの SVM を追加するか、複数の SVM で構成されるクラスタを追加することができます。 
---
= ストレージシステムを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護とプロビジョニングの処理を実行するために、SnapCenterからONTAPストレージまたはAmazon FSx for NetApp ONTAPへのアクセスを許可するストレージシステムをセットアップする必要があります。

スタンドアロンのSVMを追加することも、複数のSVMで構成されるクラスタを追加することもできます。Amazon FSx for NetApp ONTAPを使用している場合は、fsxadminアカウントを使用して複数のSVMで構成されるFSx管理LIFを追加するか、SnapCenterでFSx SVMを追加できます。

.開始する前に
* ストレージ接続を作成するには、Infrastructure Adminロールに必要な権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ホスト・プラグインのインストールは ' ストレージ・システム接続の追加中は実行しないでくださいホスト・キャッシュが更新されず ' データベース・ステータスが SnapCenter GUI に表示される場合がありますこれは ' バックアップには使用できませんまたは NetApp ストレージには使用できません

* ストレージシステム名は一意である必要があります。
+
SnapCenter では、異なるクラスタに同じ名前のストレージシステムを複数配置することはサポートされていません。SnapCenter でサポートされるストレージシステムには、それぞれ一意の名前およびデータ LIF の IP アドレスを割り当てる必要があります。



* このタスクについて *

* ストレージシステムを設定する際に、イベント管理システム（EMS）およびAutoSupportの機能を有効にすることもできます。AutoSupportツールは、システムの健常性に関するデータを収集し、システムのトラブルシューティング用にNetAppテクニカルサポートに自動的に送信します。
+
これらの機能を有効にすると、リソースが保護されたとき、リストアまたはクローニング処理が正常に終了したとき、または処理が失敗したときに、SnapCenterからストレージシステムにAutoSupport情報が、ストレージシステムのsyslogにEMSメッセージが送信されます。

* SnapMirrorデスティネーションまたはSnapVaultデスティネーションにSnapshotをレプリケートする場合は、デスティネーションSVMまたはデスティネーションクラスタとソースSVMまたはクラスタへのストレージシステム接続をセットアップする必要があります。



NOTE: ストレージシステムのパスワードを変更すると、スケジュールされたジョブ、オンデマンドバックアップ、およびリストア処理が失敗することがあります。ストレージ・システムのパスワードを変更した後、 Storage （ストレージ）タブで * Modify （変更） * をクリックしてパスワードを更新できます。

* 手順 *

. 左側のナビゲーションペインで、 * ストレージシステム * をクリックします。
. [ ストレージシステム ] ページで、 [ 新規作成 ] をクリックします。
. [Add Storage System]ページで、次の情報を入力します。
+
|===
| フィールド | 操作 


 a| 
ストレージシステム
 a| 
ストレージシステムの名前またはIPアドレスを入力します。


NOTE: ストレージシステム名は、ドメイン名を含めずに15文字以下にする必要があり、解決可能な名前である必要があります。15文字を超える名前のストレージシステム接続を作成するには、Add-SmStorageConnectionPowerShellコマンドレットを使用します。


NOTE: MetroCluster構成（MCC）のストレージシステムでノンストップオペレーションを実現するには、ローカルクラスタとピアクラスタの両方を登録することを推奨します。

SnapCenter では、異なるクラスタにある同じ名前の SVM は複数サポートされません。SnapCenter でサポートされる SVM には、それぞれ一意の名前を付ける必要があります。


NOTE: SnapCenter へのストレージ接続の追加後は、 ONTAP を使用して SVM またはクラスタの名前を変更しないでください。


NOTE: SVM に短い名前または FQDN を追加した場合は、 SnapCenter とプラグインホストの両方から解決できる必要があります。



 a| 
ユーザ名 / パスワード
 a| 
ストレージシステムへのアクセスに必要な権限を持つストレージユーザのクレデンシャルを入力します。



 a| 
イベント管理システム（EMS）とAutoSupportの設定
 a| 
保護が適用された場合、リストア処理が完了した場合、または処理が失敗した場合にEMSメッセージをストレージシステムのsyslogに送信したり、AutoSupportメッセージをストレージシステムに送信したりする場合は、該当するチェックボックスを選択します。

AutoSupport 通知を有効にするには AutoSupport メッセージが必要であるため、 ［ * 失敗した処理に対する SnapCenter 通知をストレージ・システムに送信する * ］ チェックボックスをオンにすると、 ［ * サーバ・イベントを syslog に記録する * ］ チェックボックスもオンになります。

|===
. プラットフォーム、プロトコル、ポート、およびタイムアウトに割り当てられたデフォルト値を変更する場合は、 [ その他のオプション *] をクリックします。
+
.. [プラットフォーム]で、ドロップダウンリストからいずれかのオプションを選択します。
+
SVM がバックアップ関係のセカンダリストレージシステムの場合は、 * Secondary * チェックボックスを選択します。[* Secondary] オプションを選択すると、 SnapCenter はすぐにライセンスチェックを実行しません。

+
SnapCenterでSVMを追加した場合は、ドロップダウンからプラットフォームタイプを手動で選択する必要があります。

.. [Protocol]で、SVMまたはクラスタのセットアップ時に設定したプロトコル（通常はHTTPS）を選択します。
.. ストレージシステムが受け入れるポートを入力します。
+
通常はデフォルトのポート443を使用できます。

.. 通信の試行が停止するまでの経過時間を秒単位で入力します。
+
デフォルト値は60秒です。

.. SVM に複数の管理インターフェイスがある場合は、「 * 優先 IP 」チェックボックスを選択し、 SVM 接続用の優先 IP アドレスを入力します。
.. [ 保存（ Save ） ] をクリックします。


. [Submit （送信） ] をクリックします。


* 結果 *

Storage Systems （ストレージシステム）ページの * Type （タイプ） * ドロップダウンから、次のいずれかの操作を実行します。

* 追加されたすべての ONTAP を表示する場合は、「 * SVM SVM * 」を選択します。
+
FSx SVMを追加した場合は、ここにFSx SVMが表示されます。

* 追加されたすべてのクラスタを表示するには、「 * ONTAP クラスタ * 」を選択します。
+
fsxadminを使用してFSxクラスタを追加した場合は、ここにFSxクラスタが表示されます。

+
クラスタ名をクリックすると、クラスタに含まれるすべての SVM が SVM セクションに表示されます。

+
ONTAP の GUI を使用して ONTAP クラスタに新しい SVM を追加した場合は、 * Rediscover* をクリックすると、新しく追加した SVM が表示されます。




NOTE: FASまたはAFFストレージシステムをオールSANアレイ（ASA）にアップグレードした場合は、SnapCenterサーバのストレージ接続を更新して、SnapCenterの新しいストレージタイプを反映する必要があります。

* 終了後 *

SnapCenterがアクセスできるすべてのストレージシステムからEメール通知を送信するには、クラスタ管理者が各ストレージシステムノードでAutoSupportを有効にする必要があります。そのためには、ストレージシステムのコマンドラインから次のコマンドを実行します。

`autosupport trigger modify -node nodename -autosupport-message client.app.info -to enable -noteto enable`


NOTE: Storage Virtual Machine（SVM）管理者にはAutoSupportへのアクセス権はありません。
