---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard 
summary: SnapCenterサーバインストーラの実行可能ファイルを実行して、SnapCenterサーバをインストールできます。 
---
= WindowsホストへのSnapCenterサーバのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterサーバインストーラの実行可能ファイルを実行して、SnapCenterサーバをインストールできます。

必要に応じて、PowerShellコマンドレットを使用して、いくつかのインストールと設定の手順を実行できます。PowerShell 7.4.2以降を使用している必要があります。


NOTE: コマンドラインからのSnapCenterサーバのサイレントインストールはサポートされていません。

.開始する前に
* SnapCenterサーバホストにWindowsの更新プログラムが適用されていて、システムの再起動が保留されていないことが必要です。
* SnapCenterサーバをインストールするホストにMySQLサーバがインストールされていないことを確認しておく必要があります。
* Windowsインストーラのデバッグを有効にしておく必要があります。
+
を有効にする方法については、MicrosoftのWebサイトを参照して https://support.microsoft.com/kb/223300["Windows インストーラのログ"^]ください。

+

NOTE: SnapCenter サーバは、 Microsoft Exchange サーバ、 Active Directory サーバ、またはドメインネームサーバが配置されたホストにはインストールしないでください。



* 手順 *

. からSnapCenterサーバインストールパッケージをダウンロードし https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetAppサポートサイト"^]ます。
. ダウンロードした.exeファイルをダブルクリックして、SnapCenterサーバのインストールを開始します。
+
インストールを開始すると、すべての事前確認が実行され、最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
警告メッセージは無視してインストールを続行できますが、エラーは修正する必要があります。

. SnapCenterサーバのインストールに必要な値があらかじめ入力されていることを確認し、必要に応じて変更します。
+
MySQL Serverリポジトリデータベースのパスワードを指定する必要はありません。SnapCenterサーバのインストール中に、パスワードが自動的に生成されます。

+

NOTE: パスに特殊文字「%」が含まれ%`" is not supported in the custom path for the repository database. If you include "`ていると、インストールが失敗します。

. [ 今すぐインストール ] をクリックします。
+
無効な値を指定した場合は、該当するエラーメッセージが表示されます。値を再入力してからインストールを開始してください。

+

NOTE: [Cancel] * ボタンをクリックすると、実行中のステップが完了し、ロールバック操作が開始されます。SnapCenter サーバがホストから完全に削除されます。

+
ただし、「 SnapCenter サーバサイトの再起動」または「 SnapCenter サーバの起動を待機中」の処理が実行されているときに「 * キャンセル」をクリックすると、処理はキャンセルされずにインストールが続行されます。

+
ログファイルは常に、管理者ユーザの%temp%フォルダに（古いものから順に）表示されます。ログの場所をリダイレクトする場合は、コマンドプロンプトから次のコマンドを実行してSnapCenterサーバのインストールを開始します。``C:\installer_location\installer_name.exe /log"C:\"``





== 製品を登録してサポートを有効にする

NetApp製品を初めてご利用になり、既存のNetAppアカウントをお持ちでない場合は、製品を登録してサポートを有効にする必要があります。

.手順
. SnapCenterのインストール後、*[ヘルプ]>[バージョン情報]*に移動します。
. [_About SnapCenter _]ダイアログボックスで、971で始まる20桁のSnapCenterインスタンスをメモします。
. をクリックします https://register.netapp.com[]
. [* I am not a registered NetApp Customer* ] をクリックします。
. 自分自身を登録するには、詳細を指定してください。
. NetApp Reference SNフィールドは空白のままにします。
. [Product Line]ドロップダウンから[* SnapCenter *]を選択します。
. 課金プロバイダを選択します。
. 20桁のSnapCenterインスタンスIDを入力します。
. [Submit （送信） ] をクリックします。

