---
permalink: install/task_configure_root_or_intermediate_certificates_to_trust_store.html 
sidebar: sidebar 
keywords: enable certificate-based authentication,configure CA signed key pair,configure root, configure intermediate certificates 
summary: ルート証明書または中間証明書をspl trust-storeに設定する必要があります。 
---
= spl trust-storeに対するルート証明書または中間証明書の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ルート証明書または中間証明書をspl trust-storeに設定する必要があります。ルートCA証明書のあとに中間CA証明書を追加する必要があります。

* 手順 *

. SPLキーストアが格納されているフォルダに移動します `/var/opt/snapcenter/spl/etc`。
. ファイルを探します `keystore.jks`。
. キーストアに追加された証明書を一覧表示します。
`$ keytool -list -v -keystore keystore.jks`
. ルート証明書または中間証明書を追加します。
`$ keytool -import -trustcacerts -alias <AliasNameForCerticateToBeImported> -file /<CertificatePath> -keystore` `keystore.jks`
. spl trust-storeにルート証明書または中間証明書を設定したら、サービスを再起動します。




== SPL trust-storeへのCA署名済みキーペアの設定

SPL trust-storeにCA署名付きキーペアを設定する必要があります。

* 手順 *

. SPLのキーストアが格納されているフォルダに移動し `/var/opt/snapcenter/spl/etc`ます。
. ファイルを探します `keystore.jks``。
. キーストアに追加された証明書を一覧表示します。
`$ keytool -list -v -keystore keystore.jks`
. 秘密鍵と公開鍵の両方が設定されたCA証明書を追加します。
`$ keytool -importkeystore -srckeystore <CertificatePathToImport> -srcstoretype pkcs12 -destkeystore keystore.jks` `-deststoretype JKS`
. キーストアに追加された証明書を一覧表示します。
`$ keytool -list -v -keystore keystore.jks`
. キーストアに追加された新しいCA証明書に対応するエイリアスがキーストアに含まれていることを確認します。
. CA証明書に追加した秘密鍵のパスワードをキーストアのパスワードに変更します。
+
デフォルトのSPLキーストアパスワードは、ファイル内のキーspl_keystore_passの値です `spl.properties` 。

+
`$ keytool -keypasswd -alias "<aliasNameOfAddedCertInKeystore>" -keystore keystore.jks``

. CA証明書のエイリアス名が長く、スペースまたは特殊文字（"*"、"、"、"）が含まれている場合は、エイリアス名を単純な名前に変更します。
`$ keytool -changealias -alias "<OrignalAliasName>" -destalias "<NewAliasName>" -keystore keystore.jks``
. ファイルにあるキーストアからエイリアス名を設定し `spl.properties` ます。この値をSPL_CERTIFICATE_ALIASキーに対して更新します。
. SPL trust-storeにCA署名キーペアを設定したら、サービスを再起動します。

