---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space 
summary: ファイルが削除または変更された場合、 NTFS は LUN 上の使用可能なスペースを追跡しますが、この情報はストレージシステムには報告されません。新たに解放されたブロックがストレージで空きスペースとしてマークされるようにするには、 Plug-in for Windows ホストでスペース再生用 PowerShell コマンドレットを実行します。 
---
= ストレージシステム上のスペースを再生する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルが削除または変更された場合、 NTFS は LUN 上の使用可能なスペースを追跡しますが、この情報はストレージシステムには報告されません。新たに解放されたブロックがストレージで空きスペースとしてマークされるようにするには、 Plug-in for Windows ホストでスペース再生用 PowerShell コマンドレットを実行します。

リモートのプラグインホストでコマンドレットを実行する場合は、 SnapCenterOpen-SMConnection コマンドレットを実行して SnapCenter サーバへの接続を確立する必要があります。

* 必要なもの *

* リストア処理を実行する前に、スペース再生プロセスが完了していることを確認する必要があります。
* Windows Server フェイルオーバークラスタ内のホストで LUN を共有している場合は、クラスタグループを所有するホストでスペース再生を実行する必要があります。
* ストレージのパフォーマンスを最適化するには、できるだけ頻繁にスペース再生を実行します。
+
NTFS ファイルシステム全体がスキャンされたことを確認してください。



* このタスクについて *

* スペース再生には時間がかかり、 CPU を大量に消費するため、通常はストレージシステムと Windows ホストがあまり使用されていない時間帯に実行することを推奨します。
* 使用可能なほぼすべてのスペースが再生されますが、 100% ではありません。
* スペース再生の実行中にディスクのデフラグは実行しないでください。
+
再生プロセスの速度が低下する可能性があります。



* ステップ *

アプリケーションサーバの PowerShell コマンドプロンプトで、次のコマンドを入力します。

「 Invoke-NaSdHostVolumeSpaceReclaim - Path drive_path 」です

drive_path は、 LUN にマッピングされているドライブパスです。
