---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: ソフトウェアプラットフォームおよびそれらのプラットフォームで実行されているすべてのソフトウェアのセキュリティイベントをログに記録するようにを設定できます。 
---
= 監査ログの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログは、SnapCenterサーバのすべてのアクティビティについて生成されます。デフォルトでは、監査ログはインストールされているデフォルトの場所である_ C：\Program Files\NetApp\Virtual \SnapCenter WebApp\audit\_にあります。

監査ログは、すべての監査イベントに対してデジタル署名されたダイジェストを生成して保護することで保護され、不正な変更から保護されます。生成されたダイジェストは別の監査チェックサムファイルで保持され、その下ではコンテンツの整合性を保証するために定期的な整合性チェックが行われます。

「SnapCenterAdmin」ロールでログインしておく必要があります。

* このタスクについて *

* アラートは次のシナリオで送信されます。
+
** 監査ログの整合性チェックスケジュールまたはsyslogサーバが有効または無効になっています
** 監査ログの整合性チェック、監査ログ、またはsyslogサーバログの障害
** ディスクスペースが少ない


* 整合性チェックに失敗した場合にのみEメールが送信されます。
* 監査ログディレクトリと監査チェックサムログディレクトリの両方のパスを同時に変更する必要があります。いずれか1つだけを変更することはできません。
* 監査ログディレクトリと監査チェックサムログディレクトリのパスを変更すると、以前の場所にある監査ログで整合性チェックを実行できません。
* 監査ログディレクトリと監査チェックサムログディレクトリのパスは、SnapCenterサーバのローカルドライブに配置する必要があります。
+
共有ドライブまたはネットワークマウントドライブはサポートされていません。

* syslogサーバの設定でUDPプロトコルが使用されている場合、ポートが停止しているか使用できないことによるエラーは、SnapCenterでエラーまたはアラートとしてキャプチャできません。
* Set-SmAuditSettingsコマンドとGet-SmAuditSettingsコマンドを使用して、監査ログを構成できます。
+
コマンドレットで使用できるパラメータとその説明は、Get-Help Command_nameを実行して確認できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。



* 手順 *

. [*設定*]ページで、[*設定*]>[*グローバル設定*]>[*監査ログ設定*]の順に選択します。
. [Audit log]セクションで、詳細を入力します。
. 監査ログ・ディレクトリ*および*監査チェックサム・ログ・ディレクトリ*を入力します
+
.. 最大ファイルサイズを入力します
.. ログファイルの最大数を入力
.. アラートを送信するためのディスクスペース使用量のパーセンテージを入力します


. （任意）*Log UTC time *をイネーブルにします。
. （オプション）* Audit Log Integrity Check Schedule *を有効にし、* Start Integrity Check * for On Demand integrity checkをクリックします。
+
また、*Start-SmAuditIntegrityCheck*コマンドを実行して、必要に応じて整合性チェックを開始することもできます。

. （オプション）リモートsyslogサーバへの転送監査ログを有効にし、syslogサーバの詳細を入力します。
+
TLS 1.2プロトコルの場合、syslogサーバから「信頼されたルート」に証明書をインポートする必要があります。

+
.. syslogサーバホストの入力
.. syslogサーバポートの入力
.. syslogサーバプロトコルの入力
.. RFC形式の入力


. [ 保存（ Save ） ] をクリックします。
. 監査整合性チェックとディスク領域チェックは、* Monitor *>* Jobs *をクリックすると表示できます。

