---
permalink: install/task_remove_the_trial_license.html 
sidebar: sidebar 
keywords: remove trial license 
summary: トライアルライセンス（「 50 」で終わるシリアル番号）は、 SnapCenter GUI では削除できません。コントローラベースの SnapCenter 標準ライセンスを使用していて、 SnapCenter GUI から容量ベースの試用版ライセンスを削除する必要がある場合は、 mysql コマンドを使用して試用版ライセンスを手動で削除する必要があります。 
---
= 試用版ライセンスを削除します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter GUI を使用して、試用版ライセンス（「 50 」で終わるシリアル番号）を削除することはできません。コントローラベースの SnapCenter 標準ライセンスを使用していて、 SnapCenter GUI から容量ベースの試用版ライセンスを削除する必要がある場合は、 mysql コマンドを使用して試用版ライセンスを手動で削除する必要があります。

* このタスクについて *

トライアルライセンスを手動で削除する必要があるのは、 SnapCenter の標準コントローラベースのライセンスを使用している場合のみです。SnapCenter の Standard 容量ベースのライセンスを調達し、 SnapCenter の GUI に追加すると、試用版ライセンスが自動的に上書きされます。

* 手順 *

. SnapCenter サーバで、 PowerShell ウィンドウを開き、 MySQL パスワードをリセットします。
+
.. Open-SmConnection コマンドレットを実行して、 SnapCenterAdmin アカウントの SnapCenter サーバとの接続セッションを開始します。
.. Set-SmRepositoryPassword を実行して、 MySQL パスワードをリセットします。
+
コマンドレットの詳細については、を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。



. コマンドプロンプトを開き、 mysql -u root -p を実行して MySQL にログインします。
+
パスワードの入力を求めるプロンプトが MySQL から表示されます。パスワードのリセット時に指定したクレデンシャルを入力します。

. データベースから試用版ライセンスを削除します。
+
「 nsm を使用」「 nsm ライセンスから削除」。ここで、 NSM_License_Serial_number='510000050';'


