---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space 
summary: ファイルが削除または変更されると、NTFSはLUN上の使用可能なスペースを追跡しますが、新しい情報はストレージシステムには報告しません。新しく解放されたブロックがストレージで使用可能とマークされるようにするには、Plug-in for Windowsホストでスペース再生PowerShellコマンドレットを実行します。 
---
= ストレージシステム上のスペースの再生
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルが削除または変更されると、NTFSはLUN上の使用可能なスペースを追跡しますが、新しい情報はストレージシステムには報告しません。新しく解放されたブロックがストレージで使用可能とマークされるようにするには、Plug-in for Windowsホストでスペース再生PowerShellコマンドレットを実行します。

コマンドレットをリモートのプラグインホストで実行する場合は、SnapCenterOpen-SMConnectionコマンドレットを実行してSnapCenterサーバへの接続を確立しておく必要があります。

.開始する前に
* リストア処理を実行する前に、スペース再生プロセスが完了していることを確認する必要があります。
* Windows Serverフェイルオーバークラスタ内のホストでLUNを共有している場合は、クラスタグループを所有するホストでスペース再生を実行する必要があります。
* ストレージのパフォーマンスを最適化するには、できるだけ頻繁にスペース再生を実行します。
+
NTFSファイルシステム全体がスキャンされていることを確認する必要があります。



* このタスクについて *

* スペース再生には時間がかかり、CPUを大量に消費するため、通常はストレージシステムとWindowsホストの使用率が低いときに処理を実行することを推奨します。
* スペース再生では、使用可能なほぼすべてのスペースが再生されますが、100%ではありません。
* スペース再生の実行中にディスクのデフラグは実行しないでください。
+
再利用プロセスに時間がかかることがあります。



* ステップ *

アプリケーションサーバのPowerShellコマンドプロンプトで、次のコマンドを入力します。

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_pathは、LUNにマッピングされたドライブパスです。
