---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks 
summary: Windows ホストは、ストレージシステム上の LUN を仮想ディスクとして認識します。SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を作成および設定できます。 
---
= ディスクを作成および管理する
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows ホストは、ストレージシステム上の LUN を仮想ディスクとして認識します。SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を作成および設定できます。


NOTE: SnapCenter では、ディスク名の変更はサポートされていません。SnapCenter で管理しているディスクの名前を変更すると、 SnapCenter 処理は正常に終了しません。



== ホスト上のディスクを表示します

SnapCenter で管理している各 Windows ホスト上のディスクを表示できます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。





== クラスタディスクを表示します

SnapCenter で管理しているクラスタ上のクラスタディスクを表示できます。クラスタ化されたディスクは、 Hosts （ホスト）ドロップダウンからクラスタを選択した場合にのみ表示されます。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからクラスタを選択します
+
ディスクのリストが表示されます。





== FC 接続または iSCSI 接続の LUN またはディスクを作成します

Windows ホストは、ストレージシステム上の LUN を仮想ディスクとして認識します。SnapCenter を使用して、 FC 接続 LUN または iSCSI 接続 LUN を作成および設定できます。

* 必要なもの *

* ストレージシステム上に LUN 用のボリュームを作成しておく必要があります。
+
このボリュームには、 SnapCenter で作成した LUN のみを格納します。

+

NOTE: SnapCenter で作成したクローンボリュームには、クローンがすでにスプリットされている場合を除き、 LUN を作成することはできません。

* ストレージシステムで FC サービスまたは iSCSI サービスを開始しておく必要があります。
* iSCSI を使用している場合は、ストレージシステムとの iSCSI セッションを確立しておく必要があります。
* SnapCenter Plug-ins Package for Windows は、ディスクを作成するホストにのみインストールする必要があります。


* このタスクについて *

* Windows Server フェイルオーバークラスタ内のホストで共有する場合を除き、 LUN を複数のホストに接続することはできません。
* Cluster Shared Volume （ CSV ；クラスタ共有ボリューム）を使用する Windows Server フェイルオーバークラスタ内のホストで LUN を共有する場合、クラスタグループを所有するホストにディスクを作成する必要があります。


* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
. [ 新規作成（ New ） ] をクリックする。
+
Create Disk （ディスクの作成）ウィザードが開きます。

. LUN Name ページで、 LUN を特定します。
+
|===
| フィールド | 手順 


 a| 
ストレージシステム
 a| 
LUN の SVM を選択します。



 a| 
LUN パス
 a| 
「 * Browse * 」をクリックして、 LUN を含むフォルダのフルパスを選択します。



 a| 
LUN 名
 a| 
LUN の名前を入力します。



 a| 
クラスタサイズ
 a| 
クラスタの LUN のブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティングシステムとアプリケーションによって異なります。



 a| 
LUN ラベル
 a| 
必要に応じて、 LUN の説明を入力します。

|===
. ディスクタイプページで、ディスクタイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
専用ディスク
 a| 
LUN にアクセスできるホストは 1 つだけです。

[* リソースグループ * ] フィールドは無視してください。



 a| 
共有ディスク
 a| 
Windows Server フェイルオーバークラスタ内のホストで LUN を共有します。

[ * リソースグループ * ] フィールドにクラスタリソースグループの名前を入力します。ディスクはフェイルオーバークラスタ内の 1 つのホストだけに作成する必要があります。



 a| 
Cluster Shared Volume （ CSV ；クラスタ共有ボリューム）
 a| 
CSV を使用する Windows Server フェイルオーバークラスタ内のホストで LUN を共有します。

[ * リソースグループ * ] フィールドにクラスタリソースグループの名前を入力します。ディスクを作成するホストがクラスタグループの所有者であることを確認します。

|===
. ドライブのプロパティページで、ドライブのプロパティを指定します。
+
|===
| プロパティ（ Property ） | 説明 


 a| 
マウントポイントの自動割り当て
 a| 
SnapCenter では、システムドライブに基づいてボリュームマウントポイントが自動的に割り当てられます。

たとえば、システムドライブが C: の場合、自動割り当てでは C: ドライブ (C:\scmnpt) の下にボリュームマウントポイントが作成されます。自動割り当ては共有ディスクではサポートされません。



 a| 
ドライブ文字を割り当てます
 a| 
隣接するドロップダウンリストで選択したドライブにディスクをマウントします。



 a| 
ボリュームマウントポイントを使用する
 a| 
隣接するフィールドで指定したドライブパスにディスクをマウントします。

ボリュームマウントポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
ドライブレターまたはボリュームマウントポイントを割り当てないでください
 a| 
ディスクを Windows で手動でマウントする場合は、このオプションを選択します。



 a| 
LUN サイズ
 a| 
LUN のサイズを 150MB 以上指定します。

ドロップダウンリストから MB 、 GB 、または TB を選択します。



 a| 
この LUN をホストしているボリュームにシンプロビジョニングを使用します
 a| 
LUN をシンプロビジョニングします。

シンプロビジョニングでは、ストレージスペースが必要なときに必要な分だけ割り当てられるため、 LUN は使用可能な最大容量まで効率的に拡張されます。

必要になるすべての LUN ストレージに対応できるだけの十分なスペースがボリュームにあることを確認してください。



 a| 
パーティションタイプを選択します
 a| 
GUID パーティションテーブルの場合は GPT パーティション、マスターブートレコードの場合は MBR パーティションを選択します。

MBR パーティションを Windows Server フェイルオーバークラスタで使用した場合、原因のミスアライメントが発生することがあります。


NOTE: UEFI （ Unified Extensible Firmware Interface ）パーティションディスクはサポートされていません。

|===
. LUN のマッピングページで、ホストの iSCSI イニシエータまたは FC イニシエータを選択します。
+
|===
| フィールド | 手順 


 a| 
ホスト
 a| 
クラスタグループ名をダブルクリックし、ドロップダウンリストに表示されたクラスタに属するホストの中から、イニシエータに指定するホストを選択します。

このフィールドは、 Windows Server フェイルオーバークラスタ内のホストで LUN を共有する場合にのみ表示されます。



 a| 
ホストイニシエータを選択します
 a| 
Fibre Channel * または * iSCSI * を選択し、ホスト上のイニシエータを選択します。

FC で Multipath I/O （ MPIO ；マルチパス I/O ）を使用する場合は、 FC イニシエータを複数選択できます。

|===
. Group Type ページで、既存の igroup を LUN にマッピングするか、新しい igroup を作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータ用に新しい igroup を作成します
 a| 
選択したイニシエータ用に新しい igroup を作成します。



 a| 
既存の igroup を選択するか、選択したイニシエータ用に新しい igroup を指定します
 a| 
選択したイニシエータ用に既存の igroup を指定するか、指定した名前で新しい igroup を作成します。

igroup name * フィールドに igroup 名を入力します。既存の igroup 名の最初の数文字を入力すると、残りの文字が自動的に入力されます。

|===
. [ 概要 ] ページで選択内容を確認し、 [ 完了 ] をクリックします。
+
SnapCenter によって LUN が作成され、ホスト上の指定したドライブまたはドライブパスに接続されます。





== ディスクのサイズ変更

ストレージシステムのニーズの変化に応じて、ディスクのサイズを拡張または縮小できます。

* このタスクについて *

* シンプロビジョニングされた LUN の場合、 ONTAP の LUN ジオメトリサイズは最大サイズとして表示されます。
* シックプロビジョニング LUN の場合、拡張可能なサイズ（ボリューム内の使用可能なサイズ）が最大サイズとして表示されます。
* MBR パーティション方式を使用した LUN の場合、最大サイズは 2TB です。
* GPT パーティション方式を使用した LUN の場合、ストレージシステムの最大サイズは 16TB です。
* LUN のサイズを変更する前に Snapshot コピーを作成しておくことを推奨します。
* LUN のサイズの変更前に作成された Snapshot コピーから LUN をリストアすると、 SnapCenter によって LUN のサイズが Snapshot コピーのサイズに自動的に変更されます。
+
リストア処理のあと、サイズ変更後に LUN に追加されたデータを、サイズ変更後に作成された Snapshot コピーからリストアする必要があります。



* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. ホストドロップダウンリストからホストを選択します。
+
ディスクのリストが表示されます。

. サイズを変更するディスクを選択し、 * サイズ変更 * をクリックします。
. ディスクのサイズ変更ダイアログボックスで、スライダツールを使用してディスクの新しいサイズを指定するか、サイズフィールドに新しいサイズを入力します。
+

NOTE: サイズを手動で入力する場合は、 [ 縮小 ] または [ 展開 ] ボタンを適切に有効にする前に、 [ サイズ ] フィールドの外側をクリックする必要があります。また、単位を指定するには、 MB 、 GB 、または TB をクリックする必要があります。

. 入力内容に問題がなければ、必要に応じて、 [ * 縮小（ * Shrink ） ] または [ * 展開（ * Expand ） ] をクリックします。
+
SnapCenter はディスクのサイズを変更します。





== ディスクを接続します

ディスク接続ウィザードを使用して、既存の LUN をホストに接続したり、切断された LUN を再接続したりできます。

* 必要なもの *

* ストレージシステムで FC サービスまたは iSCSI サービスを開始しておく必要があります。
* iSCSI を使用している場合は、ストレージシステムとの iSCSI セッションを確立しておく必要があります。
* Windows Server フェイルオーバークラスタ内のホストで共有する場合を除き、 LUN を複数のホストに接続することはできません。
* Cluster Shared Volume （ CSV ；クラスタ共有ボリューム）を使用する Windows Server フェイルオーバークラスタ内のホストで LUN を共有する場合、クラスタグループを所有するホストにディスクを接続する必要があります。
* Plug-in for Windows をインストールする必要があるのは、ディスクを接続するホストだけです。


* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
. [ 接続 ] をクリックします。
+
ディスクの接続ウィザードが開きます。

. LUN Name ページで、接続先の LUN を特定します。
+
|===
| フィールド | 手順 


 a| 
ストレージシステム
 a| 
LUN の SVM を選択します。



 a| 
LUN パス
 a| 
[* Browse] をクリックして、 LUN を含むボリュームの完全パスを選択します。



 a| 
LUN 名
 a| 
LUN の名前を入力します。



 a| 
クラスタサイズ
 a| 
クラスタの LUN のブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティングシステムとアプリケーションによって異なります。



 a| 
LUN ラベル
 a| 
必要に応じて、 LUN の説明を入力します。

|===
. ディスクタイプページで、ディスクタイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
専用ディスク
 a| 
LUN にアクセスできるホストは 1 つだけです。



 a| 
共有ディスク
 a| 
Windows Server フェイルオーバークラスタ内のホストで LUN を共有します。

ディスクはフェイルオーバークラスタ内の 1 つのホストだけに接続します。



 a| 
Cluster Shared Volume （ CSV ；クラスタ共有ボリューム）
 a| 
CSV を使用する Windows Server フェイルオーバークラスタ内のホストで LUN を共有します。

ディスクを接続するホストがクラスタグループの所有者であることを確認します。

|===
. ドライブのプロパティページで、ドライブのプロパティを指定します。
+
|===
| プロパティ（ Property ） | 説明 


 a| 
自動割り当て
 a| 
システムドライブに基づいて、 SnapCenter で自動的にボリュームマウントポイントを割り当てます。

たとえば、システムドライブが C: の場合、自動割り当てプロパティは C: ドライブ (C:\scmnpt) の下にボリュームマウントポイントを作成します。自動割り当てプロパティは共有ディスクではサポートされません。



 a| 
ドライブ文字を割り当てます
 a| 
ドロップダウンリストで選択したドライブにディスクをマウントします。



 a| 
ボリュームマウントポイントを使用する
 a| 
フィールドで指定したドライブパスにディスクをマウントします。

ボリュームマウントポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
ドライブレターまたはボリュームマウントポイントを割り当てないでください
 a| 
ディスクを Windows で手動でマウントする場合は、このオプションを選択します。

|===
. LUN のマッピングページで、ホストの iSCSI イニシエータまたは FC イニシエータを選択します。
+
|===
| フィールド | 手順 


 a| 
ホスト
 a| 
クラスタグループ名をダブルクリックし、ドロップダウンリストに表示されたクラスタに属するホストの中から、イニシエータに指定するホストを選択します。

このフィールドは、 Windows Server フェイルオーバークラスタ内のホストで LUN を共有する場合にのみ表示されます。



 a| 
ホストイニシエータを選択します
 a| 
Fibre Channel * または * iSCSI * を選択し、ホスト上のイニシエータを選択します。

FC で MPIO を使用している場合は、 FC イニシエータを複数選択できます。

|===
. [Group Type] ページで、既存の igroup を LUN にマッピングするか、新しい igroup を作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータ用に新しい igroup を作成します
 a| 
選択したイニシエータ用に新しい igroup を作成します。



 a| 
既存の igroup を選択するか、選択したイニシエータ用に新しい igroup を指定します
 a| 
選択したイニシエータ用に既存の igroup を指定するか、指定した名前で新しい igroup を作成します。

igroup name * フィールドに igroup 名を入力します。既存の igroup 名の最初の数文字を入力すると、残りの文字が自動的に入力されます。

|===
. [ 概要 ] ページで選択内容を確認し、 [ 完了 ] をクリックします。
+
SnapCenter は、ホスト上の指定したドライブまたはドライブパスに LUN を接続します。





== ディスクの切断

LUN は内容を残したままホストから切断できます。ただし、スプリットせずにクローンを切断した場合、クローンの内容は失われます。

* 必要なもの *

* LUN を使用しているアプリケーションがないことを確認します。
* LUN が監視ソフトウェアで監視されていないことを確認します。
* LUN が共有されている場合は、 LUN からクラスタリソースの依存関係を解除し、クラスタ内のすべてのノードの電源がオンで正常に機能しており、 SnapCenter からアクセスできることを確認します。


* このタスクについて *

SnapCenter が作成した FlexClone ボリュームの LUN を切断した場合、そのボリュームに他の LUN が接続されていなければ、 SnapCenter はボリュームを削除します。この場合、 LUN が切断される前に、 FlexClone ボリュームが削除される可能性があることを警告するメッセージが SnapCenter に表示されます。

FlexClone ボリュームが自動で削除されないようにするには、最後の LUN を切断する前にボリュームの名前を変更します。ボリュームの名前を変更するときは、最後の 1 文字だけでなく複数の文字を変更してください。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。

. 切断するディスクを選択し、 * 切断 * をクリックします。
. [ ディスクの切断 ] ダイアログボックスで、 [OK] をクリックします。
+
SnapCenter によってディスクが切断されます。





== ディスクを削除します

不要になったディスクは削除できます。削除したディスクは復元できません。

* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. Hosts （ホスト）ページで、 * Disks （ディスク） * をクリックします。
. [*Host*] ドロップダウン・リストからホストを選択します
+
ディスクのリストが表示されます。

. 削除するディスクを選択し、 * 削除 * をクリックします。
. [ ディスクの削除 ] ダイアログボックスで、 [OK] をクリックします。
+
SnapCenter によってディスクが削除されます。


