---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。 
---
= ホストを追加してPlug-ins Package for Linuxをインストールするための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してLinux用のプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。

* iSCSIを使用している場合は、iSCSIサービスが実行されている必要があります。
* rootユーザまたはroot以外のユーザ、またはSSHキーベースの認証にはパスワードベースの認証を使用できます。
+
SnapCenter Plug-in for Unix File Systemsは、root以外のユーザがインストールできます。ただし、プラグインプロセスをインストールして開始するには、root以外のユーザにsudo権限を設定する必要があります。プラグインのインストール後、プロセスはroot以外の有効なユーザとして実行されます。

* インストールユーザのクレデンシャルを、認証モードをLinuxに設定して作成します。
* Java 11をLinuxホストにインストールしておく必要があります。
+

NOTE: LinuxホストにJava 11の認定エディションのみがインストールされていることを確認します。

+
Javaのダウンロードについては、次を参照してください。 http://www.java.com/en/download/manual.jsp["すべてのオペレーティングシステム用のJavaダウンロード"^]

* プラグインのインストールには、デフォルトのシェルとして* bash *が必要です。




== Linuxホストの要件

SnapCenter Plug-ins Package for Linuxをインストールする前に、ホストが要件を満たしていることを確認する必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server（SLES）




 a| 
ホスト上のSnapCenterプラグイン用の最小RAM
 a| 
2GB



 a| 
ホスト上のSnapCenterプラグインのインストールとログの最小スペース
 a| 
2GB


NOTE: 十分なディスクスペースを割り当て、logsフォルダによるストレージ消費量を監視する必要があります。必要なログスペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理のログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
Java 11 Oracle JavaおよびOpenJDK


NOTE: LinuxホストにJava 11の認定エディションのみがインストールされていることを確認します。

を最新バージョンにアップグレードした場合は、/var/opt/java/spl/etc/ spl.propertiesにあるJAVA_HOMEオプションが正しいSnapCenterバージョンと正しいパスに設定されていることを確認する必要があります。

|===
サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"] 。
