---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: バックアップするUNIXファイルシステムのバックアップポリシーを作成します。 
---
= UNIXファイルシステムのバックアップポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してUNIXファイルシステムをバックアップする前に、バックアップ対象のリソースまたはリソースグループのバックアップポリシーを作成する必要があります。バックアップポリシーとは、バックアップを管理、スケジューリング、および保持する方法を定めた一連のルールです。レプリケーション、スクリプト、バックアップタイプの設定を指定することもできます。ポリシーを作成することで、別のリソースやリソースグループでポリシーを再利用して時間を節約することができます。

.作業を開始する前に
* SnapCenterのインストール、ホストの追加、ファイルシステムの検出、ストレージシステム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* Snapshotをミラーセカンダリストレージまたはバックアップセカンダリストレージにレプリケートする場合は、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にSVMを割り当てておく必要があります。


.手順
. 左側のナビゲーションペインで、 * 設定 * をクリックします。
. [ 設定 ] ページで、 [ * ポリシー * ] をクリックします。
. ドロップダウンリストから* Unix File Systems *を選択します。
. [ 新規作成（ New ） ] をクリックする。
. [ 名前 ] ページで、ポリシー名と概要を入力します。
. オンデマンド * 、 * 毎時 * 、 * 毎日 * 、 * 毎週 * 、または * 毎月 * を選択して、スケジュールの頻度を指定します。
. [ 保持 ] ページで ' バックアップ・タイプの保持設定と [ バックアップ・タイプ ] ページで選択したスケジュール・タイプを指定します
+
|===


| 状況 | 作業 


 a| 
一定数のSnapshotを保持
 a| 
[保持するSnapshotコピーの総数]*を選択し、保持するSnapshotの数を指定します。

Snapshotの数が指定した数を超えると、最も古いコピーから順にSnapshotが削除されます。


NOTE: 最大保持数は、 ONTAP 9.4 以降のリソースでは 1018 、 ONTAP 9.3 以前のリソースでは 254 です。保持期間を基盤となる ONTAP バージョンの値よりも大きい値に設定すると、バックアップが失敗します。


IMPORTANT: SnapVault レプリケーションを有効にする場合は、保持数を 2 以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗する可能性があります。



 a| 
Snapshotを特定の日数だけ保持
 a| 
[Keep Snapshot copies for]*を選択し、Snapshotを削除するまでの日数を指定します。

|===
+

NOTE: アーカイブログバックアップを保持できるのは、アーカイブログファイルをバックアップの一部として選択した場合だけです。

. Replication （レプリケーション）ページで、レプリケーション設定を指定します。
+
|===
| フィールド | 手順 


 a| 
ローカル Snapshot コピーの作成後に SnapMirror を更新します
 a| 
別のボリュームにバックアップセットのミラーコピーを作成する場合（ SnapMirror レプリケーション）は、このフィールドを選択します。



 a| 
ローカル Snapshot コピーの作成後に SnapVault を更新します
 a| 
ディスクツーディスクのバックアップレプリケーション（ SnapVault バックアップ）を実行する場合は、このオプションを選択します。



 a| 
セカンダリポリシーのラベル
 a| 
Snapshot ラベルを選択します。

選択したSnapshotラベルに応じて、ラベルに一致するセカンダリSnapshot保持ポリシーがONTAPによって適用されます。


NOTE: ローカル Snapshot コピーの作成後に「 * SnapMirror を更新」を選択した場合は、必要に応じてセカンダリポリシーラベルを指定できます。ただし、ローカル Snapshot コピーの作成後に「 * Update SnapVault 」を選択した場合は、セカンダリポリシーラベルを指定する必要があります。



 a| 
エラー再試行回数
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリストレージのSnapshotの最大数に達しないように、ONTAPでセカンダリストレージのSnapMirror保持ポリシーを設定する必要があります。

. スクリプトページで、バックアップ処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+

NOTE: プラグインホストで使用可能なコマンドリストにコマンドが存在するかどうかを、_/opt/NetApp/snapcenter/scc/etc/allowed _ commands.config_pathから確認する必要があります。

+
スクリプトのタイムアウト値を指定することもできます。デフォルト値は 60 秒です。

. 概要を確認し、 [ 完了 ] をクリックします。

