---
permalink: protect-scu/task_configure_snapcenter_plug_in_loader_service.html 
sidebar: sidebar 
keywords: SPL, plug-in loader service 
summary: SnapCenter Plug-in Loaderサービスは、SnapCenterサーバと対話するために、Linux用のプラグインパッケージをロードします。SnapCenter Plug-in Loaderサービスは、SnapCenter Plug-ins Package for Linuxをインストールするとインストールされます。 
---
= SnapCenter Plug-in Loaderサービスの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in Loaderサービスは、SnapCenterサーバと対話するために、Linux用のプラグインパッケージをロードします。SnapCenter Plug-in Loaderサービスは、SnapCenter Plug-ins Package for Linuxをインストールするとインストールされます。

* このタスクについて *

SnapCenter Plug-ins Package for Linuxをインストールすると、SnapCenter Plug-in Loaderサービスが自動的に開始されます。SnapCenter Plug-in Loader サービスが自動的に開始されない場合は、次のことを行う必要があります。

* プラグインが動作しているディレクトリが削除されていないことを確認してください
* Java仮想マシンに割り当てられているメモリ容量を増やす


spl.properties ファイルは、 _/custom_location/NetApp/snapcenter /spl/etc/_ にあり、次のパラメータを含みます。これらのパラメータにはデフォルト値が割り当てられています。

|===
| パラメータ名 | 説明 


 a| 
LOG_LEVEL
 a| 
サポートされているログレベルを表示します。

指定できる値は、trace、debug、info、warn、error、 致命的だ



 a| 
spl_protocol
 a| 
SnapCenter Plug-in Loader でサポートされているプロトコルを表示します。

HTTPSプロトコルのみがサポートされます。デフォルト値がない場合は、値を追加できます。



 a| 
SNAPCENTER_SERVER_PROTOCOL
 a| 
SnapCenter サーバでサポートされているプロトコルを表示します。

HTTPSプロトコルのみがサポートされます。デフォルト値がない場合は、値を追加できます。



 a| 
SKIP_JAVAHOME_UPDATE
 a| 
SPLサービスはデフォルトでJavaパスを検出し、JAVA_HOMEパラメータを更新します。

したがって、デフォルト値は FALSE に設定されます。デフォルトの動作を無効にして Java パスを手動で修正する場合は、 true に設定します。



 a| 
spl_keystore_pass
 a| 
キーストアファイルのパスワードを表示します。

この値は、パスワードを変更するか、新しいキーストアファイルを作成する場合にのみ変更できます。



 a| 
spl_port
 a| 
SnapCenter Plug-in Loader サービスが実行されているポート番号を表示します。

デフォルト値がない場合は、値を追加できます。


NOTE: プラグインのインストール後に値を変更しないでください。



 a| 
SnapCenterサーバホスト
 a| 
SnapCenter サーバの IP アドレスまたはホスト名を表示します。



 a| 
spl_keystore_path
 a| 
キーストアファイルの絶対パスを表示します。



 a| 
SNAPCENTER_SERVER_PORT
 a| 
SnapCenter サーバが稼働しているポート番号を表示します。



 a| 
logs_max_count
 a| 
SnapCenter Plug-in Loader ログファイルのうち、 _/custom_location/snapcenter /spl/logs_folder に保持されているファイルの数を表示します。

デフォルト値は5000に設定されています。この数が指定した値を超える場合は、最後に変更された5、000個のファイルが保持されます。ファイル数のチェックは、 SnapCenter Plug-in Loader サービスが開始されたときから 24 時間ごとに自動的に行われます。


NOTE: spl.propertiesファイルを手動で削除した場合、保持するファイル数は9999に設定されます。



 a| 
JAVA_HOME
 a| 
SPLサービスの開始に使用されるJAVA_HOMEディレクトリの絶対パスを表示します。

このパスは、インストール時およびSPLの開始時に決定されます。



 a| 
LOG_MAX_SIZE
 a| 
ジョブログファイルの最大サイズを表示します。

最大サイズに達すると、ログファイルが圧縮され、そのジョブの新しいファイルにログが書き込まれます。



 a| 
最後の日数のログの保持
 a| 
ログが保持されるまでの日数が表示されます。



 a| 
enable_certificate_validation
 a| 
ホストでCA証明書の検証が有効になっている場合はtrueと表示されます。

このパラメータを有効または無効にするには、spl.propertiesを編集するか、SnapCenterのGUIまたはコマンドレットを使用します。

|===
これらのパラメータのいずれかがデフォルト値に割り当てられていない場合、または値を割り当てたり変更したりする場合は、spl.propertiesファイルを変更できます。また、spl.propertiesファイルを確認し、ファイルを編集して、パラメータに割り当てられた値に関連する問題のトラブルシューティングを行うこともできます。spl.propertiesファイルを変更したら、SnapCenter Plug-in Loaderサービスを再起動する必要があります。

* 手順 *

. 必要に応じて、次のいずれかの操作を実行します。
+
** SnapCenter Plug-in Loaderサービスを開始します。
+
*** rootユーザとして、次のコマンドを実行します。 `/custom_location/NetApp/snapcenter/spl/bin/spl start`
*** root以外のユーザとして、次のコマンドを実行します。 `sudo /custom_location/NetApp/snapcenter/spl/bin/spl start`


** SnapCenter Plug-in Loader サービスを停止します。
+
*** rootユーザとして、次のコマンドを実行します。 `/custom_location/NetApp/snapcenter/spl/bin/spl stop`
*** root以外のユーザとして、次のコマンドを実行します。 `sudo /custom_location/NetApp/snapcenter/spl/bin/spl stop`
+

NOTE: stopコマンドで-forceオプションを使用すると、SnapCenter Plug-in Loaderサービスを強制的に停止できます。ただし、既存の処理も終了するため、この処理を実行する場合は注意が必要です。



** SnapCenter Plug-in Loader サービスを再起動します。
+
*** rootユーザとして、次のコマンドを実行します。 `/custom_location/NetApp/snapcenter/spl/bin/spl restart`
*** root以外のユーザとして、次のコマンドを実行します。 `sudo /custom_location/NetApp/snapcenter/spl/bin/spl restart`


** SnapCenter Plug-in Loader サービスのステータスを確認します。
+
*** rootユーザとして、次のコマンドを実行します。 `/custom_location/NetApp/snapcenter/spl/bin/spl status`
*** root以外のユーザとして、次のコマンドを実行します。 `sudo /custom_location/NetApp/snapcenter/spl/bin/spl status`


** SnapCenter Plug-in Loader サービスで変更を探します。
+
*** rootユーザとして、次のコマンドを実行します。 `/custom_location/NetApp/snapcenter/spl/bin/spl change`
*** root以外のユーザとして、次のコマンドを実行します。 `sudo /custom_location/NetApp/snapcenter/spl/bin/spl change`





