---
permalink: protect-db2/add-hosts-and-install-plug-in-packages-on-remote-hosts-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: ホストの追加ページを使用 SnapCenter してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインは、自動的にリモートホストにインストールされます。ホストの追加とプラグインパッケージのインストールは、個々のホストまたはクラスタに対して実行できます。 
---
= ホストを追加し、プラグインパッケージをリモートホストにインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの追加ページを使用 SnapCenter してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインは、自動的にリモートホストにインストールされます。ホストの追加とプラグインパッケージのインストールは、個々のホストまたはクラスタに対して実行できます。

.作業を開始する前に
* SnapCenter ServerホストのオペレーティングシステムがWindows 2019で、プラグインホストのオペレーティングシステムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* メッセージキューサービスが実行されていることを確認してください。
* 管理マニュアルには、ホストの管理に関する情報が記載されています。
* Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用している場合は、管理者権限を持つ gMSA を設定する必要があります。
+
link:../protect-db2/task_configure_gMSA_on_windows_server_2012_or_later.html["IBM DB2用のWindows Server 2016以降でのグループ管理サービスアカウントの設定"^]



.このタスクについて
* SnapCenter サーバをプラグインホストとして別の SnapCenter サーバに追加することはできません。


.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] タブが選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
ホストタイプ
 a| 
ホストのタイプを選択します。

** Windows の場合
** Linux の場合
+

NOTE: Plug-in for IBM DB2はIBM DB2クライアントホストにインストールされます。このホストはWindowsシステムでもLinuxシステムでもかまいません。





 a| 
ホスト名
 a| 
通信ホスト名を入力します。ホストの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。SnapCenter は、 DNS の適切な設定によって異なります。そのため、 FQDN を入力することを推奨します。



 a| 
クレデンシャル
 a| 
作成したクレデンシャル名を選択するか、新しいクレデンシャルを作成します。このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

クレデンシャルの詳細を表示するには、指定したクレデンシャル名にカーソルを合わせます。


NOTE: クレデンシャル認証モードは、ホストの追加ウィザードで指定したホストタイプによって決まります。

|===
. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
+
REST APIを使用してPlug-in for DB2をインストールする場合は、バージョンを3.0として渡す必要があります。例：DB2：3.0

. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 手順 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。デフォルトのポート番号は 8145 です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
Plug-in for IBM DB2はIBM DB2クライアントホストにインストールされます。このホストはWindowsシステムでもLinuxシステムでもかまいません。

** Windows 用 SnapCenter Plug-ins パッケージのデフォルトパスは C ： \Program Files\NetApp\SnapManager です。必要に応じて、パスをカスタマイズできます。
** Linux 用 SnapCenter Plug-ins パッケージのデフォルトパスは /opt/NetApp/SnapCenter です。必要に応じて、パスをカスタマイズできます。




 a| 
インストール前のチェックをスキップします
 a| 
プラグインを手動でインストール済みで、プラグインのインストール要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
プラグインサービスを実行するには、 Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用します
 a| 
Windows ホストの場合、プラグインサービスの実行にグループ管理サービスアカウント（ gMSA ）を使用する場合は、このチェックボックスをオンにします。


NOTE: gMSA 名を domainName\accountName$ の形式で指定します。


NOTE: gMSA は、 SnapCenter Plug-in for Windows サービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [Submit （送信） ] をクリックします。
+
[インストール前チェックをスキップ]チェックボックスを選択していない場合は、プラグインをインストールするための要件をホストが満たしているかどうかを検証するためにホストが検証されます。 ディスクスペース、RAM、PowerShellのバージョン、 NETバージョン、場所（Windowsプラグインの場合）、およびJava 11（WindowsプラグインとLinuxプラグインの場合）が最小要件に照らして検証されます。最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたは RAM に関連している場合は、 C ： \Program Files\NetApp\SnapManager WebApp にある web.config ファイルを更新してデフォルト値を変更することができます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HA セットアップで web.config ファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. ホストタイプが Linux の場合は、フィンガープリントを確認し、 * Confirm and Submit * をクリックします。
+
クラスタセットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

+

NOTE: 同じホストを以前に SnapCenter に追加し、フィンガープリントを確認した場合でも、フィンガープリントの検証は必須です。

. インストールの進行状況を監視します。
+
** Windowsプラグインの場合、インストールログとアップグレードログは_C：\Windows\SnapCenter <JOBID>\にあります。
** Linuxプラグインの場合、インストールログは_/var/opt/snapcenter/logs/SnapCenter _Linux_Host_Plug-in_Install_Install_Linux.log <JOBID>にあり、アップグレードログは_/var/opt/snapcenter/logs/SnapCenter <JOBID>.logにあります。




.完了後
SnapCenter 6.0バージョンにアップグレードする場合は、既存のPerlベースのPlug-in for DB2がリモートプラグインサーバからアンインストールされます。
