---
permalink: protect-db2/snapcenter-plug-in-for-ibm-db2-features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: SnapCenterは、プラグインアプリケーションおよびストレージシステム上でNetAppテクノロジと統合されます。Plug-in for IBM DB2 Databaseを操作するには、SnapCenterグラフィカルユーザーインターフェイスを使用します。 
---
= SnapCenter Plug-in for IBM DB2の機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、プラグインアプリケーションおよびストレージシステム上でNetAppテクノロジと統合されます。Plug-in for IBM DB2 Databaseを操作するには、SnapCenterグラフィカルユーザーインターフェイスを使用します。

* * 統一されたグラフィカル・ユーザー・インターフェイス *
+
SnapCenter のインターフェイスは、すべてのプラグインと環境で標準化され、一貫しています。SnapCenter インターフェイスを使用すると、すべてのプラグインでバックアップ、リストア、クローニングの各処理を一貫した方法で実行できるほか、ダッシュボードビューで概要を把握したり、ロールベースアクセス制御（ RBAC ）を設定したり、ジョブを監視したりすることができます。

* * 中央管理の自動化 *
+
バックアップ処理のスケジュールを設定したり、ポリシーベースのバックアップ保持を設定したり、リストア処理を実行したりできます。SnapCenter から E メールアラートを送信するように設定して、環境をプロアクティブに監視することもできます。

* *無停止のNetApp Snapshotコピーテクノロジ*
+
SnapCenterは、Plug-in for IBM DB2 DatabaseでNetAppスナップショットテクノロジを使用してリソースをバックアップします。



Plug-in for IBM DB2を使用すると、次のようなメリットもあります。

* バックアップ、リストア、クローニングのワークフローがサポートされます。
* RBACでサポートされるセキュリティと一元化されたロール委譲
+
クレデンシャルを設定して、許可されたSnapCenterユーザにアプリケーションレベルの権限を付与することもできます。

* NetApp FlexCloneテクノロジを使用して、テストまたはデータ抽出に使用するリソースのスペース効率に優れたポイントインタイムコピーを作成できます。
+
クローンを作成するストレージシステムにFlexCloneライセンスが必要です。

* バックアップ作成時にONTAPの整合グループ（CG）Snapshot機能がサポートされるようになりました。
* 複数のリソースホストで同時に複数のバックアップを実行可能
+
1回の操作で、1つのホスト内のリソースが同じボリュームを共有すると、スナップショットが統合されます。

* 外部コマンドを使用してスナップショットを作成する機能。
* XFSファイルシステムでのLinux LVMのサポート。

