---
permalink: protect-nsp/add_hosts_and_install_plug_in_packages_on_remote_hosts.html 
sidebar: sidebar 
keywords: add hosts 
summary: '[SnapCenter][ホストの追加]ページを使用してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインはリモートホストに自動的にインストールされます。ホストの追加とプラグインパッケージのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストを追加してリモートホストにプラグインパッケージをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[SnapCenter][ホストの追加]ページを使用してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインはリモートホストに自動的にインストールされます。ホストの追加とプラグインパッケージのインストールは、ホストごとまたはクラスタごとに実行できます。

.開始する前に
* この処理は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* メッセージキューサービスが実行されていることを確認する必要があります。
* グループ管理サービスアカウント（gMSA）を使用する場合は、管理Privilegesを使用してgMSAを設定する必要があります。
+
link:configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016以降でカスタムアプリケーション用にグループ管理サービスアカウントを設定する"]



.タスクの内容
SnapCenterサーバをプラグインホストとして別のSnapCenterサーバに追加することはできません。

クラスタ（WSFC）にプラグインをインストールすると、プラグインはクラスタのすべてのノードにインストールされます。

.手順
. 左側のナビゲーションペインで、 *Hosts* を選択します。
. 上部で [Managed Hosts] タブが選択されていることを確認します。
. 「 * 追加」を選択します。
. [Hosts]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
ホストタイプを選択します。

** ウィンドウ
** Linux



NOTE: NetAppでサポートされているプラグインは、WindowsとLinuxのどちらの環境でも使用できます。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。

SnapCenterは、DNSが適切に設定されているかどうかによって異なります。そのため、FQDNを入力することを推奨します。

Windows環境では、信頼されていないドメインホストのIPアドレスはFQDNに解決される場合にのみサポートされます。

スタンドアロンホストのIPアドレスまたはFQDNを入力できます。

SnapCenterを使用してホストを追加する場合、そのホストがサブドメインの一部であるときは、FQDNを指定する必要があります。



 a| 
クレデンシャル
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

指定したクレデンシャルの名前にカーソルを合わせると、クレデンシャルの詳細を確認できます。


NOTE: クレデンシャルの認証モードは、ホスト追加ウィザードで指定するホストタイプによって決まります。

|===
. [ インストールするプラグインを選択してください * ] セクションで、インストールするプラグインを選択します。
+
リストから次のプラグインをインストールできます。

+
** MongoDB
** ORASCPM（Oracleアプリケーションとして表示）
** SAP ASE
** ORASCPM
** SAP MaxDB
** ストレージ


. （オプション）*[その他のオプション]*を選択して、他のプラグインをインストールします。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は8145です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
カスタムプラグインは、WindowsシステムとLinuxシステムのどちらにもインストールできます。

** Windows 用 SnapCenter Plug-ins パッケージのデフォルトパスは C ： \Program Files\NetApp\SnapManager です。
+
必要に応じて、パスをカスタマイズできます。

** SnapCenter Plug-ins Package for Linuxの場合、デフォルトパスはです `/opt/NetApp/snapcenter`。
+
必要に応じて、パスをカスタマイズできます。

** SnapCenter Custom Plug-ins の場合：
+
... [Custom Plug-ins]セクションで、*[Browse]*を選択し、zip形式のカスタムプラグインフォルダを選択します。
+
zip形式のフォルダには、カスタムプラグインコードと記述子.xmlファイルが含まれています。

+
Storage Plug-inの場合は、フォルダに移動し `_C:\ProgramData\NetApp\SnapCenter\Package Repository_` て選択します `Storage.zip` 。

... [アップロード]*を選択します。
+
パッケージをアップロードする前に、zip形式のカスタムプラグインフォルダ内の記述子.xmlファイルが検証されます。

+
SnapCenter サーバにアップロードされたカスタムプラグインが表示されます。







 a| 
インストール前チェックをスキップ
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行
 a| 
Windowsホストで、グループ管理サービスアカウント（gMSA）を使用してプラグインサービスを実行する場合は、このチェックボックスをオンにします。


IMPORTANT: gMSA名をdomainName\accountName$の形式で指定してください。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオンサービスアカウントとしてのみ使用されます。

|===
. [ 送信 ] を選択します。
+
[インストール前チェックをスキップ]*チェックボックスを選択していない場合、プラグインをインストールするための要件をホストが満たしているかどうかが検証されます。 ディスクスペース、RAM、PowerShellのバージョン、 NETバージョン、場所（Windowsプラグインの場合）、およびJavaバージョン（Linuxプラグインの場合）が最小要件に照らして検証されます。最小要件を満たしていない場合は、該当するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたはRAMに関連している場合は、C：\Program Files\NetApp\SnapCenter WebAppにあるweb.configファイルを更新してデフォルト値を変更できます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HAセットアップでweb.configファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. ホストタイプがLinuxの場合は、フィンガープリントを確認し、*[確認して送信]*を選択します。
+

NOTE: 同じホストを以前に SnapCenter に追加し、フィンガープリントを確認した場合でも、フィンガープリントの検証は必須です。

. インストールの進行状況を監視します。
+
インストール固有のログファイルはlogsにあり `/custom_location/snapcenter/` ます。


