---
permalink: protect-nsp/back_up_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: backup resources 
summary: リソースをバックアップするときは、 SnapCenter サーバとの接続を確立してから、リソースの追加、ポリシーの追加、バックアップリソースグループの作成を行って、バックアップを実行します。 
---
= PowerShellコマンドレットを使用したリソースのバックアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースをバックアップするときは、 SnapCenter サーバとの接続を確立してから、リソースの追加、ポリシーの追加、バックアップリソースグループの作成を行って、バックアップを実行します。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージシステム接続を追加し、クレデンシャルを作成しておく必要があります。


.タスクの内容
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。

.手順
. Open-SmConnectionコマンドレットを使用して、指定したユーザのSnapCenterサーバとの接続セッションを開始します。
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
ユーザ名とパスワードのプロンプトが表示されます。

. Add-SmResourcesコマンドレットを使用して、リソースを追加します。
+
リソースを追加する例を次に示します。

+
[listing]
----
Add-SmResource -HostName '10.232.206.248' -PluginCode 'DB2' -ResourceName NONREC1 -ResourceType Database -StorageFootPrint ( @
{"VolumeName"="DB2_NONREC1DB";"LunName"="DB2_NONREC1DB";"Vserver"="vserver_scauto_secondary"}) -Instance db2inst1
----
. Add-SmPolicyコマンドレットを使用して、バックアップポリシーを作成します。
+
新しいバックアップポリシーを作成する例を次に示します。

+
[listing]
----
Add-SMPolicy -PolicyName 'db2VolumePolicy' -PolicyType 'Backup' -PluginPolicyType DB2  -description 'VolumePolicy'
----
. Add-SmResourceGroupコマンドレットを使用して、SnapCenterに新しいリソースグループを追加します。
+
この例では、ポリシーとリソースを指定して新しいリソースグループを作成しています。

+
[listing]
----
Add-SmResourceGroup -ResourceGroupName 'Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix' -Resources @(@
{"Host"="10.232.206.248";"Uid"="db2inst2\NONREC"},@{"Host"="10.232.206.248";"Uid"="db2inst1\NONREC"}) -Policies db2ManualPolicy
----
. New-SmBackupコマンドレットを使用して、新しいバックアップジョブを開始します。
+
[listing]
----
New-SMBackup -DatasetName Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix -Policy db2ManualPolicy
----
. Get-SmBackupReportコマンドレットを使用して、バックアップジョブのステータスを表示します。
+
次に、指定した日付に実行されたすべてのジョブのジョブ概要レポートを表示する例を示します。

+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----

