---
permalink: protect-nsp/host_requirements_to_install_snapcenter_plug_in_package_for_windows.html 
sidebar: sidebar 
keywords: SAP HANA, NetApp supported plug-in 
summary: SnapCenter Plug-ins Package for Windowsをインストールする前に、基本的なホストシステムのスペース要件とサイジング要件を理解しておく必要があります。 
---
= Windows用 SnapCenter プラグインパッケージのホスト要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-ins Package for Windowsをインストールする前に、基本的なホストシステムのスペース要件とサイジング要件を理解しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティングシステム
 a| 
Microsoft Windows

サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/imt/imt.jsp?components=180321;180339;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]。



 a| 
ホスト上のSnapCenterプラグイン用の最小RAM
 a| 
1GB



 a| 
ホスト上のSnapCenterプラグインのインストールとログの最小スペース
 a| 
5GB


NOTE: 十分なディスクスペースを割り当て、logsフォルダによるストレージ消費量を監視する必要があります。必要なログスペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスクスペースがない場合、最近実行した処理のログは作成されません。



 a| 
必要なソフトウェアパッケージ
 a| 
* ASP.NET Core Runtime 10.0.7 Hosting Bundle（またはそれ以降のバージョン）
* PowerShell 7.6.1（以降）
* Java 17 (Oracle Java、OpenJDK、またはSAP JDK) またはJava 11（SnapCenter 6.2以前の場合）


お使いの特定のSnapCenterバージョンに対応するASP.NET CoreおよびPowerShellの最新の認定バージョンについては、link:https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter Software Release Notes"^]を参照してください。

用。 NET固有のトラブルシューティング情報。を参照してください。 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["インターネットに接続されていない従来型システムでは、SnapCenter のアップグレードまたはインストールが失敗します。"]

|===