---
permalink: protect-nsp/netapp_supported_plugins_overview.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: 使用しているアプリケーション用にNetAppでサポートされているプラグインを開発し、SnapCenterを使用してそれらのアプリケーションをバックアップ、リストア、クローニングすることができます。他のSnapCenterプラグインと同様に、NetApp対応プラグインはNetApp SnapCenterソフトウェアのホスト側コンポーネントとして機能し、アプリケーションに対応したリソースのデータ保護と管理を可能にします。 
---
= NetAppでサポートされるプラグインの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用しているアプリケーションには、NetAppでサポートされているプラグイン（MongoDB、ORASCPM（Oracleアプリケーション）、SAP ASE、SAP MaxDB、Storageなど）を使用できます。その後、SnapCenterを使用してこれらのアプリケーションのバックアップ、リストア、クローニングを実行できます。NetAppでサポートされるプラグインは、NetApp SnapCenterソフトウェアのホスト側コンポーネントとして機能し、アプリケーションに対応したリソースのデータ保護と管理を可能にします。

NetAppでサポートされるプラグインがインストールされている場合は、SnapCenterとNetApp SnapMirrorテクノロジを使用して別のボリュームにバックアップセットのミラーコピーを作成し、NetApp SnapVaultテクノロジを使用してディスクツーディスクのバックアップレプリケーションを実行できます。NetAppでサポートされているプラグインは、WindowsとLinuxのどちらの環境でも使用できます。


NOTE: SnapCenterCLIでは、NetAppでサポートされるプラグインコマンドはサポートされません。

NetApp は、SnapCenter に組み込まれたプラグイン フレームワークを使用して ONTAP ストレージ上のデータ ボリュームのデータ保護操作を実行するためのストレージ プラグインを提供します。

NetAppでサポートされるプラグインは、[ホストを追加]ページからインストールできます。

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["ホストを追加し、プラグインパッケージをリモートホストにインストールする。"^]


NOTE: SnapCenterのサポートポリシーは、プラグインフレームワーク、コアエンジン、および関連APIのサポートを対象とします。プラグインのソースコードおよびプラグインフレームワーク上に構築された関連スクリプトはサポート対象外となります。
