---
permalink: protect-nsp/netapp_supported_plugins_features.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins features 
summary: SnapCenterは、プラグインアプリケーションおよびストレージシステム上でNetAppテクノロジと統合されます。NetAppでサポートされているプラグインを操作するには、SnapCenterのグラフィカルユーザインターフェイスを使用します。 
---
= NetAppでサポートされるプラグイン機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、プラグインアプリケーションおよびストレージシステム上でNetAppテクノロジと統合されます。NetAppでサポートされているプラグインを操作するには、SnapCenterのグラフィカルユーザインターフェイスを使用します。

* * 統一されたグラフィカル・ユーザー・インターフェイス *
+
SnapCenterのインターフェイスは、プラグインと環境全体で標準化され、一貫性があります。SnapCenterのインターフェイスから、すべてのプラグインで、バックアップ、リストア、リカバリ、クローニングの各処理を一貫した方法で実行できるほか、ダッシュボードビューで概要を把握したり、ロールベースアクセス制御（RBAC）を設定したり、ジョブを監視したりできます。

* * 中央管理の自動化 *
+
バックアップ処理のスケジュールを設定したり、ポリシーベースのバックアップ保持を設定したり、リストア処理を実行したりできます。SnapCenter から E メールアラートを送信するように設定して、環境をプロアクティブに監視することもできます。

* *無停止のNetAppスナップショットテクノロジ*
+
SnapCenterでは、NetAppのSnapshotテクノロジとNetAppでサポートされているプラグインを使用してリソースがバックアップされます。Snapshotはストレージスペースを最小限しか消費しません。



NetAppでサポートされるプラグイン機能を使用すると、次の利点もあります。

* バックアップ、リストア、クローニングのワークフローがサポートされます。
* RBACでサポートされるセキュリティと一元化されたロール委譲
+
クレデンシャルを設定して、許可されたSnapCenterユーザにアプリケーションレベルの権限を付与することもできます。

* NetApp FlexCloneテクノロジを使用して、テストまたはデータ抽出に使用するリソースのスペース効率に優れたポイントインタイムコピーを作成できます。
+
クローンを作成するストレージシステムにFlexCloneライセンスが必要です。

* バックアップ作成時に、ONTAPの整合グループ（CG）Snapshot機能がサポートされます。
* 複数のリソースホストで同時に複数のバックアップを実行可能
+
1回の処理では、1つのホスト内のリソースが同じボリュームを共有する場合にSnapshotが統合されます。

* 外部コマンドを使用してSnapshotを作成する機能。
* Windows環境でファイルシステムと整合性のあるSnapshotを作成する機能。

