---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。NetAppでサポートされているプラグインは、WindowsとLinuxのどちらの環境でも使用できます。 
---
= ホストを追加してNetAppでサポートされるプラグインをインストールするための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してプラグインパッケージをインストールする前に、すべての要件を満たしておく必要があります。NetAppでサポートされているプラグインは、WindowsとLinuxのどちらの環境でも使用できます。

* カスタム プラグインを作成しておく必要があります。詳細については、開発者向け情報を参照してください。
+
link:develop_a_plug_in_for_your_application.html["アプリケーション用のプラグインを開発"]

* Java 11をLinuxホストまたはWindowsホストにインストールしておく必要があります。
* Windowsホストにプラグインをインストールするときに、組み込みでないクレデンシャルを指定する場合や、ユーザがローカルワークグループに属している場合は、ホストのUACを無効にする必要があります。
* ホストの追加処理を実行するクライアントホストに、NetAppでサポートされているプラグインがインストールされている必要があります。




== 全般

iSCSIを使用している場合は、iSCSIサービスが実行されている必要があります。



== SHA512ハッシュ

* NetAppでサポートされるプラグインの場合は、NetAppでサポートされるプラグインファイルのSHA512ハッシュを_custom_plugin_checksum_list_fileに追加しておく必要があります。
+
** Linuxホストでは、SHA512ハッシュは、_/var/opt/snapcenter/scc/custom plugin _checksum_list .txt_にあります
** Windowsホストでは、SHA512ハッシュは_ C：\Program Files\NetApp\SnapManager Plug-in Creator\etc\custom_plugin_schecksum_list .txt_にあります
+
カスタムのインストールパスでは、SHA512ハッシュは_<custom path>\NetApp\SnapCenter \Snapcenter Plug-in Creator\etc\custom_plugin_checksum_list .txt_にあります



+
custom_plugin_checksum_listは、SnapCenterによるNetApp対応プラグインのホストへのインストールに含まれています。

* アプリケーション用に作成されたNetApp対応プラグインの場合は、次の手順を実行しておく必要があります。
+
.. プラグインzipファイルのSHA512ハッシュが生成されました。
+
のようなオンラインツールを使用できます https://emn178.github.io/online-tools/sha512_file_hash.html["SHA512ハッシュ"^]。

.. 生成されたSHA512ハッシュをcustom_plugin_checksum_listファイルの新しい行に追加しました。
+
コメントは、ハッシュが属するプラグインを識別するために#記号で始まります。

+
次に、チェックサムファイル内のSHA512ハッシュのエントリ例を示します。

+
....
#ORASCPM
03721f567a1e4a1cb5569066b9a58af619ee12b1f8713108f81b696cfbdb81c25232fa63d6e6777a2b2a1ec068bb0a93a59a8ade71587182f8bccbe81f7e0ba6
....






== Windowsホスト

* ローカル管理者Privilegesを持つドメインユーザと、リモートホストに対するローカルログイン権限が必要です。
* SnapCenter でクラスタノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限を持つユーザが必要です。




== Linuxホスト

* rootユーザまたはroot以外のユーザに対してパスワードベースのSSH接続を有効にしておく必要があります。
* Java 11をLinuxホストにインストールしておく必要があります。
+
SnapCenter ServerホストにWindows Server 2019またはWindows Server 2016を使用している場合は、Java 11をインストールする必要があります。要件の最新情報については、 Interoperability Matrix Tool （ IMT ）を参照してください。

+
http://www.java.com/en/download/manual.jsp["すべてのオペレーティングシステム用のJavaダウンロード"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"]

* 複数のパスにアクセスできるようにroot以外のユーザにsudo権限を設定する必要があります。visudo Linuxユーティリティを使用して、/etc/sudoersファイルに次の行を追加します。
+

NOTE: Sudoバージョン1.8.7以降を使用していることを確認します。

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_linux_user_は、作成したroot以外のユーザの名前です。

+
_checksum_value_は、次の場所にある* sc_unix_plugins_checksum.txt *ファイルから取得できます。

+
** _C：\ProgramData\NetApp\SnapCenter\Package Repository\SC_UNIX_plugins_checksum.txt_ SnapCenter ServerがWindowsホストにインストールされている場合。
** _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc _ unix_plugins_checksum.txt _ SnapCenterサーバーがLinuxホストにインストールされている場合。
+

IMPORTANT: この例は、独自のデータを作成するための参照としてのみ使用してください。




