---
permalink: protect-nsp/restore_and_recover_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore resources 
summary: 7cbb56e18d0486bb234f9b23309d948c 
---
= 3f90ba06baa30f2e66df25302c79cd63
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7cbb56e18d0486bb234f9b23309d948c

c90de0347e94ade70c96034e2ffca3ba

.f3a29486bed19a90f2da6d007818b427
. 623aa9b9d36889377a728b1284e5485e
+
[listing]
----
PS C:\> Open-Smconnection
----
. e2bd14bf4c88f10bd2230039f5ac5538
+
ca85b74e61d8e4c683f3c66af932ac63

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
d1024e540ddbde0c895907728f551025

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. 4544315cf8cf4a9ef7dd5ae463d9557d
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


74db7181476f94f0e2927d8c8d98cb97
