---
permalink: protect-nsp/what_you_can_do_with_the_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: NetAppでサポートされているプラグインをデータ保護処理に使用できます。 
---
= NetAppでサポートされるプラグインとストレージプラグインの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetAppでサポートされているプラグインをデータ保護処理に使用できます。

* NetApp対応プラグイン*

* データベース、インスタンス、ドキュメント、表領域などのリソースを追加します。
* バックアップを作成します
* バックアップからリストアします
* バックアップをクローニングする。
* バックアップ処理のスケジュールを設定します。
* バックアップ、リストア、クローニングの各処理を監視する。
* バックアップ、リストア、クローニングの各処理のレポートを表示します。


* ストレージプラグイン *

このプラグインは、データ保護処理に使用できます。

* ONTAPクラスタ間でストレージボリュームの整合グループSnapshotを作成します。
* 組み込みのプレ / ポストスクリプトフレームワークを使用してカスタムアプリケーションをバックアップします
+
ONTAP ボリューム、 LUN 、または qtree をバックアップできます。

* SnapCenterポリシーを使用して、既存のレプリケーション関係（SnapVault / SnapMirror /ユニファイドレプリケーション）を利用して、プライマリで作成されたSnapshotをONTAPセカンダリに更新します。
+
ONTAPのプライマリとセカンダリには、ONTAP FAS、AFF、All SAN Array（ASA）、Select、Cloud ONTAPがあります。

* ONTAP ボリューム、 LUN 、またはファイルの完全なリカバリ
+
参照機能またはインデックス付け機能が製品に組み込まれていないため、それぞれのファイルパスを手動で指定する必要があります。

+
qtree またはディレクトリのリストアはサポートされませんが、バックアップの範囲が qtree レベルで定義されている場合にのみ、 qtree のクローニングとエクスポートを実行できます。


