---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: SnapCenter を使用する前に、実行するバックアップ、クローニング、およびリストアの処理に関連する基本的な概念を理解しておくと役立ちます。 
---
= データ保護の重要な概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用する前に、バックアップ、クローニング、リストアの主要な概念について理解しておく必要があります。



== リソース

リソースには、データベース、Windowsファイルシステム、SnapCenterでバックアップまたはクローニングされたファイル共有などがあります。環境によっては、データベースインスタンス、SQL Server可用性グループ、Oracleデータベース、RACデータベース、カスタムアプリケーショングループなどのリソースもあります。



== リソースグループ

リソースグループは、ホストまたはクラスタ上のリソースの集まりであり、複数のホストおよびクラスタからのリソースも含まれます。リソースグループに対して実行された処理は、指定したスケジュールに基づいてすべてのリソースに適用されます。個 々 のリソースまたはグループに対して、バックアップをオンデマンドまたはスケジュール設定して実行できます。


NOTE: 共有リソースグループ内の1つのホストがメンテナンスモードになると、そのグループに対してスケジュールされているすべての処理がすべてのホストで中断されます。

関連するプラグインを使用して、特定のリソース（データベース用のデータベースプラグイン、ファイルシステム用のファイルシステムプラグイン、VMとデータストア用のSnapCenter Plug-in for VMware vSphere）をバックアップします。



== ポリシー

ポリシーは、バックアップ頻度、コピーの保持、レプリケーション、スクリプトなど、データ保護処理の特性を指定します。

ポリシーは、リソースグループの作成時またはオンデマンドバックアップの実行時に選択できます。

リソースグループは、保護する必要があるものと保護する必要があるタイミングを日時別に定義します。ポリシーには、保護の実行方法が記述されています。たとえば、ホストのすべてのデータベースまたはファイルシステムをバックアップする必要がある場合は、ホストのすべてのデータベースまたはファイルシステムを含むリソースグループを作成できます。このリソースグループには、dailyポリシーとhourlyポリシーの2つのポリシーを関連付けることができます。

リソースグループを作成してポリシーを適用する場合は、フルバックアップを1日おきに実行し、ログバックアップを1時間おきに別のスケジュールで実行するように設定できます。

カスタムのプリスクリプトとポストスクリプトをデータ保護処理で使用できます。これらのスクリプトを使用すると、データ保護ジョブの前後に自動化できます。たとえば、データ保護ジョブの失敗や警告をスクリプトで自動的に通知できます。プリスクリプトとポストスクリプトを設定する前に、これらのスクリプトを作成するための要件を理解することが重要です。



== プリスクリプトとポストスクリプトの使用

カスタムのプリスクリプトとポストスクリプトを使用すると、ジョブの前後にデータ保護タスクを自動化できます。たとえば、ジョブの失敗や警告を通知するスクリプトを追加できます。これらのスクリプトを設定する前に、これらのスクリプトの要件を理解しておく必要があります。



=== サポートされるスクリプトタイプ

Windowsでは、次の種類のスクリプトがサポートされています。

* バッチファイル
* PowerShellスクリプト
* Perlスクリフト


UNIXでは、次の種類のスクリプトがサポートされています。

* Perlスクリフト
* Pythonスクリプト
* シェルスクリプト
+

NOTE: デフォルトのbashシェルに加えて、sh-shell、k-shell、c-shellのような他のシェルもサポートされています。





=== スクリプトパス

非仮想化ストレージシステムと仮想化ストレージシステムの両方でSnapCenter処理の一環として実行されるプリスクリプトとポストスクリプトは、すべてプラグインホストで実行されます。

* Windowsスクリプトがプラグインホストにある必要があります。



NOTE: プリスクリプトまたはポストスクリプトのパスにドライブまたは共有を含めることはできません。パスはscripts_pathからの相対パスである必要があります。

* UNIXスクリプトがプラグインホスト上にある必要があります。



NOTE: スクリプトパスは実行時に検証されます。



=== スクリプトを指定する場所

スクリプトはバックアップポリシーで指定されます。バックアップジョブが開始されると、ポリシーによってスクリプトがバックアップ対象のリソースに自動的に関連付けられます。バックアップポリシーの作成時に、プリスクリプトとポストスクリプトの引数を指定できます。


NOTE: 複数のスクリプトを指定することはできません。



=== スクリプトのタイムアウト

デフォルトでは、タイムアウトは60秒に設定されています。タイムアウト値は変更できます。



=== スクリプト出力

Windowsプリスクリプトとポストスクリプトの出力ファイルのデフォルトのディレクトリは、Windows\System32です。

UNIXのプリスクリプトとポストスクリプトのデフォルトの場所はありません。出力ファイルは任意の場所にリダイレクトできます。
