---
permalink: get-started/rbac-snapcenter.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions, application-level RBAC, ONTAP permissions, default snapcenter roles, ONTAP permissions, SnapCenter Admin role 
summary: SnapCenter のロールベースアクセス制御（ RBAC ）と ONTAP 権限を使用して、 SnapCenter 管理者はロールの作成とアクセス権限の設定を行うことができます。この一元管理されたアクセスにより、アプリケーション管理者は委任された環境で安全に作業を行うことができます。 
---
= SnapCenterでのロールベースアクセス制御
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter のロールベース アクセス制御 (RBAC) とONTAP権限により、 SnapCenter管理者はユーザーまたはグループにリソース アクセスを割り当てることができます。この集中管理されたアクセスにより、アプリケーション管理者は指定された環境内で安全に作業できるようになります。

ロールを作成または変更し、ユーザーにリソース アクセスを追加する必要があります。  SnapCenter を初めてセットアップするときは、Active Directory ユーザーまたはグループをロールに追加し、それらのユーザーまたはグループにリソースを割り当てます。


NOTE: SnapCenter はユーザー アカウントまたはグループ アカウントを作成しません。オペレーティング システムまたはデータベースの Active Directory にユーザー アカウントまたはグループ アカウントを作成します。



== SnapCenterのRBACの種類

SnapCenter は、次のタイプのロールベースのアクセス制御をサポートしています。

* SnapCenter RBAC
* アプリケーションレベルのRBAC
* VMware vSphere RBAC用SnapCenterプラグイン
* ONTAPケンケン




=== SnapCenter RBAC

SnapCenter には事前定義されたロールがあり、これらのロールにユーザーまたはグループを割り当てることができます。

* SnapCenter 管理者ロール
* App Backup and Clone Adminロール
* Backup and Clone Viewerロール
* Infrastructure Adminロール


ユーザーにロールを割り当てると、そのユーザーが SnapCenterAdmin ロールを持っていない限り、 SnapCenterそのユーザーに関連するジョブが [ジョブ] ページに表示されます。

また、新しいロールを作成して権限とユーザを管理することもできます。ユーザまたはグループに権限を割り当てて、ホスト、ストレージ接続、リソースグループなどのSnapCenterオブジェクトにアクセスすることができます。

RBACの権限は、同じフォレスト内のユーザとグループ、および異なるフォレストに属するユーザに割り当てることができます。フォレスト間でネストされたグループに属するユーザにRBAC権限を割り当てることはできません。


NOTE: カスタム ロールを作成するときは、SnapCenterAdmin ロールのすべての権限が含まれていることを確認してください。一部の権限のみをコピーすると、 SnapCenterによってすべての操作の実行が阻止されます。

ユーザーは、ユーザー インターフェイスまたは PowerShell コマンドレットを使用してログインするときに認証する必要があります。ユーザーが複数のロールを持っている場合は、ログイン後にロールを選択します。API を実行するには認証も必要です。



=== アプリケーションレベルのRBAC

SnapCenterは、クレデンシャルを使用して、許可されたSnapCenterユーザがアプリケーションレベルの権限も持っていることを確認します。

たとえば、SQL Server 環境でデータ保護操作を実行するには、適切な Windows または SQL 資格情報を設定します。  ONTAPストレージ上の Windows ファイル システム環境でデータ保護操作を実行する場合、 SnapCenter管理者ロールには Windows ホストに対する管理者権限が必要です。

同様に、Oracle データベースでデータ保護操作を実行する場合、データベース ホストでオペレーティング システム (OS) 認証が無効になっている場合は、Oracle データベースまたは Oracle ASM 資格情報を使用して資格情報を設定する必要があります。SnapCenter Serverは、処理に応じて、いずれかの方法で設定されたクレデンシャルを認証します。



=== SnapCenter Plug-in for VMware vSphere の RBAC をサポートしています

VMと整合性のあるデータ保護にSnapCenter VMwareプラグインを使用している場合は、vCenter ServerでRBACをさらに強化できます。SnapCenter VMwareプラグインは、vCenter Server RBACとONTAP RBACの両方をサポートしています。 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["詳細"^]

注: NetApp、SnapCenter Plug-in for VMware vSphere操作用に 1 つのONTAPロールを作成し、必要なすべての権限を割り当てることをお勧めします。



=== ONTAPケンケン

ストレージ システムにアクセスするために必要な権限を持つ vsadmin アカウントを作成する必要があります。link:../install/task_add_a_user_or_group_and_assign_role_and_assets.html["詳細"]



== 事前定義されたSnapCenterロールに割り当てられた権限

ユーザーをロールに追加するときは、StorageConnection 権限を割り当ててストレージ仮想マシン (SVM) 通信を有効にするか、ユーザーに SVM を割り当てて SVM を使用する権限を付与します。ストレージ接続権限により、ユーザーは SVM 接続を作成できます。

たとえば、 SnapCenter管理者は SVM 接続を作成し、それを App Backup および Clone 管理者ユーザーに割り当てることができますが、App Backup および Clone 管理者ユーザーは SVM 接続を作成または編集できません。  SVM 接続がないと、ユーザーはバックアップ、クローン作成、または復元操作を実行できません。



=== SnapCenter 管理者ロール

SnapCenter Admin ロールでは、すべての権限が有効になっています。このロールの権限は変更できません。ロールにユーザやグループを追加したり、削除したりできます。



=== App Backup and Clone Adminロール

App Backup and Clone Adminロールには、アプリケーションのバックアップとクローン関連のタスクに対して管理操作を実行するために必要な権限があります。このロールには、ホスト管理、プロビジョニング、ストレージ接続管理、またはリモートインストールに関する権限はありません。

|===
| 権限 | 有効 | 作成 | 読み取り | 更新 | 削除 


 a| 
リソースグループ
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ポリシー
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
バックアップ
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ホスト
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ストレージ接続
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
クローン
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
プロビジョニング
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
ダッシュボード
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
レポート
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リストア
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リソース
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
プラグインのインストール/アンインストール
 a| 
いいえ
 a| 
該当なし
 a| 
 a| 
該当なし
 a| 
該当なし



 a| 
移行
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
マウントする
 a| 
はい
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
アンマウント
 a| 
はい
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
フルボリュームリストア
 a| 
いいえ
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
セカンダリ保護
 a| 
いいえ
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
ジョブモニタ
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし

|===


=== Backup and Clone Viewerロール

バックアップおよびクローン ビューアー ロールには、すべての権限の読み取り専用ビューが付与されます。また、検出、レポート、およびダッシュボードへのアクセスに必要な権限も有効になっています。

|===
| 権限 | 有効 | 作成 | 読み取り | 更新 | 削除 


 a| 
リソースグループ
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
ポリシー
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
バックアップ
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
ホスト
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
ストレージ接続
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
クローン
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
プロビジョニング
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
ダッシュボード
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
レポート
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リストア
 a| 
いいえ
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リソース
 a| 
いいえ
 a| 
いいえ
 a| 
はい
 a| 
はい
 a| 
いいえ



 a| 
プラグインのインストール/アンインストール
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
移行
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
マウントする
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
アンマウント
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
フルボリュームリストア
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
セカンダリ保護
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
ジョブモニタ
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし

|===


=== Infrastructure Adminロール

Infrastructure Adminロールでは、ホスト管理、ストレージ管理、プロビジョニング、リソースグループ、リモートインストールレポート、 をクリックし、ダッシュボードにアクセスします。

|===
| 権限 | 有効 | 作成 | 読み取り | 更新 | 削除 


 a| 
リソースグループ
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ポリシー
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
バックアップ
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ホスト
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ストレージ接続
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
クローン
 a| 
該当なし
 a| 
いいえ
 a| 
はい
 a| 
いいえ
 a| 
いいえ



 a| 
プロビジョニング
 a| 
該当なし
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
ダッシュボード
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
レポート
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リストア
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
リソース
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
プラグインのインストール/アンインストール
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
移行
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
マウントする
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
アンマウント
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
フルボリュームリストア
 a| 
いいえ
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
セカンダリ保護
 a| 
いいえ
 a| 
いいえ
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし



 a| 
ジョブモニタ
 a| 
はい
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
該当なし

|===