---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: サポートされるストレージシステム、アプリケーション、およびデータベースを確認しておく必要があります。 
---
= SnapCenterでサポートされるストレージシステムとアプリケーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでサポートされるストレージシステム、アプリケーション、およびデータベースを確認しておく必要があります。



== サポートされるストレージシステム

* NetApp ONTAP 9.12.1以降
* Azure NetApp Files
* Amazon FSx for NetApp ONTAP
+
Amazon FSx for NetApp ONTAP は、トランスポート制御プロトコル (TCP) 経由の不揮発性メモリエクスプレス (NVMe) をサポートしています。

+
Amazon FSx for NetApp ONTAPの詳細については、を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP のドキュメント"^]。

* NetApp ONTAP 9.16.1 以降を実行しているNetApp ASA r2 システム
+
SnapCenter Server 6.2 およびSnapCenterプラグイン 6.2 を使用している場合は、 ONTAP 9.17.1 を使用する必要があります。





== サポートされるアプリケーションとデータベース

SnapCenterは、さまざまなアプリケーションやデータベースの保護をサポートしています。サポートされているアプリケーションとデータベースの詳細については、を参照してください https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^]。

SnapCenterは、Amazon Web Services（AWS）のSoftware-Defined Data Center（SDDC）環境上のVMware Cloudで、OracleとMicrosoft SQLのワークロードの保護をサポートします。https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["詳細"^]です。
