---
permalink: get-started/reference_data_security.html 
sidebar: sidebar 
keywords: security, authentication, CA certificates, FIPS, SSL, AES, TLS, RBAC, MFA, multi-factor authentication 
summary: SnapCenter では、データのセキュリティを確保するために厳格なセキュリティおよび認証機能を採用しています。 
---
= SnapCenterのセキュリティ機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter では、データのセキュリティを確保するために厳格なセキュリティおよび認証機能を採用しています。

SnapCenter には、次のセキュリティ機能が含まれています。

* SnapCenter へのすべての通信には、 HTTP over SSL （ HTTPS ）が使用されます。
* SnapCenter のすべてのクレデンシャルは、 Advanced Encryption Standard （ AES ）暗号化を使用して保護されます。
* は、Federal Information Processing Standard（FIPS；連邦情報処理標準）に準拠したセキュリティアルゴリズムをサポートします。
* 顧客から提供された承認済みCA証明書の使用をサポートします。
* ONTAPとの通信では、Transport Layer Security（TLS）1.3がサポートされます。クライアントとサーバ間の通信にもTLS 1.2を使用できます。
* は、特定のSSL暗号スイートのセットをサポートして、ネットワーク通信全体にセキュリティを提供します。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["詳細"]です。
* SnapCenter は、会社のファイアウォールの内側にインストールされ、 SnapCenter サーバへのアクセス、および SnapCenter サーバとプラグイン間の通信を可能にします。
* SnapCenter APIおよび操作アクセスでは、AES暗号化で暗号化されたトークンが使用されます。このトークンは24時間後に期限切れになります。
* SnapCenter は、ログイン用に Windows Active Directory と統合されているほか、アクセス権限を制御するロールベースアクセス制御（ RBAC ）も統合されています。
* IPSecは、SnapCenter on ONTAP for WindowsおよびLinuxホストマシンでサポートされています。 https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["詳細"]です。
* SnapCenter PowerShellコマンドレットはセッションで保護されます。
* デフォルトでは、操作を行わないまま15分が経過すると、SnapCenterは5分後にログアウトすることを警告します。
+
操作を行わないまま20分が経過すると、SnapCenterからログアウトされ、再度ログインする必要があります。ログアウト期間は変更できます。

* ログインに5回失敗すると、ログインは一時的に無効になります。
* SnapCenterサーバとONTAP間のCA証明書認証をサポートします。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["詳細"]です。
* 整合性検証ツールはSnapCenterサーバとプラグインに追加され、新規インストールおよびアップグレード処理の際に、出荷されたすべてのバイナリが検証されます。




== CA証明書の概要

SnapCenterサーバインストーラは、インストール中に集中型SSL証明書のサポートを有効にします。SnapCenterでは、サーバとプラグイン間のセキュアな通信を強化するために、お客様から提供された承認済みCA証明書の使用をサポートしています。

SnapCenter サーバとそれぞれのプラグインをインストールしたあとに、 CA 証明書を導入する必要があります。詳細については、を参照してください link:../install/reference_generate_CA_certificate_CSR_file.html["CA証明書CSRファイルの生成"]。

SnapCenter Plug-in for VMware vSphereのCA証明書を導入することもできます。詳細については、を参照してください https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["証明書の作成とインポート"^]。



== 双方向SSL通信

双方向SSL通信は、SnapCenterサーバとプラグイン間の相互通信を保護します。



== 証明書ベースの認証の概要

証明書ベースの認証は、SnapCenterプラグインホストにアクセスしようとする各ユーザの信頼性を検証します。秘密鍵なしでSnapCenterサーバ証明書をエクスポートし、プラグインホストの信頼されたストアにインポートする必要があります。証明書ベースの認証は、双方向SSL機能が有効になっている場合にのみ機能します。



== 多要素認証（MFA）

MFAは、Security Assertion Markup Language（SAML）を介してサードパーティのアイデンティティプロバイダ（IdP）を使用してユーザセッションを管理します。この機能は、既存のユーザー名とパスワードとともに、TOTP、生体認証、プッシュ通知などの複数の要素を使用するオプションを持つことで、認証セキュリティを強化します。また、お客様は独自のユーザIDプロバイダを使用して、ポートフォリオ全体で統合ユーザログイン（SSO）を取得できます。

MFAは、SnapCenterサーバUIログインにのみ適用されます。ログインはIdP Active Directoryフェデレーションサービス（AD FS）を使用して認証されます。AD FSでは、さまざまな認証要素を設定できます。SnapCenterはサービスプロバイダであるため、AD FSでSnapCenterを証明書利用者として設定する必要があります。SnapCenterでMFAを有効にするには、AD FSメタデータが必要です。

MFAを有効にする方法については、を参照してください link:../install/enable_multifactor_authentication.html["多要素認証を有効にします"]。
