---
permalink: uninstall/reference_prerequisites_for_removing_a_host.html 
sidebar: sidebar 
keywords: uninstall, prerequisites, plug-in, plug-in packages 
summary: データ保護ジョブの管理に SnapCenter を使用する必要がなくなった場合は、ホストを削除できます。たとえば、保護が必要なデータがなくなったホストを削除できます。SnapCenter サーバからホストを削除する前に、前提条件となるタスクを実行する必要があります。 
---
= ホストを削除するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter GUI を使用して、ホストを削除し、個々のプラグインまたはプラグインパッケージをアンインストールできます。また、 SnapCenter Server ホストのコマンドラインインターフェイス（ CLI ）を使用するか、または任意のホストでローカルに Windows * プログラムのアンインストール * オプションを使用して、リモートホスト上の個々のプラグインまたはプラグインパッケージをアンインストールすることもできます。

SnapCenter サーバからホストを削除する前に、前提条件を完了しておく必要があります。

* 管理者としてログインする必要があります。
* SnapCenter Custom Plug-ins を使用している場合は、ホストに関連付けられている SnapCenter からすべてのクローンを削除する必要があります。
* ホストで検出ジョブが実行されていないことを確認する必要があります。
* ホストに関連付けられているすべてのオブジェクトを削除するために必要な権限を持つロールが割り当てられている必要があります。削除しないと、削除処理は失敗します。
* SnapCenter へのホストの追加後に SSH キーが変更された場合は、フィンガープリントを確認する必要があります。
* SnapCenter ホストが新しいバージョンの SnapCenter にアップグレードされ、プラグインホストで以前のバージョンのプラグインが実行されている場合は、フィンガープリントを確認する必要があります。




== ロールベースアクセス制御を使用するホストを削除する場合の前提条件

* ホストの読み取りと削除、プラグインのインストールとアンインストール、およびオブジェクトの削除を行う権限を持つ RBAC ロールを使用してログインしておく必要があります。
+
オブジェクトは、クローン、バックアップ、リソースグループ、ストレージシステムなどです。

* RBAC ロールに RBAC ユーザを追加しておく必要があります。
* 削除するホスト、プラグイン、クレデンシャル、リソースグループ、およびストレージシステム（クローンの場合）に RBAC ユーザを割り当てる必要があります。
* SnapCenter に RBAC ユーザとしてログインしておく必要があります。




== クローンライフサイクル処理で作成されたクローンを含むホストを削除する場合の前提条件

* SQL データベースのクローンライフサイクル管理を使用してクローニングジョブを作成しておく必要があります。
* クローンの読み取りと削除、リソースの読み取りと削除、リソースグループの読み取りと削除、ストレージの読み取りと削除、プロビジョニングの読み取りと削除、マウント、アンマウント、プラグインのインストールとアンインストール、およびホストの読み取りと削除を行う権限を持つ RBAC ロールを作成しておく必要があります。
* RBAC ロールに RBAC ユーザを割り当てておく必要があります。
* ホスト、 SnapCenter Plug-in for Microsoft SQL Server 、クレデンシャル、クローンライフサイクルリソースグループ、およびストレージシステムに RBAC ユーザを割り当てておく必要があります。
* SnapCenter に RBAC ユーザとしてログインしておく必要があります。


SnapCenter Plug-in for VMware vSphere のアンインストールについては、を参照してください https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#remove-snapcenter-plug-in-for-vmware-vsphere["SnapCenter Plug-in for VMware vSphere を削除します"^]。
