---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: SnapCenter サーバはホストを削除すると、最初にそのホストに対してリストされているバックアップ、クローン、ジョブ、リソースグループ、およびリソースを SnapCenter のリソースページから削除したあと、ホスト上のプラグインパッケージをアンインストールします。 
---
= ホストを削除します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバはホストを削除すると、最初にそのホストに対してリストされているバックアップ、クローン、ジョブ、リソースグループ、およびリソースを SnapCenter のリソースページから削除したあと、ホスト上のプラグインパッケージをアンインストールします。

* このタスクについて *

* ホストを削除すると、そのホストに関連付けられているバックアップ、クローン、およびリソースグループも削除されます。
* リソースグループを削除すると、関連付けられているスケジュールもすべて削除されます。
* ホストに別のホストと共有されているリソースグループがある場合にそのホストを削除すると、リソースグループも削除されます。
* 運用停止されたプラグインホストまたは到達不能なプラグインホストを削除するには、 _Remove-SmHost_cmdlet を使用してください。
+
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]

* ホストの削除にかかる時間は、バックアップの数と保持設定によって異なります。これは、各コントローラから Snapshot コピーが削除され、メタデータが消去されるためです。


* 手順 *

. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. [Hosts] ページで、 [*Managed Hosts] をクリックします。
. 削除するホストを選択し、 * Remove * をクリックします。
. Oracle RAC クラスタの場合、クラスタ内のすべてのホストから SnapCenter ソフトウェアを削除するには、 * クラスタのすべてのホストを含める * を選択します。
+
クラスタの 1 つのノードを削除して、すべてのノードを 1 つずつ削除することもできます。

. [OK] をクリックします。
+

NOTE: クラスタでホストプラグインをアンインストールして再インストールしても、クラスタリソースは自動的に検出されません。クラスタのホスト名を選択し、 * リソースの更新 * をクリックすると、クラスタ・リソースが自動的に検出されます。


