---
permalink: uninstall/task_uninstalling_the_snapcenter_server.html 
sidebar: sidebar 
keywords: uninstall, snapcenter server, windows 
summary: 'SnapCenterサーバを使用してデータ保護ジョブを管理する必要がなくなった場合は、SnapCenterサーバホストの[プログラムと機能]コントロールパネルを使用してSnapCenterサーバをアンインストールできます。SnapCenter サーバをアンインストールすると、そのコンポーネントがすべて削除されます。' 
---
= WindowsホストでのSnapCenterサーバのアンインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterサーバを使用してデータ保護ジョブを管理する必要がなくなった場合は、SnapCenterサーバホストの[プログラムと機能]コントロールパネルを使用してSnapCenterサーバをアンインストールできます。SnapCenter サーバをアンインストールすると、そのコンポーネントがすべて削除されます。

.開始する前に
* SnapCenterサーバがインストールされているドライブに2GB以上の空き容量があることを確認します。
* SnapCenterサーバがインストールされているドメインが削除されていないことを確認します。
+
SnapCenterサーバがインストールされているドメインを削除してからアンインストールしようとすると、処理は失敗します。

* リポジトリデータベースがクリーンアップおよびアンインストールされるため、リポジトリデータベースをバックアップしておく必要があります。


.手順
. SnapCenterサーバーホストで、[コントロールパネル]に移動します。
. 「 * カテゴリ * 」ビューにいることを確認します。
. [ プログラム ] の下にある [ プログラムのアンインストール ] をクリックします。
+
[プログラムと機能]ウィンドウが開きます。

. NetApp SnapCenter Server を選択し、 * Uninstall * をクリックします。
+
SnapCenter 4.2 では、 SnapCenter サーバをアンインストールすると、 MySQL Server リポジトリデータベースを含むすべてのコンポーネントがアンインストールされます。

+
** NLB クラスタから NLB ノードを削除した場合、 SnapCenter サーバホストを再起動する必要があります。ホストを再起動しないと、 SnapCenter サーバを再インストールしようとしたときにエラーが発生することがあります。
** 手動でアンインストールする必要があります。 アンインストール中に削除されないNet Framework。



