---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: 'SnapCenterサーバでホストを削除すると、まずSnapCenterの[Resources]ページにそのホストに対して表示されているバックアップ、クローン、クローニングジョブ、リソースグループ、およびリソースが削除され、次にホスト上のプラグインパッケージがアンインストールされます。' 
---
= ホストを削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterサーバでホストを削除すると、まずSnapCenterの[Resources]ページにそのホストに対して表示されているバックアップ、クローン、クローニングジョブ、リソースグループ、およびリソースが削除され、次にホスト上のプラグインパッケージがアンインストールされます。

.タスクの内容
* ホストを削除すると、そのホストに関連付けられているバックアップ、クローン、およびリソースグループも削除されます。
* リソースグループを削除すると、関連付けられているスケジュールもすべて削除されます。
* 別のホストと共有しているリソースグループがホストにある場合にそのホストを削除すると、リソースグループも削除されます。
* 運用停止されたプラグインホストまたは到達不能なプラグインホストを削除するには、 _Remove-SmHost_cmdlet を使用してください。
+
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]

* ホストの削除にかかる時間は、バックアップの数と保持設定によって異なります。これは、各コントローラからSnapshotが削除され、メタデータが消去されるためです。


.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. [ホスト]*ページで、*[管理対象ホスト]*をクリックします。
. 削除するホストを選択し、 * Remove * をクリックします。
. Oracle RAC クラスタの場合、クラスタ内のすべてのホストから SnapCenter ソフトウェアを削除するには、 * クラスタのすべてのホストを含める * を選択します。
+
クラスタの1つのノードを削除して、すべてのノードを1つずつ削除することもできます。

. [OK]*をクリックします。
+

NOTE: クラスタでホストプラグインをアンインストールして再インストールしても、クラスタリソースは自動的に検出されません。クラスタのホスト名を選択し、 * リソースの更新 * をクリックすると、クラスタ・リソースが自動的に検出されます。


