---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: SnapCenterソフトウェアのリリース6.0には、いくつかの新機能と拡張機能が含まれています。 
---
= SnapCenterソフトウェア6.0の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterソフトウェアのリリース6.0には、いくつかの新機能と拡張機能が含まれています。

|===
| 更新 | 説明 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["NetAppのサポートにより、エンタープライズワークロードのプラグインをサポート"]  a| 
SnapCenterは、PostgreSQL、MySQL、IBM DB2などのワークロードを管理するためのプラグインを提供します。ワークロードの検出、バックアップ、リストア、マウント、クローニングを自動で実行できます。

SnapCenterには、SAP ASE、SAP MaxDB、MongoDB、Oracleアプリケーション、ONTAPストレージなどのワークロードを管理するためのプラグインも用意されています。ワークロードのバックアップ、リストア、クローニングを実行できます。



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["クラウドとオンプレミスの両方のワークロードでLinuxバージョンのSnapCenterをサポート"]  a| 
Red Hat Enterprise Linux（RHEL）、Oracle Linux、SUSE Linux Enterprise Server（SLES）などのLinux用に個別のSnapCenterバイナリを使用できるようになりました。

* Azure NetApp Files、Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP、ONTAPストレージをサポートします。
* Red Hat Enterprise Linux（RHEL）、Oracle Linux、SUSE Linux Enterprise Server（SLES）などのLinux用の個別のバイナリ。
* SAP HANA、Oracle、IBM DB2、SAP ASE、SAP MaxDBなどの従来型データベースをサポート
* PostgreSQL、MySQL、MongoDBなどの最新のワークロードをサポートします。
* ONTAPボリュームとLinuxファイルシステム用のプラグインをサポートしているため、サポートされていないアプリケーションや自社開発のアプリケーションを保護できます。




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["SnapMirrorアクティブ同期のサポート"]  a| 
SnapCenterを使用してSnapMirrorのアクティブな同期機能を設定し、データベースやVMware VMのSANワークロードを効率的にバックアップ、リストア、クローニングできるようになりました。これにより、透過的なアプリケーションフェイルオーバーとビジネス継続性が保証されます。



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["SMB3経由でのMicrosoft SQL Serverのサポート"]  a| 
SnapCenterを使用して、ONTAP、Azure NetApp Files、Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAPのSMB3プロトコルに導入されたMicrosoft SQL Serverデータベースを保護できるようになりました。



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["NVMe / TCPのサポート"]  a| 
SnapCenterでは、アプリケーションとファイルシステムのバックアップとリカバリにNVMe over TCPプロトコルがサポートされるようになりました。



| VMware vSphere Virtual Volumes（VVol）のサポート  a| 
SnapCenterを使用して、VVOLに導入されたデータベースとファイルシステムを保護できるようになりました。

|===