---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: SnapCenterソフトウェアのリリース6.0には、いくつかの新機能と拡張機能が含まれています。 
---
= SnapCenterソフトウェア6.0の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterソフトウェアのリリース6.0には、いくつかの新機能と拡張機能が含まれています。

|===
| 更新 | 説明 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["NetAppに対応したエンタープライズワークロードプラグインをサポート"]  a| 
SnapCenterは、PostgreSQL、MySQL、IBM DB2などのワークロードを管理するためのプラグインを提供します。ワークロードの検出、バックアップ、リストア、マウント、クローニングを自動で実行できます。

SnapCenterには、SAP ASE、SAP MaxDB、MongoDB、Oracleアプリケーション、ONTAPストレージなどのワークロードを管理するためのプラグインも用意されています。ワークロードのバックアップ、リストア、クローニングを実行できます。



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["クラウドとオンプレミスの両方のワークロードでLinuxバージョンのSnapCenterをサポート"]  a| 
* Azure NetApp Files、Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP、ONTAPストレージをサポートします。
* Red Hat Enterprise Linux（RHEL）、Oracle Linux、SUSE Linux Enterprise Server（SLES）などのLinux用の個別のバイナリ。
* SAP HANA、Oracle、IBM DB2、SAP ASE、SAP MaxDBなどの従来型データベースをサポート
* PostgreSQL、MySQL、MongoDBなどの最新のワークロードをサポートします。
* ONTAPボリュームとLinuxファイルシステム用のプラグインをサポートしているため、サポートされていないアプリケーションや自社開発のアプリケーションを保護できます。




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["SnapMirror Active Syncのサポート"]  a| 
透過的なアプリケーションフェイルオーバーとビジネス継続性を実現するように設定されたSANワークロード（データベースやVMware VM）をシームレスにバックアップ、リストア、クローニングできます。



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["SMB3経由でのMicrosoft SQL Serverのサポート"]  a| 
ONTAP、Azure NetApp Files、Amazon FSx for NetApp ONTAP、およびONTAP Cloud VolumesのSMB3プロトコルに導入されたMicrosoft SQL Serverデータベースは、SnapCenterを使用して保護できるようになりました。



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["NVMe / TCPのサポート"]  a| 
パフォーマンスを向上させるために重要なワークロードをNVMe/TCPに移行する場合は、SnapCenterを使用してアプリケーションとファイルシステムをバックアップおよびリカバリできます。



| VMware VVOLのサポート  a| 
VMware VVOLにデータベースとファイルシステムを導入した場合は、SnapCenterを使用してそれらを保護できます。

|===