---
permalink: 'release-notes/what"s-new-in-snapcenter62.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.2 
summary: SnapCenter software の 6.2 リリースには、いくつかの新機能と機能強化が含まれています。 
---
= SnapCenter software6.2 の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter software 6.2 リリースには、既知のバグ修正と、SnapCenter サーバーおよびプラグインの対応バージョンのアップデートが含まれています。また、以下の拡張機能も含まれています。詳細については、link:https://library.netapp.com/ecm/ecm_download_file/ECMLP3359467["SnapCenter 6.2.2 リリースノート"^]を参照してください。

|===
| 更新 | 説明 


| link:../get-started/reference_supported_storage_systems_and_applications.html["ASA R2システムのサポート"]  a| 
SnapCenter 6.2 (サーバおよびプラグイン) は、 ONTAP 9.17.1 とともに、階層的整合性グループを利用して、物理システム (Linux および Windows) および仮想マシン ファイル システム (VMFS) で実行されているアプリケーションのプライマリ保護とセカンダリ保護の両方をサポートします。

SnapCenter 6.2 およびONTAP 9.17.1 にアップグレードすると、 SnapCenter は最初のスケジュールされたバックアップ中にフラット コンシステンシ グループを階層型コンシステンシ グループに変更します。

|===


== BlueXPはNetAppコンソールになりました

NetAppコンソールは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetAppデータ サービスの集中管理を提供し、リアルタイムの分析情報、ワークフローの高速化、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetAppコンソールのリリースノート"^] 。
