---
permalink: protect-mysql/add-hosts-and-install-plug-in-packages-on-remote-hosts-mysql.html 
sidebar: sidebar 
keywords: credentials 
summary: ホストの追加ページを使用 SnapCenter してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインは、自動的にリモートホストにインストールされます。ホストの追加とプラグインパッケージのインストールは、個々のホストまたはクラスタに対して実行できます。 
---
= ホストを追加し、プラグインパッケージをリモートホストにインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[ホストを追加]ページを使用してホストを追加し、プラグインパッケージをインストールする必要があります。プラグインはリモートホストに自動的にインストールされます。ホストを追加して、個 々 のホスト用のプラグインパッケージをインストールできます。

.作業を開始する前に
* SnapCenter ServerホストのオペレーティングシステムがWindows 2019で、プラグインホストのオペレーティングシステムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* SnapCenter Admin ロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが必要です。
* Windows ホストにプラグインをインストールする場合、ビルトインでないクレデンシャルを指定する場合、またはユーザがローカルワークグループユーザに属している場合は、ホストで UAC を無効にする必要があります。
* メッセージキューサービスが実行されていることを確認してください。
* 管理マニュアルには、ホストの管理に関する情報が記載されています。


.このタスクについて
* SnapCenter サーバをプラグインホストとして別の SnapCenter サーバに追加することはできません。


.手順
. 左側のナビゲーションペインで、 * Hosts * （ホスト）をクリックします。
. 上部で [Managed Hosts] タブが選択されていることを確認します。
. [ 追加（ Add ） ] をクリックします。
. Hosts ページで、次の操作を実行します。
+
|===
| フィールド | 手順 


 a| 
ホストタイプ
 a| 
ホストのタイプを選択します。

** Windows の場合
** Linux の場合
+

NOTE: Plug-in for MySQLをMySQLデータベースサーバにインストールする必要があります。





 a| 
ホスト名
 a| 
通信ホスト名を入力します。ホストの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。SnapCenter は、 DNS の適切な設定によって異なります。そのため、 FQDN を入力することを推奨します。



 a| 
クレデンシャル
 a| 
作成したクレデンシャル名を選択するか、新しいクレデンシャルを作成します。このクレデンシャルには、リモートホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

クレデンシャルの詳細を表示するには、指定したクレデンシャル名にカーソルを合わせます。


NOTE: クレデンシャル認証モードは、ホストの追加ウィザードで指定したホストタイプによって決まります。

|===
. インストールするプラグインの選択セクションで、インストールするプラグインを選択します。
+
REST APIを使用してPlug-in for MySQLをインストールする場合は、バージョンを3.0として渡す必要があります。例：mysql：3.0

. （オプション） * その他のオプション * をクリックします。
+
|===
| フィールド | 手順 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。デフォルトのポート番号は 8145 です。SnapCenter サーバがカスタムポートにインストールされている場合は、そのポート番号がデフォルトポートとして表示されます。


NOTE: プラグインを手動でインストールし、カスタムポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理は失敗します。



 a| 
インストールパス
 a| 
Plug-in for MySQLはMySQLクライアントホストにインストールされます。このホストはWindowsシステムでもLinuxシステムでもかまいません。

** Windows 用 SnapCenter Plug-ins パッケージのデフォルトパスは C ： \Program Files\NetApp\SnapManager です。必要に応じて、パスをカスタマイズできます。
** Linux 用 SnapCenter Plug-ins パッケージのデフォルトパスは /opt/NetApp/SnapCenter です。必要に応じて、パスをカスタマイズできます。




 a| 
インストール前のチェックをスキップします
 a| 
プラグインを手動でインストール済みで、プラグインのインストール要件をホストが満たしているかどうかを検証しない場合は、このチェックボックスを選択します。



 a| 
クラスタ内のすべてのホストを追加します
 a| 
該当なし。



 a| 
プラグインサービスを実行するには、 Group Managed Service Account （ gMSA ；グループ管理サービスアカウント）を使用します
 a| 
該当なし。

|===
. [Submit （送信） ] をクリックします。
+
[ 事前確認をスキップする ] チェックボックスを選択していない場合、ホストがプラグインのインストール要件を満たしているかどうかを検証されます。ディスクスペース、 RAM 、 PowerShell のバージョン、 .NET のバージョン、場所（ Windows プラグインの場合）、および Java のバージョン（ Linux プラグインの場合）が、最小要件に照らして検証されます。最小要件を満たしていない場合は、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスクスペースまたは RAM に関連している場合は、 C ： \Program Files\NetApp\SnapManager WebApp にある web.config ファイルを更新してデフォルト値を変更することができます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HA セットアップで web.config ファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. ホストタイプが Linux の場合は、フィンガープリントを確認し、 * Confirm and Submit * をクリックします。
+
クラスタセットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

+

NOTE: 同じホストを以前に SnapCenter に追加し、フィンガープリントを確認した場合でも、フィンガープリントの検証は必須です。

. インストールの進行状況を監視します。
+
** Windowsプラグインの場合、インストールログとアップグレードログは_C：\Windows\SnapCenter <JOBID>にあります。
** Linuxプラグインの場合、インストールログは_/var/opt/snapcenter/logs/SnapCenter _Linux_Host_Plug-in_Install_Install_Linux.log_<JOBID>にあり、アップグレードログは_/var/opt/snapcenter/logs/SnapCenter <JOBID>.log_にあります。




.完了後
SnapCenter 6.0にアップグレードする場合は、既存のPerlベースのPlug-in for MySQLがリモートプラグインサーバからアンインストールされます。
