---
permalink: protect-mysql/configure-CA-certificate-for-mysql-on-windows-host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Windowsホスト上のSnapCenter MySQLプラグインサービス用のCA証明書の設定 
---
= Windowsホスト上のSnapCenter MySQLプラグインサービス用のCA証明書の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールされたデジタル証明書をアクティブ化するには、SnapCenter プラグイン サービスを使用して、プラグイン キーストアとその証明書のパスワードを管理し、CA 証明書を構成し、プラグイン トラストストアにルート証明書または中間証明書を構成し、プラグイン トラストストアに CA 署名キー ペアを構成する必要があります。

プラグインは、信頼ストアとキーストアの両方として、_C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_ にあるファイル _keystore.jks_ を使用します。



== プラグインキーストアのパスワードと使用中のCA署名キーペアのエイリアスを管理する

.手順
. プラグイン エージェント プロパティ ファイルからプラグイン キーストアのデフォルト パスワードを取得できます。
+
key_keystore.pass_ に対応する値です。

. キーストアのパスワードを変更します。
+
_keytool -storepasswd -keystore keystore.JKS_

+

NOTE: Windowsコマンドプロンプトで「keytool」コマンドが認識されない場合は、keytoolコマンドを完全なパスに置き換えます。

+
_C ： \Program Files\Java\<JDK_version >\bin\keytool .exe "-storepasswd -keystore keystore.JKS_

. キーストア内の秘密鍵エントリのすべてのエイリアスのパスワードを、キーストアと同じパスワードに変更します。
+
_keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.JKS_

+
_agent.properties_ ファイル内のキー keystore.pass に対しても同じキーを更新します。

. パスワードを変更したら、サービスを再起動します。
+

NOTE: プラグイン キーストアのパスワードと、秘密キーに関連付けられたすべてのエイリアス パスワードは同じである必要があります。





== ルート証明書または中間証明書をプラグイン信頼ストアに設定する

信頼ストアをプラグインするには、秘密キーなしでルート証明書または中間証明書を構成する必要があります。

.手順
. プラグインキーストアが格納されているフォルダ_C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_に移動します。
. 「keystore.jks」ファイルを探します。
. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. ルート証明書または中間証明書を追加します。
+
_keytool -import-trustcacerts -alias myRootCA -file/root/USERTrustRSA_Root.cer -keystore keystore.JKS_

. ルート証明書または中間証明書をプラグイン信頼ストアに設定した後、サービスを再起動します。



NOTE: ルートCA証明書のあとに中間CA証明書を追加する必要があります。



== CA署名キーペアをプラグイン信頼ストアに設定する

CA 署名キー ペアをプラグイン信頼ストアに設定する必要があります。

.手順
. プラグインキーストアが格納されているフォルダ_C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_に移動します。
. file_keystore.JKS_</Z1> を探します。
. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. 秘密鍵と公開鍵の両方が設定されたCA証明書を追加します。
+
_keytool -importkeystore -srckeystore.root/ snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.JKS -deststoretype JKS_

. キーストアに追加された証明書を一覧表示します。
+
_keytool -list -v キーストア .JKS_

. キーストアに追加された新しいCA証明書に対応するエイリアスがキーストアに含まれていることを確認します。
. CA証明書に追加した秘密鍵のパスワードをキーストアのパスワードに変更します。
+
デフォルトのプラグイン キーストア パスワードは、agent.properties ファイルのキー KEYSTORE_PASS の値です。

+
_keytool -keypasswd -alias "alias_name_in_ca_cert" -keystore keystore.JKS__

. _agent.properties_ ファイルの CA 証明書からエイリアス名を設定します。
+
この値をSCC_CERTIFICATE_ALIASキーに対して更新します。

. CA 署名キー ペアをプラグイン トラスト ストアに設定した後、サービスを再起動します。




== SnapCenterプラグインの証明書失効リスト（CRL）を構成する

.タスクの内容
* 関連するCA証明書の最新のCRLファイルをダウンロードするには、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["SnapCenter CA 証明書の証明書失効リストファイルを更新する方法"]。
* SnapCenter プラグインは、事前に構成されたディレクトリ内の CRL ファイルを検索します。
* SnapCenter プラグインの CRL ファイルのデフォルト ディレクトリは、_'C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_ です。


.手順
. _agent.properties_ ファイルのデフォルトディレクトリを、キー crl_path に対して変更および更新できます。
. このディレクトリには、複数のCRLファイルを配置できます。
+
受信証明書は、各CRLに対して検証されます。


