---
permalink: protect-mysql/restore-mysql-using-powershell-cmdlets.html 
sidebar: sidebar 
keywords: restore, mysql, snapcenter 
summary: MySQLバックアップをリストアするには、SnapCenterサーバとの接続セッションを開始し、バックアップをリストしてバックアップ情報を取得し、バックアップをリストアします。 
---
= PowerShellコマンドレットを使用したMySQLデータベースのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQLバックアップをリストアするには、SnapCenterサーバとの接続セッションを開始し、バックアップをリストしてバックアップ情報を取得し、バックアップをリストアします。

.開始する前に
PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。

.手順
. Open-SmConnectionコマンドレットを使用して、指定したユーザのSnapCenterサーバとの接続セッションを開始します。
+
[listing]
----
PS C:\> Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Get-SmBackupコマンドレットおよびGet-SmBackupReportコマンドレットを使用して、リストアするバックアップを特定します。
+
この例では、リストアに使用できるバックアップが2つあります。

+
[listing]
----
 PS C:\> Get-SmBackup

        BackupId    BackupName                    BackupTime            BackupType
        --------    ----------                    ----------            ----------
         1          Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM  Full Backup
         2          Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
+
この例では、2015年1月29日から2015年2月3日までのバックアップに関する詳細情報を表示しています。

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. HANA Studioでリカバリプロセスを開始します。
+
データベースがシャットダウンされます。

. Restore-SmBackupコマンドレットを使用して、バックアップからデータをリストアします。
+

NOTE: AppObjectIdは「Host\Plugin\UID」です。UID =<instance_name>は手動で検出されたインスタンスリソース用、UID =<instance_name>\<databse_name>はMySQLデータベースリソース用です。リソースIDはGet-SmResourcesコマンドレットで取得できます。

+
[listing]
----
PS C:\> Get-SmResources  -HostName cn24.sccore.test.com  -PluginCode MySQL
----
+
この例は、プライマリストレージからデータベースをリストアする方法を示しています。

+
[listing]
----
PS C:\> Restore-SmBackup -PluginCode MySQL -AppObjectId cn24.sccore.test.com\MySQL\MySQLinst1\DB01 -BackupId 3
----
+
この例は、セカンダリストレージからデータベースをリストアする方法を示しています。

+
[listing]
----
PS C:\> Restore-SmBackup -PluginCode 'MySQL' -AppObjectId cn24.sccore.test.com\MySQL\MySQLinst1\DB01 -BackupId 399 -Confirm:$false  -Archive @( @{"Primary"="<Primary Vserver>:<PrimaryVolume>";"Secondary"="<Secondary Vserver>:<SecondaryVolume>"})
----
+
コマンドレットで使用できるパラメータとその説明については、 RUN_Get-Help コマンド _NAME_ を実行して参照できます。または、を参照することもできます https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter ソフトウェアコマンドレットリファレンスガイド"^]。


